import { DatabaseSync } from 'node:sqlite';
import { expect,it } from 'vitest';
import { selectedCombinedFrozenReport,selectedFrozenMiniTestReport } from '../worker/reporting-entry';

it('reads native frozen new mini tests with ownership, parent revocation, branch and staff season authorization',async()=>{
 const db=new DatabaseSync(':memory:');try{
 db.exec(`CREATE TABLE student_entities(id TEXT,first_name TEXT,last_name TEXT,status TEXT);INSERT INTO student_entities VALUES('s','Synthetic','Student','ACTIVE');
 CREATE TABLE student_enrollments(id TEXT,student_id TEXT,institution_id TEXT,season_id TEXT,class_id TEXT,student_number TEXT,grade_level INTEGER,section TEXT,status TEXT,created_at TEXT);
 INSERT INTO student_enrollments VALUES('en','s','school','season','class','1',7,'A','ACTIVE','2026'),('old-en','s','school','old-season','class','1',7,'A','ARCHIVED','2025'),('other-en','s','other','season','class','1',7,'A','ARCHIVED','2024');
 CREATE TABLE classes(id TEXT,name TEXT);INSERT INTO classes VALUES('class','7A');CREATE TABLE institutions(id TEXT,name TEXT);INSERT INTO institutions VALUES('school','Synthetic');
 CREATE TABLE parent_student_links(id TEXT,parent_user_id TEXT,student_id TEXT,active INTEGER);INSERT INTO parent_student_links VALUES('l','parent','s',1);
 CREATE TABLE teacher_assignments(user_id TEXT,class_id TEXT,subject_id TEXT,assignment_type TEXT,active INTEGER,season_id TEXT);INSERT INTO teacher_assignments VALUES('teacher','class','math','SUBJECT',1,'season');
 CREATE TABLE assignments(id TEXT,institution_id TEXT);INSERT INTO assignments VALUES('assignment','school'),('foreign-assignment','other');
 CREATE TABLE coach_mini_tests(id TEXT,student_id TEXT,assignment_id TEXT,selection_mode TEXT,status TEXT,submitted_at TEXT);
 CREATE TABLE assessment_runs(id TEXT,student_id TEXT,institution_id TEXT,source_type TEXT,status TEXT,delivery_mode TEXT,completed_at TEXT,metadata_json TEXT,source_id TEXT,assignment_id TEXT);`);
 const add=(id:string,overrides:any={})=>{
  const v={student:'s',institution:'school',subject:'math',year:'2026-2027',enrollment:'en',season:'season',mode:'NEW',assignment:'assignment',testStatus:'PASSED',source:'MINI_TEST',runStatus:'SCORED',sourceId:id,testStudent:'s',submitted:'2026-10-01 12:00:00',...overrides};
  const metadata=overrides.metadata??{selectionMode:v.mode,practiceOnly:v.mode==='REPEAT',miniEvidence:{policy:'MINI_TEST_CONTENT_AT_START_V1',enrollmentId:v.enrollment,seasonId:v.season,academicYear:v.year,gradeLevel:7,questionEvidence:[{questionId:'frozen-question',status:'CORRECT',outcomeRefs:[{outcomeId:'frozen-outcome',subjectId:v.subject,curriculumVersionId:'frozen-cv',academicYear:v.year,gradeLevel:7,programVersion:'MAARIF',verified:1}]}]}};
  db.prepare('INSERT INTO coach_mini_tests VALUES(?,?,?,?,?,?)').run(id,v.testStudent,v.assignment,v.mode,v.testStatus,v.submitted);
  db.prepare('INSERT INTO assessment_runs VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,v.student,v.institution,v.source,v.runStatus,'DIGITAL','2026-10-01 12:00:00',typeof metadata==='string'?metadata:JSON.stringify(metadata),v.sourceId,v.runAssignment??v.assignment);
 };
 add('own');add('science',{subject:'science'});add('foreign-student',{student:'foreign'});add('foreign-school',{institution:'other',enrollment:'other-en'});add('foreign-assignment',{assignment:'foreign-assignment'});add('wrong-test-owner',{testStudent:'foreign'});add('wrong-source-id',{sourceId:'own'});add('repeat',{mode:'REPEAT'});add('legacy',{mode:'LEGACY',metadata:{}});add('old',{enrollment:'old-en',season:'old-season'});add('other-year',{year:'2025-2026'});add('unsubmitted',{submitted:null});add('unscored',{runStatus:'SUBMITTED'});add('not-mini',{source:'QUESTION_BANK'});add('bad-json',{metadata:'bad json'});add('spoof-season',{season:'other'});add('spoof-run-assignment',{runAssignment:'foreign-assignment'});
 const prepare=(sql:string,args:any[]=[]):any=>({bind:(...values:any[])=>prepare(sql,values),first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)})});const env={DB:{prepare}} as any;
 const ids=['own','science','foreign-student','foreign-school','foreign-assignment','wrong-test-owner','wrong-source-id','repeat','legacy','old','other-year','unsubmitted','unscored','not-mini','bad-json','spoof-season','spoof-run-assignment'];
 const url=new URL(`https://test?academicYear=2026-2027&testIds=${ids.join(',')}`);const student={role:'STUDENT',student_id:'s'} as any;
 const data:any=await(await selectedFrozenMiniTestReport(env,student,'s',url)).json();expect(data.groups).toHaveLength(2);expect(data.groups.find((g:any)=>g.subjectId==='math').evidenceCount).toBe(2);expect(data.unavailableTestIds).toEqual(ids.filter(id=>!['own','science','old'].includes(id)));expect(JSON.stringify(data)).not.toContain('frozen-question');expect(JSON.stringify(data)).not.toContain('frozen-outcome');expect(data.officialScore).toBeNull();
 const teacher:any=await(await selectedFrozenMiniTestReport(env,{id:'teacher',role:'TEACHER',institution_id:'school'} as any,'s',url)).json();expect(teacher.groups).toHaveLength(1);expect(teacher.groups[0].subjectId).toBe('math');expect(teacher.groups[0].evidenceCount).toBe(1);expect(teacher.coverage).toBeNull();expect(teacher.unavailableTestIds).toEqual([]);expect(JSON.stringify(teacher)).not.toContain('science');
 const parent={role:'PARENT',id:'parent'} as any;expect((await selectedFrozenMiniTestReport(env,parent,'s',url)).status).toBe(200);db.exec('UPDATE parent_student_links SET active=0');expect((await selectedFrozenMiniTestReport(env,parent,'s',url)).status).toBe(403);
 expect((await selectedFrozenMiniTestReport(env,{role:'STUDENT',student_id:'foreign'} as any,'s',url)).status).toBe(403);
 expect((await selectedFrozenMiniTestReport(env,{role:'INSTITUTION_MANAGER',institution_id:'other'} as any,'s',url)).status).toBe(200);
 const manager:any=await(await selectedFrozenMiniTestReport(env,{role:'INSTITUTION_MANAGER',institution_id:'other'} as any,'s',url)).json();expect(manager.groups).toHaveLength(0);
 db.exec('UPDATE teacher_assignments SET active=0');expect((await selectedFrozenMiniTestReport(env,{id:'teacher',role:'TEACHER',institution_id:'school'} as any,'s',url)).status).toBe(403);
 expect((await selectedFrozenMiniTestReport(env,student,'s',new URL('https://test?academicYear=2026-2028&testIds=own'))).status).toBe(400);
 expect((await selectedFrozenMiniTestReport(env,student,'s',new URL(`https://test?academicYear=2026-2027&testIds=${Array.from({length:21},(_,i)=>`t${i}`).join(',')}`))).status).toBe(400);
 const combinedUrl=new URL('https://test?academicYear=2026-2027&miniTestIds=own,science');const combined:any=await(await selectedCombinedFrozenReport(env,student,'s',combinedUrl)).json();expect(combined.sourceTypes).toEqual(['MINI_TEST']);expect(combined.groups).toHaveLength(2);expect(combined.groups[0].sourceBreakdown[0].sourceType).toBe('MINI_TEST');expect(combinedUrl.searchParams.has('testIds')).toBe(false);
 db.prepare('INSERT INTO assessment_runs VALUES(?,?,?,?,?,?,?,?,?,?)').run('practice','s','school','QUESTION_BANK','SCORED','DIGITAL','2026-10-01 12:00:00',JSON.stringify({frozenEvidence:{policy:'QUESTION_PRACTICE_READ_CONTEXT_V1',enrollmentId:'en',seasonId:'season',academicYear:'2026-2027',gradeLevel:7,questionId:'practice-question',contentDigest:'a'.repeat(64),status:'WRONG',outcomeRefs:[{outcomeId:'frozen-outcome',subjectId:'math',curriculumVersionId:'frozen-cv',academicYear:'2026-2027',gradeLevel:7,programVersion:'MAARIF',verified:1}]}}),'practice-question',null);
 const mixed:any=await(await selectedCombinedFrozenReport(env,student,'s',new URL('https://test?academicYear=2026-2027&miniTestIds=own,science&runIds=practice'))).json();const math=mixed.groups.find((g:any)=>g.subjectId==='math');expect(mixed.sourceTypes).toEqual(['QUESTION_BANK','MINI_TEST']);expect(math.correct).toBe(1);expect(math.wrong).toBe(1);expect(math.evidenceCount).toBe(2);expect(math.accuracyPercent).toBe(50);expect(math.sourceBreakdown.map((s:any)=>s.sourceType)).toEqual(['QUESTION_BANK','MINI_TEST']);
 expect((await selectedCombinedFrozenReport(env,student,'s',new URL('https://test?academicYear=2026-2027&miniTestIds=own&runIds=own&repeatPolicy=BAD'))).status).toBe(400);
 db.exec("INSERT INTO assignments VALUES('assignment','school')");expect((await selectedFrozenMiniTestReport(env,student,'s',new URL('https://test?academicYear=2026-2027&testIds=own'))).status).toBe(409);
 }finally{db.close();}
});
