import { DatabaseSync } from 'node:sqlite';
import { expect, it } from 'vitest';
import { submitStudentPractice, practiceContentToken, studentPracticeQuestions } from '../worker/lib/platform-expansion';

it('isolates server-created practice attempts from supplied foreign runs and rejects inactive institution membership', async () => {
 const db=new DatabaseSync(':memory:');
 try {
  db.exec(`CREATE TABLE platform_features(feature_key TEXT,enabled_default INTEGER);INSERT INTO platform_features VALUES('QUESTION_BANK',1);
   CREATE TABLE institution_feature_overrides(feature_key TEXT,institution_id TEXT,enabled INTEGER);
   CREATE TABLE student_enrollments(student_id TEXT,institution_id TEXT,status TEXT,created_at TEXT,id TEXT,season_id TEXT,grade_level INTEGER);INSERT INTO student_enrollments VALUES('student','school','ACTIVE','2026','enrollment','season',7);CREATE TABLE institution_seasons(id TEXT,institution_id TEXT,academic_year TEXT);INSERT INTO institution_seasons VALUES('season','school','2026-2027');
   CREATE TABLE question_bank(id TEXT,correct_answer TEXT,solution_text TEXT,owner_type TEXT,owner_id TEXT,review_status TEXT,copyright_status TEXT,options_json TEXT,stem_text TEXT,updated_at TEXT,subject_id TEXT,grade_level INTEGER,academic_year TEXT);
   INSERT INTO question_bank VALUES('q','A',NULL,'PLATFORM',NULL,'APPROVED','OWNED','[]','Synthetic question','2026-10-01','math',7,'2026-2027');
   CREATE TABLE learning_nodes(id TEXT,node_type TEXT,subject_id TEXT,grade_level INTEGER,academic_year TEXT);CREATE TABLE outcomes(id TEXT,subject_id TEXT,curriculum_version_id TEXT,active INTEGER,grade_level INTEGER);CREATE TABLE curriculum_versions(id TEXT,academic_year TEXT,grade_level INTEGER,program_version TEXT,verified INTEGER);CREATE TABLE question_learning_links(question_id TEXT,node_id TEXT);
   CREATE TABLE assessment_runs(id TEXT PRIMARY KEY,institution_id TEXT,student_id TEXT,source_type TEXT,source_id TEXT,delivery_mode TEXT,status TEXT,score REAL,metadata_json TEXT,completed_at TEXT);
   INSERT INTO assessment_runs VALUES('foreign','other-school','other-student','MINI_TEST','other-source','DIGITAL','SCORED',0,NULL,NULL);
   CREATE TABLE question_practice_attempts(id TEXT PRIMARY KEY,student_id TEXT,question_id TEXT,selected_answer TEXT,is_correct INTEGER);
   CREATE TABLE assessment_responses(id TEXT,run_id TEXT,student_id TEXT,question_id TEXT,node_id TEXT,selected_answer TEXT,is_correct INTEGER,source_channel TEXT,UNIQUE(run_id,question_id));
   INSERT INTO learning_nodes VALUES('ln_o1','OUTCOME','math',7,'2026-2027'),('custom','OUTCOME','math',7,'2026-2027');
   INSERT INTO outcomes VALUES('o1','math','cv',1,7);INSERT INTO curriculum_versions VALUES('cv','2026-2027',7,'synthetic-v1',1);
   INSERT INTO question_learning_links VALUES('q','ln_o1'),('q','custom');
   CREATE TABLE learning_evidence(id TEXT,student_id TEXT,node_id TEXT,source_type TEXT,source_id TEXT,result REAL,weight REAL);
   CREATE TABLE student_learning_state(student_id TEXT,node_id TEXT,mastery REAL,confidence REAL,evidence_count INTEGER,last_evidence_at TEXT,updated_at TEXT,PRIMARY KEY(student_id,node_id));
   CREATE TABLE audit_logs(id TEXT,actor_user_id TEXT,institution_id TEXT,action TEXT,entity_type TEXT,entity_id TEXT,details_json TEXT);`);
  db.exec(`ALTER TABLE question_bank ADD COLUMN topic TEXT;ALTER TABLE question_bank ADD COLUMN subtopic TEXT;ALTER TABLE question_bank ADD COLUMN question_type TEXT;ALTER TABLE question_bank ADD COLUMN content_mode TEXT;ALTER TABLE question_bank ADD COLUMN option_count INTEGER;ALTER TABLE question_bank ADD COLUMN difficulty_level INTEGER;ALTER TABLE question_bank ADD COLUMN difficulty INTEGER;ALTER TABLE question_bank ADD COLUMN created_at TEXT;
   ALTER TABLE question_practice_attempts ADD COLUMN created_at TEXT;CREATE TABLE subjects(id TEXT,name TEXT);INSERT INTO subjects VALUES('math','Synthetic math');`);
  const prepare=(sql:string,args:any[]=[]):any=>({bind:(...values:any[])=>prepare(sql,values),first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>db.prepare(sql).run(...args),sql,args});
  const env={SESSION_SECRET:'synthetic-practice-test-secret',DB:{prepare,batch:async(stmts:any[])=>{db.exec('BEGIN');try{const results=stmts.map(x=>db.prepare(x.sql).run(...x.args));db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}}} as any;
  const user={id:'user',role:'STUDENT',student_id:'student',institution_id:'school'} as any;
  const token=async()=>practiceContentToken(env,user,{enrollment_id:'enrollment',season_id:'season',academic_year:db.prepare('SELECT academic_year FROM institution_seasons').get()?.academic_year,grade_level:7},db.prepare('SELECT * FROM question_bank').get());
  const served=await studentPracticeQuestions(new Request('https://test/api/platform/student-practice?limit=10'),env,user);expect(served.status).toBe(200);
  const servedBody:any=await served.json();expect(servedBody.questions).toHaveLength(1);expect(servedBody.questions[0].practiceToken).toMatch(/^\d+\.[0-9a-f]{64}$/);expect(servedBody.questions[0]).not.toHaveProperty('correct_answer');expect(servedBody.questions[0]).not.toHaveProperty('solution_text');
  let practiceToken=servedBody.questions[0].practiceToken;
  const send=()=>submitStudentPractice(new Request('https://test',{method:'POST',body:JSON.stringify({questionId:'q',answer:'A',runId:'foreign',practiceToken})}),env,user);
  practiceToken='';const missing=await send();expect(missing.status).toBe(409);expect(await missing.json()).toMatchObject({error:{code:'PRACTICE_CONTENT_STALE',message:expect.any(String)}});practiceToken=servedBody.questions[0].practiceToken;
  const originalToken=practiceToken;practiceToken=originalToken.slice(0,-1)+(originalToken.endsWith('0')?'1':'0');expect((await send()).status).toBe(409);practiceToken=originalToken;
  db.exec("UPDATE question_bank SET correct_answer='B'");expect((await send()).status).toBe(409);db.exec("UPDATE question_bank SET correct_answer='A'");
  practiceToken=await practiceContentToken(env,user,{enrollment_id:'enrollment',season_id:'season',academic_year:'2026-2027',grade_level:7},db.prepare('SELECT * FROM question_bank').get(),Date.now()-1);expect((await send()).status).toBe(409);practiceToken=originalToken;
  const first:any=await(await send()).json(),second:any=await(await send()).json();
  expect(first.ok).toBe(true);expect(first.runId).not.toBe('foreign');expect(second.runId).not.toBe(first.runId);
  expect(db.prepare("SELECT COUNT(*) n FROM assessment_responses WHERE run_id='foreign'").get()?.n).toBe(0);
  expect(db.prepare("SELECT student_id,source_type FROM assessment_runs WHERE id='foreign'").get()).toMatchObject({student_id:'other-student',source_type:'MINI_TEST'});
  expect(db.prepare("SELECT COUNT(*) n FROM assessment_runs WHERE student_id='student' AND institution_id='school' AND source_type='QUESTION_BANK'").get()?.n).toBe(2);
  const frozen=JSON.parse(String(db.prepare('SELECT metadata_json FROM assessment_runs WHERE id=?').get(first.runId)?.metadata_json)).frozenEvidence;
  expect(frozen).toMatchObject({status:'CORRECT',enrollmentId:'enrollment',academicYear:'2026-2027',gradeLevel:7});expect(frozen.contentDigest).toHaveLength(64);expect(frozen.outcomeRefs).toHaveLength(2);expect(frozen.outcomeRefs.find((x:any)=>x.nodeId==='ln_o1')).toMatchObject({curriculumVersionId:'cv',verified:1,programVersion:'synthetic-v1'});expect(frozen.outcomeRefs.find((x:any)=>x.nodeId==='custom')).toMatchObject({curriculumVersionId:null,verified:0});
  db.exec("UPDATE question_bank SET correct_answer='B',stem_text='Changed';UPDATE institution_seasons SET academic_year='2027-2028';UPDATE curriculum_versions SET verified=0,program_version='changed'");
  expect((await send()).status).toBe(409);practiceToken=await token();
  expect(JSON.parse(String(db.prepare('SELECT metadata_json FROM assessment_runs WHERE id=?').get(first.runId)?.metadata_json)).frozenEvidence).toEqual(frozen);
  db.exec("CREATE TRIGGER reject_response BEFORE INSERT ON assessment_responses BEGIN SELECT RAISE(ABORT,'synthetic failure');END");
  await expect(send()).rejects.toThrow('synthetic failure');
  expect(db.prepare('SELECT COUNT(*) n FROM assessment_runs').get()?.n).toBe(3);
  expect(db.prepare('SELECT COUNT(*) n FROM question_practice_attempts').get()?.n).toBe(2);
  db.exec("UPDATE student_enrollments SET institution_id='other-school'");
  expect((await send()).status).toBe(403);
  expect(db.prepare('SELECT COUNT(*) n FROM question_practice_attempts').get()?.n).toBe(2);
 } finally {db.close();}
});
