import {DatabaseSync} from 'node:sqlite';
import {describe,expect,it,vi} from 'vitest';
import {createWhatsAppWebhookPolicyEntry} from '../worker/whatsapp-webhook-policy-entry';
import type {Env} from '../worker/types';

async function signature(secret:string,body:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const value=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body));return `sha256=${[...new Uint8Array(value)].map(x=>x.toString(16).padStart(2,'0')).join('')}`}
function fixture(){
 const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE nibiru_whatsapp_status_events(provider_message_id TEXT,status TEXT,recipient_phone_e164 TEXT,error_code TEXT,occurred_at TEXT,received_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(provider_message_id,status,occurred_at));CREATE TABLE announcement_deliveries(id TEXT PRIMARY KEY,channel TEXT,status TEXT,provider_message_id TEXT,failure_code TEXT,attempted_at TEXT,delivered_at TEXT);INSERT INTO announcement_deliveries VALUES('d','WHATSAPP','SENT','wamid.1',NULL,'2026-10-01T00:00:00Z',NULL);`);
 const prepare=(sql:string,args:any[]=[]):any=>({bind:(...values:any[])=>prepare(sql,values),run:async()=>{const r=db.prepare(sql).run(...args);return{success:true,meta:{changes:Number(r.changes)}}}});
 const delegated=vi.fn(async()=>new Response('EVENT_RECEIVED',{status:200}));const waits:Promise<unknown>[]=[];const ctx={waitUntil(p:Promise<unknown>){waits.push(p)}} as any;
 const env={ENVIRONMENT:'production',WHATSAPP_VERIFY_TOKEN:'verify-me',WHATSAPP_APP_SECRET:'app-secret',DB:{prepare}} as any as Env;const app=createWhatsAppWebhookPolicyEntry({fetch:delegated} as any);
 return{db,env,delegated,ctx,call:(request:Request)=>app.fetch!(request,env,ctx),flush:async()=>{await Promise.all(waits)}};
}
describe('WhatsApp outer webhook policy',()=>{
 it('returns challenge only for the correct verify token',async()=>{const f=fixture();try{const ok=await f.call(new Request('https://x/api/nibiru/whatsapp/webhook?hub.mode=subscribe&hub.verify_token=verify-me&hub.challenge=abc'));expect(ok.status).toBe(200);expect(await ok.text()).toBe('abc');const denied=await f.call(new Request('https://x/api/nibiru/whatsapp/webhook?hub.mode=subscribe&hub.verify_token=wrong&hub.challenge=abc'));expect(denied.status).toBe(403);expect(f.delegated).not.toHaveBeenCalled();}finally{f.db.close()}});
 it('rejects invalid signatures and oversized bodies before delegation',async()=>{const f=fixture();try{const body='{}';const bad=await f.call(new Request('https://x/api/nibiru/whatsapp/webhook',{method:'POST',headers:{'x-hub-signature-256':await signature('wrong',body)},body}));expect(bad.status).toBe(401);const large=await f.call(new Request('https://x/api/nibiru/whatsapp/webhook',{method:'POST',headers:{'content-length':String(1024*1024+1),'x-hub-signature-256':await signature('app-secret',body)},body}));expect(large.status).toBe(413);expect(f.delegated).not.toHaveBeenCalled();}finally{f.db.close()}});
 it('stores delivery receipts, updates delivery state and still delegates inbound handling',async()=>{const f=fixture();try{const body=JSON.stringify({entry:[{changes:[{value:{statuses:[{id:'wamid.1',recipient_id:'905551112233',status:'delivered',timestamp:'1790812800'}]}}]}]});const response=await f.call(new Request('https://x/api/nibiru/whatsapp/webhook',{method:'POST',headers:{'x-hub-signature-256':await signature('app-secret',body)},body}));expect(response.status).toBe(200);await f.flush();expect(f.db.prepare(`SELECT status,recipient_phone_e164 FROM nibiru_whatsapp_status_events WHERE provider_message_id='wamid.1'`).get()).toMatchObject({status:'DELIVERED',recipient_phone_e164:'+905551112233'});expect(f.db.prepare(`SELECT status,delivered_at FROM announcement_deliveries WHERE id='d'`).get()).toMatchObject({status:'DELIVERED'});expect(f.delegated).toHaveBeenCalledOnce();}finally{f.db.close()}});
});
