import { useEffect,useState } from 'react';
import { Database,ExternalLink,RefreshCw,Upload } from 'lucide-react';
import { api } from '../api';

export function AcademicTargetAdmin(){
 const[sources,setSources]=useState<any[]>([]);const[sourceKind,setSourceKind]=useState('MEB_ROTA_MAARIF');const[year,setYear]=useState(2026);const[text,setText]=useState('[]');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=async()=>{try{const r=await api<any>('/api/academic-targets/sources');setSources(r.sources||[])}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);
 const importRows=async()=>{setBusy(true);setError('');setNotice('');try{const rows=JSON.parse(text);if(!Array.isArray(rows))throw new Error('JSON bir dizi olmalıdır.');const r=await api<any>('/api/academic-targets/import',{method:'POST',body:JSON.stringify({sourceKind,year,rows})});setNotice(`${r.imported} resmî hedef kaydı içe aktarıldı.`);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const example=sourceKind.startsWith('MEB')?[{externalCode:'MEB_OKUL_KODU',name:'Okul Adı',city:'İstanbul',district:'Kartal',schoolType:'Anadolu Lisesi',placementType:'CENTRAL',baseScore:480.1,percentile:0.5,quota:120,netProfile:{TURKCE:18.5,MATEMATIK:17.25,FEN:18},sourceUrl:'https://rotamaarif.meb.gov.tr/...',sourceVerifiedAt:'2026-08-22'}]:[{programCode:'YOK_PROGRAM_KODU',universityName:'Üniversite',facultyName:'Fakülte',programName:'Program',scoreType:'SAY',baseScore:470,successRank:5000,quota:80,netProfile:{'TYT Türkçe':32,'TYT Mat':30,'AYT Mat':32,'AYT Fizik':10},sourceUrl:'https://yokatlas.yok.gov.tr/...',sourceVerifiedAt:'2026-08-22'}];
 return <>
  <div className="page-head"><div><span className="eyebrow">Resmî Hedef Veri Merkezi</span><h1>MEB · ÖSYM · YÖK Atlas</h1><p>Nibiru hedef analizi yalnız doğrulanmış resmî kaynak havuzunu kullanır. Kaynak yılı, URL ve doğrulama tarihi her kayıtta saklanır.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="table-card"><table><thead><tr><th>Kaynak</th><th>Yıl</th><th>Durum</th><th>Son İçe Aktarım</th><th>Resmî Adres</th></tr></thead><tbody>{sources.map(s=><tr key={s.id}><td><strong>{s.title}</strong><div className="muted">{s.source_kind}</div></td><td>{s.data_year}</td><td><span className={`status ${s.import_status==='CURRENT'?'ok':'neutral'}`}>{s.import_status}</span></td><td>{s.last_imported_at||'Henüz yok'}</td><td><a href={s.base_url} target="_blank" rel="noreferrer">Aç <ExternalLink size={12}/></a></td></tr>)}</tbody></table></div>
  <div className="panel"><div className="panel-head"><div><h2>Resmî veri aktarımı</h2><p>Rota Maarif/e-Okul veya YÖK Atlas/ÖSYM’den alınan doğrulanmış kayıtları toplu JSON olarak içe aktarır. Nibiru kaynakta bulunmayan neti üretmez.</p></div><Database/></div><div className="form-grid"><label>Kaynak<select value={sourceKind} onChange={e=>{setSourceKind(e.target.value);setText(JSON.stringify(e.target.value.startsWith('MEB')?example:[...example],null,2))}}><option value="MEB_ROTA_MAARIF">MEB Rota Maarif</option><option value="MEB_EOKUL">MEB e-Okul</option><option value="YOK_ATLAS">YÖK Atlas</option><option value="OSYM">ÖSYM</option></select></label><label>Veri yılı<input type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></label></div><label>JSON kayıtları<textarea rows={14} value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/></label><button className="primary" disabled={busy} onClick={()=>void importRows()}><Upload size={16}/> Resmî Veriyi İçe Aktar</button><button className="ghost" onClick={()=>setText(JSON.stringify(example,null,2))}>Örnek Şablonu Getir</button></div>
  <div className="alert warning"><strong>Kaynak politikası:</strong> “MEB/ÖSYM/YÖK verisi” ibaresi yalnız kaynak URL’si ve doğrulama tarihi saklanan kayıtlarda gösterilir. Tahminler ayrıca “Nibiru tahmini” olarak etiketlenir.</div>
 </>;
}
