import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, CircleAlert, ExternalLink, FileSpreadsheet, RefreshCw, RotateCcw, ShieldCheck, Upload } from 'lucide-react';
import { api, qs } from '../api';

type SourceKind='MEB_ROTA_MAARIF'|'MEB_EOKUL'|'YOK_ATLAS'|'OSYM';
type Field={key:string;label:string;required?:boolean;aliases:string[]};
const LGS_FIELDS:Field[]=[
 {key:'externalCode',label:'Resmî okul kodu',required:true,aliases:['externalcode','okulkodu','kurumkodu']},{key:'name',label:'Okul adı',required:true,aliases:['name','okuladi','kurumadi']},{key:'city',label:'İl',required:true,aliases:['city','il','sehir']},{key:'district',label:'İlçe',aliases:['district','ilce']},{key:'schoolType',label:'Okul türü',aliases:['schooltype','okulturu']},{key:'placementType',label:'Yerleştirme türü',aliases:['placementtype','yerlestirmeturu']},{key:'baseScore',label:'Taban puan',aliases:['basescore','tabanpuan']},{key:'percentile',label:'Yüzdelik dilim',aliases:['percentile','yuzdelik','yuzdelikdilim']},{key:'quota',label:'Kontenjan',aliases:['quota','kontenjan']},{key:'netProfile',label:'Net profili (JSON)',aliases:['netprofile','netler']}
];
const YKS_FIELDS:Field[]=[
 {key:'programCode',label:'YÖK program kodu',required:true,aliases:['programcode','programkodu','yokprogramkodu']},{key:'universityName',label:'Üniversite',required:true,aliases:['universityname','universite']},{key:'facultyName',label:'Fakülte',aliases:['facultyname','fakulte']},{key:'programName',label:'Program / bölüm',required:true,aliases:['programname','program','bolum']},{key:'city',label:'Şehir',aliases:['city','il','sehir']},{key:'educationLanguage',label:'Öğretim dili',aliases:['educationlanguage','ogretimdili']},{key:'educationType',label:'Öğretim türü',aliases:['educationtype','ogrenimturu']},{key:'universityType',label:'Üniversite türü',aliases:['universitytype','universiteturu']},{key:'scholarship',label:'Burs',aliases:['scholarship','burs','bursluluk']},{key:'scoreType',label:'Puan türü',required:true,aliases:['scoretype','puanturu']},{key:'baseScore',label:'Taban puan',aliases:['basescore','tabanpuan']},{key:'successRank',label:'Başarı sırası',aliases:['successrank','basarisirasi']},{key:'quota',label:'Kontenjan',aliases:['quota','kontenjan']},{key:'minRankRule',label:'Başarı sırası şartı',aliases:['minrankrule','basarisirasisarti']},{key:'netProfile',label:'Net profili (JSON)',aliases:['netprofile','netler']}
];
const statusText:Record<string,string>={READY:'Onaya hazır',PREVIEW:'Düzeltme gerekli',COMMITTING:'Aktarılıyor',COMMITTED:'Tamamlandı',FAILED:'Yarıda kaldı',ROLLED_BACK:'Geri alındı',CURRENT:'Güncel',IMPORTING:'Aktarılıyor',STALE:'Eski'};
function norm(value:string){return value.trim().toLocaleLowerCase('tr-TR').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function headerCells(text:string){const line=text.replace(/^\uFEFF/,'').split(/\r?\n/).find(x=>x.trim())||'';const delimiter=[';','\t',','].sort((a,b)=>line.split(b).length-line.split(a).length)[0];const cells:string[]=[];let cell='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){cells.push(cell.trim());cell=''}else cell+=c}cells.push(cell.trim());return cells.filter(Boolean)}
function autoMapping(fields:Field[],headers:string[]){const index=new Map(headers.map(x=>[norm(x),x]));return Object.fromEntries(fields.map(f=>[f.key,f.aliases.map(norm).map(x=>index.get(x)).find(Boolean)||'']))}
function Summary({label,value,warn}:{label:string;value:any;warn?:boolean}){return <div className={warn&&Number(value)>0?'summary warn':'summary'}><span>{label}</span><strong>{value??0}</strong></div>}

export function AcademicTargetAdmin(){
 const[sources,setSources]=useState<any[]>([]);const[jobs,setJobs]=useState<any[]>([]);const[sourceKind,setSourceKind]=useState<SourceKind>('MEB_ROTA_MAARIF');const[year,setYear]=useState(2026);const[sourceUrl,setSourceUrl]=useState('');const[sourceTitle,setSourceTitle]=useState('');const[sourceVerifiedAt,setSourceVerifiedAt]=useState(new Date().toISOString().slice(0,10));const[file,setFile]=useState<File|null>(null);const[headers,setHeaders]=useState<string[]>([]);const[mapping,setMapping]=useState<Record<string,string>>({});const[job,setJob]=useState<any>(null);const[jobRows,setJobRows]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const fields=useMemo(()=>sourceKind.startsWith('MEB')?LGS_FIELDS:YKS_FIELDS,[sourceKind]);
 const chooseSource=(kind:SourceKind,nextYear=year,list=sources)=>{setSourceKind(kind);const source=list.find((x:any)=>x.source_kind===kind&&Number(x.data_year)===nextYear)||list.find((x:any)=>x.source_kind===kind);if(source){setSourceUrl(source.base_url||'');setSourceTitle(source.title||'')}};
 const load=async()=>{setError('');try{const[s,j]=await Promise.all([api<any>('/api/academic-targets/sources'),api<any>(`/api/academic-targets/import-jobs${qs({sourceKind,year})}`)]);const list=s.sources||[];setSources(list);setJobs(j.jobs||[]);if(!sourceUrl)chooseSource(sourceKind,year,list)}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);
 const selectFile=async(next:File|null)=>{setFile(next);setJob(null);setJobRows([]);if(!next){setHeaders([]);setMapping({});return}const found=headerCells(await next.slice(0,262144).text());setHeaders(found);setMapping(autoMapping(fields,found))};
 const preview=async()=>{if(!file)return;setBusy(true);setError('');setNotice('');try{const fd=new FormData();fd.append('file',file);fd.append('sourceKind',sourceKind);fd.append('year',String(year));fd.append('sourceUrl',sourceUrl);fd.append('sourceTitle',sourceTitle);fd.append('sourceVerifiedAt',sourceVerifiedAt);fd.append('mapping',JSON.stringify(mapping));const r=await api<any>('/api/academic-targets/import-preview',{method:'POST',body:fd});setJob(r);setJobRows(r.preview||[]);setNotice(r.invalidCount?`${r.invalidCount} satır düzeltilmeden aktarım yapılamaz.`:`${r.validCount} satır doğrulandı; henüz hedef tablolarına yazılmadı.`);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const openJob=async(id:string)=>{setBusy(true);setError('');try{const r=await api<any>(`/api/academic-targets/import-jobs/${id}`);setJob({...r.job,jobId:r.job.id});setJobRows(r.rows||[])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const commit=async()=>{const id=job?.jobId||job?.id;if(!id||!confirm('Dosyanın belirtilen resmî kaynaktan alındığını ve önizlemeyi kontrol ettiğinizi onaylıyor musunuz?'))return;setBusy(true);setError('');try{const r=await api<any>(`/api/academic-targets/import-jobs/${id}/commit`,{method:'POST',body:JSON.stringify({confirmedOfficial:true})});setNotice(`${r.imported} doğrulanmış resmî hedef kaydı aktarıldı.`);await Promise.all([openJob(id),load()])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const rollback=async()=>{const id=job?.jobId||job?.id;if(!id||!confirm('Bu dosya aktarımının oluşturduğu kayıtlar pasife alınacak, güncellediği kayıtlar önceki hâline dönecek. Devam edilsin mi?'))return;setBusy(true);setError('');try{const r=await api<any>(`/api/academic-targets/import-jobs/${id}/rollback`,{method:'POST',body:JSON.stringify({confirmed:true,reason:'Resmî Hedef Veri Merkezi üzerinden güvenli geri alma'})});setNotice(`Aktarım geri alındı: ${r.restored} kayıt eski hâline döndü, ${r.deactivated} yeni kayıt pasife alındı.`);await Promise.all([openJob(id),load()])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const invalidMapping=fields.some(f=>f.required&&!mapping[f.key]);
 return <>
  <div className="page-head"><div><span className="eyebrow">Resmî Hedef Veri Merkezi</span><h1>MEB · ÖSYM · YÖK Atlas</h1><p>Dosyayı önce güvenli staging alanında eşleyin ve doğrulayın. Onay verilmeden öğrenci hedeflerine hiçbir kayıt yazılmaz.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="target-import-steps"><span className="active">1 · Dosya</span><span className={headers.length?'active':''}>2 · Eşleme</span><span className={job?'active':''}>3 · Önizleme</span><span className={job?.status==='COMMITTED'?'active':''}>4 · Onaylı aktarım</span></div>
  <div className="panel"><div className="panel-head"><div><h2>1. Resmî dosyayı tanımla</h2><p>CSV/TXT, en fazla 5.000 satır ve 10 MB. Dosya SHA-256 özetiyle R2'de saklanır.</p></div><FileSpreadsheet/></div><div className="form-grid"><label>Kaynak<select value={sourceKind} onChange={e=>{const kind=e.target.value as SourceKind;chooseSource(kind);setHeaders([]);setMapping({});setJob(null)}}><option value="MEB_ROTA_MAARIF">MEB Rota Maarif</option><option value="MEB_EOKUL">MEB e-Okul</option><option value="YOK_ATLAS">YÖK Atlas</option><option value="OSYM">ÖSYM</option></select></label><label>Veri yılı<input type="number" min="2000" max="2100" value={year} onChange={e=>{const y=Number(e.target.value);setYear(y);chooseSource(sourceKind,y)}}/></label><label>Resmî doküman adı<input value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)} placeholder="Kılavuz / resmî tablo adı"/></label><label>Kaynak doğrulama tarihi<input type="date" value={sourceVerifiedAt} onChange={e=>setSourceVerifiedAt(e.target.value)}/></label><label className="span-2">Resmî kaynak URL<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://...meb.gov.tr veya osym.gov.tr/..."/></label><label className="span-2">Gerçek kaynak dosyası<input type="file" accept=".csv,.txt,text/csv,text/plain" onChange={e=>void selectFile(e.target.files?.[0]||null)}/><small>Örnek/sentetik dosya resmî veri olarak işaretlenmemelidir.</small></label></div></div>
  {!!headers.length&&<div className="panel"><div className="panel-head"><div><h2>2. Kolonları eşle</h2><p>{headers.length} başlık algılandı. Zorunlu alanlar yıldızlıdır; eşleme dosya başlıklarına göre kaydedilir.</p></div><Upload/></div><div className="mapping-grid">{fields.map(f=><label key={f.key}>{f.label}{f.required?' *':''}<select value={mapping[f.key]||''} onChange={e=>setMapping({...mapping,[f.key]:e.target.value})}><option value="">{f.required?'Kolon seçin':'Eşleme yok'}</option>{headers.map(h=><option value={h} key={h}>{h}</option>)}</select></label>)}</div><button className="primary" disabled={busy||invalidMapping||!sourceUrl.trim()||!sourceTitle.trim()||!sourceVerifiedAt} onClick={()=>void preview()}><ShieldCheck size={16}/> Önizle ve Doğrula</button></div>}
  {job&&<div className="panel"><div className="panel-head"><div><h2>3. Satır önizlemesi</h2><p>İş: {job.jobId||job.id} · Durum: {statusText[job.status]||job.status} · Hedef tablolarına yazma yalnız son onayla yapılır.</p></div>{Number(job.invalidCount??job.invalid_count)===0?<CheckCircle2/>:<CircleAlert/>}</div><div className="summary-strip"><Summary label="Toplam" value={job.rowCount??job.row_count}/><Summary label="Geçerli" value={job.validCount??job.valid_count}/><Summary label="Hatalı" value={job.invalidCount??job.invalid_count} warn/></div><div className="table-scroll"><table><thead><tr><th>Satır</th><th>Resmî kod</th><th>Okul / Üniversite</th><th>Program / Şehir</th><th>Puan / Sıra</th><th>Durum</th></tr></thead><tbody>{jobRows.slice(0,100).map((row:any)=>{const r=row.mapped||row.mapped_json&&JSON.parse(row.mapped_json)||{};const issues=row.issues||[];return <tr key={row.rowNo??row.row_no}><td>{row.rowNo??row.row_no}</td><td>{r.externalCode||r.programCode||'—'}</td><td>{r.name||r.universityName||'—'}</td><td>{r.district||r.programName||r.city||'—'}</td><td>{r.baseScore??r.percentile??r.successRank??'—'}</td><td>{issues.length?<span className="status warn">{issues.join(' · ')}</span>:<span className="status ok">Hazır</span>}</td></tr>})}</tbody></table></div><div className="import-history-actions"><button className="ghost" onClick={()=>void openJob(job.jobId||job.id)}>Önizlemeyi Yenile</button>{job.status==='COMMITTED'||job.status==='FAILED'?<button className="danger" disabled={busy} onClick={()=>void rollback()}><RotateCcw size={16}/> Güvenli Geri Al</button>:<button className="primary" disabled={busy||Number(job.invalidCount??job.invalid_count)!==0||job.status!=='READY'} onClick={()=>void commit()}><ShieldCheck size={16}/> Resmî Kaynak Olarak Onayla ve Aktar</button>}</div></div>}
  <div className="section-head"><div><h2>Aktarım geçmişi</h2><p>Dosya, eşleme, doğrulama, onay ve geri alma kaydı denetim iziyle korunur.</p></div></div><div className="table-card"><table><thead><tr><th>Tarih</th><th>Kaynak / yıl</th><th>Dosya</th><th>Satır</th><th>Durum</th><th></th></tr></thead><tbody>{jobs.map(x=><tr key={x.id}><td>{x.created_at}</td><td>{x.source_kind} · {x.data_year}</td><td><strong>{x.source_file_name}</strong><br/><small>{String(x.source_file_hash||'').slice(0,16)}…</small></td><td>{x.valid_count}/{x.row_count}{x.invalid_count?` · ${x.invalid_count} hatalı`:''}</td><td><span className={`status ${x.status==='COMMITTED'?'ok':x.status==='PREVIEW'||x.status==='FAILED'?'warn':'neutral'}`}>{statusText[x.status]||x.status}</span></td><td><button className="ghost" onClick={()=>void openJob(x.id)}>Aç</button></td></tr>)}</tbody></table>{!jobs.length&&<div className="empty">Bu kaynak ve yıl için dosya aktarımı yok.</div>}</div>
  <div className="section-head"><div><h2>Kaynak durumu</h2><p>Tercih Robotu yalnız “Güncel” durumdaki doğrulanmış satırları kullanır.</p></div></div><div className="table-card"><table><thead><tr><th>Kaynak</th><th>Yıl</th><th>Durum</th><th>Son İçe Aktarım</th><th>Resmî Adres</th></tr></thead><tbody>{sources.map(s=><tr key={s.id}><td><strong>{s.title}</strong><div className="muted">{s.source_kind}</div></td><td>{s.data_year}</td><td><span className={`status ${s.import_status==='CURRENT'?'ok':'neutral'}`}>{statusText[s.import_status]||s.import_status}</span></td><td>{s.last_imported_at||'Henüz yok'}</td><td><a href={s.base_url} target="_blank" rel="noreferrer">Aç <ExternalLink size={12}/></a></td></tr>)}</tbody></table></div>
  <div className="alert warning"><strong>Kaynak politikası:</strong> Resmî alan adı, doğrulama tarihi ve insan onayı olmadan kayıt yayımlanmaz. Sistem eksik okul, program, puan, yüzdelik veya başarı sırası üretmez.</div>
 </>;
}
