import { useEffect,useState } from 'react';
import { Bell,CalendarClock,MessageCircle,RefreshCw,Send,ShieldCheck } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';

export function Announcements(){
 const{user}=useAuth();const[items,setItems]=useState<any[]>([]);const[classes,setClasses]=useState<any[]>([]);const[title,setTitle]=useState('');const[body,setBody]=useState('');const[type,setType]=useState('GENERAL');const[audienceType,setAudienceType]=useState('CLASS');const[classId,setClassId]=useState('');const[whatsapp,setWhatsapp]=useState(true);const[smsFallback,setSmsFallback]=useState(true);const[template,setTemplate]=useState('');const[scheduledAt,setScheduledAt]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=async()=>{setError('');try{const [a,c]=await Promise.all([api<any>('/api/announcements'),api<any>('/api/v2/bulk/options').catch(()=>({classes:[]}))]);setItems(a.announcements||[]);setClasses(c.classes||[]);setClassId(cur=>cur||(c.classes?.[0]?.id||''))}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!title.trim()||!body.trim())return;setBusy(true);setError('');setNotice('');try{const audience=audienceType==='CLASS'?{classIds:classId?[classId]:[]}:audienceType==='ALL'?{}:{roles:['PARENT','STUDENT']};const r=await api<any>('/api/announcements',{method:'POST',body:JSON.stringify({announcementType:type,title,body,audienceType,audience,channels:['PANEL',...(whatsapp?['WHATSAPP']:[])],smsFallback,whatsappTemplateName:template||null,scheduledAt:scheduledAt||null})});setNotice(scheduledAt?`Duyuru planlandı. ${r.recipientCount} alıcı.`:`Duyuru taslağı oluşturuldu. ${r.recipientCount} alıcı.`);setTitle('');setBody('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const send=async(id:string)=>{setBusy(true);try{const r=await api<any>(`/api/announcements/${id}/send`,{method:'POST',body:'{}'});setNotice(`Duyuru işlendi: ${r.recipients||0} alıcı.`);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const teacher=user?.role==='TEACHER'||user?.role==='GUIDANCE_TEACHER';
 return <>
  <div className="page-head"><div><span className="eyebrow">İletişim Merkezi</span><h1>Duyurular · Panel + WhatsApp + SMS Yedek</h1><p>Kurum ve öğretmen duyuruları önce panel bildirimi olarak kaydedilir. WhatsApp için yalnız doğrulanmış kullanıcılar ve Meta onaylı şablonlar kullanılır; SMS yedek kanalı sağlayıcı bağlandığında devreye girer.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel"><div className="panel-head"><div><h2>Yeni duyuru</h2><p>{teacher?'Yalnız yetkili olduğunuz sınıflara veya seçili kullanıcılara gönderebilirsiniz.':'Tüm kurum, rol, sınıf veya seçili kullanıcı hedeflenebilir.'}</p></div><Bell/></div>
   <div className="form-grid"><label>Tür<select value={type} onChange={e=>setType(e.target.value)}><option value="GENERAL">Genel</option><option value="MEETING">Toplantı</option><option value="EXAM">Sınav</option><option value="RESULT">Sonuç Açıklandı</option><option value="WORKSHEET">Föy</option><option value="URGENT">Acil</option></select></label><label>Hedef kitle<select value={audienceType} onChange={e=>setAudienceType(e.target.value)}><option value="CLASS">Sınıf</option>{!teacher&&<option value="ALL">Tüm Kurum</option>}{!teacher&&<option value="ROLE">Veli + Öğrenci</option>}</select></label>{audienceType==='CLASS'&&<label>Sınıf<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Sınıf seç</option>{classes.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>Planlı gönderim<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label></div>
   <label>Başlık<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Örn. Veli toplantısı"/></label><label>Mesaj<textarea value={body} onChange={e=>setBody(e.target.value)} rows={4} placeholder="Duyuru metni"/></label>
   <div className="form-grid"><label>WhatsApp<input type="checkbox" checked={whatsapp} onChange={e=>setWhatsapp(e.target.checked)}/></label><label>SMS yedek<input type="checkbox" checked={smsFallback} onChange={e=>setSmsFallback(e.target.checked)}/></label>{whatsapp&&<label>Meta şablon adı<input value={template} onChange={e=>setTemplate(e.target.value)} placeholder="Örn. school_announcement_tr"/></label>}</div>
   <div className="alert info"><ShieldCheck size={17}/><div><strong>Güvenli gönderim</strong><span>Not, puan veya ayrıntılı öğrenci sonucu gibi hassas bilgiler mesaj gövdesine zorunlu olarak yazılmaz; duyuru paneldeki güvenli ekrana yönlendirilebilir.</span></div></div>
   <button className="primary" disabled={busy||!title.trim()||!body.trim()||(audienceType==='CLASS'&&!classId)} onClick={()=>void create()}>{scheduledAt?<CalendarClock size={16}/>:<Send size={16}/>} {scheduledAt?'Planla':'Taslak Oluştur'}</button>
  </div>
  <div className="section-head"><div><h2>Gönderim geçmişi</h2><p>Panel, WhatsApp ve SMS fallback teslimatları ayrı ayrı izlenir.</p></div><MessageCircle/></div>
  <div className="table-card"><table><thead><tr><th>Duyuru</th><th>Tür</th><th>Hedef</th><th>Kanallar</th><th>Durum</th><th>Teslimat</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.title}</strong><div className="muted">{x.created_at}</div></td><td>{x.announcement_type}</td><td>{x.audience_type}</td><td>{(x.channels||[]).join(' + ')}{x.sms_fallback?' + SMS yedek':''}</td><td><span className={`status ${x.status==='SENT'?'ok':'neutral'}`}>{x.status}</span></td><td>{x.sent_count||0}/{x.delivery_count||0}</td><td>{x.status!=='SENT'&&x.status!=='SCHEDULED'&&<button className="ghost" disabled={busy} onClick={()=>void send(x.id)}><Send size={14}/> Gönder</button>}</td></tr>)}</tbody></table>{!items.length&&<div className="empty">Henüz duyuru oluşturulmadı.</div>}</div>
 </>;
}
