import {useEffect,useMemo,useState} from 'react';
import {BookOpen,CheckCircle2,ChevronRight,Link2,Save,Users} from 'lucide-react';
import {api,qs} from '../api';
import {useAuth} from '../auth';
import {ClassSelect,InstitutionSelect} from '../components/EntitySelectors';

const initial={title:'',description:'',dueAt:'',sourceKind:'PHYSICAL_BOOK',sourceLabel:'',physicalBookId:'',worksheetId:'',digitalUrl:'',pageStart:1,pageEnd:10};
const statusLabel=(value:string)=>({ASSIGNED:'Başlamadı',STARTED:'Devam ediyor',COMPLETED:'Tamamlandı',EXCUSED:'Muaf'} as Record<string,string>)[value]||value;

export function AssignmentCenter(){
 const{user}=useAuth();const student=user?.role==='STUDENT';const[institutionId,setInstitutionId]=useState(''),[classId,setClassId]=useState(''),[options,setOptions]=useState<any>({classes:[],students:[],worksheets:[],physicalBooks:[]});const[selectedStudents,setSelectedStudents]=useState<string[]>([]),[form,setForm]=useState(initial),[rows,setRows]=useState<any[]>([]),[detail,setDetail]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const scope=qs({institutionId:user?.role==='SUPER_ADMIN'?institutionId:null});
 const loadRows=async()=>{const r=await api<any>(`/api/assignment-center${scope}`);setRows(r.assignments||[])};
 useEffect(()=>{if(user?.role==='SUPER_ADMIN'&&!institutionId)return;void loadRows().catch(e=>setError(e.message))},[institutionId,user?.role]);
 useEffect(()=>{if(student)return;if(user?.role==='SUPER_ADMIN'&&!institutionId){setOptions({classes:[],students:[],worksheets:[],physicalBooks:[]});return}void api<any>(`/api/assignment-center/options${qs({institutionId:user?.role==='SUPER_ADMIN'?institutionId:null,classId:classId||null})}`).then(r=>{setOptions(r);if(classId)setSelectedStudents((r.students||[]).map((x:any)=>x.id))}).catch(e=>setError(e.message))},[institutionId,classId,user?.role,student]);
 const open=async(id:string)=>{setBusy(true);try{setDetail(await api<any>(`/api/assignment-center/${id}`))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const create=async()=>{setBusy(true);setError('');setNotice('');try{const result=await api<any>('/api/assignment-center',{method:'POST',body:JSON.stringify({...form,institutionId:user?.role==='SUPER_ADMIN'?institutionId:null,classId,studentIds:selectedStudents})});setNotice(`${result.recipientCount} öğrenciye ödev verildi.`);setForm(initial);await loadRows();await open(result.id)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const updateProgress=async(assignmentId:string,studentId:string,progress:number,status?:string)=>{setBusy(true);try{await api(`/api/assignment-center/${assignmentId}/recipients/${studentId}`,{method:'PATCH',body:JSON.stringify({progress,status})});await open(assignmentId);await loadRows()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const allSelected=options.students?.length>0&&selectedStudents.length===options.students.length;const completion=useMemo(()=>rows.reduce((sum,row)=>sum+Number(row.completed_count||0),0),[rows]);
 if(student)return <StudentAssignments rows={rows} detail={detail} busy={busy} error={error} open={open} updateProgress={updateProgress}/>;
 return <><div className="page-head"><div><span className="eyebrow">Ödev Verme ve Takip</span><h1>Fiziksel ve dijital ödev merkezi</h1><p>Kitap sayfası, dijital kitap bağlantısı, föy veya serbest görevi sınıfa ya da seçili öğrencilere verin; tamamlanmayı tek ekrandan izleyin.</p></div></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="summary-strip"><Summary label="Ödev" value={rows.length}/><Summary label="Tamamlayan öğrenci" value={completion}/><Summary label="Seçili sınıf" value={classId?1:0}/></div>
 <div className="panel assignment-create"><div className="panel-head"><div><h2>Yeni ödev</h2><p>Önce sınıfı ve kaynağı seçin; sınıf öğrencileri güvenli biçimde otomatik gelir.</p></div><BookOpen/></div><div className="form-grid">{user?.role==='SUPER_ADMIN'&&<InstitutionSelect value={institutionId} onChange={id=>{setInstitutionId(id);setClassId('')}}/>}<ClassSelect value={classId} onChange={setClassId} institutionId={user?.role==='SUPER_ADMIN'?institutionId:undefined} required/><label>Ödev başlığı<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Son tarih<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label>Kaynak türü<select value={form.sourceKind} onChange={e=>setForm({...form,sourceKind:e.target.value})}><option value="PHYSICAL_BOOK">Fiziksel kitap</option><option value="DIGITAL_BOOK">Dijital kitap</option><option value="WORKSHEET">Föy</option><option value="TASK">Serbest görev</option></select></label>{form.sourceKind==='PHYSICAL_BOOK'&&<label>Kitap<select value={form.physicalBookId} onChange={e=>setForm({...form,physicalBookId:e.target.value})}><option value="">Kitap seçin</option>{options.physicalBooks?.map((x:any)=><option key={x.id} value={x.id}>{x.title}{x.isbn_or_code?` · ${x.isbn_or_code}`:''}</option>)}</select></label>}{form.sourceKind==='WORKSHEET'&&<label>Föy<select value={form.worksheetId} onChange={e=>setForm({...form,worksheetId:e.target.value})}><option value="">Föy seçin</option>{options.worksheets?.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}{form.sourceKind==='DIGITAL_BOOK'&&<label>Dijital kitap bağlantısı<input type="url" value={form.digitalUrl} onChange={e=>setForm({...form,digitalUrl:e.target.value})} placeholder="https://..."/></label>}{['PHYSICAL_BOOK','DIGITAL_BOOK'].includes(form.sourceKind)&&<><label>Başlangıç sayfası<input type="number" min="1" value={form.pageStart} onChange={e=>setForm({...form,pageStart:Number(e.target.value)})}/></label><label>Bitiş sayfası<input type="number" min={form.pageStart} value={form.pageEnd} onChange={e=>setForm({...form,pageEnd:Number(e.target.value)})}/></label></>}<label>Kaynak etiketi<input value={form.sourceLabel} onChange={e=>setForm({...form,sourceLabel:e.target.value})} placeholder="Kitap/föy bölüm adı"/></label></div><label>Açıklama<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
 {classId&&<div className="recipient-picker"><div><strong>Öğrenciler · {selectedStudents.length}/{options.students?.length||0}</strong><button className="ghost" onClick={()=>setSelectedStudents(allSelected?[]:(options.students||[]).map((x:any)=>x.id))}>{allSelected?'Tümünü kaldır':'Tüm sınıfı seç'}</button></div><div>{options.students?.map((x:any)=><label key={x.id}><input type="checkbox" checked={selectedStudents.includes(x.id)} onChange={()=>setSelectedStudents(current=>current.includes(x.id)?current.filter(id=>id!==x.id):[...current,x.id])}/><span>{x.first_name} {x.last_name}<small>{x.student_number||'Numara yok'}</small></span></label>)}</div></div>}
 <button className="primary" disabled={busy||!classId||!form.title.trim()||!selectedStudents.length} onClick={()=>void create()}><Save size={16}/> Ödevi Ver</button></div>
 <div className="assignment-layout"><div className="table-card"><table><thead><tr><th>Ödev</th><th>Sınıf</th><th>Kaynak</th><th>İlerleme</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.title}</strong><small>{row.due_at||'Son tarih yok'}</small></td><td>{row.class_name||'—'}</td><td>{sourceLabel(row.source_kind)}</td><td>{row.completed_count||0}/{row.recipient_count||0}<small>%{Math.round(Number(row.average_progress||0))}</small></td><td><button className="ghost" onClick={()=>void open(row.id)}>Aç <ChevronRight size={14}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">Henüz ödev bulunmuyor.</div>}</div>{detail&&<AssignmentDetail detail={detail} busy={busy} updateProgress={updateProgress} close={()=>setDetail(null)}/>}</div></>;
}

function AssignmentDetail({detail,busy,updateProgress,close}:{detail:any;busy:boolean;updateProgress:(a:string,s:string,p:number,status?:string)=>Promise<void>;close:()=>void}){const a=detail.assignment;return <div className="panel assignment-detail"><div className="panel-head"><div><span className="eyebrow">{sourceLabel(a.source_kind)} · {a.class_name}</span><h2>{a.title}</h2><p>{a.description||a.item?.label}</p></div><button className="ghost" onClick={close}>Kapat</button></div><SourceInfo assignment={a}/><div className="cards-list">{detail.recipients.map((r:any)=><div className="list-card" key={r.student_id}><div><strong>{r.first_name} {r.last_name}</strong><span>{r.student_number||'—'} · {statusLabel(r.status)} · %{Math.round(Number(r.progress||0))}</span></div><div className="assignment-progress-actions"><button disabled={busy} className="secondary" onClick={()=>void updateProgress(a.id,r.student_id,50)}>Başladı</button><button disabled={busy} className="primary" onClick={()=>void updateProgress(a.id,r.student_id,100)}>Tamamlandı</button><button disabled={busy} className="ghost" onClick={()=>void updateProgress(a.id,r.student_id,0,'EXCUSED')}>Muaf</button></div></div>)}</div></div>}
function StudentAssignments({rows,detail,busy,error,open,updateProgress}:{rows:any[];detail:any;busy:boolean;error:string;open:(id:string)=>Promise<void>;updateProgress:(a:string,s:string,p:number)=>Promise<void>}){const{user}=useAuth();return <><div className="page-head"><div><span className="eyebrow">Ödevlerim</span><h1>Çalışma listem</h1><p>Fiziksel kitap, dijital kaynak ve föy ödevlerini takip edin; başladığınızda ve bitirdiğinizde ilerlemenizi güncelleyin.</p></div></div>{error&&<div className="alert error">{error}</div>}<div className="exam-grid">{rows.map(row=><div className="exam-card" key={row.id}><span className="pill">{sourceLabel(row.source_kind)}</span><h3>{row.title}</h3><p>{row.class_name} · {row.due_at||'Son tarih yok'}</p><div className="progress-track"><span style={{width:`${row.progress||0}%`}}/></div><strong>%{Math.round(Number(row.progress||0))} · {statusLabel(row.recipient_status)}</strong><button className="secondary full" onClick={()=>void open(row.id)}>Ayrıntı</button>{row.recipient_status!=='COMPLETED'&&<div style={{display:'flex',gap:6}}><button disabled={busy} className="ghost" onClick={()=>void updateProgress(row.id,user!.student_id!,50)}>Başladım</button><button disabled={busy} className="primary" onClick={()=>void updateProgress(row.id,user!.student_id!,100)}><CheckCircle2 size={15}/> Tamamladım</button></div>}</div>)}</div>{detail&&<div className="panel" style={{marginTop:16}}><div className="panel-head"><div><h2>{detail.assignment.title}</h2><p>{detail.assignment.description}</p></div></div><SourceInfo assignment={detail.assignment}/></div>}</>}
function SourceInfo({assignment}:{assignment:any}){const item=assignment.item||{};return <div className="alert info"><strong>{item.label||sourceLabel(assignment.source_kind)}</strong>{item.pageStart&&<> · Sayfa {item.pageStart}–{item.pageEnd}</>}{item.url&&<> · <a href={item.url} target="_blank" rel="noreferrer"><Link2 size={13}/> Dijital kaynağı aç</a></>}</div>}
function sourceLabel(value:string){return({PHYSICAL_BOOK:'Fiziksel Kitap',DIGITAL_BOOK:'Dijital Kitap',WORKSHEET:'Föy',TASK:'Görev'} as Record<string,string>)[value]||value}
function Summary({label,value}:{label:string;value:number}){return <div className="summary"><span>{label}</span><strong>{value}</strong></div>}
