import { useEffect,useMemo,useState } from 'react';
import { CalendarCheck,CheckCircle2,Clock3,Save,UserMinus,Users } from 'lucide-react';
import { api } from '../api';

const STATUS_OPTIONS=[['PRESENT','Geldi'],['ABSENT','Gelmedi'],['LATE','Geç'],['EXCUSED','İzinli']] as const;
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}

export function AttendanceCenter(){
 const[classes,setClasses]=useState<any[]>([]),[classId,setClassId]=useState(''),[date,setDate]=useState(today()),[students,setStudents]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{void api<any>('/api/classes').then(r=>{setClasses(r.classes||[]);if(r.classes?.[0])setClassId(r.classes[0].id)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!classId||!date)return;setBusy(true);void api<any>(`/api/school/attendance?classId=${encodeURIComponent(classId)}&date=${date}`).then(r=>setStudents(r.students||[])).catch(e=>setError(e.message)).finally(()=>setBusy(false))},[classId,date]);
 const summary=useMemo(()=>Object.fromEntries(STATUS_OPTIONS.map(([key])=>[key,students.filter(s=>s.attendance_status===key).length])),[students]);
 const setStatus=(id:string,status:string)=>setStudents(rows=>rows.map(row=>row.id===id?{...row,attendance_status:status}:row));
 const save=async()=>{setBusy(true);setError('');setMessage('');try{await api('/api/school/attendance',{method:'POST',body:JSON.stringify({classId,date,records:students.map(s=>({studentId:s.id,status:s.attendance_status,note:s.note||null}))})});setMessage('Yoklama kaydedildi. Kurum ve veli bildirim akışlarında kullanılabilir.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <div className="role-dashboard attendance-page"><section className="role-welcome"><div><span className="eyebrow">Kurum operasyonları</span><h1>Yoklama Merkezi</h1><p>Sınıf yoklamasını mobilde tek dokunuşla, webde toplu ve hızlı biçimde kaydedin.</p></div><div className="role-welcome-icon"><CalendarCheck/></div></section>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<section className="panel attendance-toolbar"><div className="form-grid"><label>Sınıf<select value={classId} onChange={e=>setClassId(e.target.value)}>{classes.map(c=><option value={c.id} key={c.id}>{c.name} · {c.student_count} öğrenci</option>)}</select></label><label>Tarih<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div></section><div className="summary-strip attendance-summary"><div className="summary"><Users/><span>Toplam</span><strong>{students.length}</strong></div><div className="summary"><CheckCircle2/><span>Geldi</span><strong>{summary.PRESENT||0}</strong></div><div className="summary warn"><UserMinus/><span>Gelmedi</span><strong>{summary.ABSENT||0}</strong></div><div className="summary"><Clock3/><span>Geç / İzinli</span><strong>{(summary.LATE||0)+(summary.EXCUSED||0)}</strong></div></div><section className="panel"><div className="panel-head"><div><h2>Öğrenci listesi</h2><p>Varsayılan durum “Geldi”dir; yalnız farklı durumu olan öğrencileri değiştirin.</p></div><button className="primary" disabled={busy||!students.length} onClick={()=>void save()}><Save size={17}/> Yoklamayı Kaydet</button></div><div className="attendance-list">{students.map(student=><div className="attendance-row" key={student.id}><div className="avatar">{String(student.first_name||'?').charAt(0)}</div><div className="attendance-student"><strong>{student.first_name} {student.last_name}</strong><span>{student.student_number||'Numara yok'}</span></div><div className="attendance-statuses">{STATUS_OPTIONS.map(([key,label])=><button key={key} className={student.attendance_status===key?`selected status-${key.toLowerCase()}`:''} onClick={()=>setStatus(student.id,key)}>{label}</button>)}</div></div>)}{!busy&&!students.length&&<div className="empty">Seçilen sınıfta aktif öğrenci bulunmuyor.</div>}</div></section></div>
}
