import { useEffect,useState } from 'react';
import { Layers3,RefreshCw } from 'lucide-react';
import { api,qs } from '../api';
import { useAuth } from '../auth';

export function BulkOperations(){
 const{user}=useAuth();const[institutions,setInstitutions]=useState<any[]>([]);const[institutionId,setInstitutionId]=useState('');const[data,setData]=useState<any>({classes:[],worksheets:[],exams:[]});const[selected,setSelected]=useState<string[]>([]);const[operation,setOperation]=useState<'ASSIGN_WORKSHEET'|'CREATE_EXAM_PARTICIPANTS'>('ASSIGN_WORKSHEET');const[worksheetId,setWorksheetId]=useState('');const[examId,setExamId]=useState('');const[dueDate,setDueDate]=useState('');const[notice,setNotice]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{if(user?.role==='SUPER_ADMIN')void api<any>('/api/institutions').then(r=>{setInstitutions(r.institutions||[]);if(r.institutions?.[0])setInstitutionId(r.institutions[0].id)});},[user?.role]);
 const load=async()=>{setError('');try{const r=await api<any>(`/api/v2/bulk/options${qs({institutionId:user?.role==='SUPER_ADMIN'?institutionId:null})}`);setData(r);setSelected([]);if(r.worksheets?.[0])setWorksheetId(r.worksheets[0].id);if(r.exams?.[0])setExamId(r.exams[0].id);}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(user?.role!=='SUPER_ADMIN'||institutionId)void load()},[institutionId,user?.role]);
 const toggle=(id:string,on:boolean)=>setSelected(cur=>on?[...new Set([...cur,id])]:cur.filter(x=>x!==id));
 const run=async()=>{if(!selected.length)return;setBusy(true);setError('');setNotice('');try{const r=await api<any>('/api/v2/bulk/execute',{method:'POST',body:JSON.stringify({institutionId:user?.role==='SUPER_ADMIN'?institutionId:undefined,operation,classIds:selected,worksheetId:operation==='ASSIGN_WORKSHEET'?worksheetId:undefined,examId:operation==='CREATE_EXAM_PARTICIPANTS'?examId:undefined,dueDate:dueDate||null})});setNotice(`İşlem tamamlandı. ${r.summary.created||0} kayıt oluşturuldu, ${r.summary.skipped||0} mevcut kayıt atlandı.`);await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <>
  <div className="page-head"><div><span className="eyebrow">Toplu İşlemler</span><h1>Sınıf bazlı hızlı operasyon</h1><p>Tek tek işlem yapmak yerine seçili sınıflara föy veya sınav katılımcısı topluca atayın.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel"><div className="panel-head"><div><h2>İşlem seçimi</h2><p>İşlemler kurum sınırı içinde ve audit kaydıyla çalışır.</p></div><Layers3/></div><div className="form-grid">{user?.role==='SUPER_ADMIN'&&<label>Kurum<select value={institutionId} onChange={e=>setInstitutionId(e.target.value)}>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}<label>İşlem<select value={operation} onChange={e=>setOperation(e.target.value as any)}><option value="ASSIGN_WORKSHEET">Föy Ata</option><option value="CREATE_EXAM_PARTICIPANTS">Sınav Katılımcılarını Oluştur</option></select></label>{operation==='ASSIGN_WORKSHEET'?<><label>Föy<select value={worksheetId} onChange={e=>setWorksheetId(e.target.value)}>{data.worksheets.map((w:any)=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label><label>Son tarih<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></>:<label>Sınav<select value={examId} onChange={e=>setExamId(e.target.value)}>{data.exams.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}</div></div>
  <div className="table-card"><table><thead><tr><th><input type="checkbox" checked={data.classes.length>0&&selected.length===data.classes.length} onChange={e=>setSelected(e.target.checked?data.classes.map((c:any)=>c.id):[])}/></th><th>Sınıf</th><th>Düzey</th><th>Öğrenci</th></tr></thead><tbody>{data.classes.map((c:any)=><tr key={c.id}><td><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>toggle(c.id,e.target.checked)}/></td><td><strong>{c.name}</strong></td><td>{c.grade_level}. sınıf / {c.section}</td><td>{c.student_count}</td></tr>)}</tbody></table>{!data.classes.length&&<div className="empty">Aktif sınıf bulunmuyor.</div>}</div>
  <div style={{marginTop:16}}><button className="primary" disabled={!selected.length||busy||(operation==='ASSIGN_WORKSHEET'&&!worksheetId)||(operation==='CREATE_EXAM_PARTICIPANTS'&&!examId)} onClick={run}>{busy?'İşleniyor…':`${selected.length} sınıfa uygula`}</button></div>
 </>;
}
