import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2,Printer,RefreshCw,Upload,Wrench } from 'lucide-react';
import { api,post,qs } from '../api';
import { useAuth } from '../auth';
import { analyzeCalibrationImage,type CalibrationAnalysis } from '../lib/calibrationAnalyzer';
import { calibrationCorrection,calibrationTransform } from '../lib/printCalibration';

export function Calibration(){
 const{user}=useAuth();const[institutions,setInstitutions]=useState<any[]>([]);const[institutionId,setInstitutionId]=useState('');const[profiles,setProfiles]=useState<any[]>([]);const[templates,setTemplates]=useState<any[]>([]);const[rows,setRows]=useState<any[]>([]);const[profileId,setProfileId]=useState('');const[templateId,setTemplateId]=useState('');const[profileName,setProfileName]=useState('');const[printerHint,setPrinterHint]=useState('');const[cal,setCal]=useState<any>(null);const[image,setImage]=useState<File|null>(null);const[analysis,setAnalysis]=useState<CalibrationAnalysis|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 useEffect(()=>{if(user?.role==='SUPER_ADMIN')void api<any>('/api/institutions').then(r=>{setInstitutions(r.institutions||[]);if(r.institutions?.[0])setInstitutionId(r.institutions[0].id)}).catch(e=>setError(e.message))},[user?.role]);
 const instQ=user?.role==='SUPER_ADMIN'?institutionId:null;
 const load=async()=>{if(user?.role==='SUPER_ADMIN'&&!institutionId)return;setError('');const suffix=qs({institutionId:instQ});const[p,t,c]=await Promise.all([api<any>(`/api/printer-profiles${suffix}`),api<any>('/api/optical-templates'),api<any>(`/api/calibrations${suffix}`)]);setProfiles(p.profiles||[]);setTemplates((t.templates||[]).filter((x:any)=>x.version_id&&x.has_print));setRows(c.calibrations||[]);setProfileId(cur=>(p.profiles||[]).some((x:any)=>x.id===cur)?cur:(p.profiles?.[0]?.id||''));setTemplateId(cur=>(t.templates||[]).some((x:any)=>x.version_id===cur&&x.has_print)?cur:((t.templates||[]).find((x:any)=>x.version_id&&x.has_print)?.version_id||''))};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[institutionId,user?.role]);
 const createProfile=async()=>{if(!profileName.trim())return;setBusy(true);setError('');try{const r=await post<any>('/api/printer-profiles',{institutionId:instQ,name:profileName.trim(),physicalPrinterHint:printerHint.trim()||profileName.trim()});setProfileName('');setPrinterHint('');await load();if(r.id)setProfileId(r.id);setNotice('Yazıcı profili oluşturuldu. Şimdi kullanılacak optikle kalibre edin.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const start=async()=>{setError('');setNotice('');setImage(null);setAnalysis(null);try{const r=await post<any>('/api/calibrations/start',{printerProfileId:profileId,templateVersionId:templateId});setCal(r);setNotice('Kalibrasyon testi hazır. İşletim sistemi yazdırma penceresinde bu profile karşılık gelen fiziksel yazıcıyı seçin.')}catch(e:any){setError(e.message)}};
 const analyze=async(f:File)=>{setImage(f);setBusy(true);setError('');try{setAnalysis(await analyzeCalibrationImage(f))}catch(e:any){setError(e.message||'Görsel analiz edilemedi.')}finally{setBusy(false)}};
 const submit=async(mode='AUTO')=>{if(!image||!analysis||!cal)return;setBusy(true);setError('');try{const fd=new FormData();fd.append('image',image);fd.append('metrics',JSON.stringify(analysis));fd.append('mode',mode);const r=await api<any>(`/api/calibrations/${cal.calibration.id}/attempt`,{method:'POST',body:fd});setCal((x:any)=>({...x,calibration:r.calibration||{...x.calibration,status:r.status,attempt_count:r.attemptNo}}));setImage(null);setAnalysis(null);await load();if(r.status==='READY')setNotice('Kalibrasyon doğrulandı. Bu yazıcı + optik kombinasyonu artık baskıya hazır.');else if(r.status==='MANUAL_REQUIRED')setNotice('Üç otomatik düzeltme tamamlandı. Kalan sapma için manuel ince ayar ve son görsel doğrulaması gerekiyor.');else setNotice(`Otomatik düzeltme ${r.attemptNo}/3 kaydedildi. Yeni test sayfası bu düzeltmeyi otomatik uygulayacak; tekrar basıp görseli yükleyin.`)}catch(e:any){setError(e.message||'Kalibrasyon kaydedilemedi.')}finally{setBusy(false)}};
 const correction=useMemo(()=>calibrationCorrection(cal?.calibration),[cal?.calibration]);
 return <>
  <div className="page-head"><div><span className="eyebrow">Yazıcı + optik profili</span><h1>Kalibrasyon</h1><p>Her fiziksel yazıcı ve optik kombinasyonu ayrı saklanır. Sistem X/Y kaydırma, yatay-dikey ölçek ve dönüş hatasını 2–3 test baskısında otomatik azaltır.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {user?.role==='SUPER_ADMIN'&&<div className="panel"><label>Kurum<select value={institutionId} onChange={e=>{setInstitutionId(e.target.value);setCal(null)}}><option value="">Kurum seç</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div>}
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel"><div className="panel-head"><div><h2>1. Yazıcı profili</h2><p>Profil fiziksel yazıcının sistemdeki adıdır; gerçek cihazı Windows/macOS yazdırma penceresinden seçersiniz.</p></div><Printer/></div><div className="form-grid"><label>Profil adı<input value={profileName} onChange={e=>setProfileName(e.target.value)} placeholder="Canon Öğretmenler Odası"/></label><label>Fiziksel yazıcı ipucu<input value={printerHint} onChange={e=>setPrinterHint(e.target.value)} placeholder="Canon i-SENSYS ..."/></label></div><button className="secondary" disabled={busy||!profileName.trim()} onClick={createProfile}>+ Yazıcı Profili Oluştur</button></div>
  <div className="panel"><div className="panel-head"><div><h2>2. Yazıcı + optik eşleştir</h2><p>Optik 840, Optik 129 veya yeni tanımladığınız her optik için bu yazıcıya özel kalibrasyon tutulur.</p></div><Wrench/></div><div className="form-grid"><label>Yazıcı profili<select value={profileId} onChange={e=>{setProfileId(e.target.value);setCal(null)}}><option value="">Yazıcı seç</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Optik<select value={templateId} onChange={e=>{setTemplateId(e.target.value);setCal(null)}}><option value="">Optik seç</option>{templates.map(t=><option value={t.version_id} key={t.version_id}>{t.name} · {t.version}</option>)}</select></label></div><button className="primary" onClick={start} disabled={!profileId||!templateId}><Wrench size={17}/> Kalibre Et / Yeniden Kalibre Et</button></div>
  {cal&&<div className="panel calibration-work"><div className="panel-head"><div><h2>Otomatik Kalibrasyon {Math.min((cal.calibration.attempt_count||0)+1,3)}/3</h2><p>{cal.template.name} · {cal.template.pageWidthMm}×{cal.template.pageHeightMm} mm · Test baskısında Fit to Page kapalı olmalı.</p></div><span className={`status ${cal.calibration.status==='READY'?'ok':cal.calibration.status==='MANUAL_REQUIRED'?'warn':'neutral'}`}>{cal.calibration.status}</span></div>
   {(cal.calibration.attempt_count||0)>0&&<div className="alert info">Bir önceki ölçüme göre düzeltme bu test sayfasına uygulanıyor: X {correction.correctionOffsetX.toFixed(2)} mm · Y {correction.correctionOffsetY.toFixed(2)} mm · Ölçek {correction.correctionScaleX.toFixed(5)} / {correction.correctionScaleY.toFixed(5)} · Dönüş {correction.correctionRotation.toFixed(3)}°.</div>}
   <CalibrationSheet calibration={cal.calibration}/><button className="secondary" onClick={()=>window.print()}><Printer size={17}/> Test Sayfasını Yazdır</button><label className="upload-zone"><Upload/><strong>Basılmış test sayfasını yükle</strong><span>Tam sayfa tarama en güvenilir; telefonda mümkün olduğunca dik açı ve sayfanın tamamı görünmeli.</span><input type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&analyze(e.target.files[0])}/></label>{analysis&&<div className="metrics"><Metric l="X sapma" v={`${analysis.offset_x_mm} mm`}/><Metric l="Y sapma" v={`${analysis.offset_y_mm} mm`}/><Metric l="Scale X" v={analysis.scale_x}/><Metric l="Scale Y" v={analysis.scale_y}/><Metric l="Dönüş" v={`${analysis.rotation_deg}°`}/><Metric l="Güven" v={`%${Math.round(analysis.confidence*100)}`}/></div>}{analysis&&<p className="muted">{analysis.note}</p>}{cal.calibration.status==='MANUAL_REQUIRED'&&<div className="alert warning">Üç otomatik denemeden sonra tolerans sağlanamadı. Yazıcı sürücüsündeki ölçek/kenar boşluğu ayarını düzeltin veya küçük fiziksel sapmayı giderin; ardından aynı test sayfasını yeniden basıp son görseli “Manuel Doğrula” ile yükleyin.</div>}<button className="primary huge" onClick={()=>submit(cal.calibration.status==='MANUAL_REQUIRED'?'MANUAL_VERIFY':'AUTO')} disabled={!analysis||busy}>{cal.calibration.status==='MANUAL_REQUIRED'?'Manuel Ayarı Görselle Doğrula':'Ölçümü Kaydet ve Otomatik Düzelt'}</button>{cal.calibration.status==='READY'&&<div className="success-box"><CheckCircle2/><div><strong>Kalibrasyon doğrulandı</strong><span>Bu yazıcı + optik kombinasyonu Optik Hazırla / Bas ekranında otomatik kullanılacak.</span></div></div>}</div>}
  <div className="section-head"><div><h2>Kayıtlı yazıcı + optik kombinasyonları</h2><p>Kalibrasyon bir kez tamamlanınca sonraki baskılarda yeniden ayar gerekmez.</p></div></div><div className="table-card"><table><thead><tr><th>Yazıcı</th><th>Optik</th><th>Durum</th><th>Deneme</th><th>Kayıtlı düzeltme temeli</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.printer_name}</strong></td><td>{r.template_name} · {r.template_version}</td><td><span className={`status ${r.status==='READY'?'ok':r.status==='MANUAL_REQUIRED'?'warn':'neutral'}`}>{r.status}</span></td><td>{r.attempt_count}</td><td>X {Number(r.offset_x_mm).toFixed(2)} · Y {Number(r.offset_y_mm).toFixed(2)} · S {Number(r.scale_x).toFixed(5)}/{Number(r.scale_y).toFixed(5)} · R {Number(r.rotation_deg).toFixed(3)}°</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">Henüz kalibre edilmiş yazıcı + optik kombinasyonu yok.</div>}</div>
 </>;
}

function CalibrationSheet({calibration}:{calibration:any}){return <div className="calibration-sheet print-only-sheet"><div style={{position:'absolute',inset:0,transformOrigin:'0 0',transform:calibrationTransform(calibration)}}><div className="target tl"/><div className="target tr"/><div className="target bl"/><div className="target br"/><div className="cal-center"><strong>OTOMATİK KALİBRASYON TESTİ</strong><span>Actual Size / %100 · Fit to Page kapalı</span><small>Sayfanın tamamını tarayın veya mümkün olduğunca dik açıdan fotoğraflayın.</small></div></div></div>}
function Metric({l,v}:{l:string;v:string|number}){return <div><span>{l}</span><strong>{v}</strong></div>}
