import { useEffect,useState } from 'react';
import { CheckCircle2, Printer, Upload, Wrench } from 'lucide-react';
import { api, post, qs } from '../api';
import { useAuth } from '../auth';
import { analyzeCalibrationImage, type CalibrationAnalysis } from '../lib/calibrationAnalyzer';

export function Calibration(){const{user}=useAuth();const[institutionId,setInstitutionId]=useState('inst_demo');const[profiles,setProfiles]=useState<any[]>([]);const[templates,setTemplates]=useState<any[]>([]);const[rows,setRows]=useState<any[]>([]);const[profileId,setProfileId]=useState('');const[templateId,setTemplateId]=useState('');const[cal,setCal]=useState<any>(null);const[image,setImage]=useState<File|null>(null);const[analysis,setAnalysis]=useState<CalibrationAnalysis|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const instQ=user?.role==='SUPER_ADMIN'?institutionId:null;const load=async()=>{const [p,t,c]=await Promise.all([api<any>(`/api/printer-profiles${qs({institutionId:instQ})}`),api<any>('/api/optical-templates'),api<any>(`/api/calibrations${qs({institutionId:instQ})}`)]);setProfiles(p.profiles);setTemplates(t.templates.filter((x:any)=>x.version_id));setRows(c.calibrations);if(!profileId&&p.profiles[0])setProfileId(p.profiles[0].id);if(!templateId&&t.templates[0])setTemplateId(t.templates[0].version_id)};useEffect(()=>{void load()},[institutionId]);
 const createProfile=async()=>{const name=prompt('Yazıcı profil adı (örn. Canon Öğretmenler Odası)');if(!name)return;await post('/api/printer-profiles',{institutionId:instQ,name,physicalPrinterHint:name});await load()};
 const start=async()=>{setError('');try{const r=await post<any>('/api/calibrations/start',{printerProfileId:profileId,templateVersionId:templateId});setCal(r)}catch(e){setError(e instanceof Error?e.message:'Başlatılamadı.')}};
 const analyze=async(f:File)=>{setImage(f);setBusy(true);setError('');try{setAnalysis(await analyzeCalibrationImage(f))}catch(e){setError(e instanceof Error?e.message:'Görsel analiz edilemedi.')}finally{setBusy(false)}};
 const submit=async(mode='AUTO')=>{if(!image||!analysis||!cal)return;setBusy(true);const fd=new FormData();fd.append('image',image);fd.append('metrics',JSON.stringify(analysis));fd.append('mode',mode);try{const r=await api<any>(`/api/calibrations/${cal.calibration.id}/attempt`,{method:'POST',body:fd});setCal((x:any)=>({...x,calibration:{...x.calibration,status:r.status,attempt_count:r.attemptNo}}));await load();if(r.status==='READY')setError('')}catch(e){setError(e instanceof Error?e.message:'Kalibrasyon kaydedilemedi.')}finally{setBusy(false)}};
 return <><div className="page-head"><div><span className="eyebrow">Yazıcı + optik profili</span><h1>Kalibrasyon</h1><p>Test sayfasını yazdırın, PC’den tarama/fotoğraf yükleyin; sistem 2–3 denemede ölçümü düzeltir, gerekirse manuel doğrulama açar.</p></div>{user?.role==='SUPER_ADMIN'&&<label className="compact-field">Kurum<input value={institutionId} onChange={e=>setInstitutionId(e.target.value)}/></label>}</div><div className="panel"><div className="panel-head"><div><h2>Kalibrasyon başlat</h2><p>Fiziksel yazıcıyı tarayıcı değil, işletim sistemi yazdırma penceresinde siz seçersiniz.</p></div><button className="secondary" onClick={createProfile}>+ Yazıcı Profili</button></div><div className="form-grid"><label>Yazıcı profili<select value={profileId} onChange={e=>setProfileId(e.target.value)}>{profiles.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Optik<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option value={t.version_id} key={t.version_id}>{t.name}</option>)}</select></label></div><button className="primary" onClick={start} disabled={!profileId||!templateId}><Wrench size={17}/> Kalibre Et</button></div>
 {cal&&<div className="panel calibration-work"><div className="panel-head"><div><h2>Otomatik Kalibrasyon {Math.min((cal.calibration.attempt_count||0)+1,3)}/3</h2><p>{cal.template.name} · A4 {cal.template.pageWidthMm}×{cal.template.pageHeightMm} mm</p></div><span className={`status ${cal.calibration.status==='READY'?'ok':cal.calibration.status==='MANUAL_REQUIRED'?'warn':'neutral'}`}>{cal.calibration.status}</span></div><CalibrationSheet/><button className="secondary" onClick={()=>window.print()}><Printer size={17}/> Test Sayfasını Yazdır</button><label className="upload-zone"><Upload/><strong>Basılmış sayfanın görselini yükle</strong><span>Tam sayfa tarama en güvenilir yöntemdir.</span><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&analyze(e.target.files[0])}/></label>{analysis&&<div className="metrics"><Metric l="X" v={`${analysis.offset_x_mm} mm`}/><Metric l="Y" v={`${analysis.offset_y_mm} mm`}/><Metric l="Scale X" v={analysis.scale_x}/><Metric l="Scale Y" v={analysis.scale_y}/><Metric l="Dönüş" v={`${analysis.rotation_deg}°`}/><Metric l="Güven" v={`%${Math.round(analysis.confidence*100)}`}/></div>}{analysis&&<p className="muted">{analysis.note}</p>}{cal.calibration.status==='MANUAL_REQUIRED'&&<div className="alert info">3 otomatik denemeden sonra tolerans sağlanamadı. Yazıcı/driver ayarını manuel düzeltin, yeni test baskısı alın ve aşağıdaki doğrulama ile tekrar yükleyin.</div>}<button className="primary huge" onClick={()=>submit(cal.calibration.status==='MANUAL_REQUIRED'?'MANUAL_VERIFY':'AUTO')} disabled={!analysis||busy}>{cal.calibration.status==='MANUAL_REQUIRED'?'Manuel Ayarı Görselle Doğrula':'Görseli Analiz Sonucuyla Kaydet'}</button>{cal.calibration.status==='READY'&&<div className="success-box"><CheckCircle2/><div><strong>Kalibrasyon doğrulandı</strong><span>Bu yazıcı + optik kombinasyonu hazır.</span></div></div>}</div>}
 {error&&<div className="alert error">{error}</div>}<div className="section-head"><div><h2>Kalibre edilmiş kombinasyonlar</h2></div></div><div className="table-card"><table><thead><tr><th>Yazıcı</th><th>Optik</th><th>Durum</th><th>Deneme</th><th>Son ayar</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.printer_name}</strong></td><td>{r.template_name}</td><td><span className={`status ${r.status==='READY'?'ok':r.status==='MANUAL_REQUIRED'?'warn':'neutral'}`}>{r.status}</span></td><td>{r.attempt_count}</td><td>X {Number(r.offset_x_mm).toFixed(2)} · Y {Number(r.offset_y_mm).toFixed(2)}</td></tr>)}</tbody></table></div></>}
function CalibrationSheet(){return <div className="calibration-sheet print-only-sheet"><div className="target tl"/><div className="target tr"/><div className="target bl"/><div className="target br"/><div className="cal-center"><strong>OTOMATİK KALİBRASYON TESTİ</strong><span>Actual Size / %100 · Fit to Page kapalı</span><small>Sayfanın tamamını tarayın veya mümkün olduğunca dik açıdan fotoğraflayın.</small></div></div>}
function Metric({l,v}:{l:string;v:string|number}){return <div><span>{l}</span><strong>{v}</strong></div>}
