import { useEffect,useState } from 'react';
import { CalendarRange,CheckCircle2,RefreshCw,Settings2,ShieldAlert } from 'lucide-react';
import { api } from '../api';

const statusLabel:Record<string,string>={PLANNED:'Planlandı',VERIFIED_CURRICULUM_REQUIRED:'Doğrulanmış müfredat gerekli',OUTCOMES_REQUIRED:'Kazanım gerekli'};
export function CompletionCenter(){
 const[data,setData]=useState<any>(null);const[plans,setPlans]=useState<any>(null);const[form,setForm]=useState({academicYear:'2026-2027',weekCount:16,questionsPerSubject:20,grades:[5,6,7,8,9,10,11,12]});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[lastResult,setLastResult]=useState<any>(null);
 const load=async()=>{setError('');try{const[c,p]=await Promise.all([api<any>('/api/admin/completion-center'),api<any>('/api/admin/annual-content-plans')]);setData(c);setPlans(p)}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);
 const generate=async()=>{setBusy(true);setError('');setNotice('');try{const r=await api<any>('/api/admin/annual-content-plans/generate',{method:'POST',body:JSON.stringify(form)});setLastResult(r);setNotice('Doğrulanmış müfredata dayalı yıllık plan üretimi tamamlandı. Eksik sınıflar açıkça işaretlendi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const toggle=(grade:number)=>setForm({...form,grades:form.grades.includes(grade)?form.grades.filter(x=>x!==grade):[...form.grades,grade].sort((a,b)=>a-b)});
 return <><div className="page-head"><div><span className="eyebrow">Ürün kapanış ve aktivasyon</span><h1>Tamamlanma Merkezi</h1><p>Kodla tamamlanan parçaları, dış sağlayıcı bağımlılıklarını ve yıllık içerik üretim omurgasını tek ekranda izleyin.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="summary-strip"><Summary label="Doğrulanmış müfredat" value={data?.counts?.verified_curricula||0}/><Summary label="Resmî dosya bekliyor" value={data?.counts?.official_files_required||0}/><Summary label="Onaylı soru" value={data?.counts?.approved_questions||0}/><Summary label="Hazır optik" value={data?.counts?.ready_opticals||0}/><Summary label="Doğrulanmış aktarım" value={data?.counts?.verified_transfer_adapters||0}/><Summary label="100K canlı test" value={data?.counts?.completed_100k_tests||0}/><Summary label="Bekleyen üyelik" value={data?.counts?.pending_membership_orders||0}/></div>
 <h2 style={{marginTop:22}}>Dış servis aktivasyonları</h2><div className="cards-list">{(data?.integrations||[]).map((x:any)=><div className="list-card" key={x.integration_key}><div className="quick-icon">{x.active?<CheckCircle2 size={18}/>:<Settings2 size={18}/>}</div><div><strong>{x.label}</strong><span>{x.category} · {x.configuredParts}/{x.totalParts} güvenli ayar tamamlandı</span><small>{x.codeReady?(x.requiredSecrets||[]).join(' · '):'Sağlayıcı adaptörü / mağaza projesi henüz uygulanmadı'}</small></div><span className={`status ${x.active?'success':'warning'}`}>{x.active?'AKTİF':x.codeReady?'DIŞ KURULUM':'KOD BEKLİYOR'}</span></div>)}</div><div className="alert info" style={{marginTop:14}}><ShieldAlert size={18}/><div><strong>Güvenli sınır</strong><span>Secret değerleri bu ekrana veya veritabanına yazılmaz. Rehber Öğretmen AI ve Branş Öğretmeni AI sonraki faza ayrılmıştır.</span></div></div>
 <div className="panel" style={{marginTop:22}}><div className="panel-head"><div><h2>16 sayısal + 16 sözel yıllık föy planlayıcı</h2><p>Her föyde ders başına 20 soru hedefler; yalnız kaynak URL’si doğrulanmış müfredat ve mevcut kazanımları kullanır.</p></div><CalendarRange/></div><div className="form-grid"><label>Akademik yıl<input value={form.academicYear} onChange={e=>setForm({...form,academicYear:e.target.value})}/></label><label>Her seride föy sayısı<input type="number" min="1" max="52" value={form.weekCount} onChange={e=>setForm({...form,weekCount:Number(e.target.value)})}/></label><label>Her ders için soru hedefi<input type="number" min="5" max="100" value={form.questionsPerSubject} onChange={e=>setForm({...form,questionsPerSubject:Number(e.target.value)})}/></label></div><div style={{display:'flex',gap:7,flexWrap:'wrap',margin:'12px 0'}}>{[5,6,7,8,9,10,11,12].map(g=><button key={g} className={form.grades.includes(g)?'primary':'secondary'} onClick={()=>toggle(g)}>{g}. sınıf</button>)}</div><button className="primary" disabled={busy||!form.grades.length} onClick={()=>void generate()}>{busy?'Planlanıyor…':'Yıllık planları üret / yenile'}</button></div>
 {lastResult&&<div className="cards-list">{lastResult.results.map((r:any)=><div className="list-card" key={r.grade}><strong>{r.grade}. sınıf</strong><span>{statusLabel[r.status]||r.status}{r.slots?` · ${r.subjects} ders · ${r.numericIssues} sayısal + ${r.verbalIssues} sözel föy · ${r.slots} ders slotu`:''}</span></div>)}</div>}
 <div className="table-card" style={{marginTop:18}}><table><thead><tr><th>Yıl / sınıf</th><th>Müfredat kaynağı</th><th>Her seri</th><th>Ders slotu</th><th>Soru hazır</th><th>Yayınlandı</th><th>Durum</th></tr></thead><tbody>{(plans?.plans||[]).map((p:any)=><tr key={p.id}><td>{p.academic_year} · {p.grade_level}. sınıf</td><td>{p.source_title}<br/><small>{p.program_version}</small></td><td>{p.week_count} föy</td><td>{p.slot_count}</td><td>{p.ready_count}</td><td>{p.published_count}</td><td><span className="status neutral">{p.status}</span></td></tr>)}{plans&&!plans.plans?.length&&<tr><td colSpan={7}>Henüz yıllık plan üretilmedi.</td></tr>}</tbody></table></div>
 </>;
}
function Summary({label,value}:{label:string;value:any}){return <div className="summary"><span>{label}</span><strong>{value}</strong></div>}
