import { useEffect,useState } from 'react';
import { BookOpen, FileText, PlaySquare, Plus, RefreshCw, WandSparkles } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';

function difficultyMeta(q:any){const n=Number(q?.difficulty||3);if(q?.difficulty_band==='EASY'||n<=2)return {band:'easy',label:'Mavi · Kolay',color:'blue'};if(q?.difficulty_band==='HARD'||n>=4)return {band:'hard',label:'Kırmızı · Zor',color:'red'};return {band:'medium',label:'Yeşil · Orta',color:'green'}}

export function ContentCenter(){
 const {user}=useAuth();const [tab,setTab]=useState<'questions'|'studio'|'videos'>('questions');const [questions,setQuestions]=useState<any[]>([]);const [docs,setDocs]=useState<any[]>([]);const [videos,setVideos]=useState<any[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [qform,setQform]=useState({stemText:'',gradeLevel:'8',subjectId:'sub_math',difficulty:'3',correctAnswer:'A',solutionText:''});
 const [dform,setDform]=useState({title:'',documentType:'PRACTICE_EXAM',gradeLevel:'8',subjectId:'sub_math',questionCount:'20'});
 const [vform,setVform]=useState({title:'',url:'',gradeLevel:'8',subjectId:'sub_math'});
 const load=async()=>{setError('');try{const tasks:any[]=[];tasks.push(api<any>('/api/platform/questions').catch(()=>({questions:[]})));tasks.push(api<any>('/api/platform/studio').catch(()=>({documents:[]})));tasks.push(api<any>('/api/platform/videos').catch(()=>({videos:[]})));const [q,d,v]=await Promise.all(tasks);setQuestions(q.questions||[]);setDocs(d.documents||[]);setVideos(v.videos||[])}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);
 const addQuestion=async()=>{try{const r=await api<any>('/api/platform/questions',{method:'POST',body:JSON.stringify({...qform,gradeLevel:Number(qform.gradeLevel),difficulty:Number(qform.difficulty),options:['A','B','C','D','E']})});setNotice(`Soru kaydedildi · ${r.id}`);setQform(f=>({...f,stemText:'',solutionText:''}));await load()}catch(e:any){setError(e.message)}};
 const createDoc=async()=>{try{const r=await api<any>('/api/platform/studio',{method:'POST',body:JSON.stringify({...dform,gradeLevel:Number(dform.gradeLevel),questionCount:Number(dform.questionCount)})});setNotice(`Belge taslağı oluşturuldu · ${r.selectedQuestions}/${r.requestedQuestions} soru seçildi.`);setDform(f=>({...f,title:''}));await load()}catch(e:any){setError(e.message)}};
 const addVideo=async()=>{try{await api('/api/platform/videos',{method:'POST',body:JSON.stringify({...vform,gradeLevel:Number(vform.gradeLevel),approved:true})});setNotice('Video kütüphaneye eklendi.');setVform(f=>({...f,title:'',url:''}));await load()}catch(e:any){setError(e.message)}};
 const currentDifficulty=difficultyMeta(qform);
 return <><div className="page-head"><div><span className="eyebrow">İçerik Motoru</span><h1>Soru · Studio · Video</h1><p>Soru havuzu tek kaynak olarak yazılı, deneme, ödev, Recovery, akıllı tahta ve kişisel kitap üretiminde kullanılacak.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div style={{display:'flex',gap:8,marginBottom:16}}><button className={tab==='questions'?'primary':'secondary'} onClick={()=>setTab('questions')}><BookOpen size={16}/> Soru Havuzu</button><button className={tab==='studio'?'primary':'secondary'} onClick={()=>setTab('studio')}><WandSparkles size={16}/> Studio</button><button className={tab==='videos'?'primary':'secondary'} onClick={()=>setTab('videos')}><PlaySquare size={16}/> Video</button></div>
 {tab==='questions'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Yeni soru</h2><p>Kendi, AI üretimi, açık lisanslı veya izinli sorular tam soru havuzunda tutulabilir. Telifli resmî sorular yalnız analitik referans olarak ayrı merkezde izlenir.</p></div><Plus/></div><div className="form-grid"><label>Sınıf<input type="number" value={qform.gradeLevel} onChange={e=>setQform({...qform,gradeLevel:e.target.value})}/></label><label>Ders kodu<input value={qform.subjectId} onChange={e=>setQform({...qform,subjectId:e.target.value})}/></label><label>Zorluk<select value={qform.difficulty} onChange={e=>setQform({...qform,difficulty:e.target.value})}><option value="1">1 · Kolay</option><option value="2">2 · Kolay+</option><option value="3">3 · Orta</option><option value="4">4 · Zor</option><option value="5">5 · Çok Zor</option></select><span className={`difficulty-badge ${currentDifficulty.band}`} style={{marginTop:6}}><span className={`difficulty-dot ${currentDifficulty.color}`}/>{currentDifficulty.label}</span></label><label>Doğru cevap<input value={qform.correctAnswer} onChange={e=>setQform({...qform,correctAnswer:e.target.value.toUpperCase()})}/></label></div><label>Soru metni<textarea rows={4} value={qform.stemText} onChange={e=>setQform({...qform,stemText:e.target.value})}/></label><label>Çözüm<textarea rows={3} value={qform.solutionText} onChange={e=>setQform({...qform,solutionText:e.target.value})}/></label><button className="primary" onClick={addQuestion} disabled={!qform.stemText.trim()}>Soruyu Kaydet</button></div><div className="table-card"><table><thead><tr><th>Soru</th><th>Sınıf</th><th>Ders</th><th>Zorluk</th><th>Durum</th></tr></thead><tbody>{questions.map(q=>{const d=difficultyMeta(q);return <tr key={q.id}><td><strong>{q.stem_text}</strong><small>{q.topic||''} {q.subtopic||''}</small></td><td>{q.grade_level||'—'}</td><td>{q.subject_name||q.subject_id||'—'}</td><td><span className={`difficulty-badge ${d.band}`}><span className={`difficulty-dot ${d.color}`}/>{d.label}</span><small>Seviye {q.difficulty}</small></td><td><span className="status neutral">{q.review_status}</span></td></tr>})}</tbody></table></div></>}
 {tab==='studio'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Yazılı / Deneme oluştur</h2><p>Onaylı soru havuzundan hedef sayıda soru seçerek taslak oluşturur. Öğretmen kontrolünden sonra baskı aşamasına alınır.</p></div><FileText/></div><div className="form-grid"><label>Başlık<input value={dform.title} onChange={e=>setDform({...dform,title:e.target.value})}/></label><label>Tür<select value={dform.documentType} onChange={e=>setDform({...dform,documentType:e.target.value})}><option value="PRACTICE_EXAM">Deneme</option><option value="WRITTEN_EXAM">Yazılı</option><option value="WORKSHEET">Föy</option><option value="PERSONAL_BOOK">Kişisel Kitap</option></select></label><label>Sınıf<input type="number" value={dform.gradeLevel} onChange={e=>setDform({...dform,gradeLevel:e.target.value})}/></label><label>Ders kodu<input value={dform.subjectId} onChange={e=>setDform({...dform,subjectId:e.target.value})}/></label><label>Soru sayısı<input type="number" value={dform.questionCount} onChange={e=>setDform({...dform,questionCount:e.target.value})}/></label></div><button className="primary" onClick={createDoc} disabled={!dform.title.trim()}><WandSparkles size={16}/> Taslak Oluştur</button></div><div className="table-card"><table><thead><tr><th>Belge</th><th>Tür</th><th>Sınıf</th><th>Soru</th><th>Durum</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><strong>{d.title}</strong></td><td>{d.document_type}</td><td>{d.grade_level||'—'}</td><td>{d.question_count||0}</td><td><span className="status neutral">{d.status}</span></td></tr>)}</tbody></table></div></>}
 {tab==='videos'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Video ekle</h2><p>YouTube veya kendi video kaynağını kazanım/sınıf/ders ile eşleştirin.</p></div><PlaySquare/></div>{user?.role==='SUPER_ADMIN'&&<><div className="form-grid"><label>Başlık<input value={vform.title} onChange={e=>setVform({...vform,title:e.target.value})}/></label><label>URL<input value={vform.url} onChange={e=>setVform({...vform,url:e.target.value})}/></label><label>Sınıf<input type="number" value={vform.gradeLevel} onChange={e=>setVform({...vform,gradeLevel:e.target.value})}/></label><label>Ders kodu<input value={vform.subjectId} onChange={e=>setVform({...vform,subjectId:e.target.value})}/></label></div><button className="primary" onClick={addVideo} disabled={!vform.title||!vform.url}>Videoyu Ekle</button></>}</div><div className="exam-grid">{videos.map(v=><div className="exam-card" key={v.id}><span className="pill">{v.provider}</span><h3>{v.title}</h3><p>{v.grade_level?`${v.grade_level}. sınıf · `:''}{v.subject_name||''}</p><a className="secondary full" href={v.url} target="_blank" rel="noreferrer">Videoyu Aç</a></div>)}</div></>}
 </>;
}
