import { useEffect, useState } from 'react';
import { CheckCircle2, CircleAlert, FileUp, RefreshCw, ShieldCheck } from 'lucide-react';
import { api, qs } from '../api';

type Program='SCHOOL'|'TYT'|'AYT';

export function CurriculumAdmin(){
 const[year,setYear]=useState('2026-2027');const[program,setProgram]=useState<Program>('SCHOOL');const[grade,setGrade]=useState(7);const[programVersion,setProgramVersion]=useState('');const[authority,setAuthority]=useState('MEB');const[sourceUrl,setSourceUrl]=useState('');const[sourceTitle,setSourceTitle]=useState('');const[sourcePublishedAt,setSourcePublishedAt]=useState('');const[file,setFile]=useState<File|null>(null);
 const[versions,setVersions]=useState<any[]>([]);const[job,setJob]=useState<any>(null);const[jobRows,setJobRows]=useState<any[]>([]);const[selectedVersion,setSelectedVersion]=useState<any>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
 const loadVersions=async()=>{const r=await api<any>(`/api/curriculum-admin${qs({academicYear:year,programCode:program})}`);setVersions(r.versions||[])};useEffect(()=>{void loadVersions().catch(e=>setError(e.message))},[year,program]);
 const preview=async()=>{if(!file)return;setBusy(true);setError('');setNotice('');setJob(null);setJobRows([]);try{const fd=new FormData();fd.append('file',file);fd.append('academicYear',year);fd.append('programCode',program);if(program==='SCHOOL')fd.append('gradeLevel',String(grade));fd.append('programVersion',programVersion);fd.append('authority',authority);fd.append('sourceUrl',sourceUrl);fd.append('sourceTitle',sourceTitle);if(sourcePublishedAt)fd.append('sourcePublishedAt',sourcePublishedAt);const r=await api<any>('/api/curriculum-admin/import-preview',{method:'POST',body:fd});setJob(r);setJobRows(r.preview||[]);setNotice(r.invalidCount===0?`${r.validCount} satır doğrulandı. Veritabanına yazılmadan önce son onay bekliyor.`:`${r.invalidCount} satır düzeltme gerektiriyor; aktarım henüz yapılamaz.`)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const reloadJob=async()=>{if(!job?.jobId)return;const r=await api<any>(`/api/curriculum-admin/imports/${job.jobId}`);setJob((j:any)=>({...j,...r.job}));setJobRows(r.rows||[])};
 const commit=async()=>{if(!job?.jobId||!confirm('Yüklediğiniz dosyanın belirtilen resmî kaynaktan alındığını doğruluyor musunuz? Bu işlem yeni, doğrulanmış müfredat sürümü oluşturacaktır.'))return;setBusy(true);setError('');setNotice('');try{const r=await api<any>(`/api/curriculum-admin/imports/${job.jobId}/commit`,{method:'POST',body:JSON.stringify({confirmedOfficial:true})});setNotice(`${r.outcomeCount} resmî kazanım/öğrenme çıktısı sürümlü olarak aktarıldı.`);await Promise.all([loadVersions(),reloadJob()])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const openVersion=async(id:string)=>{setError('');try{const r=await api<any>(`/api/curriculum-admin/versions/${id}`);setSelectedVersion(r)}catch(e:any){setError(e.message)}};
 return <>
  <div className="page-head"><div><span className="eyebrow">Resmî Veri Merkezi</span><h1>Müfredat & Kazanımlar</h1><p>Resmî MEB/TTKB/ÖSYM verisini kaynak bilgisi, dosya özeti ve onay kaydıyla sürümlü olarak içeri alın. Sistem eksik kazanım uydurmaz.</p></div><button className="ghost" onClick={()=>void loadVersions()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel"><div className="panel-head"><div><h2>Resmî kazanım CSV aktarımı</h2><p>Önce staging önizleme yapılır. Hatalı satır varsa hiçbir outcome kaydı yazılmaz.</p></div><ShieldCheck/></div><div className="form-grid"><label>Akademik yıl<input value={year} onChange={e=>setYear(e.target.value)} placeholder="2026-2027"/></label><label>Program<select value={program} onChange={e=>setProgram(e.target.value as Program)}><option value="SCHOOL">Okul Müfredatı</option><option value="TYT">TYT</option><option value="AYT">AYT</option></select></label>{program==='SCHOOL'&&<label>Sınıf<input type="number" min="1" max="12" value={grade} onChange={e=>setGrade(Number(e.target.value))}/></label>}<label>Müfredat/Program sürümü<input value={programVersion} onChange={e=>setProgramVersion(e.target.value)} placeholder="Örn. TYMM-2026-v1"/></label><label>Yetkili kaynak<select value={authority} onChange={e=>setAuthority(e.target.value)}><option value="MEB">MEB</option><option value="TTKB">TTKB</option><option value="ÖSYM">ÖSYM</option></select></label><label>Resmî doküman adı<input value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)} placeholder="Dokümanın resmî adı"/></label><label>Resmî kaynak URL<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://...meb.gov.tr/..."/></label><label>Kaynak yayın tarihi<input type="date" value={sourcePublishedAt} onChange={e=>setSourcePublishedAt(e.target.value)}/></label><label>CSV dosyası<input type="file" accept=".csv,text/csv,text/plain" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="alert info"><strong>CSV başlıkları:</strong> subject_code, grade_level, outcome_code, topic, subtopic, title. TYT/AYT için grade_level boş olabilir. Ders kodu sistemdeki ders koduyla eşleşmelidir.</div><button className="primary" disabled={busy||!file||!programVersion.trim()||!sourceUrl.trim()||!sourceTitle.trim()} onClick={preview}><FileUp size={16}/> Önizleme ve Doğrulama</button></div>
  {job&&<div className="panel" style={{marginTop:20}}><div className="panel-head"><div><h2>Aktarım önizlemesi</h2><p>Job: {job.jobId} · kaynağın SHA-256 özeti saklandı.</p></div>{Number(job.invalidCount??job.invalid_count)===0?<CheckCircle2/>:<CircleAlert/>}</div><div className="summary-strip"><Summary label="Toplam" value={job.rowCount??job.row_count}/><Summary label="Geçerli" value={job.validCount??job.valid_count}/><Summary label="Hatalı" value={job.invalidCount??job.invalid_count} warn/></div><div style={{overflowX:'auto',marginTop:12}}><table><thead><tr><th>Satır</th><th>Ders</th><th>Sınıf</th><th>Kod</th><th>Konu</th><th>Kazanım / Öğrenme Çıktısı</th><th>Durum</th></tr></thead><tbody>{jobRows.slice(0,100).map((r:any)=><tr key={r.rowNo??r.row_no}><td>{r.rowNo??r.row_no}</td><td>{r.subjectCode??r.subject_code}</td><td>{r.gradeLevel??r.grade_level??'—'}</td><td>{r.outcomeCode??r.outcome_code??'—'}</td><td>{r.topic||'—'}</td><td>{r.title}</td><td>{(r.issues||[]).length?<span className="status warn">{r.issues.join(' · ')}</span>:<span className="status ok">Hazır</span>}</td></tr>)}</tbody></table></div><div style={{display:'flex',gap:8,marginTop:14}}><button className="ghost" onClick={reloadJob}>Job'u Yenile</button><button className="primary" disabled={busy||Number(job.invalidCount??job.invalid_count)!==0||job.status==='COMMITTED'} onClick={commit}><ShieldCheck size={16}/> Resmî Kaynak Olarak Onayla ve Aktar</button></div></div>}
  <div className="section-head"><div><h2>Doğrulanmış sürümler</h2><p>Föy ve sınav kazanım eşleştirmeleri bu sürümlere bağlanır; geçmiş sürüm değiştirilmez.</p></div></div><div className="table-card"><table><thead><tr><th>Akademik yıl</th><th>Program</th><th>Sürüm</th><th>Kaynak</th><th>Durum</th><th>Kazanım</th><th></th></tr></thead><tbody>{versions.map(v=><tr key={v.id}><td>{v.academic_year}</td><td>{v.program_code}{v.grade_level?` · ${v.grade_level}. sınıf`:''}</td><td><strong>{v.program_version}</strong></td><td>{v.authority}<br/><small>{v.source_title||v.source_url||'—'}</small></td><td>{v.verified?<span className="status ok">Doğrulandı</span>:<span className="status warn">Doğrulama gerekli</span>}</td><td>{v.outcome_count||0} · {v.subject_count||0} ders</td><td><button className="ghost" onClick={()=>openVersion(v.id)}>Görüntüle</button></td></tr>)}</tbody></table>{!versions.length&&<div className="empty">Bu filtrede müfredat sürümü yok.</div>}</div>
  {selectedVersion&&<div className="panel" style={{marginTop:20}}><div className="panel-head"><div><h2>{selectedVersion.version.program_version}</h2><p>{selectedVersion.version.authority} · {selectedVersion.version.source_title} · {selectedVersion.outcomes.length} kayıt</p></div><CheckCircle2/></div><div style={{overflowX:'auto'}}><table><thead><tr><th>Ders</th><th>Kod</th><th>Konu</th><th>Alt konu</th><th>Kazanım / Öğrenme Çıktısı</th></tr></thead><tbody>{selectedVersion.outcomes.slice(0,500).map((o:any)=><tr key={o.id}><td>{o.subject_name}</td><td>{o.code||'—'}</td><td>{o.topic||'—'}</td><td>{o.subtopic||'—'}</td><td>{o.title}</td></tr>)}</tbody></table></div></div>}
 </>;
}
function Summary({label,value,warn}:{label:string;value:any;warn?:boolean}){return <div className={warn&&Number(value)>0?'summary warn':'summary'}><span>{label}</span><strong>{value??0}</strong></div>}
