import { useEffect, useState } from 'react';
import { CheckCircle2, Eraser, RefreshCw, ShieldCheck, UserCheck } from 'lucide-react';
import { api } from '../api';

type PrivacyRequest = { id: string; request_type: string; status: string; identity_verification_status: string; subject_user_id?: string|null; subject_student_id?: string|null; received_at?: string };
type DeletionJob = { id: string; request_id?: string|null; mode: string; status: string; reason_code: string; affected_records?: number|null; created_at?: string };

export function DataLifecycle(){
  const [overview,setOverview]=useState<any>(null); const [requests,setRequests]=useState<PrivacyRequest[]>([]); const [jobs,setJobs]=useState<DeletionJob[]>([]);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const load=async()=>{setBusy(true);setError('');try{const [o,r,j]=await Promise.all([api<any>('/api/admin/privacy/overview'),api<any>('/api/admin/privacy/requests'),api<any>('/api/admin/privacy/deletion-jobs')]);setOverview(o);setRequests(r.items||[]);setJobs(j.items||[])}catch(e:any){setError(e.message||'Veri yaşam döngüsü yüklenemedi.')}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const verify=async(id:string)=>{setBusy(true);setError('');try{await api(`/api/admin/privacy/requests/${id}/verify`,{method:'POST'});setNotice('Kimlik doğrulama adımı kaydedildi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const queue=async(request:PrivacyRequest)=>{if(!confirm('Bu doğrulanmış talep için hukuk incelemesine silme işi açılsın mı?'))return;setBusy(true);setError('');try{await api('/api/admin/privacy/deletion-jobs',{method:'POST',body:JSON.stringify({requestId:request.id,mode:request.request_type,reasonCode:'USER_REQUEST'})});setNotice('Silme işi hukuk incelemesine alındı; veri hemen silinmedi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const counts=overview?.counts||{};
  return <div className="data-lifecycle-page"><div className="page-head"><div><span className="eyebrow">ANUNEX · VERİ YÖNETİMİ</span><h1>Veri Silme</h1><p>Silme ve anonimleştirme işlemleri doğrulama, hukuk incelemesi ve denetlenebilir iş kaydıyla yürütülür.</p></div><button className="ghost" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/> Yenile</button></div>
    {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
    <div className="summary-strip"><div className="summary"><span>Açık başvuru</span><strong>{counts.open_requests||0}</strong></div><div className="summary"><span>Açık silme işi</span><strong>{counts.open_deletion_jobs||0}</strong></div><div className="summary"><span>Saklama politikası bekleyen</span><strong>{counts.retention_pending||0}</strong></div><div className="summary"><span>Aktif işlem kaydı</span><strong>{counts.processing_activities||0}</strong></div></div>
    <div className="panel" style={{marginTop:16}}><div className="panel-head"><div><h2>KVKK başvuruları</h2><p>Kimlik doğrulanmadan silme veya anonimleştirme işi oluşturulamaz.</p></div><ShieldCheck/></div><div className="table-card"><table><thead><tr><th>Talep</th><th>Tür</th><th>Durum</th><th>Kimlik</th><th></th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><strong>{r.id}</strong><small>{r.subject_student_id||r.subject_user_id||'Konu belirtilmedi'}</small></td><td>{r.request_type==='ANONYMIZE'?'Anonimleştir':'Silme'}</td><td>{r.status}</td><td>{r.identity_verification_status}</td><td>{r.identity_verification_status!=='VERIFIED'?<button className="secondary" disabled={busy} onClick={()=>void verify(r.id)}><UserCheck size={15}/> Kimliği doğrula</button>:['DELETE','ANONYMIZE'].includes(r.request_type)&&r.status!=='COMPLETED'?<button className="primary" disabled={busy} onClick={()=>void queue(r)}><Eraser size={15}/> İncelemeye al</button>:<CheckCircle2 size={16}/>}</td></tr>)}{!requests.length&&<tr><td colSpan={5}><div className="empty">Açık veri talebi bulunmuyor.</div></td></tr>}</tbody></table></div></div>
    <div className="panel" style={{marginTop:16}}><div className="panel-head"><div><h2>Silme / anonimleştirme işleri</h2><p>Bu liste yalnız iş kaydını gösterir; yürütme onayı ve kanıtı olmadan veri kaldırılmaz.</p></div><Eraser/></div><div className="table-card"><table><thead><tr><th>İş</th><th>Mod</th><th>Durum</th><th>Neden</th><th>Oluşturulma</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><strong>{j.id}</strong><small>{j.request_id||'Başvuru yok'}</small></td><td>{j.mode}</td><td>{j.status}</td><td>{j.reason_code}</td><td>{j.created_at?new Date(j.created_at).toLocaleString('tr-TR'):'—'}</td></tr>)}{!jobs.length&&<tr><td colSpan={5}><div className="empty">Henüz silme işi bulunmuyor.</div></td></tr>}</tbody></table></div></div>
  </div>;
}
