import { useEffect,useMemo,useState } from 'react';
import { BarChart3,Building2,Download,Network,RefreshCw,School,ShieldCheck,Store,Users } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';

const unitLabels:Record<string,string>={HEADQUARTERS:'Genel Merkez',REGION:'Bölge',PROVINCE:'İl',DISTRICT:'İlçe',CAMPUS:'Kampüs'};
const number=(value:unknown)=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(Number(value||0));

export function EnterpriseCenter(){
 const {user}=useAuth();const [tab,setTab]=useState('networks');const [networks,setNetworks]=useState<any[]>([]);const [publishers,setPublishers]=useState<any[]>([]);const [campaigns,setCampaigns]=useState<any[]>([]);const [campus,setCampus]=useState<any>(null);const [institutions,setInstitutions]=useState<any[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [netForm,setNetForm]=useState({name:'',code:'',headquartersInstitutionId:''});const [pubForm,setPubForm]=useState({name:'',code:''});const [admForm,setAdmForm]=useState({title:'',campaignType:'SCHOLARSHIP'});const [campusForm,setCampusForm]=useState({subdomain:'',customDomain:'',welcomeText:'',enabled:false});
 const load=async()=>{const [n,p,a,c,i]=await Promise.all([api<any>('/api/platform/networks').catch(()=>({networks:[]})),api<any>('/api/platform/publishers').catch(()=>({publishers:[]})),api<any>('/api/platform/admissions').catch(()=>({campaigns:[]})),api<any>('/api/platform/campus').catch(()=>null),user?.role==='SUPER_ADMIN'?api<any>('/api/institutions').catch(()=>({institutions:[]})):Promise.resolve({institutions:[]})]);setNetworks(n.networks||[]);setPublishers(p.publishers||[]);setCampaigns(a.campaigns||[]);setCampus(c?.campus||null);setInstitutions(i.institutions||[]);if(c?.campus)setCampusForm({subdomain:c.campus.subdomain||'',customDomain:c.campus.custom_domain||'',welcomeText:c.campus.welcome_text||'',enabled:!!c.campus.enabled})};useEffect(()=>{void load()},[]);
 const addNetwork=async()=>{try{setError('');await api('/api/platform/networks',{method:'POST',body:JSON.stringify(netForm)});setNotice('Kurum ağı ve genel merkez hiyerarşisi oluşturuldu.');setNetForm({name:'',code:'',headquartersInstitutionId:''});await load()}catch(e:any){setError(e.message)}};
 const addPublisher=async()=>{try{await api('/api/platform/publishers',{method:'POST',body:JSON.stringify(pubForm)});setNotice('Yayınevi tanımlandı.');setPubForm({name:'',code:''});await load()}catch(e:any){setError(e.message)}};
 const addCampaign=async()=>{try{await api('/api/platform/admissions',{method:'POST',body:JSON.stringify(admForm)});setNotice('Kabul/bursluluk kampanyası oluşturuldu.');setAdmForm({title:'',campaignType:'SCHOLARSHIP'});await load()}catch(e:any){setError(e.message)}};
 const saveCampus=async()=>{try{await api('/api/platform/campus',{method:'PUT',body:JSON.stringify(campusForm)});setNotice('Campus ayarları kaydedildi.');await load()}catch(e:any){setError(e.message)}};
 return <><div className="page-head"><div><span className="eyebrow">Enterprise</span><h1>Zincir Kurum ve Platform Merkezi</h1><p>Genel merkezden kampüse yetki kontrollü yönetim, karşılaştırmalı KPI ve merkezi raporlama.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="enterprise-tabs"><button className={tab==='networks'?'primary':'secondary'} onClick={()=>setTab('networks')}><Network size={16}/> Zincirler</button>{user?.role==='SUPER_ADMIN'&&<button className={tab==='publishers'?'primary':'secondary'} onClick={()=>setTab('publishers')}><Store size={16}/> Yayınevleri</button>}<button className={tab==='admissions'?'primary':'secondary'} onClick={()=>setTab('admissions')}><Users size={16}/> Admissions</button><button className={tab==='campus'?'primary':'secondary'} onClick={()=>setTab('campus')}><School size={16}/> Campus</button></div>
 {tab==='networks'&&<NetworkExecutive networks={networks} institutions={institutions} isSuper={user?.role==='SUPER_ADMIN'} onCreate={addNetwork} netForm={netForm} setNetForm={setNetForm} setError={setError} setNotice={setNotice}/>}
 {tab==='publishers'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Yayınevi merkezi</h2><p>Merkezi denemelerde kurum/öğrenci katılımı ve soru analitiği için yayıncı kimliği.</p></div><Store/></div><div className="form-grid"><label>Yayınevi adı<input value={pubForm.name} onChange={e=>setPubForm({...pubForm,name:e.target.value})}/></label><label>Kod<input value={pubForm.code} onChange={e=>setPubForm({...pubForm,code:e.target.value.toUpperCase()})}/></label></div><button className="primary" onClick={addPublisher} disabled={!pubForm.name||!pubForm.code}>Yayınevini Ekle</button></div><div className="table-card"><table><thead><tr><th>Yayınevi</th><th>Kod</th><th>Sınav</th><th>Durum</th></tr></thead><tbody>{publishers.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.code}</td><td>{p.exam_count||0}</td><td><span className="status ok">Aktif</span></td></tr>)}</tbody></table></div></>}
 {tab==='admissions'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Bursluluk / kabul / seviye tespit</h2><p>Aday öğrenci kampanyaları mevcut sınav motoruyla bağlanır.</p></div><Users/></div><div className="form-grid"><label>Kampanya adı<input value={admForm.title} onChange={e=>setAdmForm({...admForm,title:e.target.value})}/></label><label>Tür<select value={admForm.campaignType} onChange={e=>setAdmForm({...admForm,campaignType:e.target.value})}><option value="SCHOLARSHIP">Bursluluk</option><option value="PLACEMENT">Seviye Tespit</option><option value="ADMISSION">Kabul</option></select></label></div><button className="primary" onClick={addCampaign} disabled={!admForm.title}>Kampanya Oluştur</button></div><div className="exam-grid">{campaigns.map(c=><div className="exam-card" key={c.id}><span className="pill">{c.campaign_type}</span><h3>{c.title}</h3><p>{c.candidate_count||0} aday · {c.status}</p></div>)}</div></>}
 {tab==='campus'&&<div className="panel"><div className="panel-head"><div><h2>Okul logolu Campus</h2><p>Subdomain, özel domain ve kurum karşılama mesajını yönetin.</p></div><Building2/></div><div className="form-grid"><label>Subdomain<input value={campusForm.subdomain} onChange={e=>setCampusForm({...campusForm,subdomain:e.target.value})} placeholder="okuladi"/></label><label>Özel domain<input value={campusForm.customDomain} onChange={e=>setCampusForm({...campusForm,customDomain:e.target.value})} placeholder="akademi.okuladi.com"/></label></div><label>Karşılama metni<textarea rows={3} value={campusForm.welcomeText} onChange={e=>setCampusForm({...campusForm,welcomeText:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={campusForm.enabled} onChange={e=>setCampusForm({...campusForm,enabled:e.target.checked})}/> Campus alanını etkinleştir</label><button className="primary" onClick={saveCampus}>Kaydet</button></div>}
 </>;
}

function NetworkExecutive({networks,institutions,isSuper,onCreate,netForm,setNetForm,setError,setNotice}:any){
 const [selected,setSelected]=useState('');const [dashboard,setDashboard]=useState<any>(null);const [roles,setRoles]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [filters,setFilters]=useState({unitId:'',from:'',to:''});
 const [unitForm,setUnitForm]=useState({name:'',code:'',unitType:'REGION',parentUnitId:'',city:'',district:''});const [memberForm,setMemberForm]=useState({institutionId:'',unitId:'',regionLabel:''});const [roleForm,setRoleForm]=useState({userId:'',role:'NETWORK_VIEWER',scopeUnitId:''});
 useEffect(()=>{if(!selected&&networks[0]?.id)setSelected(networks[0].id)},[networks,selected]);
 const query=()=>{const p=new URLSearchParams();if(filters.unitId)p.set('unitId',filters.unitId);if(filters.from)p.set('from',filters.from);if(filters.to)p.set('to',filters.to);return p.toString()};
 const loadDashboard=async()=>{if(!selected)return;try{setBusy(true);setError('');const d=await api<any>(`/api/platform/networks/${selected}/dashboard?${query()}`);setDashboard(d);if(d.permission?.canManage){const r=await api<any>(`/api/platform/networks/${selected}/roles`);setRoles(r.roles||[])}else setRoles([])}catch(e:any){setError(e.message);setDashboard(null)}finally{setBusy(false)}};
 useEffect(()=>{void loadDashboard()},[selected]);
 const act=async(path:string,body:any,method='POST',message='İşlem tamamlandı.')=>{try{setError('');await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});setNotice(message);await loadDashboard();return true}catch(e:any){setError(e.message);return false}};
 const addUnit=async()=>{if(await act(`/api/platform/networks/${selected}/units`,unitForm,'POST','Hiyerarşi birimi eklendi.'))setUnitForm({name:'',code:'',unitType:'REGION',parentUnitId:'',city:'',district:''})};
 const addMember=async()=>{if(await act(`/api/platform/networks/${selected}/members`,memberForm,'POST','Kurum zincire bağlandı.'))setMemberForm({institutionId:'',unitId:'',regionLabel:''})};
 const addRole=async()=>{if(await act(`/api/platform/networks/${selected}/roles`,roleForm,'POST','Zincir yetkisi kaydedildi.'))setRoleForm({userId:'',role:'NETWORK_VIEWER',scopeUnitId:''})};
 const availableInstitutions=useMemo(()=>institutions.filter((i:any)=>!dashboard?.institutions?.some((m:any)=>m.id===i.id)),[institutions,dashboard]);
 const canManage=!!dashboard?.permission?.canManage;
 return <div className="network-center">
  {isSuper&&<details className="panel network-create"><summary>Yeni zincir kurum oluştur</summary><div className="form-grid"><label>Ağ adı<input value={netForm.name} onChange={(e:any)=>setNetForm({...netForm,name:e.target.value})}/></label><label>Kod<input value={netForm.code} onChange={(e:any)=>setNetForm({...netForm,code:e.target.value.toUpperCase()})}/></label><label>Genel merkez<select value={netForm.headquartersInstitutionId} onChange={(e:any)=>setNetForm({...netForm,headquartersInstitutionId:e.target.value})}><option value="">Seçim yok</option>{institutions.map((i:any)=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div><button className="primary" onClick={onCreate} disabled={!netForm.name||!netForm.code}>Zinciri Oluştur</button></details>}
  <div className="panel network-selector"><div><span className="eyebrow">Yönetim kapsamı</span><h2>{dashboard?.network?.name||'Zincir seçin'}</h2><p>{dashboard?.permission?.role==='NETWORK_VIEWER'?'Salt okunur üst yönetim görünümü':'Hiyerarşi ve şube yönetimi yetkisi'}</p></div><label>Zincir<select value={selected} onChange={e=>{setSelected(e.target.value);setFilters({unitId:'',from:'',to:''})}}><option value="">Seçin</option>{networks.map((n:any)=><option key={n.id} value={n.id}>{n.name} ({n.institution_count||0})</option>)}</select></label></div>
  {!selected&&<div className="empty-state"><Network size={34}/><h3>Yetkili olduğunuz zincir bulunmuyor</h3><p>Sıradan kurum üyeliği zincir raporlarını açmaz. Süper Admin, Zincir Yöneticisi veya Zincir Görüntüleyici rolü tanımlamalıdır.</p></div>}
  {selected&&<><div className="panel network-filters"><label>Hiyerarşi kapsamı<select value={filters.unitId} onChange={e=>setFilters({...filters,unitId:e.target.value})}><option value="">Tüm yetkili kapsam</option>{dashboard?.units?.map((u:any)=><option value={u.id} key={u.id}>{unitLabels[u.unit_type]} · {u.name}</option>)}</select></label><label>Başlangıç<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Bitiş<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><button className="secondary" onClick={()=>void loadDashboard()} disabled={busy}><RefreshCw size={16}/>{busy?'Hazırlanıyor…':'Raporu Uygula'}</button><a className="secondary" href={`/api/platform/networks/${selected}/export?${query()}`}><Download size={16}/> CSV İndir</a></div>
  {dashboard&&<><div className="network-kpis"><Kpi label="Kurum / Kampüs" value={dashboard.totals.institution_count}/><Kpi label="Aktif Öğrenci" value={dashboard.totals.active_students}/><Kpi label="Sınav Katılımı" value={dashboard.totals.participant_count}/><Kpi label="Devam Oranı" value={`${number(dashboard.totals.attendance_rate)}%`}/><Kpi label="Ödev Tamamlama" value={`${number(dashboard.totals.assignment_completion_rate)}%`}/><Kpi label="Aktif Sıfır Hata" value={dashboard.totals.active_recovery}/></div>
  <section className="panel"><div className="panel-head"><div><h2>Şubeler arası karşılaştırma</h2><p>Seçili tarih ve hiyerarşi kapsamındaki operasyonel göstergeler.</p></div><BarChart3/></div><div className="table-scroll"><table><thead><tr><th>Kurum</th><th>Konum / Birim</th><th>Öğrenci</th><th>Misafir</th><th>Katılım</th><th>Ort. net</th><th>Başarı</th><th>Devam</th><th>Ödev</th><th>Sıfır Hata</th>{canManage&&<th>İşlem</th>}</tr></thead><tbody>{dashboard.institutions.map((i:any)=><tr key={i.id}><td><strong>{i.name}</strong><small className="cell-sub">{i.code}</small></td><td>{i.city||'—'} / {i.district||'—'}<small className="cell-sub">{i.unit_name||'Birim atanmamış'}</small></td><td>{number(i.active_students)}</td><td>{number(i.guest_students)}</td><td>{number(i.participant_count)}</td><td>{number(i.avg_net)}</td><td>{number(i.avg_success)}%</td><td>{number(i.attendance_rate)}%</td><td>{number(i.assignment_completion_rate)}%</td><td>{number(i.active_recovery)}</td>{canManage&&<td><button className="danger-link" disabled={dashboard.network.headquarters_institution_id===i.id} onClick={()=>window.confirm(`${i.name} zincirden çıkarılsın mı?`)&&void act(`/api/platform/networks/${selected}/members/${i.id}`,undefined,'DELETE','Kurum zincirden çıkarıldı.')}>Çıkar</button></td>}</tr>)}</tbody></table></div>{!dashboard.institutions.length&&<div className="empty-state compact"><p>Bu kapsamda bağlı kurum bulunmuyor.</p></div>}</section>
  <div className="network-admin-grid"><section className="panel"><div className="panel-head"><div><h2>Hiyerarşi</h2><p>Genel merkez → bölge → il → ilçe → kampüs</p></div><Network/></div><div className="unit-list">{dashboard.units.map((u:any)=><div key={u.id}><span className="pill">{unitLabels[u.unit_type]}</span><strong>{u.name}</strong><small>{u.code}{u.city?` · ${u.city}`:''}{u.district?` / ${u.district}`:''}</small></div>)}</div>{canManage&&<><h3>Yeni birim</h3><div className="form-grid compact"><label>Tür<select value={unitForm.unitType} onChange={e=>setUnitForm({...unitForm,unitType:e.target.value})}>{Object.entries(unitLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Üst birim<select value={unitForm.parentUnitId} onChange={e=>setUnitForm({...unitForm,parentUnitId:e.target.value})}><option value="">Kök birim</option>{dashboard.units.map((u:any)=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><label>Ad<input value={unitForm.name} onChange={e=>setUnitForm({...unitForm,name:e.target.value})}/></label><label>Kod<input value={unitForm.code} onChange={e=>setUnitForm({...unitForm,code:e.target.value.toUpperCase()})}/></label><label>İl<input value={unitForm.city} onChange={e=>setUnitForm({...unitForm,city:e.target.value})}/></label><label>İlçe<input value={unitForm.district} onChange={e=>setUnitForm({...unitForm,district:e.target.value})}/></label></div><button className="primary" disabled={!unitForm.name||!unitForm.code} onClick={()=>void addUnit()}>Birimi Ekle</button></>}</section>
  <section className="panel"><div className="panel-head"><div><h2>Kurum ve yetki</h2><p>Kampüs bağlantıları ile kapsamlı yönetici/görüntüleyici rolleri.</p></div><ShieldCheck/></div>{canManage&&isSuper&&<><h3>Kurum bağla</h3><div className="form-grid compact"><label>Kurum<select value={memberForm.institutionId} onChange={e=>setMemberForm({...memberForm,institutionId:e.target.value})}><option value="">Seçin</option>{availableInstitutions.map((i:any)=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Hiyerarşi birimi<select value={memberForm.unitId} onChange={e=>setMemberForm({...memberForm,unitId:e.target.value})}><option value="">Atanmamış</option>{dashboard.units.map((u:any)=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><label>Bölge etiketi<input value={memberForm.regionLabel} onChange={e=>setMemberForm({...memberForm,regionLabel:e.target.value})}/></label></div><button className="primary" disabled={!memberForm.institutionId} onClick={()=>void addMember()}>Kurumu Bağla</button></>}{canManage&&<><h3>Zincir rolü</h3><div className="form-grid compact"><label>Yönetici hesabı<select value={roleForm.userId} onChange={e=>setRoleForm({...roleForm,userId:e.target.value})}><option value="">Seçin</option>{dashboard.roleCandidates.map((u:any)=><option value={u.id} key={u.id}>{u.display_name} · {u.institution_name||'Platform'}</option>)}</select></label><label>Rol<select value={roleForm.role} onChange={e=>setRoleForm({...roleForm,role:e.target.value})}><option value="NETWORK_VIEWER">Görüntüleyici</option><option value="NETWORK_ADMIN">Yönetici</option></select></label><label>Kapsam<select value={roleForm.scopeUnitId} onChange={e=>setRoleForm({...roleForm,scopeUnitId:e.target.value})}><option value="">Tüm zincir</option>{dashboard.units.map((u:any)=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label></div><button className="primary" disabled={!roleForm.userId} onClick={()=>void addRole()}>Rolü Kaydet</button><div className="role-list">{roles.map((r:any)=><div key={r.user_id}><strong>{r.display_name}</strong><span>{r.role==='NETWORK_ADMIN'?'Yönetici':'Görüntüleyici'} · {r.scope_name||'Tüm zincir'}</span></div>)}</div></>}</section></div>
  <section className="panel"><div className="panel-head"><div><h2>Merkezi sınav yayınları</h2><p>Dondurulmuş ve yayınlanmış zincir sınavı snapshotları.</p></div><School/></div><div className="exam-grid">{dashboard.exams.map((e:any)=><div className="exam-card" key={e.id}><span className="pill">{e.result_freeze_status}</span><h3>{e.title}</h3><p>{number(e.participant_count)} katılımcı · sürüm {e.snapshot_version||0}</p></div>)}</div>{!dashboard.exams.length&&<p className="muted">Henüz zincir kapsamlı sınav yayını yok.</p>}</section></>}
  </>}</div>;
}

function Kpi({label,value}:{label:string;value:any}){return <div className="network-kpi"><span>{label}</span><strong>{typeof value==='string'?value:number(value)}</strong></div>}
