import { useEffect,useState } from 'react';
import { Building2,Network,RefreshCw,School,Store,Users } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';

export function EnterpriseCenter(){
 const {user}=useAuth();const [tab,setTab]=useState('networks');const [networks,setNetworks]=useState<any[]>([]);const [publishers,setPublishers]=useState<any[]>([]);const [campaigns,setCampaigns]=useState<any[]>([]);const [campus,setCampus]=useState<any>(null);const [institutions,setInstitutions]=useState<any[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [netForm,setNetForm]=useState({name:'',code:'',headquartersInstitutionId:''});const [pubForm,setPubForm]=useState({name:'',code:''});const [admForm,setAdmForm]=useState({title:'',campaignType:'SCHOLARSHIP'});const [campusForm,setCampusForm]=useState({subdomain:'',customDomain:'',welcomeText:'',enabled:false});
 const load=async()=>{const [n,p,a,c,i]=await Promise.all([api<any>('/api/platform/networks').catch(()=>({networks:[]})),api<any>('/api/platform/publishers').catch(()=>({publishers:[]})),api<any>('/api/platform/admissions').catch(()=>({campaigns:[]})),api<any>('/api/platform/campus').catch(()=>null),user?.role==='SUPER_ADMIN'?api<any>('/api/institutions').catch(()=>({institutions:[]})):Promise.resolve({institutions:[]})]);setNetworks(n.networks||[]);setPublishers(p.publishers||[]);setCampaigns(a.campaigns||[]);setCampus(c?.campus||null);setInstitutions(i.institutions||[]);if(c?.campus)setCampusForm({subdomain:c.campus.subdomain||'',customDomain:c.campus.custom_domain||'',welcomeText:c.campus.welcome_text||'',enabled:!!c.campus.enabled})};useEffect(()=>{void load()},[]);
 const addNetwork=async()=>{try{await api('/api/platform/networks',{method:'POST',body:JSON.stringify(netForm)});setNotice('Kurum ağı oluşturuldu.');setNetForm({name:'',code:'',headquartersInstitutionId:''});await load()}catch(e:any){setError(e.message)}};
 const addPublisher=async()=>{try{await api('/api/platform/publishers',{method:'POST',body:JSON.stringify(pubForm)});setNotice('Yayınevi tanımlandı.');setPubForm({name:'',code:''});await load()}catch(e:any){setError(e.message)}};
 const addCampaign=async()=>{try{await api('/api/platform/admissions',{method:'POST',body:JSON.stringify(admForm)});setNotice('Kabul/bursluluk kampanyası oluşturuldu.');setAdmForm({title:'',campaignType:'SCHOLARSHIP'});await load()}catch(e:any){setError(e.message)}};
 const saveCampus=async()=>{try{await api('/api/platform/campus',{method:'PUT',body:JSON.stringify(campusForm)});setNotice('Campus ayarları kaydedildi. Final logo/marka alanları bilinçli olarak bekletiliyor.');await load()}catch(e:any){setError(e.message)}};
 return <><div className="page-head"><div><span className="eyebrow">Enterprise</span><h1>Kurum Ağı · Yayınevi · Admissions · Campus</h1><p>Tek okuldan yüzlerce kampüslü zincire ve Türkiye geneli yayınevi sınavına aynı çekirdek sistemle ölçeklenir.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}><button className={tab==='networks'?'primary':'secondary'} onClick={()=>setTab('networks')}><Network size={16}/> Zincirler</button>{user?.role==='SUPER_ADMIN'&&<button className={tab==='publishers'?'primary':'secondary'} onClick={()=>setTab('publishers')}><Store size={16}/> Yayınevleri</button>}<button className={tab==='admissions'?'primary':'secondary'} onClick={()=>setTab('admissions')}><Users size={16}/> Admissions</button><button className={tab==='campus'?'primary':'secondary'} onClick={()=>setTab('campus')}><School size={16}/> Campus</button></div>
 {tab==='networks'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Kurum ağları</h2><p>Merkez → il → ilçe → kampüs → sınıf sıralama ve karşılaştırma altyapısı.</p></div><Network/></div>{user?.role==='SUPER_ADMIN'&&<><div className="form-grid"><label>Ağ adı<input value={netForm.name} onChange={e=>setNetForm({...netForm,name:e.target.value})}/></label><label>Kod<input value={netForm.code} onChange={e=>setNetForm({...netForm,code:e.target.value.toUpperCase()})}/></label><label>Merkez kurum<select value={netForm.headquartersInstitutionId} onChange={e=>setNetForm({...netForm,headquartersInstitutionId:e.target.value})}><option value="">Seçim yok</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div><button className="primary" onClick={addNetwork} disabled={!netForm.name||!netForm.code}>Ağı Oluştur</button></>}</div><div className="exam-grid">{networks.map(n=><div className="exam-card" key={n.id}><Network size={26}/><h3>{n.name}</h3><p>{n.code} · {n.institution_count||0} kurum</p><a className="secondary full" href={`/api/platform/networks/${n.id}/dashboard`} target="_blank" rel="noreferrer">Dashboard JSON</a></div>)}</div></>}
 {tab==='publishers'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Yayınevi merkezi</h2><p>Merkezi denemelerde kurum/öğrenci katılımı ve soru analitiği için yayıncı kimliği.</p></div><Store/></div><div className="form-grid"><label>Yayınevi adı<input value={pubForm.name} onChange={e=>setPubForm({...pubForm,name:e.target.value})}/></label><label>Kod<input value={pubForm.code} onChange={e=>setPubForm({...pubForm,code:e.target.value.toUpperCase()})}/></label></div><button className="primary" onClick={addPublisher} disabled={!pubForm.name||!pubForm.code}>Yayınevini Ekle</button></div><div className="table-card"><table><thead><tr><th>Yayınevi</th><th>Kod</th><th>Sınav</th><th>Durum</th></tr></thead><tbody>{publishers.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.code}</td><td>{p.exam_count||0}</td><td><span className="status ok">Aktif</span></td></tr>)}</tbody></table></div></>}
 {tab==='admissions'&&<><div className="panel" style={{marginBottom:16}}><div className="panel-head"><div><h2>Bursluluk / kabul / seviye tespit</h2><p>Aday öğrenci kampanyaları mevcut sınav motoruyla bağlanır.</p></div><Users/></div><div className="form-grid"><label>Kampanya adı<input value={admForm.title} onChange={e=>setAdmForm({...admForm,title:e.target.value})}/></label><label>Tür<select value={admForm.campaignType} onChange={e=>setAdmForm({...admForm,campaignType:e.target.value})}><option value="SCHOLARSHIP">Bursluluk</option><option value="PLACEMENT">Seviye Tespit</option><option value="ADMISSION">Kabul</option></select></label></div><button className="primary" onClick={addCampaign} disabled={!admForm.title}>Kampanya Oluştur</button></div><div className="exam-grid">{campaigns.map(c=><div className="exam-card" key={c.id}><span className="pill">{c.campaign_type}</span><h3>{c.title}</h3><p>{c.candidate_count||0} aday · {c.status}</p></div>)}</div></>}
 {tab==='campus'&&<div className="panel"><div className="panel-head"><div><h2>Okul logolu Campus</h2><p>Subdomain, özel domain ve kurum mesajı hazır. Final platform adı/logo tasarımı en sona bırakıldığı için global marka varlığı burada henüz doldurulmuyor.</p></div><Building2/></div><div className="form-grid"><label>Subdomain<input value={campusForm.subdomain} onChange={e=>setCampusForm({...campusForm,subdomain:e.target.value})} placeholder="okuladi"/></label><label>Özel domain<input value={campusForm.customDomain} onChange={e=>setCampusForm({...campusForm,customDomain:e.target.value})} placeholder="akademi.okuladi.com"/></label></div><label>Karşılama metni<textarea rows={3} value={campusForm.welcomeText} onChange={e=>setCampusForm({...campusForm,welcomeText:e.target.value})}/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={campusForm.enabled} onChange={e=>setCampusForm({...campusForm,enabled:e.target.checked})}/> Campus alanını etkinleştir</label><button className="primary" onClick={saveCampus}>Kaydet</button></div>}
 </>;
}
