import { useEffect,useMemo,useRef,useState } from 'react';
import { Camera, CheckCircle2, FileUp, RefreshCw, ScanLine, TriangleAlert } from 'lucide-react';
import { useParams,useSearchParams } from 'react-router-dom';
import { api, ApiError } from '../api';
import { captureVideoFrame, parseRuntimeTemplate, readOmrImage, scoreTemplate, type OmrTemplateRuntime } from '../lib/omrEngine';

export function ExamEvaluate(){
 const {examId}=useParams(); const [params]=useSearchParams(); const institutionId=params.get('institutionId');
 const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<any>(null); const [batch,setBatch]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [templateNeeded,setTemplateNeeded]=useState<any[]>([]); const [manualTemplate,setManualTemplate]=useState('');
 const upload=async()=>{if(!file||!examId)return;setLoading(true);setError('');const fd=new FormData();fd.append('file',file);if(institutionId)fd.append('institutionId',institutionId);if(manualTemplate)fd.append('templateVersionId',manualTemplate);try{const r=await api<any>(`/api/exams/${examId}/preview-file`,{method:'POST',body:fd});await acceptPreview(r);}catch(e){if(e instanceof ApiError){setError(e.message);const d=e.details as any;if(d?.templates)setTemplateNeeded(d.templates);}else setError('Dosya okunamadı.')}finally{setLoading(false)}};
 const loadBatch=async(id:string)=>{const r=await api<any>(`/api/scan-batches/${id}`);setBatch(r)};
 const acceptPreview=async(r:any)=>{setPreview(r);await loadBatch(r.batchId)};
 const resolve=async(recordId:string,asNewGuest=true)=>{await api(`/api/scan-batches/${preview.batchId}/records/${recordId}/resolve`,{method:'POST',body:JSON.stringify({asNewGuest})});await loadBatch(preview.batchId)};
 const evaluate=async()=>{setLoading(true);setError('');try{const r=await api<any>(`/api/scan-batches/${preview.batchId}/evaluate`,{method:'POST'});setPreview((p:any)=>({...p,evaluated:r.processed}));await loadBatch(preview.batchId)}catch(e){setError(e instanceof Error?e.message:'Değerlendirme başarısız.')}finally{setLoading(false)}};
 const reviewRows=(batch?.records||[]).filter((r:any)=>['AMBIGUOUS','INVALID'].includes(r.match_status)||(r.issues||[]).length>0);
 return <><div className="page-head"><div><span className="eyebrow">Hızlı akış</span><h1>Sınav Değerlendir</h1><p>Sadece kaynağı seçin. Optik/FMT tespiti ve öğrenci eşleştirme otomatik yapılır.</p></div></div>
 {!preview&&<div className="source-grid"><label className="source-card"><FileUp size={36}/><h2>TXT / DAT Yükle</h2><p>Dosyayı seçin; sistem formatı otomatik algılamaya çalışsın.</p><input type="file" accept=".txt,.dat,.csv,text/plain,text/csv" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<strong>{file.name}</strong>}<button type="button" className="primary" onClick={upload} disabled={!file||loading}>{loading?'Analiz ediliyor…':'Dosyayı Analiz Et'}</button></label><CameraSource examId={examId||''} institutionId={institutionId} onPreview={acceptPreview} onError={setError}/></div>}
 {templateNeeded.length>0&&!preview&&<div className="panel warning-panel"><TriangleAlert/><div><h3>Optik format kesin belirlenemedi</h3><p>Geri dönmeden aşağıdan şablon seçerek tekrar deneyebilirsiniz.</p><select value={manualTemplate} onChange={e=>setManualTemplate(e.target.value)}><option value="">Şablon seç</option>{templateNeeded.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><button className="primary" onClick={upload} disabled={!manualTemplate||loading}>Seçili Şablonla Tekrar Oku</button></div></div>}
 {error&&<div className="alert error">{error}</div>}
 {preview&&<><div className="summary-strip"><Summary label="Toplam" value={preview.total}/><Summary label="Aktif eşleşti" value={preview.counts.active}/><Summary label="Bilinen misafir" value={preview.counts.guest}/><Summary label="Yeni misafir" value={preview.counts.newGuest}/><Summary label="Kontrol" value={reviewRows.length} warn/></div><div className="panel"><div className="panel-head"><div><h2>Kontrol</h2><p>{preview.detection.templateName||'Şablon'} · güven %{Math.round((preview.detection.confidence||0)*100)}</p></div><span className={`status ${batch?.batch.status==='COMMITTED'?'ok':batch?.batch.status==='NEEDS_REVIEW'?'warn':'ok'}`}>{batch?.batch.status}</span></div>{reviewRows.map((r:any)=>batch?.batch.source_type==='CAMERA'?<CameraReview key={r.id} row={r} batchId={preview.batchId} reload={()=>loadBatch(preview.batchId)}/>:<div className="issue-row" key={r.id}><div><strong>{r.canonical.name||`Satır ${r.row_no}`}</strong><span>{r.issues.join(' · ')}</span></div><button className="secondary" onClick={()=>resolve(r.id,true)}>Misafir Olarak Devam Et</button></div>)}{batch?.batch.status!=='NEEDS_REVIEW'&&batch?.batch.status!=='COMMITTED'&&<button className="primary huge" onClick={evaluate} disabled={loading}><ScanLine/> {loading?'Değerlendiriliyor…':'SINAVI DEĞERLENDİR'}</button>}{batch?.batch.status==='COMMITTED'&&<div className="success-box"><CheckCircle2/> <div><strong>Değerlendirme tamamlandı</strong><span>{preview.evaluated||preview.total} katılımcının sonucu işlendi.</span></div></div>}</div></>}
 </>;
}
function Summary({label,value,warn}:{label:string;value:number;warn?:boolean}){return <div className={warn&&value?'summary warn':'summary'}><span>{label}</span><strong>{value}</strong></div>}

function CameraSource({examId,institutionId,onPreview,onError}:{examId:string;institutionId:string|null;onPreview:(r:any)=>Promise<void>;onError:(m:string)=>void}){
 const video=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const [on,setOn]=useState(false);const [templates,setTemplates]=useState<OmrTemplateRuntime[]>([]);const [selectedId,setSelectedId]=useState('');const [records,setRecords]=useState<any[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [last,setLast]=useState<any>(null);
 const selected=useMemo(()=>templates.find(t=>t.id===selectedId)||null,[templates,selectedId]);
 const stop=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(video.current)video.current.srcObject=null};
 useEffect(()=>{if(on&&video.current&&streamRef.current)video.current.srcObject=streamRef.current},[on]);
 useEffect(()=>()=>stop(),[]);
 const start=async()=>{setBusy(true);onError('');try{const r=await api<any>('/api/camera/templates');const list=(r.templates||[]).map(parseRuntimeTemplate);setTemplates(list);if(!list.length){setMsg('Kamera için READY durumda gerçek optik şablonu bulunmuyor. Optik Şablon Merkezi’nden gerçek geometri tanımlanmadan sonuç üretilmez.');return}stop();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1920},height:{ideal:1080}}});streamRef.current=stream;setOn(true);requestAnimationFrame(()=>{if(video.current&&streamRef.current)video.current.srcObject=streamRef.current});setMsg('Optiğin tamamını kadraja alın. İlk sayfada şablon otomatik tanınmaya çalışılır.')}catch(e){stop();setOn(false);setMsg(e instanceof Error?e.message:'Kamera açılamadı. Tarayıcı iznini kontrol edin.')}finally{setBusy(false)}};
 const capture=async()=>{if(!video.current||!templates.length)return;setBusy(true);onError('');try{const frame=captureVideoFrame(video.current);let template=selected;if(!template){const scores=templates.map(t=>({t,...scoreTemplate(frame,t)})).sort((a,b)=>b.confidence-a.confidence);const best=scores[0],second=scores[1];if(!best||best.confidence<.52||(second&&best.confidence-second.confidence<.08)){setMsg('Optik şablonu kesin belirlenemedi. Aşağıdan doğru şablonu seçip tekrar okutun.');setLast({scores:scores.slice(0,4)});return}template=best.t;setSelectedId(template.id)}const result=readOmrImage(frame,template);setLast(result);if(!Object.keys(result.answers_by_subject).length){setMsg(result.issues.join(' · ')||'Cevap alanları okunamadı.');return}const rec={name:'',student_number:result.student_number,booklet:result.booklet,answers_by_subject:result.answers_by_subject,confidence:result.confidence,issues:result.issues};setRecords(cur=>{if(rec.student_number){const idx=cur.findIndex(x=>x.student_number===rec.student_number);if(idx>=0){const next=[...cur];next[idx]=rec;return next}}return[...cur,rec]});setMsg(`${rec.student_number?`No ${rec.student_number} · `:''}${Object.keys(rec.answers_by_subject).join(', ')} okundu. Kamera açık; sonraki optiğe geçebilirsiniz.`)}catch(e){onError(e instanceof Error?e.message:'Optik okunamadı.')}finally{setBusy(false)}};
 const finish=async()=>{if(!examId||!selectedId||!records.length)return;setBusy(true);onError('');try{const r=await api<any>(`/api/exams/${examId}/camera-preview`,{method:'POST',body:JSON.stringify({institutionId,templateVersionId:selectedId,records})});stop();setOn(false);await onPreview(r)}catch(e){onError(e instanceof Error?e.message:'Kamera kayıtları gönderilemedi.')}finally{setBusy(false)}};
 return <div className="source-card"><Camera size={36}/><h2>Kameradan Optik Oku</h2><p>Kamera açık kalır; optikleri art arda okutun. Belirsiz işaretler değerlendirmeden önce kontrol ekranına düşer.</p>{on&&<video ref={video} autoPlay playsInline muted className="camera-preview"/>}{on&&<select value={selectedId} onChange={e=>setSelectedId(e.target.value)}><option value="">Otomatik şablon algıla</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" className="secondary" onClick={start} disabled={busy}>{on?<><RefreshCw size={16}/> Kamerayı Yenile</>:<><Camera size={16}/> Kamerayı Aç</>}</button>{on&&<button type="button" className="primary" onClick={capture} disabled={busy}><ScanLine size={16}/> Optiği Oku</button>}</div>{records.length>0&&<div className="success-box"><CheckCircle2/><div><strong>{records.length} optik hazır</strong><span>Aynı öğrenci numarası tekrar okunursa son okuma kullanılır.</span></div></div>}{records.length>0&&<button type="button" className="primary huge" onClick={finish} disabled={busy||!selectedId}>Okumayı Bitir ve Kontrole Geç</button>}{msg&&<small className="muted">{msg}</small>}{last?.scores&&<small className="muted">Adaylar: {last.scores.map((x:any)=>`${x.templateName} %${Math.round(x.confidence*100)}`).join(' · ')}</small>}</div>
}

function CameraReview({row,batchId,reload}:{row:any;batchId:string;reload:()=>Promise<void>}){
 const [name,setName]=useState(row.canonical.name||'');const [studentNo,setStudentNo]=useState(row.canonical.student_number||'');const [booklet,setBooklet]=useState(row.canonical.booklet||'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const identityProblem=['AMBIGUOUS','INVALID'].includes(row.match_status);
 const patch=async()=>{setBusy(true);setError('');try{await api(`/api/camera/scan-batches/${batchId}/records/${row.id}/identity`,{method:'POST',body:JSON.stringify({name,studentNumber:studentNo,booklet})});await reload()}catch(e){setError(e instanceof Error?e.message:'Kimlik güncellenemedi.')}finally{setBusy(false)}};
 const accept=async()=>{setBusy(true);setError('');try{await api(`/api/camera/scan-batches/${batchId}/records/${row.id}/accept`,{method:'POST'});await reload()}catch(e){setError(e instanceof Error?e.message:'Kayıt kabul edilemedi.')}finally{setBusy(false)}};
 return <div className="panel" style={{background:'#fffaf0',borderColor:'#f6d69a'}}><div className="panel-head"><div><strong>{row.canonical.name||row.canonical.student_number||`Optik ${row.row_no}`}</strong><p>{(row.issues||[]).join(' · ')||'Kontrol gerekli'}</p></div><span className="status warn">{row.match_status}</span></div>{identityProblem&&<div className="form-grid"><label>Öğrenci no<input value={studentNo} onChange={e=>setStudentNo(e.target.value)}/></label><label>Ad soyad<input value={name} onChange={e=>setName(e.target.value)} placeholder="Kayıtlı değilse misafir adı"/></label><label>Kitapçık<input value={booklet} onChange={e=>setBooklet(e.target.value.toUpperCase())}/></label></div>}{error&&<div className="alert error">{error}</div>}<div style={{display:'flex',gap:8}}>{identityProblem&&<button className="secondary" onClick={patch} disabled={busy||(!name&&!studentNo)}>Kimliği Güncelle / Eşleştir</button>}{!identityProblem&&(row.issues||[]).length>0&&<button className="secondary" onClick={accept} disabled={busy}>Bu şekilde kabul et</button>}</div></div>
}
