import { useEffect,useMemo,useState } from 'react';
import { BarChart3, Building2, CheckCircle2, ChevronRight, Database, FileUp, Globe2, Layers3, LockKeyhole, Network, Play, RefreshCw, Save, Search, Settings2, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api,qs } from '../api';
import { useAuth } from '../auth';

type Scope='ALL'|'CENTRAL'|'NETWORK'|'INSTITUTION';

export function ExamCenter(){
 const {user}=useAuth(); const [rows,setRows]=useState<any[]>([]); const [summary,setSummary]=useState<any>({});const [live,setLive]=useState<any[]>([]);
 const [q,setQ]=useState('');const [scope,setScope]=useState<Scope>('ALL');const [examType,setExamType]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [selected,setSelected]=useState<any>(null);
 const isSuper=user?.role==='SUPER_ADMIN';const canEvaluate=user?.role==='INSTITUTION_MANAGER';
 const load=async()=>{setError('');try{const [c,s]=await Promise.all([api<any>(`/api/exam-center/catalog${qs({q:q||null,scope:scope==='ALL'?null:scope,examType:examType||null})}`),api<any>('/api/exam-center/summary')]);setRows(c.exams||[]);setSummary(s.summary||{});setLive(s.live||[]);return c.exams||[]}catch(e:any){setError(e.message);return[]}};
 useEffect(()=>{const t=setTimeout(()=>void load(),q?250:0);return()=>clearTimeout(t)},[q,scope,examType]);
 const action=async(exam:any,kind:'freeze'|'build-ranking'|'publish')=>{setBusy(`${exam.id}:${kind}`);setError('');setNotice('');try{const r=await api<any>(`/api/exam-center/exams/${exam.id}/${kind}`,{method:'POST'});setNotice(kind==='freeze'?'Veri alımı donduruldu. Sıralama hazırlanabilir.':kind==='build-ranking'?`Sıralama snapshotı hazırlandı${r.snapshot?.participant_count!=null?`: ${r.snapshot.participant_count} katılımcı`:''}.`:'Sonuçlar yayınlandı. Öğrenciler hazır snapshot üzerinden sonuçlarını görebilir.');await load();setSelected(null);}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const filtered=useMemo(()=>rows,[rows]);
 return <>
  <div className="page-head"><div><span className="eyebrow">Hızlı Ölçme & Değerlendirme</span><h1>Sınav Merkezi</h1><p>Hazır yayınevi sınavını bulun, optik verisini yükleyin ve sonucu alın. Teknik tanımlar yalnız gerektiğinde görünür.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{isSuper&&<Link className="secondary" to="/exam-definitions"><Settings2 size={16}/> Sınav Kataloğu</Link>}<button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="kpi-grid exam-center-kpis"><Kpi icon={<Database/>} label="Sınav" value={summary.exam_count||0}/><Kpi icon={<Globe2/>} label="Merkezi" value={summary.central_count||0}/><Kpi icon={<Network/>} label="Zincir / Ağ" value={summary.network_count||0}/><Kpi icon={<Building2/>} label="Kurum" value={summary.institution_count||0}/><Kpi icon={<CheckCircle2/>} label="Yayınlanan" value={summary.published_count||0}/></div>

  <div className="panel exam-quick-panel">
   <div className="panel-head"><div><h2>Sınavı bul ve yükle</h2><p>Sınav adı, yayınevi veya sınav koduyla arayın. Hazır katalog sınavlarında cevap anahtarı ve puanlama tekrar girilmez.</p></div><Sparkles size={20}/></div>
   <div className="exam-search-row"><div className="exam-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Örn. 3D TYT TG-4, Özdebir LGS, sınav kodu…" autoFocus/></div><select value={examType} onChange={e=>setExamType(e.target.value)}><option value="">Tüm sınav türleri</option><option>LGS</option><option>TYT</option><option>AYT</option></select></div>
   <div className="scope-tabs"><button className={scope==='ALL'?'active':''} onClick={()=>setScope('ALL')}>Tümü</button><button className={scope==='CENTRAL'?'active':''} onClick={()=>setScope('CENTRAL')}><Globe2 size={15}/> Merkezi / Türkiye Geneli</button><button className={scope==='NETWORK'?'active':''} onClick={()=>setScope('NETWORK')}><Network size={15}/> Zincir / Ağ</button><button className={scope==='INSTITUTION'?'active':''} onClick={()=>setScope('INSTITUTION')}><Building2 size={15}/> Kurum Sınavları</button></div>
  </div>

  <div className="table-card exam-center-table"><table><thead><tr><th>Sınav</th><th>Kapsam</th><th>Hazırlık</th><th>Katılım</th><th>Sonuç</th><th>İşlem</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><strong>{e.title}</strong><small>{[e.publisher_name,e.series_name,e.exam_code].filter(Boolean).join(' · ')||`${e.academic_year} · ${e.exam_type}`}</small></td><td><ScopeBadge scope={e.scope_type}/><small>{e.exam_date||'Tarih yok'}</small></td><td><div className="ready-stack"><span className={e.answer_key_count>0?'verified':'warning'}>{e.answer_key_count>0?<CheckCircle2 size={14}/>:<ShieldCheck size={14}/>} Cevap anahtarı</span><span className={e.optical_name?'verified':'warning'}>{e.optical_name?<CheckCircle2 size={14}/>:<ShieldCheck size={14}/>} {e.optical_name||'Optik seçilecek'}</span></div></td><td><strong>{e.participant_count||0}</strong><small>{e.institution_count||0} kurum</small></td><td><span className={`status ${e.ranking_status==='PUBLISHED'?'ok':e.ranking_status==='READY'?'warn':'neutral'}`}>{rankLabel(e.ranking_status)}</span></td><td><div className="row-actions">{canEvaluate&&<Link className="primary subtle" to={`/exams/${e.id}/evaluate`}><FileUp size={15}/> Veri Yükle</Link>}<button className="icon-button" title="Ayrıntı" onClick={()=>setSelected(e)}><ChevronRight size={16}/></button></div></td></tr>)}{!filtered.length&&<tr><td colSpan={6}><div className="empty">Aramanıza uygun sınav bulunamadı. Kurum sınavı oluşturmak için “Kendi sınavımı oluştur” seçeneğini kullanın.</div></td></tr>}</tbody></table></div>

  <div className="exam-center-bottom"><Link className="quick-card" to="/exam-definitions"><div className="quick-icon"><Layers3/></div><div><h3>Kendi sınavımı oluştur</h3><p>Cevap anahtarını yükleyin; ders ve soru yapısı otomatik oluşturulsun.</p></div><ChevronRight/></Link>{isSuper&&<Link className="quick-card" to="/networks"><div className="quick-icon"><Network/></div><div><h3>Zincir kurum yönetimi</h3><p>Merkez → il → ilçe → kampüs kapsamlarını tanımlayın.</p></div><ChevronRight/></Link>}</div>

  {isSuper&&live.length>0&&<div className="panel" style={{marginTop:20}}><div className="panel-head"><div><h2>Merkezi sınav katılımı</h2><p>Türkiye geneli ve zincir sınavlarda anlık toplanan katılım görünümü.</p></div><Globe2/></div><div className="live-exam-grid">{live.map(x=><div className="live-exam" key={x.id}><div><ScopeBadge scope={x.scope_type}/><strong>{x.title}</strong><span>{x.publisher_name||x.exam_type}</span></div><div><b>{x.participant_count||0}</b><small>öğrenci</small></div><div><b>{x.institution_count||0}</b><small>kurum</small></div></div>)}</div></div>}

  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="panel-head"><div><ScopeBadge scope={selected.scope_type}/><h2 style={{marginTop:8}}>{selected.title}</h2><p>{selected.publisher_name||'Kurum sınavı'} · {selected.exam_type}</p></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><div className="detail-grid"><Info label="Katılımcı" value={selected.participant_count||0}/><Info label="Kurum" value={selected.institution_count||0}/><Info label="Kitapçık" value={selected.booklet_codes||'—'}/><Info label="Optik" value={selected.optical_name||'Otomatik / seçilecek'}/></div>{canEvaluate&&<Link className="primary huge" to={`/exams/${selected.id}/evaluate`}><Play size={17}/> SINAV VERİSİNİ YÜKLE</Link>}{isSuper&&<CatalogEditor exam={selected} onSaved={async()=>{await load();setSelected(null)}} onError={setError} onNotice={setNotice}/>} {isSuper&&selected.scope_type!=='INSTITUTION'&&<div className="admin-release"><h3>Merkezi sonuç yayınlama</h3><p>Veri alımını kapatın, tek seferlik sıralama snapshotını hazırlayın ve sonucu yayınlayın.</p><div className="release-steps"><button className="secondary" disabled={!!busy||selected.ranking_status!=='OPEN'} onClick={()=>void action(selected,'freeze')}><LockKeyhole size={16}/> 1. Veriyi Dondur</button><button className="secondary" disabled={!!busy||!['FROZEN','READY'].includes(selected.ranking_status)} onClick={()=>void action(selected,'build-ranking')}><BarChart3 size={16}/> 2. Sıralamayı Hazırla</button><button className="primary" disabled={!!busy||selected.ranking_status!=='READY'} onClick={()=>void action(selected,'publish')}><Users size={16}/> 3. Sonuçları Yayınla</button></div></div>}</div></div>}
 </>;
}

function CatalogEditor({exam,onSaved,onError,onNotice}:{exam:any;onSaved:()=>Promise<void>;onError:(x:string)=>void;onNotice:(x:string)=>void}){
 const [form,setForm]=useState({scopeType:exam.scope_type||'INSTITUTION',publisherName:exam.publisher_name||'',seriesName:exam.series_name||'',examCode:exam.exam_code||'',verifiedCatalog:!!exam.verified_catalog,defaultOpticalTemplateVersionId:exam.optical_template_version_id||'',dataClosesAt:toLocal(exam.data_closes_at),resultReleaseAt:toLocal(exam.result_release_at),organizationId:''});
 const [templates,setTemplates]=useState<any[]>([]);const [networks,setNetworks]=useState<any[]>([]);const [saving,setSaving]=useState(false);
 useEffect(()=>{void Promise.all([api<any>('/api/camera/templates').catch(()=>({templates:[]})),api<any>('/api/exam-center/networks').catch(()=>({networks:[]})),api<any>(`/api/exam-center/exams/${exam.id}/networks`).catch(()=>({network:null}))]).then(([t,n,en])=>{setTemplates(t.templates||[]);setNetworks(n.networks||[]);if(en.network?.id)setForm(f=>({...f,organizationId:en.network.id}))})},[exam.id]);
 const save=async()=>{setSaving(true);onError('');try{if(form.scopeType==='CENTRAL'&&!form.verifiedCatalog)throw new Error('Türkiye geneli sınavı önce doğrulanmış katalog sınavı olarak işaretleyin.');await api(`/api/exam-center/exams/${exam.id}/catalog`,{method:'PATCH',body:JSON.stringify({...form,dataClosesAt:toIso(form.dataClosesAt),resultReleaseAt:toIso(form.resultReleaseAt)})});if(form.scopeType==='NETWORK'){if(!form.organizationId)throw new Error('Zincir sınavı için organizasyon ağı seçin.');await api(`/api/exam-center/exams/${exam.id}/networks`,{method:'POST',body:JSON.stringify({organizationId:form.organizationId})});}onNotice('Sınav katalog ve kapsam ayarları kaydedildi.');await onSaved();}catch(e:any){onError(e.message)}finally{setSaving(false)}};
 return <div className="catalog-editor"><div className="panel-head"><div><h3>Merkezi katalog ayarları</h3><p>Yayınevi sınavını kuruma hazır hale getiren teknik bilgileri yalnız Süper Admin yönetir.</p></div><Settings2 size={18}/></div><div className="form-grid"><label>Kapsam<select value={form.scopeType} onChange={e=>setForm(f=>({...f,scopeType:e.target.value}))}><option value="INSTITUTION">Kurum</option><option value="NETWORK">Zincir / Ağ</option><option value="CENTRAL">Merkezi / Türkiye Geneli</option></select></label><label>Yayınevi<input value={form.publisherName} onChange={e=>setForm(f=>({...f,publisherName:e.target.value}))} placeholder="3D Yayınları"/></label><label>Seri / Paket<input value={form.seriesName} onChange={e=>setForm(f=>({...f,seriesName:e.target.value}))} placeholder="TYT Türkiye Geneli"/></label><label>Sınav kodu<input value={form.examCode} onChange={e=>setForm(f=>({...f,examCode:e.target.value.toUpperCase()}))} placeholder="3D-TYT-TG4-2026"/></label><label>Varsayılan optik<select value={form.defaultOpticalTemplateVersionId} onChange={e=>setForm(f=>({...f,defaultOpticalTemplateVersionId:e.target.value}))}><option value="">Otomatik algıla</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}{t.version?` · ${t.version}`:''}</option>)}</select></label>{form.scopeType==='NETWORK'&&<label>Organizasyon ağı<select value={form.organizationId} onChange={e=>setForm(f=>({...f,organizationId:e.target.value}))}><option value="">Ağ seçin</option>{networks.map(n=><option key={n.id} value={n.id}>{n.name} · {n.institution_count||0} kurum</option>)}</select></label>}<label>Veri kapanış<input type="datetime-local" value={form.dataClosesAt} onChange={e=>setForm(f=>({...f,dataClosesAt:e.target.value}))}/></label><label>Sonuç yayın zamanı<input type="datetime-local" value={form.resultReleaseAt} onChange={e=>setForm(f=>({...f,resultReleaseAt:e.target.value}))}/></label></div><label className="catalog-check"><input type="checkbox" checked={form.verifiedCatalog} onChange={e=>setForm(f=>({...f,verifiedCatalog:e.target.checked}))}/><span>Doğrulanmış merkezi katalog sınavı</span></label><button className="secondary full" disabled={saving} onClick={()=>void save()}><Save size={16}/> {saving?'Kaydediliyor…':'Katalog Ayarlarını Kaydet'}</button></div>;
}
function Kpi({icon,label,value}:{icon:any;label:string;value:any}){return <div className="kpi-card exam-kpi"><div>{icon}</div><span>{label}</span><strong>{value}</strong></div>}
function ScopeBadge({scope}:{scope:string}){return <span className={`scope-badge ${String(scope).toLowerCase()}`}>{scope==='CENTRAL'?<><Globe2 size={13}/> Merkezi</>:scope==='NETWORK'?<><Network size={13}/> Zincir</>:<><Building2 size={13}/> Kurum</>}</span>}
function rankLabel(v:string){return ({OPEN:'Veri alınıyor',FROZEN:'Donduruldu',CALCULATING:'Hesaplanıyor',READY:'Yayına hazır',PUBLISHED:'Yayınlandı'} as any)[v]||v}
function Info({label,value}:{label:string;value:any}){return <div className="detail-info"><span>{label}</span><strong>{value}</strong></div>}
function toLocal(v:any){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v).slice(0,16);const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
function toIso(v:string){return v?new Date(v).toISOString():null}
