import { useEffect,useRef,useState } from 'react';
import { Camera, CheckCircle2, FileUp, RefreshCw, ScanLine, TriangleAlert } from 'lucide-react';
import { useParams,useSearchParams } from 'react-router-dom';
import { api, ApiError } from '../api';

export function ExamEvaluate(){
 const {examId}=useParams(); const [params]=useSearchParams(); const institutionId=params.get('institutionId');
 const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<any>(null); const [batch,setBatch]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [templateNeeded,setTemplateNeeded]=useState<any[]>([]); const [manualTemplate,setManualTemplate]=useState('');
 const upload=async()=>{if(!file||!examId)return;setLoading(true);setError('');const fd=new FormData();fd.append('file',file);if(institutionId)fd.append('institutionId',institutionId);if(manualTemplate)fd.append('templateVersionId',manualTemplate);try{const r=await api<any>(`/api/exams/${examId}/preview-file`,{method:'POST',body:fd});setPreview(r);await loadBatch(r.batchId);}catch(e){if(e instanceof ApiError){setError(e.message);const d=e.details as any;if(d?.templates)setTemplateNeeded(d.templates);}else setError('Dosya okunamadı.')}finally{setLoading(false)}};
 const loadBatch=async(id:string)=>{const r=await api<any>(`/api/scan-batches/${id}`);setBatch(r)};
 const resolve=async(recordId:string,asNewGuest=true)=>{await api(`/api/scan-batches/${preview.batchId}/records/${recordId}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asNewGuest})});await loadBatch(preview.batchId)};
 const evaluate=async()=>{setLoading(true);setError('');try{const r=await api<any>(`/api/scan-batches/${preview.batchId}/evaluate`,{method:'POST'});setPreview((p:any)=>({...p,evaluated:r.processed}));await loadBatch(preview.batchId)}catch(e){setError(e instanceof Error?e.message:'Değerlendirme başarısız.')}finally{setLoading(false)}};
 return <><div className="page-head"><div><span className="eyebrow">Hızlı akış</span><h1>Sınav Değerlendir</h1><p>Sadece kaynağı seçin. Optik/FMT tespiti ve öğrenci eşleştirme otomatik yapılır.</p></div></div>
 {!preview&&<div className="source-grid"><label className="source-card"><FileUp size={36}/><h2>TXT / DAT Yükle</h2><p>Dosyayı seçin; sistem formatı otomatik algılamaya çalışsın.</p><input type="file" accept=".txt,.dat,.csv,text/plain,text/csv" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<strong>{file.name}</strong>}<button type="button" className="primary" onClick={upload} disabled={!file||loading}>{loading?'Analiz ediliyor…':'Dosyayı Analiz Et'}</button></label><CameraSource/></div>}
 {templateNeeded.length>0&&!preview&&<div className="panel warning-panel"><TriangleAlert/><div><h3>Optik format kesin belirlenemedi</h3><p>Geri dönmeden aşağıdan şablon seçerek tekrar deneyebilirsiniz.</p><select value={manualTemplate} onChange={e=>setManualTemplate(e.target.value)}><option value="">Şablon seç</option>{templateNeeded.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><button className="primary" onClick={upload} disabled={!manualTemplate||loading}>Seçili Şablonla Tekrar Oku</button></div></div>}
 {error&&<div className="alert error">{error}</div>}
 {preview&&<><div className="summary-strip"><Summary label="Toplam" value={preview.total}/><Summary label="Aktif eşleşti" value={preview.counts.active}/><Summary label="Bilinen misafir" value={preview.counts.guest}/><Summary label="Yeni misafir" value={preview.counts.newGuest}/><Summary label="Kontrol" value={preview.counts.ambiguous+preview.counts.invalid} warn/></div><div className="panel"><div className="panel-head"><div><h2>Kontrol</h2><p>{preview.detection.templateName||'Şablon'} · güven %{Math.round((preview.detection.confidence||0)*100)}</p></div><span className={`status ${batch?.batch.status==='COMMITTED'?'ok':batch?.batch.status==='NEEDS_REVIEW'?'warn':'ok'}`}>{batch?.batch.status}</span></div>{(batch?.records||[]).filter((r:any)=>['AMBIGUOUS','INVALID'].includes(r.match_status)).map((r:any)=><div className="issue-row" key={r.id}><div><strong>{r.canonical.name||`Satır ${r.row_no}`}</strong><span>{r.issues.join(' · ')}</span></div><button className="secondary" onClick={()=>resolve(r.id,true)}>Misafir Olarak Devam Et</button></div>)}{batch?.batch.status!=='NEEDS_REVIEW'&&batch?.batch.status!=='COMMITTED'&&<button className="primary huge" onClick={evaluate} disabled={loading}><ScanLine/> {loading?'Değerlendiriliyor…':'SINAVI DEĞERLENDİR'}</button>}{batch?.batch.status==='COMMITTED'&&<div className="success-box"><CheckCircle2/> <div><strong>Değerlendirme tamamlandı</strong><span>{preview.evaluated||preview.total} katılımcının sonucu işlendi.</span></div></div>}</div></>}
 </>;
}
function Summary({label,value,warn}:{label:string;value:number;warn?:boolean}){return <div className={warn&&value?'summary warn':'summary'}><span>{label}</span><strong>{value}</strong></div>}
function CameraSource(){const video=useRef<HTMLVideoElement>(null);const [on,setOn]=useState(false);const [msg,setMsg]=useState('');useEffect(()=>()=>{const s=video.current?.srcObject as MediaStream|null;s?.getTracks().forEach(t=>t.stop())},[]);const start=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(video.current)video.current.srcObject=stream;setOn(true);setMsg('Bilinen optik şablonu olmadan sonuç uydurulmaz. Kamera pipeline hazır; gerçek şablon geometrisi eklenince okuma aktifleşir.')}catch{setMsg('Kamera açılamadı. Tarayıcı iznini kontrol edin.')}};return <div className="source-card"><Camera size={36}/><h2>Kameradan Optik Oku</h2><p>Aynı kamera oturumunda optikleri art arda okutmak için hazırlanmıştır.</p>{on&&<video ref={video} autoPlay playsInline className="camera-preview"/>}<button className="secondary" onClick={start}>{on?<><RefreshCw size={16}/> Kamerayı Yenile</>:<><Camera size={16}/> Kamerayı Aç</>}</button>{msg&&<small className="muted">{msg}</small>}</div>}
