import { useEffect,useState } from 'react';
import { CalendarClock,CheckCircle2,RefreshCw,RotateCcw,ShieldCheck } from 'lucide-react';
import { api } from '../api';

function statusName(v:string){return ({ACTIVE:'Aktif',EXPIRED:'Süresi Doldu',SUSPENDED:'Askıda',CANCELLED:'İptal',LEGACY_ACTIVE:'Mevcut Aktif'} as Record<string,string>)[v]||v}
function planName(v:string){return ({TRIAL_7_DAY:'7 Günlük Demo',ANNUAL:'Yıllık Lisans',PILOT:'Pilot',CUSTOM:'Özel',LEGACY:'Mevcut Lisans'} as Record<string,string>)[v]||v}

export function Licenses(){
 const[items,setItems]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=async()=>{setError('');try{const r=await api<any>('/api/admin/licenses');setItems(r.licenses||[])}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const act=async(path:string,body:any,message:string)=>{setBusy(true);setError('');setNotice('');try{await api(path,{method:'POST',body:JSON.stringify(body)});setNotice(message);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const annual=(x:any,mode:'KEEP_DATA'|'RESET_DATA')=>{const text=mode==='RESET_DATA'?'Demo akademik verileri temiz başlangıç için arşivlenecek; kullanıcı ve kurum hesabı korunacak. Devam edilsin mi?':'Demo verileri aynen korunarak yıllık lisansa geçirilsin mi?';if(!confirm(text))return;void act('/api/admin/licenses/annual',{institutionId:x.id,mode,days:365},mode==='RESET_DATA'?'Kurum yıllık lisansa temiz başlangıçla geçirildi.':'Kurum yıllık lisansa mevcut veriler korunarak geçirildi.')};
 return <>
  <div className="page-head"><div><span className="eyebrow">Lisans Yönetimi</span><h1>7 Günlük Demo → Yıllık Lisans</h1><p>Gerçek kurum ürünü 7 gün kendi verileriyle kullanır. Süre sonunda verileri koruyarak veya akademik trial verisini temiz başlangıca alarak yıllık lisansa geçirebilirsiniz.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel"><div className="panel-head"><div><h2>Lisans davranışı</h2><p>7. gün sonunda veriler otomatik silinmez. Kurum kilitlenir; Süper Admin karar verene kadar geçmiş güvenli biçimde korunur.</p></div><ShieldCheck/></div><div className="summary-strip"><div className="kpi-card"><span>Trial</span><strong>7 Gün</strong></div><div className="kpi-card"><span>Dönüşüm 1</span><strong>Verileri Koru</strong></div><div className="kpi-card"><span>Dönüşüm 2</span><strong>Temiz Başla</strong></div><div className="kpi-card"><span>Yıllık</span><strong>365 Gün</strong></div></div><div className="alert info" style={{marginTop:14}}><RotateCcw size={17}/><div><strong>“Temiz Başla” geri döndürülebilir mantıkla tasarlandı.</strong><span>Trial dönemindeki akademik kayıtlar görünür aktif yapıdan çıkarılır/arşivlenir; kurum ve kullanıcı kimlikleri korunur. Böylece yanlışlıkla kalıcı veri kaybı riski azaltılır.</span></div></div></div>
  <div className="table-card"><table><thead><tr><th>Kurum</th><th>Öğrenci</th><th>Plan</th><th>Durum</th><th>Süre</th><th>İşlemler</th></tr></thead><tbody>{items.map(x=>{const l=x.license;return <tr key={x.id}><td><strong>{x.name}</strong><div className="muted">{x.code}</div></td><td>{x.student_count}</td><td>{planName(l.planCode)}</td><td><span className={`status ${l.locked?'warn':'ok'}`}>{statusName(l.status)}</span></td><td>{l.daysRemaining==null?'—':`${l.daysRemaining} gün`}</td><td><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button className="secondary" disabled={busy} onClick={()=>void act('/api/admin/licenses/trial',{institutionId:x.id,days:7},'7 günlük demo lisansı başlatıldı.')}><CalendarClock size={14}/> 7 Gün Demo</button><button className="secondary" disabled={busy} onClick={()=>annual(x,'KEEP_DATA')}><CheckCircle2 size={14}/> Yıllık · Verileri Koru</button><button className="secondary" disabled={busy} onClick={()=>annual(x,'RESET_DATA')}><RotateCcw size={14}/> Yıllık · Temiz Başla</button>{l.id&&l.status==='ACTIVE'&&<button className="ghost" disabled={busy} onClick={()=>void act('/api/admin/licenses/status',{institutionId:x.id,status:'SUSPENDED'},'Lisans askıya alındı.')}>Askıya Al</button>}{l.id&&l.status==='SUSPENDED'&&<button className="ghost" disabled={busy} onClick={()=>void act('/api/admin/licenses/status',{institutionId:x.id,status:'ACTIVE'},'Lisans yeniden etkinleştirildi.')}>Etkinleştir</button>}</div></td></tr>})}</tbody></table>{!items.length&&<div className="empty">Kurum bulunmuyor.</div>}</div>
 </>;
}
