import { useEffect,useState } from 'react';
import { CheckCircle2,CreditCard,RefreshCw,XCircle } from 'lucide-react';
import { api } from '../api';

export function MembershipOrders(){
 const[data,setData]=useState<any>(null);const[status,setStatus]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[providerReference,setProviderReference]=useState('');const[note,setNote]=useState('');
 const load=async()=>{setError('');try{setData(await api<any>(`/api/admin/membership/orders${status?`?status=${status}`:''}`))}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[status]);
 const decide=async(id:string,action:'APPROVE'|'REJECT')=>{setBusy(id);setError('');setNotice('');try{await api(`/api/admin/membership/orders/${id}`,{method:'PATCH',body:JSON.stringify({action,providerReference,note})});setNotice(action==='APPROVE'?'Üyelik etkinleştirildi ve krediler işlendi.':'Talep reddedildi.');setProviderReference('');setNote('');await load()}catch(e:any){setError(e.message)}finally{setBusy('')}};
 return <><div className="page-head"><div><span className="eyebrow">Ticari paket yönetimi</span><h1>Üyelik Talepleri</h1><p>Gold ve Premium yıllık taleplerini gerçek ödeme kaydıyla onaylayın; onaysız talep üyelik açmaz.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="panel"><div className="form-grid"><label>Durum<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tümü</option><option value="PENDING">Bekleyen</option><option value="PAID">Ödendi</option><option value="REJECTED">Reddedildi</option></select></label><label>Sağlayıcı / dekont referansı<input value={providerReference} onChange={e=>setProviderReference(e.target.value)} placeholder="Onay için referans"/></label><label>Karar notu<input value={note} onChange={e=>setNote(e.target.value)} placeholder="İsteğe bağlı"/></label></div><div className="alert warning">Onay, öğrencinin mevcut üyeliğini kapatıp seçilen yıllık paketi açar. Yalnız ödeme/dekont doğrulandıktan sonra kullanın.</div></div>
 <div className="table-card"><table><thead><tr><th>Öğrenci / kurum</th><th>Plan</th><th>Tutar</th><th>Ödeme</th><th>Talep</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{(data?.orders||[]).map((o:any)=><tr key={o.id}><td><strong>{o.student_name}</strong><br/><small>{o.institution_name}</small></td><td>{o.plan_name}</td><td>{o.amount_try} TL</td><td>{o.payment_method}<br/><small>{o.provider_reference||'Referans yok'}</small></td><td>{new Date(o.requested_at).toLocaleString('tr-TR')}<br/><small>{o.requested_by_name}</small></td><td><span className={`status ${o.status==='PAID'?'success':o.status==='PENDING'?'warning':'danger'}`}>{o.status}</span></td><td>{o.status==='PENDING'?<div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="primary" disabled={busy===o.id||!providerReference.trim()} onClick={()=>void decide(o.id,'APPROVE')}><CheckCircle2 size={15}/> Onayla</button><button className="secondary" disabled={busy===o.id} onClick={()=>void decide(o.id,'REJECT')}><XCircle size={15}/> Reddet</button></div>:<CreditCard size={18}/>}</td></tr>)}{data&&!data.orders?.length&&<tr><td colSpan={7}>Bu filtrede üyelik talebi yok.</td></tr>}</tbody></table></div>
 </>;
}
