import { useEffect,useMemo,useState } from 'react';
import { Building2, Network, Plus, RefreshCw, Save, Users } from 'lucide-react';
import { api } from '../api';

export function NetworkAdmin(){
 const [networks,setNetworks]=useState<any[]>([]);const [institutions,setInstitutions]=useState<any[]>([]);const [users,setUsers]=useState<any[]>([]);const [selected,setSelected]=useState('');const [name,setName]=useState('');const [code,setCode]=useState('');const [chosenInstitutions,setChosenInstitutions]=useState<string[]>([]);const [managerUser,setManagerUser]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{setError('');try{const [n,i,u]=await Promise.all([api<any>('/api/exam-center/networks'),api<any>('/api/institutions'),api<any>('/api/users')]);setNetworks(n.networks||[]);setInstitutions(i.institutions||[]);setUsers(u.users||[]);if(!selected&&n.networks?.[0])setSelected(n.networks[0].id);}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const active=useMemo(()=>networks.find(n=>n.id===selected),[networks,selected]);
 const create=async()=>{if(!name.trim()||!code.trim())return;setBusy(true);setError('');try{const r=await api<any>('/api/exam-center/networks',{method:'POST',body:JSON.stringify({name,code})});setNotice('Zincir kurum ağı oluşturuldu.');setName('');setCode('');await load();setSelected(r.id);}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const saveInstitutions=async()=>{if(!selected||!chosenInstitutions.length)return;setBusy(true);setError('');try{await api(`/api/exam-center/networks/${selected}/institutions`,{method:'POST',body:JSON.stringify({institutions:chosenInstitutions})});setNotice(`${chosenInstitutions.length} kurum ağa bağlandı.`);setChosenInstitutions([]);await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const grant=async()=>{if(!selected||!managerUser)return;setBusy(true);setError('');try{await api(`/api/exam-center/networks/${selected}/users`,{method:'POST',body:JSON.stringify({userId:managerUser,accessLevel:'MANAGE'})});setNotice('Merkez yönetici yetkisi verildi.');setManagerUser('');}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const toggle=(id:string)=>setChosenInstitutions(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 return <><div className="page-head"><div><span className="eyebrow">Enterprise</span><h1>Zincir Kurum Yönetimi</h1><p>Çok şubeli yapılarda merkez, il, ilçe ve kampüs karşılaştırmalarının temel organizasyon ağını yönetin.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="network-layout"><div className="panel"><div className="panel-head"><div><h2>Organizasyon ağları</h2><p>Örn. Çözüm Eğitim Kurumları</p></div><Network/></div><div className="cards-list">{networks.map(n=><button key={n.id} className={`network-select ${selected===n.id?'active':''}`} onClick={()=>setSelected(n.id)}><div><strong>{n.name}</strong><span>{n.code}</span></div><b>{n.institution_count||0} kurum</b></button>)}</div><div className="divider"/><h3>Yeni ağ</h3><label>Ağ adı<input value={name} onChange={e=>setName(e.target.value)} placeholder="Çözüm Eğitim Kurumları"/></label><label>Ağ kodu<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="COZUM"/></label><button className="primary full" onClick={()=>void create()} disabled={busy||!name||!code}><Plus size={16}/> Oluştur</button></div>
 <div>{active?<><div className="panel"><div className="panel-head"><div><h2>{active.name}</h2><p>Bu ağa bağlanacak kurumları seçin.</p></div><Building2/></div><div className="institution-picker">{institutions.filter(i=>i.status==='ACTIVE').map(i=><label className="pick-row" key={i.id}><input type="checkbox" checked={chosenInstitutions.includes(i.id)} onChange={()=>toggle(i.id)}/><div><strong>{i.name}</strong><span>{[i.city,i.district].filter(Boolean).join(' / ')}</span></div></label>)}</div><button className="primary" onClick={()=>void saveInstitutions()} disabled={busy||!chosenInstitutions.length}><Save size={16}/> Seçili Kurumları Bağla ({chosenInstitutions.length})</button></div>
 <div className="panel"><div className="panel-head"><div><h2>Merkez yönetici</h2><p>Bu kullanıcı ağ genelindeki sınav ve karşılaştırmaları yönetebilir.</p></div><Users/></div><label>Kullanıcı<select value={managerUser} onChange={e=>setManagerUser(e.target.value)}><option value="">Kullanıcı seçin</option>{users.filter(u=>['INSTITUTION_MANAGER'].includes(u.role)).map(u=><option key={u.id} value={u.id}>{u.display_name} · {u.username||u.email||u.id}</option>)}</select></label><button className="secondary" onClick={()=>void grant()} disabled={busy||!managerUser}><Save size={16}/> Yönetim Yetkisi Ver</button></div></>:<div className="panel empty">Önce bir organizasyon ağı oluşturun.</div>}</div></div></>;
}
