import { useEffect,useMemo,useState } from 'react';
import { Bot,CheckCircle2,Copy,Link2,RefreshCw,ShieldCheck,Smartphone,Volume2 } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';

function roleName(role:string){return ({PARENT:'Veli',TEACHER:'Branş Öğretmeni',GUIDANCE_TEACHER:'Rehber Öğretmeni',INSTITUTION_MANAGER:'Kurum Yöneticisi'} as Record<string,string>)[role]||role}

export function NibiruAdmin(){
 const{user}=useAuth();const[data,setData]=useState<any>(null);const[voice,setVoice]=useState<any>(null);const[voiceProbe,setVoiceProbe]=useState<any>(null);const[users,setUsers]=useState<any[]>([]);const[events,setEvents]=useState<any[]>([]);const[publicNumber,setPublicNumber]=useState('');const[enabled,setEnabled]=useState(true);const[whatsappEnabled,setWhatsappEnabled]=useState(false);const[selectedUser,setSelectedUser]=useState('');const[pairing,setPairing]=useState<any>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=async()=>{setError('');try{const[s,u,a,v]=await Promise.all([api<any>('/api/nibiru/settings'),api<any>('/api/nibiru/users'),api<any>('/api/nibiru/audit'),api<any>('/api/nibiru/voice/status')]);setData(s);setVoice(v);setUsers(u.users||[]);setEvents(a.events||[]);setPublicNumber(s.settings?.public_whatsapp_number||'');setEnabled(Boolean(s.settings?.enabled));setWhatsappEnabled(Boolean(s.settings?.whatsapp_enabled));setSelectedUser(cur=>cur||(u.users?.[0]?.id||''))}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const save=async()=>{setBusy(true);setError('');setNotice('');try{await api('/api/nibiru/settings',{method:'PUT',body:JSON.stringify({enabled,whatsappEnabled,publicWhatsappNumber:publicNumber})});setNotice('Nibiru platform ayarları kaydedildi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const createCode=async()=>{if(!selectedUser)return;setBusy(true);setError('');try{const r=await api<any>('/api/nibiru/pairing-code',{method:'POST',body:JSON.stringify({userId:selectedUser})});setPairing(r)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const probeVoice=async(mode:'standard'|'premium')=>{setBusy(true);setError('');setVoiceProbe(null);try{const r=await api<any>(`/api/nibiru/voice/probe?mode=${mode}`,{method:'POST'});setVoiceProbe(r);setNotice(`Nibiru ${mode==='premium'?'Premium':'Standard'} ses testi başarılı: ${r.provider}.`)}catch(e:any){setError(e.message||'Ses sağlayıcı testi başarısız.')}finally{setBusy(false)}};
 const verified=useMemo(()=>users.filter(x=>x.whatsapp_status==='VERIFIED').length,[users]);
 return <>
  <div className="page-head"><div><span className="eyebrow">Nibiru Yönetimi</span><h1>Nibiru · AI, Ses ve WhatsApp Yönetimi</h1><p>Tüm Nibiru kanalları aynı rol, kurum ve doğrulanmış akademik veri sınırlarını kullanır. Dış sağlayıcı sırları kaynak kodda tutulmaz.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="summary-strip" style={{marginBottom:20}}><div className="kpi-card"><span>Nibiru</span><strong>{data?.settings?.enabled?'Aktif':'Kapalı'}</strong></div><div className="kpi-card"><span>Sesli Nibiru</span><strong>{voice?.providers?.standardReady?'Aktif':'Kurulum Gerekli'}</strong></div><div className="kpi-card"><span>WhatsApp</span><strong>{data?.settings?.whatsapp_enabled?'Aktif':'Kapalı'}</strong></div><div className="kpi-card"><span>Doğrulanmış Kimlik</span><strong>{verified}</strong></div></div>
  <div className="panel"><div className="panel-head"><div><h2>🤖 Nibiru kimliği</h2><p>Her kullanıcı ilk mesajdan itibaren yapay zekâyla konuştuğunu görür. Nibiru MEB ürünü/temsilcisi olduğunu iddia etmez.</p></div><Bot/></div><div className="alert info"><ShieldCheck size={17}/><div><strong>Kilitli konuşma ilkeleri</strong><span>Doğrulanmış veri · rol bazlı erişim · geliştirici/yargısız dil · veri yoksa tahmin yok · psikolojik/tıbbi tanı yok · bağlam dışı soruda akademik alana yönlendirme.</span></div></div>{user?.role==='SUPER_ADMIN'?<><div className="form-grid"><label>Nibiru aktif<input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><label>WhatsApp aktif<input type="checkbox" checked={whatsappEnabled} onChange={e=>setWhatsappEnabled(e.target.checked)}/></label><label>Herkese gösterilecek WhatsApp numarası<input value={publicNumber} onChange={e=>setPublicNumber(e.target.value)} placeholder="+90 ..."/></label></div><button className="primary" disabled={busy} onClick={save}>Ayarları Kaydet</button></>:<div className="muted">Platform ve WhatsApp aç/kapat ayarlarını Süper Admin yönetir.</div>}</div>
  <div className="panel"><div className="panel-head"><div><h2>🔊 Nibiru Voice</h2><p>Bas-konuş ile Türkçe STT; cevaplarda kurumsal öğretmen TTS. Standart rota maliyet odaklı, Premium rota doğallık odaklıdır.</p></div><Volume2/></div><div className="metrics"><Metric l="Türkçe STT · Whisper" ok={voice?.providers?.stt?.ready}/><Metric l="Google WaveNet" ok={voice?.providers?.google?.ready}/><Metric l="OpenAI Unified TTS" ok={voice?.providers?.openaiUnified?.ready}/><Metric l="Direct GPT-4o Mini TTS" ok={voice?.providers?.openaiDirect?.ready}/></div><div className={voice?.providers?.standardReady?'success-box':'alert warning'}>{voice?.providers?.standardReady?<><CheckCircle2/><div><strong>Standart ses rotası çalışmaya hazır</strong><span>{voice?.plans?.standard?.providers?.join(' → ')||'Sağlayıcı rotası hazır.'}</span></div></>:<><strong>Standart ses sağlayıcısı eksik.</strong> Workers AI binding veya Google WaveNet servis hesabı doğrulanmalıdır.</>}</div><div className="alert info" style={{marginTop:12}}><ShieldCheck size={17}/><div><strong>Ses politikası</strong><span>{voice?.policy?.teacherTone||'Sakin, açık ve geliştirici öğretmen dili.'} Mikrofon sürekli dinlemez; yalnız kullanıcı başlattığında en fazla 45 saniyelik kayıt alınır.</span></div></div>{user?.role==='SUPER_ADMIN'&&<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><button className="secondary" disabled={busy||!voice?.providers?.standardReady} onClick={()=>void probeVoice('standard')}><Volume2 size={15}/> Standard Sesi Test Et</button><button className="secondary" disabled={busy||!voice?.providers?.premiumReady} onClick={()=>void probeVoice('premium')}><SparkleText/> Premium Sesi Test Et</button>{voiceProbe&&<span className="status ok">{voiceProbe.provider} · {voiceProbe.bytes} bayt</span>}</div>}<p className="muted" style={{marginTop:10}}>Google WaveNet düşük maliyetli standart ana ses olarak tanımlanır; servis hesabı yoksa Cloudflare AI Gateway Unified Billing TTS yedek olarak kullanılır. Direct OpenAI anahtarı Premium için opsiyoneldir.</p></div>
  <div className="panel"><div className="panel-head"><div><h2>Meta WhatsApp bağlantı hazırlığı</h2><p>Telefon numarasını burada tanımlarsınız; erişim tokenı ve uygulama sırrı kaynak koda yazılmaz, Cloudflare secret olarak tutulur.</p></div><Smartphone/></div><div className="metrics"><Metric l="Verify Token" ok={data?.provider?.verifyToken}/><Metric l="App Secret" ok={data?.provider?.appSecret}/><Metric l="Access Token" ok={data?.provider?.accessToken}/><Metric l="Phone Number ID" ok={data?.provider?.phoneNumberId}/></div><div className={data?.provider?.ready?'success-box':'alert warning'}>{data?.provider?.ready?<><CheckCircle2/><div><strong>WhatsApp sağlayıcı tarafı hazır</strong><span>Webhook ve gönderim için gerekli temel Cloudflare değişkenleri tanımlı.</span></div></>:<><strong>Cloudflare secret kurulumu bekleniyor.</strong> Telefon numarası geldiğinde WHATSAPP_VERIFY_TOKEN, WHATSAPP_APP_SECRET, WHATSAPP_ACCESS_TOKEN ve WHATSAPP_PHONE_NUMBER_ID tanımlanacak.</>}</div></div>
  <div className="panel"><div className="panel-head"><div><h2>WhatsApp kullanıcı eşleştirme</h2><p>Kullanıcı web’e girmeden WhatsApp’tan “BAĞLA 123456” yazar. Kod 15 dakika geçerlidir ve tek kullanımlıktır.</p></div><Link2/></div><div className="form-grid"><label>Kullanıcı<select value={selectedUser} onChange={e=>{setSelectedUser(e.target.value);setPairing(null)}}><option value="">Kullanıcı seç</option>{users.map(x=><option key={x.id} value={x.id}>{x.display_name} · {roleName(x.role)}{x.whatsapp_status==='VERIFIED'?' · bağlı':''}</option>)}</select></label></div><button className="primary" disabled={!selectedUser||busy} onClick={createCode}>Eşleştirme Kodu Üret</button>{pairing&&<div className="success-box" style={{marginTop:14}}><CheckCircle2/><div><strong>{pairing.user.displayName} · {pairing.code}</strong><span>{pairing.instruction} Kod 15 dakika içinde kullanılmalıdır.</span></div><button className="ghost" onClick={()=>navigator.clipboard.writeText(pairing.instruction)}><Copy size={15}/> Kopyala</button></div>}</div>
  <div className="table-card"><table><thead><tr><th>Kullanıcı</th><th>Rol</th><th>WhatsApp</th><th>Son kullanım</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><strong>{x.display_name}</strong><div className="muted">{x.username||x.email||x.phone||'—'}</div></td><td>{roleName(x.role)}</td><td>{x.whatsapp_status==='VERIFIED'?<span className="status ok">Doğrulandı · {x.phone_e164}</span>:<span className="status neutral">Bağlı değil</span>}</td><td>{x.last_seen_at||'—'}</td></tr>)}</tbody></table>{!users.length&&<div className="empty">Eşleştirilebilir kullanıcı bulunmuyor.</div>}</div>
  <div className="section-head"><div><h2>Son Nibiru erişimleri</h2><p>Mesaj metni saklanmadan; kanal, rol, niyet ve erişim sonucu denetim amacıyla kaydedilir.</p></div></div><div className="table-card"><table><thead><tr><th>Zaman</th><th>Kullanıcı</th><th>Kanal</th><th>Rol</th><th>Niyet</th><th>Sonuç</th></tr></thead><tbody>{events.map((e:any)=><tr key={e.id}><td>{e.created_at}</td><td>{e.display_name||'—'}</td><td>{e.channel}</td><td>{roleName(e.role||'')}</td><td>{e.intent}</td><td><span className={`status ${e.outcome==='ANSWERED'?'ok':'neutral'}`}>{e.outcome}</span></td></tr>)}</tbody></table>{!events.length&&<div className="empty">Henüz Nibiru erişimi yok.</div>}</div>
 </>;
}
function Metric({l,ok}:{l:string;ok:boolean}){return <div><span>{l}</span><strong>{ok?'Hazır':'Eksik'}</strong></div>}
function SparkleText(){return <span aria-hidden="true">✨</span>}
