import { useEffect,useMemo,useState } from 'react';
import { BarChart3, CheckCircle2, Database, RefreshCw, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { api,qs } from '../api';

type Source={source_key:string;authority:string;label:string;source_kind:string;exam_family?:string|null;rights_status:string;ingestion_policy:string;archive_count:number;verified_mapping_count:number;last_checked_at?:string|null;last_success_at?:string|null;notes?:string|null};
type Insight={id:string;code?:string|null;title:string;grade_level?:number|null;subject_name:string;summary?:{examFamily:string;fromYear:number;toYear:number;totalQuestionCount:number;latestYearQuestionCount:number;yearsAppeared:number;yearsAnalyzed:number;historicalPriorityScore:number;historicalPriorityBand:'LOW'|'MEDIUM'|'HIGH';perYear:Array<{year:number;count:number}>}|null};

export function OfficialQuestionIntelligenceAdmin(){
 const [sources,setSources]=useState<Source[]>([]);const [runs,setRuns]=useState<any[]>([]);const [coverage,setCoverage]=useState<any[]>([]);const [items,setItems]=useState<Insight[]>([]);const [q,setQ]=useState('');const [family,setFamily]=useState<'LGS'|'YKS'>('LGS');const [grade,setGrade]=useState('8');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [mappingJson,setMappingJson]=useState('');const [mappingSource,setMappingSource]=useState('MEB_LGS_ARCHIVE');
 const loadStatus=async()=>{const r=await api<any>('/api/official-question-intelligence/status');setSources(r.sources||[]);setRuns(r.runs||[]);setCoverage(r.coverage||[])};
 const loadInsights=async()=>{const r=await api<any>(`/api/official-question-intelligence/outcomes${qs({q:q||null,examFamily:family,gradeLevel:grade||null})}`);setItems(r.items||[])};
 useEffect(()=>{void loadStatus().catch(e=>setError(e.message))},[]);useEffect(()=>{const t=setTimeout(()=>void loadInsights().catch(e=>setError(e.message)),250);return()=>clearTimeout(t)},[q,family,grade]);
 const refresh=async(sourceKey:string)=>{setBusy(sourceKey);setError('');setNotice('');try{const r=await api<any>(`/api/official-question-intelligence/sources/${sourceKey}/refresh`,{method:'POST'});setNotice(`${sourceKey}: ${r.discovered||0} yeni, ${r.updated||0} güncel kayıt. Telifli soru metni kopyalanmadı.`);await Promise.all([loadStatus(),loadInsights()])}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const refreshQuestionSources=async()=>{setBusy('QUESTION_SOURCES');setError('');setNotice('');try{for(const key of ['MEB_OGM_MATERIAL','EBA_RESOURCE'])await api(`/api/official-question-intelligence/sources/${key}/refresh`,{method:'POST'});setNotice('EBA / OGM kaynak durumu kontrol edildi. Yalnız izinli/açık lisanslı içerikler tam soru havuzuna alınabilir.');await loadStatus()}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const importMappings=async()=>{setError('');setNotice('');try{const parsed=JSON.parse(mappingJson);const rows=Array.isArray(parsed)?parsed:parsed.rows;if(!Array.isArray(rows))throw new Error('JSON bir dizi veya {rows:[...]} olmalı.');const r=await api<any>('/api/official-question-intelligence/mappings/import',{method:'POST',body:JSON.stringify({sourceKey:mappingSource,rows})});setNotice(`${r.mapped||0} soru-kazanım eşleştirmesi işlendi; ${r.skipped||0} satır atlandı.`);setMappingJson('');await Promise.all([loadStatus(),loadInsights()])}catch(e:any){setError(e.message)}};
 const sourceMap=useMemo(()=>Object.fromEntries(sources.map(s=>[s.source_key,s])),[sources]);
 return <>
  <div className="page-head"><div><span className="eyebrow">Süper Admin · Resmî Veri Zekâsı</span><h1>Çıkmış Soru & Kazanım Merkezi</h1><p>MEB LGS ve ÖSYM YKS geçmişini kazanım bazında izler. Telifli soru metinlerini kopyalamadan yıl, soru no, kazanım, zorluk ve resmî kaynak referansı tutulur.</p></div><button className="ghost" onClick={()=>void Promise.all([loadStatus(),loadInsights()])}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="alert warning"><ShieldCheck size={20}/><div><strong>Telif güvenli mod</strong><span>ÖSYM ve EBA/OGM içerikleri ücretsiz erişilebilir olsa da otomatik olarak telifsiz değildir. Bu merkez telifli resmî soruların metnini/şıklarını çoğaltmaz; analitik metadata ve resmî bağlantı saklar. Açık lisans, kamu malı veya yazılı izinli sorular ise tam soru havuzuna alınabilir.</span></div></div>

  <div className="summary-strip" style={{marginTop:16}}><S label="LGS kapsama yılı" value={coverage.find(x=>x.exam_family==='LGS')?.year_count||0}/><S label="LGS doğrulanmış eşleşme" value={coverage.find(x=>x.exam_family==='LGS')?.mapped_question_count||0}/><S label="YKS kapsama yılı" value={coverage.find(x=>x.exam_family==='YKS')?.year_count||0}/><S label="YKS doğrulanmış eşleşme" value={coverage.find(x=>x.exam_family==='YKS')?.mapped_question_count||0}/></div>

  <div className="panel" style={{marginBottom:18}}><div className="panel-head"><div><h2>Tek tuşla resmî kaynak güncelleme</h2><p>Yeni yıl/sınav yayınlarını resmî indekslerden keşfeder. Güncelleme kayıtları audit log ve senkron geçmişine yazılır.</p></div><Database/></div><div className="exam-grid">
   <SourceCard source={sourceMap.MEB_LGS_ARCHIVE} action="MEB / LGS Güncelle" busy={busy==='MEB_LGS_ARCHIVE'} onClick={()=>void refresh('MEB_LGS_ARCHIVE')}/>
   <SourceCard source={sourceMap.OSYM_YKS_GROUP} action="ÖSYM / YKS Güncelle" busy={busy==='OSYM_YKS_GROUP'} onClick={()=>void refresh('OSYM_YKS_GROUP')}/>
   <div className="exam-card"><span className="pill">SORU KAYNAKLARI</span><h3>EBA / OGM / açık lisans kontrolü</h3><p>Kaynakların erişimini ve kullanım politikasını kontrol eder; telifli içeriği kopyalamaz.</p><button className="primary full" disabled={!!busy} onClick={()=>void refreshQuestionSources()}>{busy==='QUESTION_SOURCES'?'Kontrol ediliyor…':'Soru Kaynaklarını Güncelle'}</button></div>
  </div></div>

  <div className="panel" style={{marginBottom:18}}><div className="panel-head"><div><h2>Zorluk renk standardı</h2><p>Soru havuzu, Studio, Recovery ve raporlarda aynı renk dili kullanılacak.</p></div><Sparkles/></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Difficulty color="blue" label="Mavi · Kolay" detail="Zorluk 1–2"/><Difficulty color="green" label="Yeşil · Orta" detail="Zorluk 3"/><Difficulty color="red" label="Kırmızı · Zor" detail="Zorluk 4–5"/></div></div>

  <div className="panel" style={{marginBottom:18}}><div className="panel-head"><div><h2>Kazanımın yıllara göre çıkmış soru dağılımı</h2><p>“Çıkma olasılığı” yerine yanıltıcı olmayan tarihsel öncelik skoru kullanılır: geçmiş sıklık + son yıllar + süreklilik.</p></div><BarChart3/></div><div className="exam-search-row"><div className="exam-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Kazanım adı, kodu veya konu ara…"/></div><select value={family} onChange={e=>{const v=e.target.value as 'LGS'|'YKS';setFamily(v);setGrade(v==='LGS'?'8':'12')}}><option value="LGS">LGS</option><option value="YKS">YKS / TYT / AYT</option></select></div><div style={{marginTop:10,maxWidth:220}}><label>Sınıf<input type="number" min="5" max="12" value={grade} onChange={e=>setGrade(e.target.value)}/></label></div>
   <div className="table-card" style={{marginTop:14}}><table><thead><tr><th>Kazanım</th><th>Toplam</th><th>Son yıl</th><th>Yıllar</th><th>Tarihsel öncelik</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.subject_name} · {i.title}</strong><small>{i.code||''}</small></td><td>{i.summary?.totalQuestionCount??'—'}</td><td>{i.summary?`${i.summary.toYear}: ${i.summary.latestYearQuestionCount}`:'—'}</td><td>{i.summary?<div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{i.summary.perYear.map(y=><span className="pill" key={y.year}>{y.year} · {y.count}</span>)}</div>:'Henüz doğrulanmış eşleştirme yok'}</td><td>{i.summary?<Priority band={i.summary.historicalPriorityBand} score={i.summary.historicalPriorityScore}/>:<span className="status neutral">Veri bekliyor</span>}</td></tr>)}</tbody></table>{!items.length&&<div className="empty-state">Aramaya uygun kazanım bulunamadı.</div>}</div>
  </div>

  <details className="panel" style={{marginBottom:18}}><summary style={{cursor:'pointer',fontWeight:800}}>Doğrulanmış soru-kazanım eşleştirme paketi içe aktar</summary><p style={{marginTop:12}}>Bu alan soru metni istemez. Yalnız yıl, sınav oturumu, soru numarası, kazanım ve zorluk metadata'sı girilir. Böylece eski müfredat/yeni müfredat eşleştirmeleri de denetlenebilir.</p><div className="form-grid"><label>Kaynak<select value={mappingSource} onChange={e=>setMappingSource(e.target.value)}>{sources.filter(s=>s.exam_family).map(s=><option key={s.source_key} value={s.source_key}>{s.label}</option>)}</select></label></div><textarea rows={10} value={mappingJson} onChange={e=>setMappingJson(e.target.value)} placeholder={'[{"year":2026,"examFamily":"LGS","sessionCode":"SAYISAL","subjectName":"Matematik","questionNo":1,"outcomeCode":"...","difficulty":4,"verified":true}]'}/><button className="primary" disabled={!mappingJson.trim()} onClick={()=>void importMappings()}>Eşleştirmeleri İçe Aktar</button></details>

  <div className="panel"><div className="panel-head"><div><h2>Son güncelleme kayıtları</h2><p>Kaynak bazında keşif ve eşleştirme geçmişi.</p></div><CheckCircle2/></div><div className="table-card"><table><thead><tr><th>Kaynak</th><th>İşlem</th><th>Durum</th><th>Yeni</th><th>Eşleşme</th><th>Tarih</th></tr></thead><tbody>{runs.slice(0,20).map(r=><tr key={r.id}><td>{r.source_label}</td><td>{r.sync_kind}</td><td><span className={`status ${r.status==='SUCCESS'?'ok':r.status==='FAILED'?'error':'neutral'}`}>{r.status}</span></td><td>{r.discovered_count||0}</td><td>{r.mapped_count||0}</td><td>{r.started_at}</td></tr>)}</tbody></table></div></div>
 </>;
}
function S({label,value}:{label:string;value:any}){return <div className="summary"><span>{label}</span><strong>{value}</strong></div>}
function SourceCard({source,action,busy,onClick}:{source?:Source;action:string;busy:boolean;onClick:()=>void}){return <div className="exam-card"><span className="pill">{source?.authority||'RESMÎ'}</span><h3>{source?.label||action}</h3><p>{source?.archive_count||0} arşiv · {source?.verified_mapping_count||0} doğrulanmış soru-kazanım kaydı</p><small>{source?.last_success_at?`Son başarılı: ${source.last_success_at}`:'Henüz güncellenmedi'}</small><button className="primary full" disabled={busy} onClick={onClick}>{busy?'Güncelleniyor…':action}</button></div>}
function Difficulty({color,label,detail}:{color:'blue'|'green'|'red';label:string;detail:string}){return <div style={{display:'flex',alignItems:'center',gap:9,border:'1px solid var(--line,#dfe4ea)',borderRadius:12,padding:'10px 14px'}}><span className={`difficulty-dot ${color}`}/><div><strong>{label}</strong><small style={{display:'block'}}>{detail}</small></div></div>}
function Priority({band,score}:{band:'LOW'|'MEDIUM'|'HIGH';score:number}){const label=band==='HIGH'?'Yüksek':band==='MEDIUM'?'Orta':'Düşük';return <div><span className={`priority ${band.toLowerCase()}`}>{label}</span><small style={{display:'block',marginTop:4}}>Skor {score}/100 · tahmin değil</small></div>}
