import { useEffect,useMemo,useState } from 'react';
import { Printer,RefreshCw } from 'lucide-react';
import { api,ApiError,qs } from '../api';
import { useAuth } from '../auth';

type PrintField={key:string;xMm?:number;yMm?:number;x?:number;y?:number;fontSizePt?:number;columnPitchMm?:number;rowPitchMm?:number;digits?:number};

export function OpticalPrepare(){
 const{user}=useAuth();const[institutions,setInstitutions]=useState<any[]>([]);const[institutionId,setInstitutionId]=useState('');const[classes,setClasses]=useState<any[]>([]);const[templates,setTemplates]=useState<any[]>([]);const[exams,setExams]=useState<any[]>([]);const[classId,setClassId]=useState('');const[templateId,setTemplateId]=useState('');const[examId,setExamId]=useState('');const[bookletSet,setBookletSet]=useState('');const[sort,setSort]=useState('number');const[data,setData]=useState<any>(null);const[selected,setSelected]=useState<string[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{void api<any>('/api/optical-templates').then(t=>{const list=(t.templates||[]).filter((x:any)=>x.has_print);setTemplates(list);if(list[0])setTemplateId(list[0].version_id)}).catch(e=>setError(e.message));if(user?.role==='SUPER_ADMIN')void api<any>('/api/institutions').then(r=>{setInstitutions(r.institutions||[]);if(r.institutions?.[0])setInstitutionId(r.institutions[0].id)}).catch(e=>setError(e.message));},[user?.role]);
 const loadScope=async()=>{setData(null);setSelected([]);setError('');try{const suffix=qs({institutionId:user?.role==='SUPER_ADMIN'?institutionId:null});const[c,e]=await Promise.all([api<any>(`/api/classes${suffix}`),api<any>(`/api/exams${suffix}`)]);setClasses(c.classes||[]);setExams(e.exams||[]);setClassId(c.classes?.[0]?.id||'');}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(user?.role!=='SUPER_ADMIN'||institutionId)void loadScope()},[institutionId,user?.role]);
 const load=async()=>{setBusy(true);setError('');try{const r=await api<any>(`/api/optical-prepare${qs({institutionId:user?.role==='SUPER_ADMIN'?institutionId:null,classId,templateVersionId:templateId,examId:examId||null,bookletSet:bookletSet||null,sort})}`);setData(r);setSelected(r.students.map((s:any)=>s.id));}catch(e){setError(e instanceof ApiError?e.message:'Optikler hazırlanamadı.')}finally{setBusy(false)}};
 const students=useMemo(()=>data?.students?.filter((s:any)=>selected.includes(s.id))||[],[data,selected]);
 const fields:PrintField[]=useMemo(()=>{const p=data?.template?.printFields;if(!p)return[];return Array.isArray(p.fields)?p.fields:Object.entries(p).map(([key,value]:any)=>({key,...value}))},[data]);
 const toggle=(id:string,on:boolean)=>setSelected(cur=>on?[...new Set([...cur,id])]:cur.filter(x=>x!==id));
 const fieldValue=(f:PrintField,s:any)=>{switch(f.key){case'studentName':return`${s.first_name} ${s.last_name}`;case'studentNumber':return s.student_number||'';case'class':return`${s.grade_level||''}/${s.section||''}`;case'section':return s.section||'';case'institutionCode':return data?.institution?.code||'';case'bookletCode':return s.booklet_code||'A';case'examTitle':return data?.exam?.title||'';case'examCode':return data?.exam?.id||'';case'qr':case'barcode':return`${data?.exam?.id||'OPT'}:${s.id}`;default:return''}};
 const renderField=(f:PrintField,s:any,i:number)=>{const left=Number(f.xMm??f.x??0),top=Number(f.yMm??f.y??0);const baseStyle:React.CSSProperties={position:'absolute',left:`${left}mm`,top:`${top}mm`,fontSize:`${Number(f.fontSizePt||9)}pt`,fontWeight:700,lineHeight:1};if(f.key==='studentNumberBubbles')return <BubbleNumber key={`${s.id}-${i}`} value={String(s.student_number||'')} field={f} style={baseStyle}/>;return <div key={`${s.id}-${i}`} style={baseStyle}>{fieldValue(f,s)}</div>};
 return <>
  <style>{`@media print{body *{visibility:hidden!important}.optical-print-root,.optical-print-root *{visibility:visible!important}.optical-print-root{position:absolute!important;left:0;top:0;width:100%;}.optical-controls{display:none!important}.print-optical-page{margin:0!important;border:0!important;box-shadow:none!important;page-break-after:always;break-after:page}.print-optical-page:last-child{page-break-after:auto;break-after:auto}@page{margin:0}}`}</style>
  <div className="page-head optical-controls"><div><span className="eyebrow">Optik Merkezi · Kişiye özel baskı</span><h1>Optik Hazırla / Bas</h1><p>Admin veya kurum yöneticisi; kurum, sınıf, sınav ve optiği seçerek öğrenci bilgileri önceden işlenmiş optikleri tekil ya da toplu basabilir.</p></div><button className="ghost" onClick={()=>void loadScope()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error optical-controls">{error}</div>}
  <div className="panel optical-controls"><div className="form-grid">{user?.role==='SUPER_ADMIN'&&<label>Kurum<select value={institutionId} onChange={e=>setInstitutionId(e.target.value)}>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}<label>Optik<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Baskı tanımı olan optik seç</option>{templates.map(t=><option key={t.version_id} value={t.version_id}>{t.name}</option>)}</select></label><label>Sınıf<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Sınıf seç</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.student_count} öğrenci</option>)}</select></label><label>Sınav (isteğe bağlı)<select value={examId} onChange={e=>setExamId(e.target.value)}><option value="">Sınavsız genel optik</option>{exams.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Kitapçık seti<input value={bookletSet} onChange={e=>setBookletSet(e.target.value.toUpperCase())} placeholder="Boş = sınavdan otomatik, örn. A,B,C,D"/></label><label>Sıralama<select value={sort} onChange={e=>setSort(e.target.value)}><option value="number">Öğrenci numarası</option><option value="name">Ad soyad</option></select></label></div><button className="primary" onClick={load} disabled={busy||!classId||!templateId}><Printer size={17}/>{busy?'Hazırlanıyor…':'Optikleri Hazırla'}</button></div>
  {data&&<div className="panel optical-controls"><div className="panel-head"><div><h2>{data.class.name} · {data.students.length} öğrenci</h2><p>Seçili {students.length} optik basılacak. Yazıcıda %100 / Actual Size kullanın; kalibrasyonu tamamlanmış yazıcı profili tercih edin.</p></div><button className="primary" disabled={!students.length} onClick={()=>window.print()}><Printer size={17}/> Seçilenleri Yazdır</button></div><div style={{display:'flex',gap:12,alignItems:'center',marginBottom:12}}><label className="check"><input type="checkbox" checked={selected.length===data.students.length} onChange={e=>setSelected(e.target.checked?data.students.map((s:any)=>s.id):[])}/> Tümünü seç</label><span className="muted">Kitapçık: {(data.bookletCodes||[]).join(' / ')}</span></div><div className="table-card"><table><thead><tr><th></th><th>No</th><th>Öğrenci</th><th>Sınıf</th><th>Kitapçık</th></tr></thead><tbody>{data.students.map((s:any)=><tr key={s.id}><td><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>toggle(s.id,e.target.checked)}/></td><td>{s.student_number||'—'}</td><td><strong>{s.first_name} {s.last_name}</strong></td><td>{s.grade_level}/{s.section}</td><td>{s.booklet_code||'A'}</td></tr>)}</tbody></table></div></div>}
  {data&&<div className="optical-print-root" style={{display:students.length?'block':'none'}}>{students.map((s:any)=><div className="print-optical-page" key={s.id} style={{width:`${data.template.pageWidthMm}mm`,height:`${data.template.pageHeightMm}mm`,position:'relative',margin:'16px auto',backgroundColor:'#fff',backgroundImage:`url(/api/v2/optical-print-base?versionId=${encodeURIComponent(data.template.id)})`,backgroundSize:'100% 100%',backgroundRepeat:'no-repeat',border:'1px solid #d7dde7',overflow:'hidden'}}>{fields.map((f,i)=>renderField(f,s,i))}</div>)}</div>}
 </>;
}

function BubbleNumber({value,field,style}:{value:string;field:PrintField;style:React.CSSProperties}){
 const digits=Math.max(Number(field.digits||value.length||4),value.length);const padded=value.padStart(digits,'0').slice(-digits);const colPitch=Number(field.columnPitchMm||5);const rowPitch=Number(field.rowPitchMm||4.1);
 return <div style={style}>{Array.from({length:digits}).map((_,col)=><div key={col} style={{position:'absolute',left:`${col*colPitch}mm`,top:0}}>{Array.from({length:10}).map((__,n)=><div key={n} style={{position:'absolute',top:`${n*rowPitch}mm`,width:'3.2mm',height:'3.2mm',border:'0.25mm solid #111',borderRadius:'50%',background:padded[col]===String(n)?'#111':'transparent'}}/>)}</div>)}</div>;
}
