import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2,Printer,RefreshCw,Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api,ApiError,qs } from '../api';
import { useAuth } from '../auth';
import { calibrationCorrection,calibrationTransform,isPrintCalibrationReady } from '../lib/printCalibration';

type PrintField={key:string;xMm?:number;yMm?:number;x?:number;y?:number;fontSizePt?:number;columnPitchMm?:number;rowPitchMm?:number;digits?:number};

export function OpticalPrepare(){
 const{user}=useAuth();
 const[institutions,setInstitutions]=useState<any[]>([]);const[institutionId,setInstitutionId]=useState('');
 const[classes,setClasses]=useState<any[]>([]);const[templates,setTemplates]=useState<any[]>([]);const[exams,setExams]=useState<any[]>([]);const[profiles,setProfiles]=useState<any[]>([]);const[calibrations,setCalibrations]=useState<any[]>([]);
 const[classId,setClassId]=useState('');const[templateId,setTemplateId]=useState('');const[profileId,setProfileId]=useState('');const[examId,setExamId]=useState('');const[bookletSet,setBookletSet]=useState('');const[sort,setSort]=useState('number');
 const[data,setData]=useState<any>(null);const[selected,setSelected]=useState<string[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{void api<any>('/api/optical-templates').then(t=>{const list=(t.templates||[]).filter((x:any)=>x.has_print);setTemplates(list);if(list[0])setTemplateId(list[0].version_id)}).catch(e=>setError(e.message));if(user?.role==='SUPER_ADMIN')void api<any>('/api/institutions').then(r=>{setInstitutions(r.institutions||[]);if(r.institutions?.[0])setInstitutionId(r.institutions[0].id)}).catch(e=>setError(e.message));},[user?.role]);
 const loadScope=async()=>{setData(null);setSelected([]);setError('');try{const suffix=qs({institutionId:user?.role==='SUPER_ADMIN'?institutionId:null});const[c,e,p,cal]=await Promise.all([api<any>(`/api/classes${suffix}`),api<any>(`/api/exams${suffix}`),api<any>(`/api/printer-profiles${suffix}`),api<any>(`/api/calibrations${suffix}`)]);setClasses(c.classes||[]);setExams(e.exams||[]);setProfiles(p.profiles||[]);setCalibrations(cal.calibrations||[]);setClassId(c.classes?.[0]?.id||'');setProfileId(cur=>(p.profiles||[]).some((x:any)=>x.id===cur)?cur:(p.profiles?.[0]?.id||''));}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(user?.role!=='SUPER_ADMIN'||institutionId)void loadScope()},[institutionId,user?.role]);
 useEffect(()=>{if(!templateId||!profiles.length)return;const ready=calibrations.find((c:any)=>c.optical_template_version_id===templateId&&c.status==='READY');if(ready)setProfileId(ready.printer_profile_id)},[templateId,calibrations,profiles.length]);
 const calibration=useMemo(()=>calibrations.find((c:any)=>c.printer_profile_id===profileId&&c.optical_template_version_id===templateId)||null,[calibrations,profileId,templateId]);
 const calibrationReady=isPrintCalibrationReady(calibration);const correction=calibrationCorrection(calibration);
 const load=async()=>{setBusy(true);setError('');try{const r=await api<any>(`/api/optical-prepare${qs({institutionId:user?.role==='SUPER_ADMIN'?institutionId:null,classId,templateVersionId:templateId,examId:examId||null,bookletSet:bookletSet||null,sort})}`);setData(r);setSelected(r.students.map((s:any)=>s.id));}catch(e){setError(e instanceof ApiError?e.message:'Optikler hazırlanamadı.')}finally{setBusy(false)}};
 const students=useMemo(()=>data?.students?.filter((s:any)=>selected.includes(s.id))||[],[data,selected]);
 const fields:PrintField[]=useMemo(()=>{const p=data?.template?.printFields;if(!p)return[];return Array.isArray(p.fields)?p.fields:Object.entries(p).map(([key,value]:any)=>({key,...value}))},[data]);
 const toggle=(id:string,on:boolean)=>setSelected(cur=>on?[...new Set([...cur,id])]:cur.filter(x=>x!==id));
 const fieldValue=(f:PrintField,s:any)=>{switch(f.key){case'studentName':return`${s.first_name} ${s.last_name}`;case'studentNumber':return s.student_number||'';case'class':return`${s.grade_level||''}/${s.section||''}`;case'section':return s.section||'';case'institutionCode':return data?.institution?.code||'';case'bookletCode':return s.booklet_code||'A';case'examTitle':return data?.exam?.title||'';case'examCode':return data?.exam?.id||'';case'qr':case'barcode':return`${data?.exam?.id||'OPT'}:${s.id}`;default:return''}};
 const renderField=(f:PrintField,s:any,i:number)=>{const left=Number(f.xMm??f.x??0),top=Number(f.yMm??f.y??0);const baseStyle:React.CSSProperties={position:'absolute',left:`${left}mm`,top:`${top}mm`,fontSize:`${Number(f.fontSizePt||9)}pt`,fontWeight:700,lineHeight:1};if(f.key==='studentNumberBubbles')return <BubbleNumber key={`${s.id}-${i}`} value={String(s.student_number||'')} field={f} style={baseStyle}/>;return <div key={`${s.id}-${i}`} style={baseStyle}>{fieldValue(f,s)}</div>};
 const printNow=()=>{if(!calibrationReady){setError('Bu yazıcı + optik kombinasyonu kalibre edilmeden hassas optik baskısı başlatılamaz. Önce Kalibrasyon ekranını tamamlayın.');return}window.print()};
 return <>
  <style>{`@media print{body *{visibility:hidden!important}.optical-print-root,.optical-print-root *{visibility:visible!important}.optical-print-root{position:absolute!important;left:0;top:0;width:100%;}.optical-controls{display:none!important}.print-optical-page{margin:0!important;border:0!important;box-shadow:none!important;page-break-after:always;break-after:page}.print-optical-page:last-child{page-break-after:auto;break-after:auto}@page{margin:0}}`}</style>
  <div className="page-head optical-controls"><div><span className="eyebrow">Optik Merkezi · Kişiye özel baskı</span><h1>Optik Hazırla / Bas</h1><p>Optik bir kez tanımlandıktan sonra kalıcı şablon olur. Optik 840, Optik 129 veya yeni tanımlanan optiği seçin; kayıtlı yazıcı kalibrasyonu otomatik uygulansın.</p></div><button className="ghost" onClick={()=>void loadScope()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error optical-controls">{error}</div>}
  <div className="panel optical-controls"><div className="panel-head"><div><h2>Hazır optik şablonları</h2><p>Tek tıkla baskı şablonunu değiştirin. Yeni optikler tanımlandıkça bu listeye otomatik eklenir.</p></div><Link className="secondary" to="/opticals">Yeni Optik Tanımla</Link></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{templates.map(t=><button key={t.version_id} className={templateId===t.version_id?'primary':'secondary'} onClick={()=>setTemplateId(t.version_id)}>{t.name}’a Bas</button>)}{!templates.length&&<span className="muted">Henüz baskı alanı tanımlanmış optik yok.</span>}</div></div>
  <div className="panel optical-controls"><div className="form-grid">{user?.role==='SUPER_ADMIN'&&<label>Kurum<select value={institutionId} onChange={e=>setInstitutionId(e.target.value)}>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}<label>Optik<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Baskı tanımı olan optik seç</option>{templates.map(t=><option key={t.version_id} value={t.version_id}>{t.name}</option>)}</select></label><label>Yazıcı profili<select value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">Yazıcı profili seç</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Sınıf<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Sınıf seç</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.student_count} öğrenci</option>)}</select></label><label>Sınav (isteğe bağlı)<select value={examId} onChange={e=>setExamId(e.target.value)}><option value="">Sınavsız genel optik</option>{exams.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Kitapçık seti<input value={bookletSet} onChange={e=>setBookletSet(e.target.value.toUpperCase())} placeholder="Boş = sınavdan otomatik, örn. A,B,C,D"/></label><label>Sıralama<select value={sort} onChange={e=>setSort(e.target.value)}><option value="number">Öğrenci numarası</option><option value="name">Ad soyad</option></select></label></div>{!profiles.length?<div className="alert info">Bu kurum için yazıcı profili yok. <Link className="link-button" to="/calibration">Yazıcı profili oluştur ve kalibre et.</Link></div>:calibrationReady?<div className="success-box"><CheckCircle2/><div><strong>{profiles.find(p=>p.id===profileId)?.name} + {templates.find(t=>t.version_id===templateId)?.name} hazır</strong><span>Kalibrasyon baskıya otomatik uygulanacak: X {correction.correctionOffsetX.toFixed(2)} mm · Y {correction.correctionOffsetY.toFixed(2)} mm · Ölçek {correction.correctionScaleX.toFixed(5)} / {correction.correctionScaleY.toFixed(5)} · Dönüş {correction.correctionRotation.toFixed(3)}°</span></div></div>:profileId&&templateId?<div className="alert warning">Bu yazıcı + optik kombinasyonu henüz doğrulanmadı. <Link className="link-button" to="/calibration"><Wrench size={14}/> Kalibrasyona Git</Link></div>:null}<button className="primary" style={{marginTop:14}} onClick={load} disabled={busy||!classId||!templateId}><Printer size={17}/>{busy?'Hazırlanıyor…':'Optikleri Hazırla'}</button></div>
  {data&&<div className="panel optical-controls"><div className="panel-head"><div><h2>{data.class.name} · {data.students.length} öğrenci</h2><p>Seçili {students.length} optik basılacak. İşletim sistemi penceresinde kayıtlı profile karşılık gelen fiziksel yazıcıyı seçin ve %100 / Actual Size kullanın.</p></div><button className="primary" disabled={!students.length||!calibrationReady} onClick={printNow}><Printer size={17}/> Seçilenleri Yazdır</button></div><div style={{display:'flex',gap:12,alignItems:'center',marginBottom:12}}><label className="check"><input type="checkbox" checked={selected.length===data.students.length} onChange={e=>setSelected(e.target.checked?data.students.map((s:any)=>s.id):[])}/> Tümünü seç</label><span className="muted">Kitapçık: {(data.bookletCodes||[]).join(' / ')}</span><span className={`status ${calibrationReady?'ok':'warn'}`}>{calibrationReady?'Kalibrasyon hazır':'Kalibrasyon gerekli'}</span></div><div className="table-card"><table><thead><tr><th></th><th>No</th><th>Öğrenci</th><th>Sınıf</th><th>Kitapçık</th></tr></thead><tbody>{data.students.map((s:any)=><tr key={s.id}><td><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>toggle(s.id,e.target.checked)}/></td><td>{s.student_number||'—'}</td><td><strong>{s.first_name} {s.last_name}</strong></td><td>{s.grade_level}/{s.section}</td><td>{s.booklet_code||'A'}</td></tr>)}</tbody></table></div></div>}
  {data&&<div className="optical-print-root" style={{display:students.length?'block':'none'}}>{students.map((s:any)=><div className="print-optical-page" key={s.id} style={{width:`${data.template.pageWidthMm}mm`,height:`${data.template.pageHeightMm}mm`,position:'relative',margin:'16px auto',background:'#fff',border:'1px solid #d7dde7',overflow:'hidden'}}><div style={{position:'absolute',left:0,top:0,width:`${data.template.pageWidthMm}mm`,height:`${data.template.pageHeightMm}mm`,transformOrigin:'0 0',transform:calibrationReady?calibrationTransform(calibration):'none',backgroundImage:`url(/api/v2/optical-print-base?versionId=${encodeURIComponent(data.template.id)})`,backgroundSize:'100% 100%',backgroundRepeat:'no-repeat'}}>{fields.map((f,i)=>renderField(f,s,i))}</div></div>)}</div>}
 </>;
}

function BubbleNumber({value,field,style}:{value:string;field:PrintField;style:React.CSSProperties}){
 const digits=Math.max(Number(field.digits||value.length||4),value.length);const padded=value.padStart(digits,'0').slice(-digits);const colPitch=Number(field.columnPitchMm||5);const rowPitch=Number(field.rowPitchMm||4.1);
 return <div style={style}>{Array.from({length:digits}).map((_,col)=><div key={col} style={{position:'absolute',left:`${col*colPitch}mm`,top:0}}>{Array.from({length:10}).map((__,n)=><div key={n} style={{position:'absolute',top:`${n*rowPitch}mm`,width:'3.2mm',height:'3.2mm',border:'0.25mm solid #111',borderRadius:'50%',background:padded[col]===String(n)?'#111':'transparent'}}/>)}</div>)}</div>;
}
