import { useEffect,useState } from 'react';
import { BarChart3, ChevronDown, ChevronUp, Target } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';

type Stat={examFamily:string;fromYear:number;toYear:number;totalQuestionCount:number;latestYearQuestionCount:number;yearsAppeared:number;yearsAnalyzed:number;historicalPriorityScore:number;historicalPriorityBand:'LOW'|'MEDIUM'|'HIGH';perYear:Array<{year:number;count:number}>};

export function Outcomes(){
 const{user}=useAuth();const[rows,setRows]=useState<any[]>([]);const[open,setOpen]=useState('');const[history,setHistory]=useState<Record<string,{loading?:boolean;LGS?:Stat|null;YKS?:Stat|null;error?:string}>>({});
 useEffect(()=>{const p=user?.role==='STUDENT'?'/api/my-outcomes':'/api/teacher/insights';void api<any>(p).then(r=>setRows(r.outcomes||[])).catch(()=>setRows([]))},[user?.role]);
 const toggle=async(o:any)=>{const id=String(o.id||o.outcome_id||'');if(!id)return;if(open===id){setOpen('');return}setOpen(id);if(history[id])return;setHistory(h=>({...h,[id]:{loading:true}}));try{const [lgs,yks]=await Promise.all([api<any>(`/api/official-question-intelligence/outcomes/${id}/stats?examFamily=LGS`).catch(()=>null),api<any>(`/api/official-question-intelligence/outcomes/${id}/stats?examFamily=YKS`).catch(()=>null)]);setHistory(h=>({...h,[id]:{LGS:lgs?.stats?.[0]||null,YKS:yks?.stats?.[0]||null}}))}catch(e:any){setHistory(h=>({...h,[id]:{error:e.message||'Geçmiş veri alınamadı.'}}))}};
 return <><div className="page-head"><div><span className="eyebrow">Kazanım odaklı takip</span><h1>{user?.role==='STUDENT'?'Geliştirilecek Kazanımlarım':'Kazanım Analizi'}</h1><p>{user?.role==='STUDENT'?'Tek bir yanlışla değil, yeterli soru kanıtına göre değerlendirilir. Kazanıma dokunarak resmî LGS/YKS geçmişindeki soru dağılımını da görebilirsin.':'Yetkiniz dışında kalan ders ve sınıf verileri backend tarafından filtrelenir. Kazanıma dokunarak doğrulanmış resmî sınav geçmişini görüntüleyebilirsiniz.'}</p></div></div><div className="outcome-table">{rows.map((o:any)=>{const id=String(o.id||o.outcome_id||'');const h=history[id];return <div className="outcome-history-wrap" key={`${id}-${o.class_id||''}`}><button type="button" className="outcome-line outcome-clickable" onClick={()=>void toggle(o)}><div className="outcome-icon"><Target size={18}/></div><div className="grow"><strong>{o.title}</strong><span>{o.subject_name}{o.topic?` · ${o.topic}`:''}</span><div className="progress"><i style={{width:`${Math.round(Number(o.success_rate)*100)}%`}}/></div></div><div className="percent">%{Math.round(Number(o.success_rate)*100)}<small>{o.evidence_count||o.evidence} soru</small></div>{open===id?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>{open===id&&<div className="official-history-panel"><div className="official-history-title"><BarChart3 size={17}/><div><strong>Resmî sınav geçmişi</strong><span>Doğrulanmış soru–kazanım eşleştirmeleri · gelecekte soru çıkacağına dair garanti değildir.</span></div></div>{h?.loading?<div className="empty-state">Geçmiş dağılım yükleniyor…</div>:h?.error?<div className="alert error">{h.error}</div>:<div className="official-history-grid"><HistoryCard label="LGS" stat={h?.LGS}/><HistoryCard label="YKS / TYT / AYT" stat={h?.YKS}/></div>}</div>}</div>})}{!rows.length&&<div className="empty">Yeterli kazanım verisi henüz oluşmadı.</div>}</div></>}
}
function HistoryCard({label,stat}:{label:string;stat?:Stat|null}){if(!stat)return <div className="history-card empty-history"><span className="pill">{label}</span><strong>Doğrulanmış geçmiş eşleştirme yok</strong><small>Sistem sayı tahmin etmez veya uydurmaz.</small></div>;const priority=stat.historicalPriorityBand==='HIGH'?'Yüksek':stat.historicalPriorityBand==='MEDIUM'?'Orta':'Düşük';return <div className="history-card"><div className="history-head"><span className="pill">{label}</span><span className={`priority ${stat.historicalPriorityBand.toLowerCase()}`}>{priority} tarihsel öncelik</span></div><div className="history-numbers"><div><span>Toplam</span><strong>{stat.totalQuestionCount}</strong><small>{stat.fromYear}–{stat.toYear}</small></div><div><span>Son yıl</span><strong>{stat.latestYearQuestionCount}</strong><small>{stat.toYear}</small></div><div><span>Görüldüğü yıl</span><strong>{stat.yearsAppeared}/{stat.yearsAnalyzed}</strong><small>doğrulanmış kapsam</small></div></div><div className="year-chips">{stat.perYear.map(y=><span key={y.year}>{y.year} · {y.count}</span>)}</div><small className="history-note">Tarihsel skor {stat.historicalPriorityScore}/100 · bir sınav tahmini değildir.</small></div>}
