import { useEffect,useState } from 'react';
import { CalendarDays,Gamepad2,RefreshCw,Sparkles,TicketCheck } from 'lucide-react';
import { api } from '../api';

export function PremiumCenter(){
 const [membership,setMembership]=useState<any>(null);const [live,setLive]=useState<any>(null);const [games,setGames]=useState<any>(null);const [tab,setTab]=useState('membership');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [session,setSession]=useState({sessionType:'COACH',scheduledAt:'',providerId:'',creditCost:1});
 const load=async()=>{const [m,l,g]=await Promise.all([api<any>('/api/platform/membership').catch(()=>null),api<any>('/api/platform/live').catch(()=>null),api<any>('/api/platform/games').catch(()=>null)]);setMembership(m);setLive(l);setGames(g)};useEffect(()=>{void load()},[]);
 const reserve=async()=>{try{const r=await api<any>('/api/platform/live',{method:'POST',body:JSON.stringify(session)});setNotice(`Rezervasyon oluşturuldu · ${r.id}. Görüşme sağlayıcısı daha sonra bağlanacak.`);await load()}catch(e:any){setError(e.message)}};
 const playDemo=async(code:string)=>{try{await api('/api/platform/games',{method:'POST',body:JSON.stringify({gameCode:code,score:80,xpEarned:25,durationSeconds:60})});setNotice('Demo oyun oturumu kaydedildi ve XP işlendi.');await load()}catch(e:any){setError(e.message)}};
 return <><div className="page-head"><div><span className="eyebrow">Lisanslı Öğrenci Ürünleri</span><h1>Gold · Premium · Live</h1><p>Kurum lisansı çekirdek kullanımı sağlar. İleri AI/RBA/Recovery ve insan desteği entitlement + kredi modeliyle yönetilir.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div style={{display:'flex',gap:8,marginBottom:16}}><button className={tab==='membership'?'primary':'secondary'} onClick={()=>setTab('membership')}><Sparkles size={16}/> Üyelik</button><button className={tab==='live'?'primary':'secondary'} onClick={()=>setTab('live')}><CalendarDays size={16}/> Live</button><button className={tab==='games'?'primary':'secondary'} onClick={()=>setTab('games')}><Gamepad2 size={16}/> Oyunlar</button></div>
 {tab==='membership'&&<><div className="summary-strip"><S label="Mevcut plan" value={membership?.membership?.plan_name||'Standard'}/><S label="Live Credit" value={membership?.wallet?.balance||0}/></div><div className="exam-grid">{(membership?.plans||[]).map((p:any)=><div className="exam-card" key={p.id}><span className="pill">{p.code}</span><h3>{p.name}</h3><p>{p.monthly_live_credits?`Aylık ${p.monthly_live_credits} Live Credit`:'Live Credit dahil değil'}</p><div className="feature-list">{Object.keys(p.entitlements||{}).map(k=><span key={k}>✓ {k.replaceAll('_',' ')}</span>)}</div></div>)}</div><div className="alert warning" style={{marginTop:16}}>Ödeme sağlayıcısı ve mağaza içi satın alma henüz bağlanmadı. Bu ekran entitlement modelini test eder; sahte ödeme üretmez.</div></>}
 {tab==='live'&&<><div className="summary-strip"><S label="Kredi" value={live?.wallet?.balance||0}/><S label="Yaklaşan" value={(live?.sessions||[]).filter((s:any)=>['RESERVED','CONFIRMED'].includes(s.status)).length}/></div><div className="panel" style={{marginBottom:16}}><h2>Görüşme rezervasyonu</h2><div className="form-grid"><label>Tür<select value={session.sessionType} onChange={e=>setSession({...session,sessionType:e.target.value})}><option value="GUIDANCE">Canlı Rehberlik</option><option value="COACH">Canlı Eğitim Koçu</option><option value="LESSON">Canlı Ders</option></select></label><label>Uzman<select value={session.providerId} onChange={e=>setSession({...session,providerId:e.target.value})}><option value="">Uygun uzman daha sonra eşleşsin</option>{(live?.providers||[]).filter((p:any)=>p.provider_type===session.sessionType).map((p:any)=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>Tarih / saat<input type="datetime-local" value={session.scheduledAt} onChange={e=>setSession({...session,scheduledAt:e.target.value})}/></label><label>Kredi<input type="number" min="1" value={session.creditCost} onChange={e=>setSession({...session,creditCost:Number(e.target.value)})}/></label></div><button className="primary" onClick={reserve} disabled={!session.scheduledAt}><TicketCheck size={16}/> Rezervasyon Yap</button></div><div className="table-card"><table><thead><tr><th>Tarih</th><th>Tür</th><th>Uzman</th><th>Kredi</th><th>Durum</th></tr></thead><tbody>{(live?.sessions||[]).map((s:any)=><tr key={s.id}><td>{s.scheduled_at}</td><td>{s.session_type}</td><td>{s.provider_name||'Eşleşecek'}</td><td>{s.credit_cost}</td><td><span className="status neutral">{s.status}</span></td></tr>)}</tbody></table></div><div className="alert warning" style={{marginTop:16}}>Gerçek video görüşme sağlayıcısı seçilmedi. Rezervasyon/kredi altyapısı hazır; meeting linki ancak güvenli sağlayıcı bağlandıktan sonra üretilecek.</div></>}
 {tab==='games'&&<><div className="summary-strip"><S label="XP" value={games?.profile?.xp||0}/><S label="Seviye" value={games?.profile?.level||1}/><S label="Seri" value={games?.profile?.streak_days||0}/></div><div className="exam-grid">{(games?.games||[]).map((g:any)=><div className="exam-card" key={g.code}><Gamepad2 size={28}/><h3>{g.title}</h3><p>Learning Graph'a kanıt üreten mini oyun altyapısı.</p><button className="secondary full" onClick={()=>void playDemo(g.code)}>Demo Oturumu Kaydet</button></div>)}</div></>}
 </>;
}
function S({label,value}:{label:string;value:any}){return <div className="summary"><span>{label}</span><strong>{value}</strong></div>}
