import { useEffect,useState } from 'react';
import { Bot,CalendarDays,Gamepad2,RefreshCw,ShoppingCart,Sparkles,TicketCheck } from 'lucide-react';
import { api } from '../api';

export function PremiumCenter(){
 const [membership,setMembership]=useState<any>(null);const [live,setLive]=useState<any>(null);const [games,setGames]=useState<any>(null);const [tab,setTab]=useState('membership');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [orderBusy,setOrderBusy]=useState('');const [session,setSession]=useState({sessionType:'COACH',scheduledAt:'',providerId:'',creditCost:1});const [aiMessage,setAiMessage]=useState('Bugün neye öncelik vermeliyim?');const [aiAnswer,setAiAnswer]=useState('');const [aiBusy,setAiBusy]=useState(false);
 const load=async()=>{const [catalog,current,l,g]=await Promise.all([api<any>('/api/membership/catalog').catch(()=>null),api<any>('/api/platform/membership').catch(()=>null),api<any>('/api/platform/live').catch(()=>null),api<any>('/api/platform/games').catch(()=>null)]);setMembership({...current,...catalog,membership:catalog?.membership||current?.membership});setLive(l);setGames(g)};useEffect(()=>{void load()},[]);
 const requestOrder=async(planId:string)=>{setOrderBusy(planId);setError('');setNotice('');try{const r=await api<any>('/api/membership/orders',{method:'POST',body:JSON.stringify({planId,paymentMethod:'BANK_TRANSFER'})});setNotice(`${r.plan} için ${r.amountTry} TL yıllık üyelik talebi alındı. Ödeme kaydı Süper Admin onayından sonra etkinleşir.`);await load()}catch(e:any){setError(e.message)}finally{setOrderBusy('')}};
 const reserve=async()=>{try{const r=await api<any>('/api/platform/live',{method:'POST',body:JSON.stringify(session)});setNotice(`Rezervasyon oluşturuldu · ${r.id}. Görüşme sağlayıcısı daha sonra bağlanacak.`);await load()}catch(e:any){setError(e.message)}};
 const askAi=async()=>{setAiBusy(true);setError('');setAiAnswer('');try{const r=await api<any>('/api/platform/ai-coach',{method:'POST',body:JSON.stringify({message:aiMessage})});setAiAnswer(r.answer)}catch(e:any){setError(e.message)}finally{setAiBusy(false)}};
 return <><div className="page-head"><div><span className="eyebrow">Lisanslı Öğrenci Ürünleri</span><h1>Gold · Premium · Live</h1><p>Kurum lisansı çekirdek kullanımı sağlar. İleri AI/RBA/Recovery ve insan desteği entitlement + kredi modeliyle yönetilir.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap'}}><button className={tab==='membership'?'primary':'secondary'} onClick={()=>setTab('membership')}><Sparkles size={16}/> Üyelik</button><button className={tab==='ai'?'primary':'secondary'} onClick={()=>setTab('ai')}><Bot size={16}/> AI Eğitim Koçu</button><button className={tab==='live'?'primary':'secondary'} onClick={()=>setTab('live')}><CalendarDays size={16}/> Live</button><button className={tab==='games'?'primary':'secondary'} onClick={()=>setTab('games')}><Gamepad2 size={16}/> Oyunlar</button></div>
 {tab==='membership'&&<><div className="summary-strip"><S label="Mevcut plan" value={membership?.membership?.plan_name||'Ücretsiz / Standard'}/><S label="Live Credit" value={membership?.wallet?.balance||0}/><S label="Bekleyen talep" value={(membership?.orders||[]).filter((o:any)=>o.status==='PENDING').length}/></div><div className="exam-grid">{(membership?.plans||[]).map((p:any)=><div className="exam-card" key={p.id}><span className="pill">{p.code}</span><h3>{p.name}</h3><strong style={{fontSize:26}}>{Number(p.annual_price_try||0)===0?'Ücretsiz':`${p.annual_price_try} TL / yıl`}</strong><p>{p.monthly_live_credits?`Aylık ${p.monthly_live_credits} Live Credit`:'Live Credit dahil değil'}</p><div className="feature-list">{Object.keys(p.entitlements||{}).map(k=><span key={k}>✓ {k.replaceAll('_',' ')}</span>)}</div>{p.code!=='STANDARD'&&<button className="primary full" disabled={Boolean(orderBusy)||(membership?.orders||[]).some((o:any)=>o.status==='PENDING')} onClick={()=>void requestOrder(p.id)}><ShoppingCart size={16}/>{orderBusy===p.id?'Talep oluşturuluyor…':'Yıllık üyelik talebi'}</button>}</div>)}</div>{Boolean(membership?.orders?.length)&&<div className="table-card" style={{marginTop:16}}><table><thead><tr><th>Plan</th><th>Tutar</th><th>Yöntem</th><th>Durum</th><th>Tarih</th></tr></thead><tbody>{membership.orders.map((o:any)=><tr key={o.id}><td>{o.plan_name}</td><td>{o.amount_try} TL</td><td>{o.payment_method}</td><td><span className={`status ${o.status==='PAID'?'success':o.status==='PENDING'?'warning':'danger'}`}>{o.status}</span></td><td>{new Date(o.requested_at).toLocaleDateString('tr-TR')}</td></tr>)}</tbody></table></div>}<div className="alert info" style={{marginTop:16}}>Banka transferi talebi gerçek bir yönetici onayıyla etkinleşir. iyzico, PayTR ve mağaza ödemeleri anahtarları girilmeden ödeme yapılmış sayılmaz.</div></>}
 {tab==='ai'&&<div className="panel"><div className="panel-head"><div><h2>Nibiru AI Eğitim Koçu</h2><p>Gold/Premium hakkı sunucuda doğrulanır; yalnız öğrencinin gerçek akademik verisi kullanılır.</p></div><Bot/></div><label>Ne sormak istiyorsun?<textarea rows={4} value={aiMessage} onChange={e=>setAiMessage(e.target.value)}/></label><button className="primary" onClick={askAi} disabled={aiBusy||!aiMessage.trim()}>{aiBusy?'Nibiru düşünüyor…':'Nibiru’ya Sor'}</button>{aiAnswer&&<div className="success-box" style={{marginTop:16}}><Bot/><div><strong>AI Eğitim Koçu</strong><span style={{whiteSpace:'pre-wrap'}}>{aiAnswer}</span></div></div>}<div className="alert info" style={{marginTop:16}}>AI Rehber Öğretmeni ve AI Branş Öğretmeni bu teslimin dışında, sonraki faza bırakıldı.</div></div>}
 {tab==='live'&&<><div className="summary-strip"><S label="Kredi" value={live?.wallet?.balance||0}/><S label="Yaklaşan" value={(live?.sessions||[]).filter((s:any)=>['RESERVED','CONFIRMED'].includes(s.status)).length}/></div><div className="panel" style={{marginBottom:16}}><h2>Görüşme rezervasyonu</h2><div className="form-grid"><label>Tür<select value={session.sessionType} onChange={e=>setSession({...session,sessionType:e.target.value})}><option value="GUIDANCE">Canlı Rehberlik</option><option value="COACH">Canlı Eğitim Koçu</option><option value="LESSON">Canlı Ders</option></select></label><label>Uzman<select value={session.providerId} onChange={e=>setSession({...session,providerId:e.target.value})}><option value="">Uygun uzman daha sonra eşleşsin</option>{(live?.providers||[]).filter((p:any)=>p.provider_type===session.sessionType).map((p:any)=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>Tarih / saat<input type="datetime-local" value={session.scheduledAt} onChange={e=>setSession({...session,scheduledAt:e.target.value})}/></label><label>Kredi<input type="number" min="1" value={session.creditCost} onChange={e=>setSession({...session,creditCost:Number(e.target.value)})}/></label></div><button className="primary" onClick={reserve} disabled={!session.scheduledAt}><TicketCheck size={16}/> Rezervasyon Yap</button></div><div className="table-card"><table><thead><tr><th>Tarih</th><th>Tür</th><th>Uzman</th><th>Kredi</th><th>Durum</th></tr></thead><tbody>{(live?.sessions||[]).map((s:any)=><tr key={s.id}><td>{s.scheduled_at}</td><td>{s.session_type}</td><td>{s.provider_name||'Eşleşecek'}</td><td>{s.credit_cost}</td><td><span className="status neutral">{s.status}</span></td></tr>)}</tbody></table></div><div className="alert warning" style={{marginTop:16}}>Gerçek video görüşme sağlayıcısı seçilmedi. Rezervasyon/kredi altyapısı hazır; meeting linki ancak güvenli sağlayıcı bağlandıktan sonra üretilecek.</div></>}
 {tab==='games'&&<><div className="summary-strip"><S label="XP" value={games?.profile?.xp||0}/><S label="Seviye" value={games?.profile?.level||1}/><S label="Seri" value={games?.profile?.streak_days||0}/></div><div className="exam-grid">{(games?.games||[]).map((g:any)=><div className="exam-card" key={g.code}><Gamepad2 size={28}/><h3>{g.title}</h3><p>Gerçek soru ve süre akışıyla çalışan mini oyunu Oyunlarım sayfasında aç.</p><a className="secondary full" href="/student-games">Oyuna git</a></div>)}</div></>}
 </>;
}
function S({label,value}:{label:string;value:any}){return <div className="summary"><span>{label}</span><strong>{value}</strong></div>}
