import { useCallback,useEffect,useState } from 'react';
import { ArrowLeft,ArrowRight,BookOpenCheck,Building2,CheckCircle2,ChevronRight,Download,FileUp,Landmark,LineChart,LockKeyhole,MessageCircle,PlayCircle,ScanLine,ShieldCheck,Sparkles,UserRound } from 'lucide-react';
import { api,ApiError } from '../api';
import { AnunexBrand } from '../components/AnunexBrand';
import { NibiruMark } from '../components/NibiruMark';
import { Turnstile } from '../components/Turnstile';
import './result-portal.css';
import './result-portal-premium.css';

type Role='STUDENT'|'INSTITUTION'|'DEALER';
const roleCards=[{key:'STUDENT' as const,title:'Öğrenci Sonuç',text:'Tüm sınavların, kazanım analizin ve sana özel kısa çalışma ipuçların.',icon:UserRound},{key:'INSTITUTION' as const,title:'Kurum Sonuç',text:'Kendi sınavlarını değerlendir, raporla ve geçmiş sonuçlarını takip et.',icon:Building2},{key:'DEALER' as const,title:'Bayi Sonuç',text:'Yalnız yetkili olduğunuz kurumlarda yükleme, değerlendirme ve raporlama.',icon:Landmark}];

export function ResultPortal(){
 const[operator,setOperator]=useState<any>(null),[operatorForm,setOperatorForm]=useState({identifier:'',password:''}),[config,setConfig]=useState<any>(null),[role,setRole]=useState<Role|null>(null),[step,setStep]=useState<'LOOKUP'|'VERIFY'|'RESULTS'>('LOOKUP'),[institutions,setInstitutions]=useState<any[]>([]),[institution,setInstitution]=useState<any>(null),[query,setQuery]=useState(''),[form,setForm]=useState({gradeLevel:'',fullName:'',lookupType:'STUDENT_NUMBER',lookupValue:''}),[token,setToken]=useState(''),[challenge,setChallenge]=useState(''),[accessCode,setAccessCode]=useState(''),[result,setResult]=useState<any>(null),[detail,setDetail]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const[opsExams,setOpsExams]=useState<any[]>([]),[opsTemplates,setOpsTemplates]=useState<any[]>([]),[opsInstitutions,setOpsInstitutions]=useState<any[]>([]),[opsQuery,setOpsQuery]=useState(''),[opsInstitution,setOpsInstitution]=useState<any>(null),[opsExamId,setOpsExamId]=useState(''),[opsTemplateId,setOpsTemplateId]=useState(''),[opsFile,setOpsFile]=useState<File|null>(null),[opsBatch,setOpsBatch]=useState<any>(null),[opsEvaluation,setOpsEvaluation]=useState<any>(null),[opsNotice,setOpsNotice]=useState('');
 useEffect(()=>{void api('/api/public/results/config').then(setConfig).catch(()=>setConfig({turnstileSiteKey:''}))},[]);
 useEffect(()=>{const handle=setTimeout(()=>{if(query.trim().length<2){setInstitutions([]);return}void api<any>(`/api/public/results/institutions?q=${encodeURIComponent(query)}`).then(r=>setInstitutions(r.institutions||[])).catch(()=>setInstitutions([]))},250);return()=>clearTimeout(handle)},[query]);
 useEffect(()=>{if(role!=='DEALER'||!operator||opsQuery.trim().length<2){setOpsInstitutions([]);return}const handle=setTimeout(()=>{void api<any>(`/api/result-operator/institutions?q=${encodeURIComponent(opsQuery)}`).then(r=>setOpsInstitutions(r.institutions||[])).catch(()=>setOpsInstitutions([]))},220);return()=>clearTimeout(handle)},[role,operator,opsQuery]);
 const onToken=useCallback((value:string)=>setToken(value),[]);
 const lookup=async(e:React.FormEvent)=>{e.preventDefault();if(!institution)return;setBusy(true);setError('');try{const r=await api<any>('/api/public/results/lookup',{method:'POST',body:JSON.stringify({...form,institutionCode:institution.code,turnstileToken:token})});if(!r.found){setError(r.message||'Bilgiler eşleşmedi.');return}setChallenge(r.challengeId);setStep('VERIFY')}catch(e){setError(e instanceof ApiError?e.message:'Arama yapılamadı.')}finally{setBusy(false)}};
 const verify=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/public/results/verify',{method:'POST',body:JSON.stringify({challengeId:challenge,accessCode})});const r=await api('/api/public/results/student');setResult(r);setStep('RESULTS')}catch(e){setError(e instanceof ApiError?e.message:'Doğrulama yapılamadı.')}finally{setBusy(false)}};
 const loadOperations=async(currentRole:Role)=>{if(currentRole==='INSTITUTION'){const[e,t]=await Promise.all([api<any>('/api/result-institution/exams'),api<any>('/api/result-institution/optical-templates')]);setOpsExams(e.exams||[]);setOpsTemplates(t.templates||[]);if(e.exams?.[0])setOpsExamId(e.exams[0].id);if(t.templates?.[0])setOpsTemplateId(t.templates[0].id)}else if(currentRole==='DEALER'){const[e,t]=await Promise.all([api<any>('/api/result-operator/exams'),api<any>('/api/result-operator/optical-templates')]);setOpsExams(e.exams||[]);setOpsTemplates(t.templates||[]);if(e.exams?.[0])setOpsExamId(e.exams[0].exam_id||e.exams[0].id);if(t.templates?.[0])setOpsTemplateId(t.templates[0].id)}};
 const operatorLogin=async(e:React.FormEvent)=>{e.preventDefault();if(!role||role==='STUDENT')return;setBusy(true);setError('');try{if(role==='INSTITUTION'){await api('/api/result-institution/login',{method:'POST',body:JSON.stringify(operatorForm)});const current=await api<any>('/api/result-institution/me');setOperator({...current.account,name:current.account?.name});await loadOperations('INSTITUTION')}else{await api('/api/result-operator/login',{method:'POST',body:JSON.stringify(operatorForm)});const current=await api<any>('/api/result-operator/me');setOperator({...current.operator,name:current.operator?.displayName});await loadOperations('DEALER')}}catch(e){setError(e instanceof ApiError?e.message:e instanceof Error?e.message:'Yetkili giriş yapılamadı.')}finally{setBusy(false)}};
 const previewOperation=async()=>{if(!role||role==='STUDENT'||!opsExamId||!opsFile)return;setBusy(true);setError('');setOpsNotice('');setOpsBatch(null);setOpsEvaluation(null);try{if(role==='DEALER'&&!opsInstitution)throw new Error('Önce yetkili kurumunuzu seçin.');const fd=new FormData();fd.set('file',opsFile);if(opsTemplateId)fd.set('templateVersionId',opsTemplateId);const base=role==='INSTITUTION'?`/api/result-institution/exams/${encodeURIComponent(opsExamId)}/preview-file`:`/api/result-operator/exams/${encodeURIComponent(opsExamId)}/preview-file?mebCode=${encodeURIComponent(opsInstitution.code)}`;const r=await api<any>(base,{method:'POST',body:fd});setOpsBatch(r);setOpsNotice(r.status==='READY'?`${r.total} kayıt okundu. Değerlendirmeye hazır.`:'Dosya okundu; sorunlu kayıtları düzeltmeden değerlendirme başlatılamaz.')}catch(e){setError(e instanceof ApiError?e.message:e instanceof Error?e.message:'Dosya önizlenemedi.')}finally{setBusy(false)}};
 const evaluateOperation=async()=>{if(!role||role==='STUDENT'||!opsBatch?.batchId)return;setBusy(true);setError('');try{const base=role==='INSTITUTION'?`/api/result-institution/scan-batches/${encodeURIComponent(opsBatch.batchId)}/evaluate`:`/api/result-operator/scan-batches/${encodeURIComponent(opsBatch.batchId)}/evaluate`;const r=await api<any>(base,{method:'POST'});setOpsEvaluation(r);setOpsNotice(`${r.processed??opsBatch.total??0} öğrenci kaydı değerlendirildi. Raporlar kurum sonuç arşivine işlendi.`)}catch(e){setError(e instanceof ApiError?e.message:'Değerlendirme tamamlanamadı.')}finally{setBusy(false)}};
 const openExam=async(id:string)=>{setBusy(true);setError('');try{setDetail(await api(`/api/public/results/exams/${encodeURIComponent(id)}`))}catch(e){setError(e instanceof ApiError?e.message:'Sınav ayrıntısı açılamadı.')}finally{setBusy(false)}};
 const reset=()=>{setRole(null);setStep('LOOKUP');setChallenge('');setAccessCode('');setResult(null);setDetail(null);setOperator(null);setOperatorForm({identifier:'',password:''});setOpsExams([]);setOpsTemplates([]);setOpsInstitutions([]);setOpsQuery('');setOpsInstitution(null);setOpsExamId('');setOpsTemplateId('');setOpsFile(null);setOpsBatch(null);setOpsEvaluation(null);setOpsNotice('');setError('')};
 const copy=config?.copy||{};
 return <main className="result-portal"><header className="result-nav"><a className="result-brand" href="https://anunex.com" aria-label="ANUNEX ana sayfa"><AnunexBrand tagline/></a><nav><a href="https://anunex.com/#platform">Platformu keşfet</a><a className="result-admin-link" href="#result-access">Sonuç Ağını Yönet</a><a className="result-login-link" href="https://app.anunex.com/login">Lisanslı ANUNEX <ChevronRight size={16}/></a></nav></header>
  <section className="result-hero"><div className="result-hero-copy"><span className="result-kicker">{copy.badge||'ANUNEX DOĞRULANMIŞ SONUÇ AĞI'}</span><h1>{copy.title_line||'Sonuç yalnızca bir sayı değil.'}<br/><em>{copy.title_emphasis||'Bir sonraki akademik rota.'}</em></h1><p>{copy.subtitle||'Kurumunuz ANUNEX lisansı kullanmasa da yayınlanmış sınav sonuçlarınıza güvenle ulaşın.'}</p><div className="result-proof"><span><ShieldCheck/> İkinci doğrulama</span><span><CheckCircle2/> Doğrulanmış sonuç</span><span><LockKeyhole/> TCKN açık saklanmaz</span></div></div><div className="result-orbit result-planet-hero" aria-label="Nibiru — öğrenmenin yaşayan zekâsı"><NibiruMark size={290} state="thinking" interactive showWordmark/></div></section>
  {!role&&<section className="result-role-grid">{roleCards.map(card=><button key={card.key} onClick={()=>setRole(card.key)}><span><card.icon/></span><div><h2>{card.title}</h2><p>{card.text}</p></div><ChevronRight/></button>)}</section>}
  {role&&role!=='STUDENT'&&<section className="result-workspace result-operator" id="result-access"><button className="result-back" onClick={reset}><ArrowLeft/> Sonuç türleri</button>{error&&<div className="result-alert">{error}</div>}{opsNotice&&<div className="result-alert" style={{borderColor:'rgba(74,222,128,.35)'}}>{opsNotice}</div>}
   {!operator?<form className="result-operator-login" onSubmit={operatorLogin}><div className="operator-intro"><span className="result-kicker">BAĞIMSIZ YETKİLİ ERİŞİM</span><h2>{role==='INSTITUTION'?'Kurum Sonuç Merkezi':'Bayi Operasyon Merkezi'}</h2><p>{role==='INSTITUTION'?'Süper Admin tarafından verilen kurum kullanıcı adı ve şifresiyle yalnız kendi kurumunuzun sınavlarını değerlendirin ve takip edin.':'Bayi hesabınız yalnız Süper Admin tarafından tanımlanan il/ilçe sınırlarında çalışır.'}</p></div><label>Kullanıcı adı<input required autoComplete="username" value={operatorForm.identifier} onChange={e=>setOperatorForm({...operatorForm,identifier:e.target.value})}/></label><label>Şifre<input required type="password" autoComplete="current-password" value={operatorForm.password} onChange={e=>setOperatorForm({...operatorForm,password:e.target.value})}/></label><button className="result-primary" disabled={busy}>{busy?'Yetki doğrulanıyor…':'Sonuç merkezine güvenli giriş'}</button><small>Bu hesap yalnız sonuc.anunex.com içindir.</small></form>:
   <div className="result-operator-dashboard"><div className="operator-welcome"><span className="result-kicker">SONUÇ OPERASYON MERKEZİ</span><h2>Hoş geldiniz, {operator.name||operator.identifier||'yetkili kullanıcı'}.</h2><p>{role==='INSTITUTION'?`${operator.mebCode||''} · ${operator.city||''} ${operator.district?`/ ${operator.district}`:''}`:`Yetki alanınız: ${(operator.scopes||[]).map((x:any)=>`${x.city}${x.district?` / ${x.district}`:''}`).join(', ')||'tanımlı bölge'}`}</p></div>
    <div className="grid-2"><label>Sınav<select value={opsExamId} onChange={e=>{setOpsExamId(e.target.value);setOpsBatch(null);setOpsEvaluation(null)}}><option value="">Sınav seçin</option>{opsExams.map((x:any)=><option key={x.exam_id||x.id} value={x.exam_id||x.id}>{x.academic_year} · {x.publisher_name?`${x.publisher_name} · `:''}{x.title}</option>)}</select></label><label>Optik format<select value={opsTemplateId} onChange={e=>setOpsTemplateId(e.target.value)}><option value="">Otomatik algıla</option>{opsTemplates.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>
    {role==='INSTITUTION'?<div className="operator-notice"><Building2/><p><strong>{operator.name}</strong><br/>Kurum sabittir; başka bir kurum seçilemez. Değerlendirme yalnız {operator.mebCode} MEB koduna işlenir.</p></div>:<label>Kurum<input value={opsQuery} onChange={e=>{setOpsQuery(e.target.value);setOpsInstitution(null)}} placeholder="Yetki alanındaki kurum adı veya MEB kodu"/>{!!opsInstitutions.length&&!opsInstitution&&<div className="institution-options">{opsInstitutions.map((x:any)=><button type="button" key={x.code} onClick={()=>{setOpsInstitution(x);setOpsQuery(`${x.name} · ${x.code}`);setOpsInstitutions([])}}><strong>{x.name}</strong><span>{x.city} · {x.district} · {x.code}</span></button>)}</div>}</label>}
    <label>Optik sonuç dosyası<input type="file" accept=".dat,.txt,.csv,text/plain,text/csv" onChange={e=>{setOpsFile(e.target.files?.[0]||null);setOpsBatch(null);setOpsEvaluation(null)}}/></label><button className="result-primary" disabled={busy||!opsExamId||!opsFile||(role==='DEALER'&&!opsInstitution)} onClick={()=>void previewOperation()}><FileUp/> {busy?'Dosya işleniyor…':'Dosyayı oku ve kontrol et'}</button>
    {opsBatch&&<div className="operator-notice"><ScanLine/><p><strong>{opsBatch.detection?.templateName||'Optik format'} · {opsBatch.total} kayıt</strong><br/>Aktif: {opsBatch.counts?.active||0} · Misafir: {(opsBatch.counts?.guest||0)+(opsBatch.counts?.newGuest||0)} · Belirsiz: {opsBatch.counts?.ambiguous||0} · Hatalı: {opsBatch.counts?.invalid||0}</p></div>}
    {opsBatch?.status==='READY'&&!opsEvaluation&&<button className="result-primary" disabled={busy} onClick={()=>void evaluateOperation()}><CheckCircle2/> Değerlendirmeyi başlat</button>}
    {opsEvaluation&&<div className="operator-notice"><ShieldCheck/><p><strong>Değerlendirme tamamlandı.</strong><br/>Aynı ANUNEX puanlama motoru kullanıldı; sonuçlar yalnız yetkili kurum kapsamına işlendi.</p></div>}
   </div>}
  </section>}
  {role==='STUDENT'&&<section className="result-workspace"><button className="result-back" onClick={reset}><ArrowLeft/> Sonuç türleri</button>
   {error&&<div className="result-alert">{error}</div>}
   {step==='LOOKUP'&&<form className="result-form" onSubmit={lookup}><div><span className="result-kicker">1 · SONUCUNU BUL</span><h2>Kurum ve öğrenci bilgilerin</h2><p>Bu bilgiler yalnız eşleşme içindir. T.C. kimlik numarası sonuç veritabanında açık olarak tutulmaz.</p></div><label>Kurum<input value={query} onChange={e=>{setQuery(e.target.value);setInstitution(null)}} placeholder="Kurum adı veya MEB kurum kodu" required/>{!!institutions.length&&!institution&&<div className="institution-options">{institutions.map(x=><button type="button" key={x.code} onClick={()=>{setInstitution(x);setQuery(`${x.name} · ${x.code}`);setInstitutions([])}}><strong>{x.name}</strong><span>{x.city} · {x.district} · {x.code}</span></button>)}</div>}</label><div className="result-two"><label>Sınıf düzeyi<select value={form.gradeLevel} onChange={e=>setForm({...form,gradeLevel:e.target.value})} required><option value="">Seçin</option>{Array.from({length:8},(_,i)=>i+5).map(x=><option key={x}>{x}</option>)}</select></label><label>Arama yöntemi<select value={form.lookupType} onChange={e=>setForm({...form,lookupType:e.target.value})}><option value="STUDENT_NUMBER">Öğrenci numarası</option><option value="TCKN">T.C. kimlik numarası</option></select></label></div><label>Ad soyad<input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} autoComplete="name" required/></label><label>{form.lookupType==='TCKN'?'T.C. kimlik numarası':'Öğrenci numarası'}<input value={form.lookupValue} onChange={e=>setForm({...form,lookupValue:e.target.value.replace(/\s/g,'')})} inputMode={form.lookupType==='TCKN'?'numeric':'text'} required/></label><Turnstile siteKey={config?.turnstileSiteKey||''} onToken={onToken}/><button className="result-primary" disabled={busy||!institution}>{busy?'Aranıyor…':'Sonucumu bul'}</button></form>}
   {step==='VERIFY'&&<form className="result-form verify" onSubmit={verify}><LockKeyhole/><span className="result-kicker">2 · KİŞİSEL DOĞRULAMA</span><h2>Sonuç erişim kodunu gir</h2><p>Kurumunuzun verdiği sınav kartındaki 6 haneli kodu kullanın. Öğrenci numarası veya TCKN tek başına sonucu açmaz.</p><label>Kişisel erişim kodu<input value={accessCode} onChange={e=>setAccessCode(e.target.value.replace(/\s/g,'').slice(0,12))} inputMode="numeric" autoComplete="one-time-code" maxLength={12} autoFocus required/></label><button className="result-primary" disabled={busy}>{busy?'Doğrulanıyor…':'Sonuçlarıma güvenli giriş'}</button></form>}
   {step==='RESULTS'&&result&&<div className="result-dashboard"><div className="result-student-head"><div><span className="result-kicker">ÖĞRENCİ SONUÇ MERKEZİ</span><h2>{result.student.name}</h2><p>{result.student.institution} · {result.student.gradeLevel}. sınıf</p></div><button onClick={()=>window.print()}><Download/> Sonuç karnesi</button></div><div className="result-tip"><Sparkles/><div><strong>Nibiru’dan kısa rota</strong>{(result.tips||[]).slice(0,3).map((x:string)=><p key={x}>{x}</p>)}</div></div><div className="result-exams"><h3>Sınav geçmişim <span>{result.exams.length}</span></h3>{result.exams.map((x:any)=><button key={x.exam_id} onClick={()=>void openExam(x.exam_id)}><div><strong>{x.title}</strong><span>{x.academic_year} · {x.exam_type} · {x.exam_date||'Tarih yok'}</span></div><div className="exam-metrics"><b>{Number(x.net).toLocaleString('tr-TR')} net</b><span>{x.score==null?'—':Number(x.score).toLocaleString('tr-TR')} puan</span><small>{x.general_rank?`${x.participant_count||'—'} kişi içinde ${x.general_rank}.`:''}</small></div><ChevronRight/></button>)}</div>{detail&&<div className="result-detail"><div className="detail-head"><h3>Sınav analizi</h3><button onClick={()=>setDetail(null)}>Kapat</button></div><div className="subject-grid">{detail.subjects.map((x:any)=><article key={x.subject}><strong>{x.subject}</strong><b>{Number(x.net).toLocaleString('tr-TR')} net</b><span>{x.correct_count} doğru · {x.wrong_count} yanlış · {x.blank_count} boş</span></article>)}</div><h3>Kazanım rotası</h3>{detail.outcomes.slice(0,12).map((x:any)=><div className="outcome-row" key={x.outcome}><div><strong>{x.outcome}</strong><span>{x.topic||''}</span></div><b>%{Math.round(Number(x.success_rate||0))}</b></div>)}{!!detail.videos.length&&<><h3>Tanımlı video çözümleri</h3><div className="video-grid">{detail.videos.map((x:any)=><a key={`${x.url}-${x.question_no}`} href={x.url} target="_blank" rel="noreferrer"><PlayCircle/><span><strong>{x.title||`${x.question_no}. soru çözümü`}</strong><small>Onaylı video</small></span></a>)}</div></>}</div>}</div>}
  </section>}
  {!role&&<section className="result-license-story"><div><span className="result-kicker">SONUÇTAN GELİŞİM SİSTEMİNE</span><h2>{copy.license_title||'Sonucu görmek başlangıç. Gelişimi yönetmek ANUNEX.'}</h2><p>{copy.license_text||'Optik okumadan kazanım analizine, yoklamadan kişisel öğrenme rotasına kadar kurumunuzun akademik operasyonunu tek sistemde birleştirin.'}</p><a href={copy.cta_url||'https://demo.anunex.com'}>{copy.cta_label||'Kurum demosunu inceleyin'} <ArrowRight/></a></div><div className="result-license-grid"><article><ScanLine/><strong>Optik + kamera</strong><span>Okut, değerlendir, aynı anda raporla.</span></article><article><LineChart/><strong>Kazanım zekâsı</strong><span>Sınıftan Türkiye geneline gerçek kıyas.</span></article><article><BookOpenCheck/><strong>Kişisel öğrenme</strong><span>Yanlıştan ödeve, videoya ve kitaba.</span></article><article><MessageCircle/><strong>WhatsApp + Nibiru</strong><span>Doğru kişiye, doğru anda güvenli destek.</span></article></div></section>}
  <footer><AnunexBrand compact tagline/><span>Sonuç erişiminde ikinci doğrulama · Kişisel veri minimizasyonu · Süreli saklama</span><span>© 2026 ANUNEX</span></footer>
 </main>
}
