import { useEffect,useState } from 'react';
import { Building2,ExternalLink,FileUp,Globe2,RefreshCw,Save,Send,Settings2 } from 'lucide-react';
import { api } from '../api';

function parseDirectory(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),delimiter=lines[0]?.includes(';')?';':',';return lines.slice(1).map(line=>{const [mebCode,name,city,district,institutionType,ownership,educationLevel,officialUrl]=line.split(delimiter).map(x=>x.trim().replace(/^"|"$/g,''));return{mebCode,name,city,district,institutionType,ownership:String(ownership||'').toUpperCase(),educationLevel,officialUrl}})}
const emptyCopy={badge:'',title_line:'',title_emphasis:'',subtitle:'',license_title:'',license_text:'',cta_label:'',cta_url:'',support_phone:''};

export function ResultNetworkAdmin(){
 const[exams,setExams]=useState<any[]>([]),[data,setData]=useState<any>({administrations:[],directoryCount:0}),[governance,setGovernance]=useState<any>({institutions:[],dealers:[],events:[]}),[copy,setCopy]=useState<any>(emptyCopy),[examId,setExamId]=useState(''),[sourceUrl,setSourceUrl]=useState('https://www.meb.gov.tr/baglantilar/okullar/index.php'),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{const[e,a,p,g]=await Promise.all([api<any>('/api/exam-definitions'),api<any>('/api/admin/result-network/administrations'),api<any>('/api/admin/result-network/portal-settings'),api<any>('/api/admin/result-network/governance')]);setExams(e.exams||[]);setData(a);setGovernance(g);setCopy(p.copy||emptyCopy);if(!examId&&e.exams?.[0])setExamId(e.exams[0].id)};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const importRows=async()=>{setBusy(true);setError('');try{let total=0;for(let i=0;i<rows.length;i+=5000){const r=await api<any>('/api/admin/institution-directory/import',{method:'POST',body:JSON.stringify({sourceType:'MEB_OFFICIAL_EXPORT',sourceUrl,rows:rows.slice(i,i+5000)})});total+=r.rowsUpserted}setNotice(`${total.toLocaleString('tr-TR')} kurum referans dizinine işlendi.`);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const create=async()=>{setBusy(true);setError('');try{await api('/api/admin/result-network/administrations',{method:'POST',body:JSON.stringify({examId})});setNotice('Sınav sonuç ağına taslak olarak eklendi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const publish=async(id:string)=>{if(!window.confirm('Bu sınav sonuç ağında yayınlansın mı? Saklama süresi bu anda başlayacak.'))return;setBusy(true);try{await api(`/api/admin/result-network/administrations/${id}/publish`,{method:'POST'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const savePortal=async()=>{setBusy(true);setError('');try{const r=await api<any>('/api/admin/result-network/portal-settings',{method:'PATCH',body:JSON.stringify(copy)});setCopy(r.copy);setNotice('sonuc.anunex.com marka ve iletişim içeriği yayınlandı.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const field=(key:string,label:string,wide=false)=><label className={wide?'portal-copy-wide':''}>{label}{key.endsWith('_text')||key==='subtitle'?<textarea rows={3} value={copy[key]||''} onChange={e=>setCopy({...copy,[key]:e.target.value})}/>:<input value={copy[key]||''} onChange={e=>setCopy({...copy,[key]:e.target.value})}/>}</label>;
 return <><div className="page-head"><div><span className="eyebrow">Lisanssız ölçme değerlendirme</span><h1>Sonuç Ağı Yönetimi</h1><p>Sınav yayınlarını, resmî kurum dizinini ve sonuc.anunex.com marka deneyimini tek merkezden yönetin.</p></div><Globe2/></div>
 {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="kpi-grid"><div className="kpi-card"><span>MEB referans kurumu</span><strong>{Number(data.directoryCount||0).toLocaleString('tr-TR')}</strong></div><div className="kpi-card"><span>Sonuç ağı sınavı</span><strong>{(data.administrations||[]).length}</strong></div><div className="kpi-card"><span>Canlı portal</span><strong>Aktif</strong><a href="https://sonuc.anunex.com" target="_blank" rel="noreferrer">Görüntüle <ExternalLink size={14}/></a></div></div>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Kurum ve bayi yetki merkezi</h2><p>Süper admin kurum açar, pasife alır, dondurur veya arşivler. Onaylı bayiler yalnız tanımlı kapsamlarında işlem yapar.</p></div><Building2/></div><div className="kpi-grid"><div className="kpi-card"><span>Tenant kurum</span><strong>{(governance.institutions||[]).length}</strong></div><div className="kpi-card"><span>Onaylı bayi</span><strong>{(governance.dealers||[]).filter((x:any)=>x.status==='APPROVED').length}</strong></div></div><div className="cards-list">{(governance.institutions||[]).slice(0,12).map((x:any)=><div className="list-card" key={x.id}><div><strong>{x.name}</strong><span>{x.code} · {x.city}/{x.district}</span><small>Durum: {x.lifecycle_status}</small></div><div style={{display:'flex',gap:8}}>{['ACTIVE','PASSIVE','FROZEN','ARCHIVED'].map((s)=>s!==x.lifecycle_status&&<button className="ghost" key={s} disabled={busy} onClick={()=>void api('/api/admin/result-network/institutions/'+x.id+'/status',{method:'POST',body:JSON.stringify({status:s})}).then(()=>load()).catch((e:any)=>setError(e.message))}>{s==='ACTIVE'?'Etkinleştir':s==='PASSIVE'?'Pasife al':s==='FROZEN'?'Dondur':'Arşivle'}</button>)}</div></div>)}</div>{!(governance.institutions||[]).length&&<div className="empty">Henüz lisanslı tenant kurum yok; MEB dizini referans kayıtları ayrı tutulur.</div>}</section>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>sonuc.anunex.com görünüm ve iletişim yönetimi</h2><p>Portal mesajını ve lisanslı ürüne yönlendiren çağrıyı yönetin. Sabit ANUNEX ve Nibiru logoları marka kilididir; değiştirilemez.</p></div><Settings2/></div><div className="grid-2">{field('badge','Üst marka mesajı')}{field('support_phone','Destek telefonu')}{field('title_line','Ana başlık')}{field('title_emphasis','Vurgulu başlık')}{field('subtitle','Açıklama',true)}{field('license_title','Lisans çağrısı başlığı')}{field('license_text','Lisans çağrısı açıklaması',true)}{field('cta_label','Buton metni')}{field('cta_url','Buton bağlantısı')}</div><div style={{display:'flex',gap:10,marginTop:16}}><button className="primary" disabled={busy} onClick={()=>void savePortal()}><Save/> Canlı portalı güncelle</button><a className="ghost" href="https://sonuc.anunex.com" target="_blank" rel="noreferrer"><ExternalLink/> Önizlemeyi aç</a></div></section>
 <div className="grid-2" style={{marginTop:18}}><section className="panel"><div className="panel-head"><div><h2>MEB kurum referans dizini</h2><p>Resmî CSV dışa aktarımını içeri alın. Bu kayıtlar lisans veya aktif tenant oluşturmaz.</p></div><Building2/></div><label>Resmî kaynak URL<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></label><label>CSV dosyası<input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void file.text().then(x=>setRows(parseDirectory(x)))}}/></label><p className="muted">Sütunlar: MEB kodu, kurum adı, il, ilçe, tür, PUBLIC/PRIVATE, kademe, resmî URL.</p><button className="primary" disabled={busy||!rows.length||!sourceUrl.startsWith('https://')} onClick={()=>void importRows()}><FileUp/> {rows.length?`${rows.length.toLocaleString('tr-TR')} kurumu aktar`:'CSV seçin'}</button></section>
 <section className="panel"><div className="panel-head"><div><h2>Tanımlı sınavı sonuç ağına aç</h2><p>Sınav tanımı, cevap anahtarı, kazanımlar ve videolar kalıcı katalogda kalır.</p></div><Send/></div><label>Sınav<select value={examId} onChange={e=>setExamId(e.target.value)}>{exams.map(x=><option key={x.id} value={x.id}>{x.academic_year} · {x.title}</option>)}</select></label><button className="primary" disabled={busy||!examId} onClick={()=>void create()}>Taslak sonuç ağı oluştur</button></section></div>
 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Yıl → sınav arşivi ve yayınlar</h2><p>Her yeni uygulama ayrı katılımcı kümesi ve ayrı silinme tarihi taşır.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw/> Yenile</button></div><div className="cards-list">{(data.administrations||[]).map((x:any)=><div className="list-card" key={x.id}><div><strong>{x.academic_year} · {x.publisher_name?`${x.publisher_name} · `:''}{x.title}</strong><span>{x.exam_type} · {x.linked_institutions} kurum · {x.access_count} öğrenci erişimi</span><small>Durum: {x.status}{x.retention_due_at?` · Kişisel veri silinme: ${new Date(x.retention_due_at).toLocaleDateString('tr-TR')}`:''}</small></div>{x.status==='DRAFT'&&<button className="primary" disabled={busy} onClick={()=>void publish(x.id)}>Yayınla</button>}</div>)}{!data.administrations?.length&&<div className="empty">Henüz sonuç ağına açılmış sınav yok.</div>}</div></section></>;
}
