import { useEffect,useState } from 'react';
import { Building2,ExternalLink,FileUp,Globe2,KeyRound,MapPin,Pencil,Plus,RefreshCw,Save,Settings2,Store } from 'lucide-react';
import { api } from '../api';

function parseDirectory(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),delimiter=lines[0]?.includes(';')?';':',';return lines.slice(1).map(line=>{const [mebCode,name,city,district,institutionType,ownership,educationLevel,officialUrl]=line.split(delimiter).map(x=>x.trim().replace(/^"|"$/g,''));return{mebCode,name,city,district,institutionType,ownership:String(ownership||'').toUpperCase(),educationLevel,officialUrl}})}
const emptyCopy={badge:'',title_line:'',title_emphasis:'',subtitle:'',license_title:'',license_text:'',cta_label:'',cta_url:'',support_phone:''};
const emptyInstitution={mebCode:'',name:'',city:'',district:'',institutionType:'',ownership:'PUBLIC',educationLevel:'',officialUrl:'',status:'ACTIVE'};
const anatolianDistricts=['ADALAR','ATAŞEHİR','BEYKOZ','ÇEKMEKÖY','KADIKÖY','KARTAL','MALTEPE','PENDİK','SANCAKTEPE','SULTANBEYLİ','ŞİLE','TUZLA','ÜMRANİYE','ÜSKÜDAR'];

export function ResultNetworkAdmin(){
 const[exams,setExams]=useState<any[]>([]),[data,setData]=useState<any>({administrations:[],directoryCount:0}),[copy,setCopy]=useState<any>(emptyCopy),[sourceUrl,setSourceUrl]=useState('https://www.meb.gov.tr/baglantilar/okullar/index.php'),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[directoryQuery,setDirectoryQuery]=useState(''),[directory,setDirectory]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[institutionForm,setInstitutionForm]=useState<any>(emptyInstitution),[newMode,setNewMode]=useState(false);
 const[accountForm,setAccountForm]=useState({identifier:'',password:'',canEvaluate:true}),[operators,setOperators]=useState<any[]>([]),[dealerForm,setDealerForm]=useState({displayName:'',identifier:'',password:'',city:'İSTANBUL',districts:'PENDİK'});
 const load=async()=>{const[e,a,p,o]=await Promise.all([api<any>('/api/exam-definitions'),api<any>('/api/admin/result-network/administrations'),api<any>('/api/admin/result-network/portal-settings'),api<any>('/api/admin/result-operators')]);setExams(e.exams||[]);setData(a);setCopy(p.copy||emptyCopy);setOperators(o.operators||[])};
 const searchDirectory=async(q=directoryQuery)=>{const r=await api<any>(`/api/admin/result-institutions?q=${encodeURIComponent(q)}&limit=100`);setDirectory(r.institutions||[])};
 useEffect(()=>{void Promise.all([load(),searchDirectory('')]).catch(e=>setError(e.message))},[]);
 const importRows=async()=>{setBusy(true);setError('');try{let total=0;for(let i=0;i<rows.length;i+=5000){const r=await api<any>('/api/admin/institution-directory/import',{method:'POST',body:JSON.stringify({sourceType:'MEB_OFFICIAL_EXPORT',sourceUrl,rows:rows.slice(i,i+5000)})});total+=r.rowsUpserted}setNotice(`${total.toLocaleString('tr-TR')} kurum referans dizinine işlendi.`);await Promise.all([load(),searchDirectory('')])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const publish=async(id:string)=>{if(!window.confirm('Bu sınav sonuç ağında yayınlansın mı? Saklama süresi bu anda başlayacak.'))return;setBusy(true);try{await api(`/api/admin/result-network/administrations/${id}/publish`,{method:'POST'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const savePortal=async()=>{setBusy(true);setError('');try{const r=await api<any>('/api/admin/result-network/portal-settings',{method:'PATCH',body:JSON.stringify(copy)});setCopy(r.copy);setNotice('sonuc.anunex.com marka ve iletişim içeriği yayınlandı.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const field=(key:string,label:string,wide=false)=><label className={wide?'portal-copy-wide':''}>{label}{key.endsWith('_text')||key==='subtitle'?<textarea rows={3} value={copy[key]||''} onChange={e=>setCopy({...copy,[key]:e.target.value})}/>:<input value={copy[key]||''} onChange={e=>setCopy({...copy,[key]:e.target.value})}/>}</label>;
 const chooseInstitution=(x:any)=>{setSelected(x);setNewMode(false);setInstitutionForm({mebCode:x.meb_code,name:x.name,city:x.city,district:x.district,institutionType:x.institution_type||'',ownership:x.ownership||'PUBLIC',educationLevel:x.education_level||'',officialUrl:x.official_url||'',status:x.status||'ACTIVE'});setAccountForm({identifier:x.account_identifier||x.meb_code,password:'',canEvaluate:x.account_id?Boolean(x.can_evaluate):true})};
 const startNew=()=>{setSelected(null);setNewMode(true);setInstitutionForm({...emptyInstitution});setAccountForm({identifier:'',password:'',canEvaluate:true})};
 const saveInstitution=async()=>{setBusy(true);setError('');try{if(newMode){await api('/api/admin/result-institutions',{method:'POST',body:JSON.stringify(institutionForm)});setNotice('Yeni kurum yalnız sonuc.anunex.com referans dizinine eklendi.')}else if(selected){await api(`/api/admin/result-institutions/${encodeURIComponent(selected.meb_code)}`,{method:'PATCH',body:JSON.stringify(institutionForm)});setNotice('Kurum bilgileri güncellendi.')}await searchDirectory(directoryQuery);setNewMode(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const saveAccount=async()=>{const mebCode=selected?.meb_code||institutionForm.mebCode;if(!mebCode)return;setBusy(true);setError('');try{if(selected?.account_id){await api(`/api/admin/result-institution-accounts/${encodeURIComponent(selected.account_id)}`,{method:'PATCH',body:JSON.stringify({identifier:accountForm.identifier,password:accountForm.password||undefined,canEvaluate:accountForm.canEvaluate,status:'ACTIVE'})});setNotice('Kurum giriş bilgileri ve değerlendirme yetkisi güncellendi.')}else{const r=await api<any>('/api/admin/result-institution-accounts',{method:'POST',body:JSON.stringify({mebCode,identifier:accountForm.identifier||mebCode,password:accountForm.password||undefined,canEvaluate:accountForm.canEvaluate})});setNotice(r.oneTimePassword?`Kurum hesabı oluşturuldu. İlk şifre: ${r.oneTimePassword}`:'Kurum hesabı oluşturuldu.')}setAccountForm(x=>({...x,password:''}));await searchDirectory(directoryQuery)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const dealerScopes=()=>{const city=dealerForm.city.trim().toLocaleUpperCase('tr-TR');const districts=dealerForm.districts.split(',').map(x=>x.trim().toLocaleUpperCase('tr-TR')).filter(Boolean);return districts.length?districts.map(district=>({city,district})):[{city,district:null}]};
 const createDealer=async()=>{setBusy(true);setError('');try{const r=await api<any>('/api/admin/result-operators',{method:'POST',body:JSON.stringify({displayName:dealerForm.displayName,identifier:dealerForm.identifier,password:dealerForm.password||undefined,scopes:dealerScopes()})});setNotice(r.oneTimePassword?`Bayi oluşturuldu. İlk şifre: ${r.oneTimePassword}`:'Bayi oluşturuldu.');setDealerForm({displayName:'',identifier:'',password:'',city:'İSTANBUL',districts:'PENDİK'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const setDealerStatus=async(id:string,status:string)=>{setBusy(true);try{await api(`/api/admin/result-operators/${encodeURIComponent(id)}/status`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const useAnatolianPreset=()=>setDealerForm(x=>({...x,city:'İSTANBUL',districts:anatolianDistricts.join(', ')}));
 return <><div className="page-head"><div><span className="eyebrow">ANUNEX Türkiye Sınav Değerlendirme Ağı</span><h1>Sonuç Ağı Yönetimi</h1><p>MEB kurum referanslarını, kurum şifrelerini, bölgesel bayileri ve sonuc.anunex.com yayınlarını tek merkezden yönetin.</p></div><Globe2/></div>
 {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="kpi-grid"><div className="kpi-card"><span>MEB referans kurumu</span><strong>{Number(data.directoryCount||0).toLocaleString('tr-TR')}</strong></div><div className="kpi-card"><span>Merkezi sınav</span><strong>{exams.length}</strong><small>Tanımlandığında Sonuç Ağı’na otomatik düşer</small></div><div className="kpi-card"><span>Bayi / operatör</span><strong>{operators.length}</strong></div><div className="kpi-card"><span>Canlı portal</span><strong>Aktif</strong><a href="https://sonuc.anunex.com" target="_blank" rel="noreferrer">Görüntüle <ExternalLink size={14}/></a></div></div>

 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Kurum dizini ve kurum hesapları</h2><p>Kurum referansları yalnız sonuc.anunex.com içindir. Yeni kurum ekleme, düzenleme ve kurum şifresi verme yalnız Süper Admin yetkisidir.</p></div><Building2/></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><input style={{flex:'1 1 280px'}} value={directoryQuery} onChange={e=>setDirectoryQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void searchDirectory()}} placeholder="Kurum adı veya MEB kurum kodu"/><button className="ghost" onClick={()=>void searchDirectory()}><RefreshCw/> Ara</button><button className="primary" onClick={startNew}><Plus/> Yeni kurum ekle</button></div>
  <div className="grid-2" style={{marginTop:16}}><div className="cards-list" style={{maxHeight:460,overflow:'auto'}}>{directory.map((x:any)=><button type="button" className="list-card" key={x.meb_code} onClick={()=>chooseInstitution(x)} style={{textAlign:'left',width:'100%'}}><div><strong>{x.name}</strong><span>{x.city} · {x.district} · MEB {x.meb_code}</span><small>{x.institution_type||'Tür belirtilmemiş'} · {x.account_id?'Kurum hesabı aktif':'Şifre verilmemiş'}</small></div><Pencil/></button>)}{!directory.length&&<div className="empty">Kurum bulunamadı.</div>}</div>
   <div>{(selected||newMode)?<><div className="grid-2"><label>MEB kurum kodu<input disabled={!newMode} value={institutionForm.mebCode} onChange={e=>setInstitutionForm({...institutionForm,mebCode:e.target.value.replace(/\D/g,'').slice(0,12)})}/></label><label>Kurum adı<input value={institutionForm.name} onChange={e=>setInstitutionForm({...institutionForm,name:e.target.value})}/></label><label>İl<input value={institutionForm.city} onChange={e=>setInstitutionForm({...institutionForm,city:e.target.value})}/></label><label>İlçe<input value={institutionForm.district} onChange={e=>setInstitutionForm({...institutionForm,district:e.target.value})}/></label><label>Kurum türü<input value={institutionForm.institutionType} onChange={e=>setInstitutionForm({...institutionForm,institutionType:e.target.value})}/></label><label>Kademe<input value={institutionForm.educationLevel} onChange={e=>setInstitutionForm({...institutionForm,educationLevel:e.target.value})}/></label><label>Statü<select value={institutionForm.ownership} onChange={e=>setInstitutionForm({...institutionForm,ownership:e.target.value})}><option value="PUBLIC">Resmî</option><option value="PRIVATE">Özel</option></select></label><label>Durum<select value={institutionForm.status} onChange={e=>setInstitutionForm({...institutionForm,status:e.target.value})}><option value="ACTIVE">Aktif</option><option value="CLOSED">Kapalı</option><option value="UNVERIFIED">Doğrulanmamış</option></select></label></div><label>Resmî web adresi<input value={institutionForm.officialUrl} onChange={e=>setInstitutionForm({...institutionForm,officialUrl:e.target.value})}/></label><button className="primary" disabled={busy} onClick={()=>void saveInstitution()}><Save/> {newMode?'Kurumu ekle':'Kurum bilgilerini kaydet'}</button>
    {!newMode&&selected&&<section style={{marginTop:18,paddingTop:16,borderTop:'1px solid rgba(148,163,184,.2)'}}><h3 style={{marginTop:0}}>Kurum sonuç hesabı</h3><p className="muted">Bu kullanıcı adı ve şifre yalnız sonuc.anunex.com üzerinde çalışır.</p><label>Kullanıcı adı<input value={accountForm.identifier} onChange={e=>setAccountForm({...accountForm,identifier:e.target.value})}/></label><label>{selected.account_id?'Yeni şifre (değiştirmeyecekseniz boş bırakın)':'Şifre (boş bırakırsanız sistem üretir)'}<input type="password" value={accountForm.password} onChange={e=>setAccountForm({...accountForm,password:e.target.value})}/></label><label style={{display:'flex',alignItems:'center',gap:10}}><input type="checkbox" checked={accountForm.canEvaluate} onChange={e=>setAccountForm({...accountForm,canEvaluate:e.target.checked})}/> Kurum kendi sınavlarını değerlendirebilsin</label><button className="primary" disabled={busy} onClick={()=>void saveAccount()}><KeyRound/> {selected.account_id?'Hesap / şifreyi güncelle':'Kurum şifresi oluştur'}</button></section>}</>:<div className="empty">Düzenlemek için soldan kurum seçin veya yeni kurum ekleyin.</div>}</div></div>
 </section>

 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Bayi / sonuç operatörü</h2><p>Bayi platform kullanıcısı değildir. Yalnız kendisine verilen il/ilçe kapsamındaki kurumlarda sınav değerlendirebilir.</p></div><Store/></div><div className="grid-2"><div><label>Bayi adı<input value={dealerForm.displayName} onChange={e=>setDealerForm({...dealerForm,displayName:e.target.value})} placeholder="Yıldız Kitabevi"/></label><label>Kullanıcı adı<input value={dealerForm.identifier} onChange={e=>setDealerForm({...dealerForm,identifier:e.target.value})}/></label><label>Şifre (boşsa sistem üretir)<input type="password" value={dealerForm.password} onChange={e=>setDealerForm({...dealerForm,password:e.target.value})}/></label><label>İl<input value={dealerForm.city} onChange={e=>setDealerForm({...dealerForm,city:e.target.value})}/></label><label>İlçeler — virgülle ayırın<input value={dealerForm.districts} onChange={e=>setDealerForm({...dealerForm,districts:e.target.value})} placeholder="PENDİK, KARTAL, TUZLA"/></label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="ghost" type="button" onClick={useAnatolianPreset}><MapPin/> İstanbul Anadolu Yakası</button><button className="primary" disabled={busy||!dealerForm.displayName||!dealerForm.identifier||!dealerForm.city} onClick={()=>void createDealer()}><Plus/> Bayi oluştur</button></div></div><div className="cards-list" style={{maxHeight:430,overflow:'auto'}}>{operators.map((x:any)=><div className="list-card" key={x.id}><div><strong>{x.display_name}</strong><span>{x.identifier}</span><small>{(x.scopes||[]).filter((s:any)=>s.status==='ACTIVE').map((s:any)=>`${s.city}${s.district?` / ${s.district}`:''}`).join(', ')}</small></div><button className="ghost" disabled={busy} onClick={()=>void setDealerStatus(x.id,x.status==='ACTIVE'?'SUSPENDED':'ACTIVE')}>{x.status==='ACTIVE'?'Durdur':'Aktifleştir'}</button></div>)}{!operators.length&&<div className="empty">Henüz bayi tanımlanmadı.</div>}</div></div></section>

 <div className="grid-2" style={{marginTop:18}}><section className="panel"><div className="panel-head"><div><h2>MEB kurum toplu aktarım</h2><p>Otomatik resmî senkronun yanında gerektiğinde MEB Excel/CSV dışa aktarımını topluca içeri alabilirsiniz.</p></div><FileUp/></div><label>Resmî kaynak URL<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></label><label>CSV dosyası<input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void file.text().then(x=>setRows(parseDirectory(x)))}}/></label><p className="muted">Sütunlar: MEB kodu, kurum adı, il, ilçe, tür, PUBLIC/PRIVATE, kademe, resmî URL.</p><button className="primary" disabled={busy||!rows.length||!sourceUrl.startsWith('https://')} onClick={()=>void importRows()}><FileUp/> {rows.length?`${rows.length.toLocaleString('tr-TR')} kurumu aktar`:'CSV seçin'}</button></section>
 <section className="panel"><div className="panel-head"><div><h2>Ortak sınav çekirdeği</h2><p>app.anunex.com’da merkezi sınav oluşturulduğunda sonuç ağı kaydı otomatik açılır. Ayrı sınav tanımlamanız gerekmez.</p></div><RefreshCw/></div><div className="kpi-card"><span>Tanımlı merkezi sınav</span><strong>{exams.length}</strong></div><p className="muted">Optik, cevap anahtarı, kazanım ve puanlama tanımları aynı merkezi katalogdan okunur.</p></section></div>

 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Yıl → sınav arşivi ve yayınlar</h2><p>Her uygulama ayrı katılımcı kümesi ve ayrı saklama tarihi taşır.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw/> Yenile</button></div><div className="cards-list">{(data.administrations||[]).map((x:any)=><div className="list-card" key={x.id}><div><strong>{x.academic_year} · {x.publisher_name?`${x.publisher_name} · `:''}{x.title}</strong><span>{x.exam_type} · {x.linked_institutions} kurum · {x.access_count} öğrenci erişimi</span><small>Durum: {x.status}{x.retention_due_at?` · Kişisel veri silinme: ${new Date(x.retention_due_at).toLocaleDateString('tr-TR')}`:''}</small></div>{x.status==='DRAFT'&&<button className="primary" disabled={busy} onClick={()=>void publish(x.id)}>Yayınla</button>}</div>)}{!data.administrations?.length&&<div className="empty">Henüz sonuç ağına açılmış sınav yok.</div>}</div></section>

 <section className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>sonuc.anunex.com görünüm ve iletişim yönetimi</h2><p>ANUNEX ve Nibiru marka kilidi değişmez; yalnız portal mesajı ve iletişim içeriği yönetilir.</p></div><Settings2/></div><div className="grid-2">{field('badge','Üst marka mesajı')}{field('support_phone','Destek telefonu')}{field('title_line','Ana başlık')}{field('title_emphasis','Vurgulu başlık')}{field('subtitle','Açıklama',true)}{field('license_title','Lisans çağrısı başlığı')}{field('license_text','Lisans çağrısı açıklaması',true)}{field('cta_label','Buton metni')}{field('cta_url','Buton bağlantısı')}</div><div style={{display:'flex',gap:10,marginTop:16}}><button className="primary" disabled={busy} onClick={()=>void savePortal()}><Save/> Canlı portalı güncelle</button><a className="ghost" href="https://sonuc.anunex.com" target="_blank" rel="noreferrer"><ExternalLink/> Önizlemeyi aç</a></div></section>
 </>;
}
