import { useEffect,useState } from 'react';
import { Database,Play,RefreshCw } from 'lucide-react';
import { api } from '../api';

export function ScaleInfrastructure(){
 const[data,setData]=useState<any>(null);const[tests,setTests]=useState<any>(null);const[benchmarks,setBenchmarks]=useState<any>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const load=async()=>{setError('');try{const[h,t,b]=await Promise.all([api<any>('/api/v2/scale/health'),api<any>('/api/admin/capacity-tests'),api<any>('/api/admin/capacity-benchmarks')]);setData(h);setTests(t);setBenchmarks(b)}catch(e:any){setError(e.message)}};
 const startProfile=async(profileKey:'SMALL'|'REGIONAL'|'NATIONAL')=>{const profile=benchmarks?.profiles?.[profileKey];if(!profile||!window.confirm(`${profile.institutions.toLocaleString('tr-TR')} kurum / ${profile.students.toLocaleString('tr-TR')} öğrenci staging benchmark başlatılsın mı?`))return;setBusy(true);setError('');try{await api('/api/admin/capacity-benchmarks',{method:'POST',body:JSON.stringify({profileKey,confirmation:`RUN_${profileKey}_${profile.students}`})});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const labels:Record<string,string>={institutions:'Kurum',students:'Aktif Öğrenci',classes:'Sınıf',exams:'Sınav',participants:'Sınav Katılımcısı',results:'Sonuç',scanRecords:'Optik Kayıt',publishedWorksheets:'Yayınlanmış Föy',bulkJobs:'Toplu İşlem'};
 return <>
  <div className="page-head"><div><span className="eyebrow">Ölçek Altyapısı</span><h1>Platform kapasite görünümü</h1><p>2 kurum / 45 öğrenciden 15.000 kurum / 1.000.000 öğrenciye kadar aynı kuyruk motorunu doğrulayın.</p></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{(['SMALL','REGIONAL','NATIONAL'] as const).map(key=><button key={key} className={key==='NATIONAL'?'primary':'ghost'} disabled={busy||!benchmarks?.queueConfigured||benchmarks?.environment!=='staging'} onClick={()=>void startProfile(key)}><Play size={16}/> {key}</button>)}<button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div></div>
  {error&&<div className="alert error">{error}</div>}
  {!tests?.queueConfigured&&<div className="alert info">SCALE_QUEUE henüz Cloudflare hesabında oluşturulup bağlanmadığı için canlı test başlatılamaz.</div>}
  <div className="kpi-grid">{Object.entries(data?.metrics||{}).map(([k,v])=><div className="kpi-card" key={k}><span>{labels[k]||k}</span><strong>{Number(v).toLocaleString('tr-TR')}</strong></div>)}</div>
  <div className="panel" style={{marginTop:20}}><div className="panel-head"><div><h2>Mimari durumu</h2><p>Mevcut production yaklaşımı ve sonraki büyüme sınırı.</p></div><Database/></div><div className="cards-list">{Object.entries(data?.architecture||{}).map(([k,v])=><div className="list-card" key={k}><div><strong>{k}</strong><span>{String(v)}</span></div></div>)}</div></div>
  <div className="panel"><div className="panel-head"><div><h2>Ölçek uyarıları</h2><p>Hacim eşikleri aşıldığında uzun işlemler queue/workflow katmanına taşınır.</p></div></div>{(data?.warnings||[]).length?(data.warnings||[]).map((w:string)=><div className="alert info" key={w}>{w}</div>):<div className="alert success">Mevcut veri hacmi için kritik ölçek uyarısı bulunmuyor.</div>}</div>
  <div className="panel"><div className="panel-head"><div><h2>100.000 öğrenci test defteri</h2><p>Test verisi gerçek öğrenci tablolarından tamamen ayrıdır ve yalnız staging ortamında üretilir.</p></div></div><div className="cards-list">{(tests?.runs||[]).map((r:any)=><div className="list-card" key={r.id}><div><strong>{Number(r.target_count).toLocaleString('tr-TR')} kayıt · {r.status}</strong><span>{Number(r.processed_count).toLocaleString('tr-TR')} işlendi · {r.completed_chunks}/{r.total_chunks} parça · {r.started_at}</span>{r.last_error&&<span>{r.last_error}</span>}</div></div>)}{!(tests?.runs||[]).length&&<div className="empty">Henüz kaydedilmiş kapasite koşusu yok.</div>}</div></div>
  <div className="panel"><div className="panel-head"><div><h2>Ulusal ölçek kabul profilleri</h2><p>Kompakt cevap nesnesi, 256 sonuç shard'ı ve kurum shard dağılımı sentetik tablolarda ölçülür.</p></div></div><div className="cards-list">{(benchmarks?.runs||[]).map((r:any)=><div className="list-card" key={r.id}><div><strong>{r.profile_key} · {Number(r.institution_target_count).toLocaleString('tr-TR')} kurum / {Number(r.student_target_count).toLocaleString('tr-TR')} öğrenci · {r.status}</strong><span>{Number(r.processed_count).toLocaleString('tr-TR')} işlendi · {r.completed_chunks}/{r.total_chunks} parça</span>{r.last_error&&<span>{r.last_error}</span>}</div></div>)}{!(benchmarks?.runs||[]).length&&<div className="empty">Henüz yeni ölçek profili çalıştırılmadı.</div>}</div></div>
 </>;
}
