import { useEffect,useState } from 'react';
import { BarChart3, BookOpenCheck, Building2, CalendarDays, ClipboardCheck, GraduationCap, Layers3, Printer, ShieldCheck, Target, UserCog, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { useAuth } from '../auth';

function useDashboard(){const[data,setData]=useState<any>(null);const[error,setError]=useState('');useEffect(()=>{void api<any>('/api/dashboard').then(setData).catch(e=>setError(e.message))},[]);return{data,error}}
function Kpis({cards}:{cards:any[]}){return <div className="kpi-grid">{(cards||[]).map((c:any)=><div className="kpi-card" key={c.label}><span>{c.label}</span><strong>{c.value}</strong></div>)}</div>}
function Action({to,icon,title,text}:{to:string;icon:any;title:string;text:string}){return <Link to={to} className="exam-card" style={{textDecoration:'none',color:'inherit'}}><div className="quick-icon">{icon}</div><h3>{title}</h3><p>{text}</p><span className="link-button">Aç →</span></Link>}

export function SuperAdminStandardHome(){const{user}=useAuth();const{data,error}=useDashboard();return <><div className="page-head"><div><span className="eyebrow">Standard · Süper Admin</span><h1>Platform Kontrol Merkezi</h1><p>Kurum, sınav, optik, içerik, kullanıcı ve Standard kapanış durumunu tek merkezden yönetin.</p></div><ShieldCheck/></div>{error&&<div className="alert error">{error}</div>}<Kpis cards={data?.cards||[]}/><div className="action-grid" style={{marginTop:18}}><Action to="/standard-readiness" icon={<ShieldCheck/>} title="Standard Hazırlık" text="Çekirdek modülleri ve dış servis yapılandırmalarını doğrula."/><Action to="/completion-center" icon={<Layers3/>} title="Tamamlanma Merkezi" text="Dış aktivasyonları ve yıllık içerik planını yönet."/><Action to="/membership-orders" icon={<UserCog/>} title="Üyelik Talepleri" text="Gold ve Premium ödeme taleplerini sonuçlandır."/><Action to="/institutions" icon={<Building2/>} title="Kurumlar" text="Kurum yaşam döngüsü ve erişimlerini yönet."/><Action to="/exam-center" icon={<ClipboardCheck/>} title="Sınav Merkezi" text="Kurum, ağ ve merkezi sınavları yönet."/><Action to="/content-center" icon={<Layers3/>} title="Soru Havuzu" text="Soruları, Studio belgelerini ve videoları yönet."/><Action to="/opticals" icon={<Printer/>} title="Optik Merkezi" text="Optik tanımla, kalibrasyon ve baskı standardını yönet."/><Action to="/users" icon={<UserCog/>} title="Kullanıcılar" text="Rol, hesap ve erişim kapsamlarını yönet."/></div><div className="alert info" style={{marginTop:18}}>Aktif kullanıcı: {user?.display_name}. Production yayını, Standard kabul kontrolleri yeşile dönmeden yapılmamalıdır.</div></>}

export function TeacherStandardHome(){const{user}=useAuth();const{data,error}=useDashboard();const guidance=user?.role==='GUIDANCE_TEACHER';return <><div className="page-head"><div><span className="eyebrow">Standard · {guidance?'Rehber Öğretmen':'Branş Öğretmeni'}</span><h1>{guidance?'Sınıf Gelişim Merkezi':'Branş Akademik Merkezi'}</h1><p>{guidance?'Atandığınız sınıfların tüm ders gelişimini; sonuç, kazanım ve föylerle birlikte izleyin.':'Yalnız atanmış sınıflarınız ve branşınız için sınav, kazanım, soru havuzu ve föy akışını yönetin.'}</p></div><GraduationCap/></div>{error&&<div className="alert error">{error}</div>}<Kpis cards={data?.cards||[]}/>{data?.scope&&<div className="alert info" style={{marginTop:16}}>Yetki modu: {data.scope.mode==='GUIDANCE'?'Rehberlik · atanmış sınıfların tüm dersleri':'Branş · yalnız atanmış sınıf ve ders'}.</div>}<div className="action-grid" style={{marginTop:18}}><Action to="/classes" icon={<Users/>} title="Sınıflarım" text="Yetkili sınıfları ve öğrenci kapsamını gör."/><Action to="/exams" icon={<ClipboardCheck/>} title="Sınavlar" text="Yetki alanındaki sınavları ve sonuçları incele."/><Action to="/outcomes" icon={<Target/>} title="Kazanımlar" text="Gelişime açık ve güçlü kazanımları takip et."/><Action to="/content-center" icon={<Layers3/>} title="Soru Havuzu" text="Soru ekle; içerikleri inceleme akışına gönder."/><Action to="/worksheets" icon={<BookOpenCheck/>} title="Föyler" text="Sınıf ve branşa uygun haftalık föyleri kullan."/><Action to="/reports" icon={<BarChart3/>} title="Akademik Rapor" text="Öğrenci veya branş gelişimini raporla."/></div></>}

export function ParentStandardHome(){const{data,error}=useDashboard();const children=data?.children||[];return <><div className="page-head"><div><span className="eyebrow">Standard · Veli</span><h1>Çocuğumun Gelişimi</h1><p>Sonuç, gelişim, haftalık özet ve bildirimleri sade bir ekrandan takip edin.</p></div><Users/></div>{error&&<div className="alert error">{error}</div>}<div className="kpi-grid"><div className="kpi-card"><span>Bağlı öğrenci</span><strong>{children.length}</strong></div></div><div className="cards-list" style={{marginTop:18}}>{children.map((c:any)=><Link key={c.id} to={`/reports?studentId=${c.id}`} className="list-card"><div className="avatar big">{String(c.name||'?').charAt(0)}</div><div><strong>{c.name}</strong><span>{c.class_name?`${c.class_name} · `:''}Gelişim raporunu aç</span></div></Link>)}{!children.length&&<div className="empty">Bu veli hesabına bağlı aktif öğrenci bulunmuyor.</div>}</div><div className="action-grid" style={{marginTop:18}}><Action to="/weekly-summary" icon={<CalendarDays/>} title="Haftalık Özet" text="Son 7 günlük sınav ve kazanım gelişimini gör."/><Action to="/reports" icon={<BarChart3/>} title="Gelişim Raporu" text="Sınav, ders ve kazanım gelişimini incele."/><Action to="/children" icon={<Users/>} title="Çocuklarım" text="Bağlı öğrencileri ve erişim durumunu gör."/></div></>}
