import { useEffect,useState } from 'react';
import { Activity,AlertTriangle,BarChart3, BookOpenCheck, Bot, Building2, CalendarClock, CalendarDays, CheckCircle2, ClipboardCheck, GraduationCap, KeyRound, Layers3, Plus, Printer, ScanLine,ShieldCheck, Target, UserCog, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { useAuth } from '../auth';
import { useEnabledFeatures } from '../hooks/useEnabledFeatures';

function useDashboard(){const[data,setData]=useState<any>(null);const[error,setError]=useState('');useEffect(()=>{void api<any>('/api/dashboard').then(setData).catch(e=>setError(e.message))},[]);return{data,error}}
function Kpis({cards}:{cards:any[]}){return <div className="kpi-grid">{(cards||[]).map((c:any)=><div className="kpi-card" key={c.label}><span>{c.label}</span><strong>{c.value}</strong></div>)}</div>}
function Action({to,icon,title,text}:{to:string;icon:any;title:string;text:string}){return <Link to={to} className="exam-card" style={{textDecoration:'none',color:'inherit'}}><div className="quick-icon">{icon}</div><h3>{title}</h3><p>{text}</p><span className="link-button">Aç →</span></Link>}

export function SuperAdminStandardHome(){
 const{data,error}=useDashboard();const[licenses,setLicenses]=useState<any[]>([]);const[readiness,setReadiness]=useState<any>(null);useEffect(()=>{void api<any>('/api/admin/licenses').then(r=>setLicenses(r.licenses||[])).catch(()=>setLicenses([]));void api<any>('/api/standard-readiness').then(setReadiness).catch(()=>setReadiness(null))},[]);
 const institutions=Number(data?.cards?.find((c:any)=>c.label==='Kurum')?.value||0),trials=licenses.filter(x=>x.license?.planCode==='TRIAL_7_DAY'&&!x.license?.locked).length,pending=licenses.filter(x=>x.annual_consent_status==='PENDING').length,annual=licenses.filter(x=>x.license?.planCode==='ANNUAL'&&x.license?.status==='ACTIVE').length;
 return <><div className="page-head admin-hero"><div><span className="eyebrow">ANUNEX · Platform Yönetimi</span><h1>Kontrol Merkezi</h1><p>Kurum, lisans, ölçme operasyonu ve Nibiru akademik zekâsını tek merkezden yönetin.</p></div><div className="admin-hero-mark"><span>ANUNEX</span><Bot/></div></div>{error&&<div className="alert error">{error}</div>}
 <div className="kpi-grid"><div className="kpi-card"><span>Toplam Kurum</span><strong>{institutions}</strong></div><div className="kpi-card"><span>Aktif Demo</span><strong>{trials}</strong></div><div className="kpi-card"><span>Lisans Onayı Bekleyen</span><strong>{pending}</strong></div><div className="kpi-card"><span>Yıllık Lisans</span><strong>{annual}</strong></div><div className="kpi-card"><span>Bugün Değerlendirilen</span><strong>{data?.cards?.find((c:any)=>c.label==='Bugün Değerlendirilen')?.value||0}</strong></div></div>
 <div className="section-head"><div><span className="eyebrow">Canlı Operasyon</span><h2>Servis ve işlem sağlığı</h2><p>Sınav, optik ve Nibiru durumunu teknik ekrana girmeden izleyin.</p></div></div><div className="kpi-grid"><div className="kpi-card"><span>Aktif Sınav</span><strong>{data?.operations?.activeExams||0}</strong></div><div className="kpi-card"><span>Optik Kuyruğu</span><strong>{data?.operations?.pendingScans||0}</strong></div><div className="kpi-card"><span>Başarısız Optik</span><strong className={data?.operations?.failedScans?'danger-text':''}>{data?.operations?.failedScans||0}</strong></div><div className="kpi-card"><span>Hazır Optik Şablonu</span><strong>{data?.operations?.readyOpticals||0}</strong></div><div className="kpi-card"><span>Nibiru Hatası · 24s</span><strong>{data?.operations?.nibiruErrors24h||0}</strong></div></div>
 <div className="service-health-grid"><div className="panel"><div className="panel-head"><div><h3>Platform servisleri</h3><p>Bağlantı ve temel hazırlık özeti.</p></div><Activity/></div><div className="health-list"><Health label="Veritabanı" ready={Boolean(data)}/><Health label="Dosya depolama" ready={readiness?.checks?.some((x:any)=>x.key==='R2'&&x.state==='READY')??false}/><Health label="Workers AI" ready={readiness?.checks?.some((x:any)=>x.key==='NIBIRU_BASIC'&&x.state==='READY')??false}/><Health label="Standard çekirdek" ready={Boolean(readiness?.summary?.coreReady)}/></div></div><div className="panel"><div className="panel-head"><div><h3>Son işlemler</h3><p>Platform genelindeki son denetim kayıtları.</p></div><ScanLine/></div><div className="health-list">{(data?.recentActivity||[]).map((x:any,i:number)=><div className="health-row" key={`${x.created_at}-${i}`}><CheckCircle2 size={16}/><div><strong>{actionName(x.action)}</strong><span>{x.actor_name||'Sistem'} · {new Date(x.created_at).toLocaleString('tr-TR')}</span></div></div>)}{!data?.recentActivity?.length&&<div className="empty">Henüz işlem kaydı yok.</div>}</div></div></div>
 {institutions===0&&<div className="empty-onboarding"><div className="quick-icon"><Building2/></div><div><span className="eyebrow">İlk Kurulum</span><h2>İlk kurumunuzu 7 günlük demoyla oluşturun</h2><p>Kurum, yönetici, sezon, paket ve modül yetkileri tek akışta hazırlanır.</p></div><Link className="primary" to="/institutions"><Plus size={16}/> İlk Kurumu Oluştur</Link></div>}
 <div className="section-head"><div><span className="eyebrow">Günlük Operasyon</span><h2>Öncelikli işlemler</h2><p>En sık kullanılan kurum, lisans, sınav ve Nibiru süreçleri.</p></div></div><div className="action-grid"><Action to="/institutions" icon={<Building2/>} title="Kurum & Demo Kur" text="Yeni kurumu, yöneticiyi, paketi ve 7 günlük demoyu oluştur."/><Action to="/licenses" icon={<KeyRound/>} title="Lisans Kararları" text={`${pending} kurum kararı bekliyor; demo ve yıllık lisansları yönet.`}/><Action to="/exam-center" icon={<ClipboardCheck/>} title="Sınav Operasyonu" text="Kurum, zincir ve merkezi sınavları tek merkezden yönet."/><Action to="/optical-prepare" icon={<Printer/>} title="Optik Hazırla / Bas" text="Kişiselleştirilmiş optikleri tekil veya toplu üret."/><Action to="/nibiru-admin" icon={<Bot/>} title="Nibiru AI Yönetimi" text="AI erişimi, kanal durumu ve akademik denetim kayıtlarını izle."/><Action to="/reports" icon={<BarChart3/>} title="Rapor Merkezi" text="Kurum, öğrenci, sınav ve gelişim raporlarını incele."/></div>
 <div className="section-head"><div><span className="eyebrow">Platform Durumu</span><h2>Hazırlık ve yönetim</h2></div></div><div className="action-grid"><Action to="/standard-readiness" icon={<ShieldCheck/>} title="Sistem Hazırlığı" text="Çekirdek modülleri ve dış servis yapılandırmalarını doğrula."/><Action to="/completion-center" icon={<CheckCircle2/>} title="Tamamlama Merkezi" text="Dış girdileri ve ürün kapanış işlerini takip et."/><Action to="/membership-orders" icon={<CalendarClock/>} title="Üyelik Talepleri" text="Gold ve Premium üyelik taleplerini sonuçlandır."/></div></>;
}

function Health({label,ready}:{label:string;ready:boolean}){return <div className="health-row">{ready?<CheckCircle2 className="ok-text" size={17}/>:<AlertTriangle className="warn-text" size={17}/>}<div><strong>{label}</strong><span>{ready?'Hazır':'Kurulum veya doğrulama gerekli'}</span></div></div>}
function actionName(value:string){return ({INSTITUTION_ONBOARDED:'Kurum oluşturuldu',PASSWORD_CHANGED:'Şifre değiştirildi',SESSION_REVOKED:'Oturum kapatıldı',ALL_SESSIONS_REVOKED:'Tüm oturumlar kapatıldı',INSTITUTION_PAUSED:'Kurum pasife alındı',INSTITUTION_REACTIVATED:'Kurum yeniden etkinleştirildi'} as Record<string,string>)[value]||String(value||'Sistem işlemi').replaceAll('_',' ')}

export function TeacherStandardHome(){
 const{user}=useAuth();const{data,error}=useDashboard();const{enabled}=useEnabledFeatures();const guidance=user?.role==='GUIDANCE_TEACHER',classes=data?.scope?.classes||[],subjects=data?.scope?.subjects||[],hasAssignment=classes.length>0;
 return <><div className="page-head"><div><span className="eyebrow">Standard · {guidance?'Rehber Öğretmen':'Branş Öğretmeni'}</span><h1>{guidance?'Sınıf Gelişim Merkezi':'Branş Akademik Merkezi'}</h1><p>{guidance?'Atandığınız sınıfların tüm ders gelişimini; sonuç, kazanım ve föylerle birlikte izleyin.':'Yalnız atanmış sınıflarınız ve branşınız için sınav, kazanım, soru havuzu ve föy akışını yönetin.'}</p></div><GraduationCap/></div>{error&&<div className="alert error">{error}</div>}<Kpis cards={data?.cards||[]}/>{data?.scope&&<div className="panel teacher-scope"><div><span className="eyebrow">Aktif Yetki Kapsamı</span><h2>{data.scope.mode==='GUIDANCE'?'Rehberlik · atanmış sınıfların tüm dersleri':'Branş · yalnız atanmış sınıf ve ders'}</h2></div><div><strong>Sınıflar</strong><div className="package-scope-tags">{classes.map((row:any)=><span className="status ok" key={row.id}>{row.name}</span>)}{!classes.length&&<span className="muted">Aktif sınıf ataması yok</span>}</div>{!guidance&&<><strong>Dersler</strong><div className="package-scope-tags">{subjects.map((row:any)=><span className="status neutral" key={row.id}>{row.name}</span>)}{!subjects.length&&<span className="muted">Aktif branş ataması yok</span>}</div></>}</div></div>}
 {!hasAssignment&&data&&<div className="alert warning" style={{marginTop:16}}>Kurum yöneticiniz henüz aktif sınıf ve branş ataması yapmamış. Akademik veriler atama tamamlanınca otomatik açılır.</div>}
 {hasAssignment&&<div className="action-grid" style={{marginTop:18}}><Action to="/classes" icon={<Users/>} title="Sınıflarım" text="Yetkili sınıfları ve öğrenci kapsamını gör."/>{enabled('EXAM_CENTER')&&<Action to="/exams" icon={<ClipboardCheck/>} title="Sınavlar" text="Yetki alanındaki sınavları ve sonuçları incele."/>}{enabled('REPORTING')&&<Action to="/outcomes" icon={<Target/>} title="Kazanımlar" text="Gelişime açık ve güçlü kazanımları takip et."/>}{enabled('QUESTION_BANK')&&<Action to="/content-center" icon={<Layers3/>} title="Soru Havuzu" text="Yalnız kendi branşında soru ekle; inceleme akışına gönder."/>}{enabled('WORKSHEETS')&&<Action to="/worksheets" icon={<BookOpenCheck/>} title="Föyler" text="Sınıf ve branşa uygun haftalık föyleri kullan."/>}{enabled('REPORTING')&&<Action to="/reports" icon={<BarChart3/>} title="Akademik Rapor" text="Yalnız yetkili öğrenci ve branş gelişimini raporla."/>}</div>}</>
}

export function ParentStandardHome(){const{data,error}=useDashboard();const children=data?.children||[];return <><div className="page-head"><div><span className="eyebrow">Standard · Veli</span><h1>Çocuğumun Gelişimi</h1><p>Sonuç, gelişim, haftalık özet ve bildirimleri sade bir ekrandan takip edin.</p></div><Users/></div>{error&&<div className="alert error">{error}</div>}<div className="kpi-grid"><div className="kpi-card"><span>Bağlı öğrenci</span><strong>{children.length}</strong></div></div><div className="cards-list" style={{marginTop:18}}>{children.map((c:any)=><Link key={c.id} to={`/reports?studentId=${c.id}`} className="list-card"><div className="avatar big">{String(c.name||'?').charAt(0)}</div><div><strong>{c.name}</strong><span>{c.class_name?`${c.class_name} · `:''}Gelişim raporunu aç</span></div></Link>)}{!children.length&&<div className="empty">Bu veli hesabına bağlı aktif öğrenci bulunmuyor.</div>}</div><div className="action-grid" style={{marginTop:18}}><Action to="/weekly-summary" icon={<CalendarDays/>} title="Haftalık Özet" text="Son 7 günlük sınav ve kazanım gelişimini gör."/><Action to="/reports" icon={<BarChart3/>} title="Gelişim Raporu" text="Sınav, ders ve kazanım gelişimini incele."/><Action to="/children" icon={<Users/>} title="Çocuklarım" text="Bağlı öğrencileri ve erişim durumunu gör."/></div></>}
