import { useEffect,useState } from 'react';
import { CheckCircle2, RefreshCw, Settings2, ShieldCheck, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { SUPER_ADMIN_ACCEPTANCE } from '../lib/super-admin-acceptance';

type Check={key:string;label:string;state:'READY'|'CONFIG_REQUIRED'|'MISSING';detail:string};
type Operational={key:string;label:string;state:'READY'|'SETUP_REQUIRED';value:number;detail:string;blocking:boolean};
function ProviderItem({label,ok}:{label:string;ok:boolean}){return <div className="list-card"><div className="quick-icon">{ok?<CheckCircle2 size={18}/>:<Settings2 size={18}/>}</div><div><strong>{ok?'🟩':'🟨'} {label}</strong><span>{ok?'Cloudflare secret tanımlı.':'Opsiyonel kanal için Cloudflare secret tanımlanmalı.'}</span></div><span className={`status ${ok?'success':'warning'}`}>{ok?'HAZIR':'BEKLİYOR'}</span></div>}

export function StandardReadiness(){
 const[data,setData]=useState<any>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);setError('');try{setData(await api<any>('/api/standard-readiness'))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const ready=Boolean(data?.acceptance?.standardPackageReady);
 return <><div className="page-head"><div><span className="eyebrow">Standard Paket · Final Kapanış</span><h1>Standard Hazırlık Denetçisi</h1><p>Standard paket kendi kodu, verisi ve tüketilebilir içerik akışıyla değerlendirilir. YouTube otomatik keşif ve WhatsApp ayrı, opsiyonel kanal aktivasyonlarıdır.</p></div><button className="ghost" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}
 {data&&<><div className="kpi-grid" style={{marginBottom:18}}><div className="kpi-card"><span>🟩 Hazır modül</span><strong>{data.summary.ready}</strong></div><div className="kpi-card"><span>🟥 Çekirdek eksik</span><strong>{data.summary.missing}</strong></div><div className="kpi-card"><span>Standard kurulum eksiği</span><strong>{(data.acceptance?.blockingSetup||0)+(data.acceptance?.packageConfigRequired||0)}</strong></div><div className="kpi-card"><span>🟨 Opsiyonel kanal</span><strong>{data.acceptance?.optionalChannelSetup??0}</strong></div></div>
 <div className={`alert ${ready?'success':'error'}`} style={{marginBottom:16}}><ShieldCheck size={18}/><div><strong>{ready?'🟩 Standard paket satışa hazır':'🟥 Standard paket kapanışında eksik var'}</strong><span>{ready?'Optik, değerlendirme, analiz, Nibiru, föy, mikro öğrenme, kişisel kitap, Sıfır Hata ve öğrenci deneyimi çekirdeği kabul edildi.':'Aşağıdaki bloklayan Standard maddeleri tamamlanmalıdır.'} · Ortam: {data.environment} · {new Date(data.generatedAt).toLocaleString('tr-TR')}</span></div></div>
 {ready&&!data.acceptance?.fullChannelReady&&<div className="alert info" style={{marginBottom:16}}><Settings2 size={18}/><div><strong>🟨 Opsiyonel kanallar ayrıca aktive edilebilir</strong><span>Bu durum Standard paketin satış/kullanım hazırlığını bloklamaz. YouTube otomatik keşif, WhatsApp ve benzeri dış kanallar kendi provider kurulumu tamamlandığında açılır.</span></div></div>}
 <h2>1 · Kod ve veri modeli</h2><div className="cards-list">{(data.checks as Check[]).map(c=><div className="list-card" key={c.key}><div className="quick-icon">{c.state==='READY'?<CheckCircle2 size={18}/>:c.state==='CONFIG_REQUIRED'?<Settings2 size={18}/>:<XCircle size={18}/>}</div><div><strong>{c.state==='READY'?'🟩':c.state==='CONFIG_REQUIRED'?'🟨':'🟥'} {c.label}</strong><span>{c.detail}{['YOUTUBE_MICRO','WHATSAPP'].includes(c.key)&&c.state!=='READY'?' · Opsiyonel kanal; Standard paketi bloklamaz.':''}</span></div><span className={`status ${c.state==='READY'?'success':c.state==='CONFIG_REQUIRED'?'warning':'danger'}`}>{c.state==='READY'?'HAZIR':c.state==='CONFIG_REQUIRED'?'AYAR GEREKLİ':'EKSİK'}</span></div>)}</div>
 <h2 style={{marginTop:24}}>2 · Standard operasyonel kabul</h2>{data.operationalError&&<div className="alert error">Operasyon kontrolü çalıştırılamadı: {data.operationalError}</div>}<div className="cards-list">{(data.operational as Operational[]||[]).map(c=><div className="list-card" key={c.key}><div className="quick-icon">{c.state==='READY'?<CheckCircle2 size={18}/>:<Settings2 size={18}/>}</div><div><strong>{c.state==='READY'?'🟩':'🟨'} {c.label}</strong><span>{c.detail}{!c.blocking&&c.state!=='READY'?' · Standard paketini bloklamaz.':''}</span></div><span className={`status ${c.state==='READY'?'success':'warning'}`}>{c.state==='READY'?'HAZIR':'KURULUM GEREKLİ'}</span></div>)}</div>
 <h2 style={{marginTop:24}}>3 · Opsiyonel dış kanallar</h2><div className="panel"><div className="panel-head"><div><h3>YouTube otomatik mikro öğrenme keşfi</h3><p>Standard’da onaylı kayıtlı çözüm/konu videosu çalışır. YouTube anahtarı yalnız uygun kayıt yoksa otomatik kısa video bulma katmanını açar.</p></div><span className={`status ${data.providers?.youtube?.ready?'success':'warning'}`}>{data.providers?.youtube?.ready?'AKTİF':'OPSİYONEL'}</span></div><div className="cards-list"><ProviderItem label="YOUTUBE_API_KEY" ok={Boolean(data.providers?.youtube?.apiKey)}/></div></div>
 <div className="panel"><div className="panel-head"><div><h3>WhatsApp akademik kanal</h3><p>Web Standard paketinden bağımsız mesajlaşma kanalıdır; dört Meta secret tamamlandığında açılır.</p></div><Link className="ghost" to="/nibiru-admin">Nibiru Yönetimi</Link></div><div className="cards-list"><ProviderItem label="WHATSAPP_VERIFY_TOKEN" ok={Boolean(data.providers?.whatsapp?.verifyToken)}/><ProviderItem label="WHATSAPP_APP_SECRET" ok={Boolean(data.providers?.whatsapp?.appSecret)}/><ProviderItem label="WHATSAPP_ACCESS_TOKEN" ok={Boolean(data.providers?.whatsapp?.accessToken)}/><ProviderItem label="WHATSAPP_PHONE_NUMBER_ID" ok={Boolean(data.providers?.whatsapp?.phoneNumberId)}/></div></div>
 <div className="panel"><div className="panel-head"><div><h3>Resmî hedef verisi</h3><p>Hedef motoru hazırdır; gerçek okul/program araması doğrulanmış MEB, ÖSYM ve YÖK Atlas kayıtlarıyla beslenir. Veri yokluğu sahte hedef üretmez.</p></div><Link className="ghost" to="/academic-target-admin">Hedef Veri Merkezi</Link></div></div>
 <h2 style={{marginTop:24}}>4 · Süper Admin rol kabulü</h2><p className="muted">Bu matris yalnız ekranın açılmasını değil; görünürlük, yetki, kurum kapsamı, boş/hata durumu, mobil kullanım, pratiklik, çıktı ve denetim şartlarını birlikte izler.</p><div className="acceptance-grid">{SUPER_ADMIN_ACCEPTANCE.map(item=><Link to={item.path} className="acceptance-card" key={item.key}><div className="acceptance-card-head"><CheckCircle2 size={18}/><strong>{item.title}</strong><span className="status success">KOD KABULÜ</span></div><p>{item.detail}</p><small>{item.evidence}</small></Link>)}</div>
 </>}
 </>;
}
