import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,BookOpenCheck,CheckCircle2,Printer,RefreshCcw,Sparkles,Target,XCircle} from 'lucide-react';
import {api} from '../api';
import './student-standard.css';

export function StudentBooks(){
 const[personal,setPersonal]=useState<any[]>([]),[zero,setZero]=useState<any[]>([]),[exams,setExams]=useState<any[]>([]);const[selectedExam,setSelectedExam]=useState(''),[selectedBook,setSelectedBook]=useState<any>(null),[answers,setAnswers]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{setError('');try{const[p,z,e]=await Promise.all([api<any>('/api/student-books/personal'),api<any>('/api/student-books/zero-error'),api<any>('/api/my-results')]);setPersonal(p.books||[]);setZero(z.booklets||[]);setExams(e.exams||[])}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setMsg('');try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const createPersonal=()=>run(async()=>{const r=await api<any>('/api/student-books/personal',{method:'POST',body:JSON.stringify({outcomeLimit:8,questionsPerOutcome:4})});setMsg(`Kişiye Özel Kitap hazırlandı: ${r.outcomeCount} kazanım, ${r.questionCount} çalışma sorusu.`);await load();await openBook(r.id)});
 const createZero=()=>run(async()=>{if(!selectedExam)return;const r=await api<any>('/api/student-books/zero-error',{method:'POST',body:JSON.stringify({examId:selectedExam,practicePerSource:2})});setMsg(`Sıfır Hata Kitapçığı hazırlandı: ${r.wrongCount} yanlış, ${r.blankCount} boş, ${r.practiceCount} benzer çalışma sorusu.`);await load()});
 const openBook=async(id:string)=>{setError('');try{setSelectedBook(await api<any>(`/api/student-books/personal/${id}`));window.scrollTo({top:0,behavior:'smooth'})}catch(e:any){setError(e.message)}};
 const answer=async(item:any)=>{const value=String(answers[item.id]||'').trim();if(!value)return;await run(async()=>{const r=await api<any>(`/api/student-books/personal/items/${item.id}/attempt`,{method:'POST',body:JSON.stringify({answer:value})});setMsg(r.correct?'Doğru cevap! Bu kazanım güçleniyor.':`Tekrar deneyebilirsin. Doğru cevap: ${r.correctAnswer}`);await openBook(item.book_id);await load()})};
 if(selectedBook)return <BookReader data={selectedBook} answers={answers} setAnswers={setAnswers} busy={busy} error={error} msg={msg} onAnswer={answer} onBack={()=>setSelectedBook(null)}/>;
 return <><div className="page-head"><div><span className="eyebrow">Kişisel çalışma ürünleri</span><h1>📚 Benim Kitaplarım</h1><p>Sınav ve kazanım verilerinden sana özel çalışma çıktıları oluştur.</p></div><BookOpenCheck/></div>{error&&<div className="alert error">{error}</div>}{msg&&<div className="alert success">{msg}</div>}
  <div className="student-top-grid"><div className="goal-story-card"><div className="goal-story-icon"><Sparkles/></div><span>Kişiye Özel Kitap</span><h2>Gelişim alanlarından kişisel kitap</h2><p>Birden fazla ölçme kanıtına göre gelişime açık kazanımlar seçilir; yalnız kurumunun erişebildiği, onaylı ve hakları doğrulanmış sorular kullanılır.</p><button className="primary" disabled={busy} onClick={()=>void createPersonal()}><Sparkles size={16}/> Kitabımı Oluştur</button></div>
  <div className="goal-story-card"><div className="goal-story-icon"><Target/></div><span>Sıfır Hata Kitapçığı</span><h2>Yanlış ve boşları kapat</h2><p>Sonuçlanmış sınavındaki yanlış ve boş soruların kazanımları üzerinden benzer sorularla tekrar döngüsü oluşturur.</p><div className="book-create-row"><select value={selectedExam} onChange={e=>setSelectedExam(e.target.value)}><option value="">Sınav seç</option>{exams.map((e:any)=><option key={e.exam_id} value={e.exam_id}>{e.title}{e.exam_date?` · ${e.exam_date}`:''}</option>)}</select><button className="primary" disabled={busy||!selectedExam} onClick={()=>void createZero()}><RefreshCcw size={16}/> Kitapçığı Oluştur</button></div></div></div>
  <div className="panel"><div className="panel-head"><div><h2>Kişiye Özel Kitaplarım</h2><p>Kitabını aç, soruları çöz ve gelişimini takip et.</p></div></div><div className="cards-list">{personal.map((b:any)=>{const percent=b.question_count?Math.round(Number(b.mastered_count||0)/Number(b.question_count)*100):0;return <button className="list-card book-list-button" key={b.id} onClick={()=>void openBook(b.id)}><div className="quick-icon"><Sparkles size={18}/></div><div><strong>{b.title}</strong><span>{b.outcome_count} kazanım · {b.question_count} soru · {b.attempted_count||0} çözüldü · %{percent} tamamlandı</span><div className="book-progress"><i style={{width:`${percent}%`}}/></div></div></button>})}{!personal.length&&<div className="empty">Henüz kişiye özel kitabın yok.</div>}</div></div>
  <div className="panel"><div className="panel-head"><div><h2>Sıfır Hata Kitapçıklarım</h2><p>Yanlış ve boşlardan tekrar öğrenme döngüsü.</p></div></div><div className="cards-list">{zero.map((b:any)=><div className="list-card" key={b.id}><div className="quick-icon"><Target size={18}/></div><div><strong>{b.title}</strong><span>{b.source_exam_title||'Sınav'} · {b.wrong_count} yanlış · {b.blank_count} boş · {b.unresolved_count} açık madde</span></div></div>)}{!zero.length&&<div className="empty">Henüz Sıfır Hata Kitapçığın yok.</div>}</div></div></>;
}

function BookReader({data,answers,setAnswers,busy,error,msg,onAnswer,onBack}:any){const book=data.book,questions=useMemo(()=>data.items.filter((x:any)=>x.item_type==='PRACTICE_QUESTION'),[data.items]);const percent=book.question_count?Math.round(Number(book.mastered_count||0)/Number(book.question_count)*100):0;return <div className="personal-book-reader"><div className="page-head no-print"><div><button className="ghost" onClick={onBack}><ArrowLeft size={16}/> Kitaplarıma dön</button><span className="eyebrow">ANUNEX · Nibiru kişisel öğrenme rotası</span><h1>{book.title}</h1><p>{book.outcome_count} gelişim alanı · {book.question_count} çalışma sorusu · %{percent} tamamlandı</p></div><button className="secondary" onClick={()=>window.print()}><Printer size={16}/> Yazdır / PDF kaydet</button></div>{error&&<div className="alert error no-print">{error}</div>}{msg&&<div className="alert success no-print">{msg}</div>}
 <div className="print-book-cover"><span>ANUNEX</span><h1>{book.title}</h1><p>Nibiru tarafından ölçme kanıtlarından oluşturulan kişisel gelişim kitabı</p><small>{book.academic_year||''} · {book.grade_level?`${book.grade_level}. sınıf`:''}</small></div>
 <div className="book-summary no-print"><div><strong>{book.attempted_count||0}/{book.question_count}</strong><span>Çözülen</span></div><div><strong>{book.mastered_count||0}</strong><span>Doğru tamamlanan</span></div><div><strong>%{percent}</strong><span>İlerleme</span></div></div>
 <div className="personal-book-pages">{data.items.map((item:any,index:number)=>item.item_type==='OUTCOME_HEADER'?<section className="book-outcome" key={item.id}><span>{item.subject_name}</span><h2>{item.outcome_title||item.payload?.title}</h2><p>{[item.payload?.topic,item.payload?.subtopic].filter(Boolean).join(' · ')}</p><small>Başlangıç başarı düzeyi: %{Math.round(Number(item.payload?.successRate||0)*100)} · {item.payload?.evidenceCount||0} kanıt</small></section>:<section className="book-question" key={item.id}><span className="question-no">Soru {questions.findIndex((q:any)=>q.id===item.id)+1}</span><h3>{item.stem_text}</h3>{Array.isArray(item.options)&&item.options.length>0&&<div className="book-options">{item.options.map((option:any,ix:number)=>{const value=typeof option==='string'?option:String(option?.value||option?.label||'');return <label key={ix}><input type="radio" name={item.id} value={value} checked={answers[item.id]===value} onChange={e=>setAnswers({...answers,[item.id]:e.target.value})}/><span>{String.fromCharCode(65+ix)}) {value}</span></label>})}</div>}<div className="book-answer no-print">{(!item.options||!item.options.length)&&<input value={answers[item.id]||''} onChange={e=>setAnswers({...answers,[item.id]:e.target.value})} placeholder="Cevabını yaz"/>}<button className="primary" disabled={busy||!String(answers[item.id]||'').trim()} onClick={()=>void onAnswer(item)}>Cevapla</button></div>{item.last_attempt_at&&<div className={`book-feedback ${Number(item.last_correct)===1?'correct':'wrong'}`}>{Number(item.last_correct)===1?<CheckCircle2/>:<XCircle/>}<div><strong>{Number(item.last_correct)===1?'Doğru cevap':'Tekrar çalış'}</strong><p>Son cevabın: {item.last_answer}{item.correct_answer?` · Doğru cevap: ${item.correct_answer}`:''}</p>{item.solution_text&&<small>{item.solution_text}</small>}</div></div>}<div className="print-answer-line">Cevap: ____________________</div></section>)}</div>
 </div>}
