import { useEffect,useState } from 'react';
import { BrainCircuit,RefreshCw,Route,Target,WandSparkles } from 'lucide-react';
import { api } from '../api';

export function StudentGrowthCenter(){
 const [graph,setGraph]=useState<any>(null);const [plans,setPlans]=useState<any[]>([]);const [profile,setProfile]=useState<any>(null);const [tab,setTab]=useState('graph');const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [v,setV]=useState({planning:3,review:3,consistency:3,pace:3,persistence:3});
 const load=async()=>{const [g,r,p]=await Promise.all([api<any>('/api/platform/learning-state').catch(()=>null),api<any>('/api/platform/recovery').catch(()=>({plans:[]})),api<any>('/api/platform/rba').catch(()=>null)]);setGraph(g);setPlans(r?.plans||[]);setProfile(p)};useEffect(()=>{void load()},[]);
 const recovery=async()=>{try{const r=await api<any>('/api/platform/recovery/generate',{method:'POST',body:JSON.stringify({title:'Kişisel Eksik Tamamlama Rotam'})});setNotice(`${r.stepCount} adımlık rota hazırlandı.`);await load()}catch(e:any){setError(e.message)}};
 const save=async()=>{try{const dimensions={analytical:{a:v.planning,b:v.review},verbal:{a:v.review},numeric:{a:v.planning},consistency:{a:v.consistency},errorRepetition:{a:v.review},pace:{a:v.pace},planAdherence:{a:v.planning},persistence:{a:v.persistence},stability:{a:v.consistency}};const r=await api<any>('/api/platform/rba',{method:'POST',body:JSON.stringify({version:'RBA-1',dimensions})});setProfile({profile:r.result,disclaimer:r.disclaimer});setNotice('Öğrenme davranışı profili güncellendi.')}catch(e:any){setError(e.message)}};
 return <><div className="page-head"><div><span className="eyebrow">Kişisel Gelişim</span><h1>Akademik Gelişim Merkezi</h1><p>Learning Graph, Recovery ve RBA aynı öğrenci verisiyle çalışır.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div style={{display:'flex',gap:8,marginBottom:16}}><button className={tab==='graph'?'primary':'secondary'} onClick={()=>setTab('graph')}><Target size={16}/> Learning Graph</button><button className={tab==='recovery'?'primary':'secondary'} onClick={()=>setTab('recovery')}><Route size={16}/> Recovery</button><button className={tab==='rba'?'primary':'secondary'} onClick={()=>setTab('rba')}><BrainCircuit size={16}/> RBA</button></div>
 {tab==='graph'&&<div className="panel"><h2>Öğrenme haritası</h2>{!graph?.nodes?.length?<div className="empty-state">Henüz yeterli öğrenme kanıtı yok.</div>:<div className="feature-grid">{graph.nodes.slice(0,50).map((n:any)=><div className="feature-card" key={n.node_id}><div><span className="pill">{n.node_type}</span><h3>{n.title}</h3><small>{n.evidence_count} kanıt</small></div><strong>%{Math.round(Number(n.mastery||0)*100)}</strong></div>)}</div>}</div>}
 {tab==='recovery'&&<><div className="panel" style={{marginBottom:16}}><h2>Eksik kapatma rotası</h2><p>Yanlış/boş → açıklama → pratik → yeniden ölçme.</p><button className="primary" onClick={recovery}><WandSparkles size={16}/> Recovery Oluştur</button></div><div className="exam-grid">{plans.map(p=><div className="exam-card" key={p.id}><span className="status neutral">{p.status}</span><h3>{p.title}</h3><p>{p.done_count||0}/{p.step_count||0} adım</p></div>)}</div></>}
 {tab==='rba'&&<><div className="alert warning"><strong>Eğitsel kullanım:</strong> RBA psikolojik veya tıbbi tanı üretmez; çalışma ve öğrenme davranışı hakkında farkındalık sağlar.</div><div className="panel"><h2>RBA öğrenme davranışı profili</h2>{Object.entries({planning:'Çalışmaya başlamadan önce hedef belirlerim.',review:'Yanlış yaptığım sorulara tekrar dönerim.',consistency:'Planımı çoğu gün uygularım.',pace:'Çalışma tempomu korurum.',persistence:'Zor soruda hemen vazgeçmem.'}).map(([k,t])=><label key={k}>{t}<input type="range" min="1" max="5" value={(v as any)[k]} onChange={e=>setV({...v,[k]:Number(e.target.value)})}/><strong>{(v as any)[k]}/5</strong></label>)}<button className="primary" onClick={save}>Profili Güncelle</button></div>{profile?.profile&&<div className="panel" style={{marginTop:16}}><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(profile.profile,null,2)}</pre></div>}</>}
 </>;
}
