import { useEffect,useState } from 'react';
import { CheckCircle2, Send, UserRoundPlus } from 'lucide-react';
import { api, post, qs } from '../api';
import { useAuth } from '../auth';
import { InstitutionSelect } from '../components/EntitySelectors';

export function Students(){
 const {user}=useAuth(); const [tab,setTab]=useState<'ACTIVE'|'GUEST'>('ACTIVE'); const [rows,setRows]=useState<any[]>([]); const [institutionId,setInstitutionId]=useState(''); const [busy,setBusy]=useState(''); const [notice,setNotice]=useState(''); const[error,setError]=useState('');
 const load=()=>user?.role==='SUPER_ADMIN'&&!institutionId?Promise.resolve():api<any>(`/api/students${qs({status:tab,institutionId:user?.role==='SUPER_ADMIN'?institutionId:null})}`).then(r=>setRows(r.students));
 useEffect(()=>{void load().catch(e=>setError(e.message))},[tab,institutionId]);
 const activate=async(id:string)=>{if(!confirm('Ödeme/onay tamamlandı ve bu misafir öğrenci aktif öğrenciye dönüştürülsün mü?'))return;setBusy(id);setError('');try{const r=await post<any>(`/api/students/${id}/activate`,{paymentConfirmed:true});setNotice(`Öğrenci aktif edildi. Geçmiş ${r.priorExamCount} sınav otomatik bağlandı.`);await load()}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const requestActivation=async(id:string)=>{const note=prompt('Aktivasyon talebi notu (isteğe bağlı)')||'';setBusy(id);setError('');try{await post('/api/activation-requests',{studentId:id,note});setNotice('Aktivasyon talebi Süper Admin onayına gönderildi.');}catch(e:any){setError(e.message)}finally{setBusy('')}};
 return <><div className="page-head"><div><span className="eyebrow">Öğrenci yaşam döngüsü</span><h1>Öğrenciler</h1><p>Aktif öğrenciler tam sisteme erişir; misafirler sınav sonucu için tutulur ve kurum talebiyle aktifleştirilebilir.</p></div>{user?.role==='SUPER_ADMIN'&&<div className="compact-field"><InstitutionSelect value={institutionId} onChange={setInstitutionId}/></div>}</div>
 <div className="tabs"><button className={tab==='ACTIVE'?'active':''} onClick={()=>setTab('ACTIVE')}>Aktif Öğrenciler</button><button className={tab==='GUEST'?'active':''} onClick={()=>setTab('GUEST')}>Misafir Katılımcılar</button></div>{notice&&<div className="alert success">{notice}</div>}{error&&<div className="alert error">{error}</div>}
 <div className="table-card"><table><thead><tr><th>Öğrenci</th><th>No</th><th>Sınıf</th><th>Sınav</th><th>Durum</th>{tab==='GUEST'&&<th></th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.first_name} {r.last_name}</strong></td><td>{r.student_number||'—'}</td><td>{r.grade_level?`${r.grade_level}/${r.section||'—'}`:'—'}</td><td>{r.exam_count}</td><td><span className={`status ${r.status==='ACTIVE'?'ok':'neutral'}`}>{r.status==='ACTIVE'?<><CheckCircle2 size={14}/> Aktif</>:'Misafir'}</span></td>{tab==='GUEST'&&<td>{user?.role==='SUPER_ADMIN'?<button className="primary subtle" disabled={busy===r.id} onClick={()=>activate(r.id)}><UserRoundPlus size={16}/> Aktif Öğrenci Yap</button>:<button className="secondary subtle" disabled={busy===r.id} onClick={()=>void requestActivation(r.id)}><Send size={15}/> Aktivasyon Talebi Gönder</button>}</td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty">Bu filtrede öğrenci bulunamadı.</div>}</div></>
}
