import { useEffect,useState } from 'react';
import { CheckCircle2,ExternalLink,GraduationCap,Search,Sparkles,Target,Trash2 } from 'lucide-react';
import { api } from '../api';
import './student-standard.css';

function num(v:any){return v==null?'—':Number(v).toLocaleString('tr-TR',{maximumFractionDigits:2})}
function pct(v:any){return v==null?'—':`%${Number(v).toLocaleString('tr-TR',{maximumFractionDigits:3})}`}
function label(t:any){return t.target_type==='LGS_SCHOOL'?t.school_name:`${t.university_name} · ${t.program_name}`}

export function StudentTargetsV2(){
 const[info,setInfo]=useState<any>(null),[results,setResults]=useState<any[]>([]),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selectedPriority,setSelectedPriority]=useState(1),[professionPriority,setProfessionPriority]=useState(1);
 const load=async()=>{try{setInfo(await api<any>('/api/student-standard/targets'))}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);
 const grade=Number(info?.gradeLevel||0),isYks=grade===12||info?.enrollmentStatus==='GRADUATED',type=isYks?'YKS_PROGRAM':grade===8?'LGS_SCHOOL':null;
 const search=async()=>{if(!type||!q.trim())return;setBusy(true);setError('');try{const r=await api<any>(`/api/academic-targets/search?type=${type}&year=2026&q=${encodeURIComponent(q.trim())}`);setResults(r.targets||[])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const choose=async(targetId:string)=>{if(!type)return;setBusy(true);setError('');try{await api('/api/student-standard/targets',{method:'POST',body:JSON.stringify({targetType:type,targetId,priority:isYks?selectedPriority:1})});setResults([]);setQ('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const remove=async(id:string)=>{setBusy(true);try{await api(`/api/student-standard/targets/${id}`,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const chooseProfession=async(code:string)=>{setBusy(true);setError('');try{await api('/api/student-standard/professions',{method:'POST',body:JSON.stringify({professionCode:code,priority:professionPriority})});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const removeProfession=async(id:string)=>{setBusy(true);try{await api(`/api/student-standard/professions/${id}`,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const active=info?.targets||[],professions=info?.professions||[];
 return <><div className="page-head"><div><span className="eyebrow">Nibiru · Hedef yolculuğu</span><h1>🎯 Hedeflerim ve gelecek rotam</h1><p>{grade===8?'Hedef liseni ve hayalindeki meslekleri birlikte belirle.':isYks?'En fazla üç üniversite + bölüm ve üç meslek rotası seç.':'İlgi duyduğun meslekleri seç; Nibiru yalnız anlamlı anlarda bu rotayı hatırlatsın.'}</p></div><Target/></div>{error&&<div className="alert error">{error}</div>}
  {type?<><div className={`target-slot-grid ${isYks?'three':''}`}>{Array.from({length:isYks?3:1},(_,i)=>i+1).map(priority=>{const t=active.find((x:any)=>Number(x.priority)===priority);return <div className={`target-slot ${priority===1?'primary':''}`} key={priority}><span>{priority}. Akademik hedef</span>{t?<><h3>{label(t)}</h3><p>{t.target_type==='LGS_SCHOOL'?`${t.school_city||''} ${t.school_district||''}`:`${t.score_type||''} · Başarı sırası ${t.success_rank?.toLocaleString('tr-TR')||'—'}`}</p>{t.motivation_enabled&&t.motivation_label&&<div className="target-motivation">✨ {t.motivation_label}</div>}<button className="ghost" disabled={busy} onClick={()=>void remove(t.id)}><Trash2 size={15}/> Hedefi kaldır</button></>:<><GraduationCap size={30}/><h3>Hedef bekliyor</h3><p>Aşağıdan arayıp bu sıraya ekleyebilirsin.</p><button className={selectedPriority===priority?'primary':'ghost'} onClick={()=>setSelectedPriority(priority)}>Bu sıraya hedef seç</button></>}</div>})}</div><div className="panel"><div className="panel-head"><div><h2>{isYks?'Üniversite / bölüm ara':'Lise ara'}</h2><p>Doğrulanmış hedef havuzunda ara ve rotana ekle.</p></div><Search/></div>{isYks&&<div className="priority-picker">{[1,2,3].map(x=><button key={x} className={selectedPriority===x?'primary':'ghost'} onClick={()=>setSelectedPriority(x)}>{x}. hedef</button>)}</div>}<div style={{display:'flex',gap:8,marginTop:12}}><input style={{flex:1}} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder={isYks?'Örn. Cerrahpaşa Tıp, Boğaziçi Bilgisayar':'Okul adı, il veya ilçe'}/><button className="primary" disabled={busy||!q.trim()} onClick={()=>void search()}>Ara</button></div>{!!results.length&&<div className="table-card" style={{marginTop:14}}><table><thead><tr><th>{isYks?'Program':'Okul'}</th><th>{isYks?'Sıralama':'Yüzdelik'}</th><th>Puan</th><th>Kaynak</th><th></th></tr></thead><tbody>{results.map((t:any)=><tr key={t.id}><td><strong>{isYks?t.program_name:t.name}</strong><div className="muted">{isYks?`${t.university_name} · ${t.score_type}`:`${t.city} · ${t.district||''}`}</div></td><td>{isYks?(t.success_rank?.toLocaleString('tr-TR')||'—'):pct(t.percentile)}</td><td>{num(t.base_score)}</td><td>{t.source_url?<a href={t.source_url} target="_blank" rel="noreferrer">{t.source_title} <ExternalLink size={12}/></a>:'—'}</td><td><button className="ghost" disabled={busy} onClick={()=>void choose(t.id)}><CheckCircle2 size={15}/> Hedef yap</button></td></tr>)}</tbody></table></div>}</div></>:<div className="panel"><div className="empty">Bu sınıf düzeyinde lise/üniversite hedefi açılmaz; meslek ve ilgi rotanı aşağıdan oluşturabilirsin.</div></div>}
  <div className="panel profession-panel"><div className="panel-head"><div><h2>Hayalimdeki meslekler</h2><p>En fazla üç meslek seç. Birinci seçim ana rotandır; hitaplar sık tekrarlanmaz, yalnız ayarladığın motivasyon anlarında kullanılır.</p></div><Sparkles/></div><div className="priority-picker">{[1,2,3].map(x=><button key={x} className={professionPriority===x?'primary':'ghost'} onClick={()=>setProfessionPriority(x)}>{x}. meslek</button>)}</div><div className="profession-choice-grid">{(info?.professionCatalog||[]).map((item:any)=>{const chosen=professions.find((x:any)=>x.code===item.code);return <button key={item.code} className={chosen?'selected':''} disabled={busy} onClick={()=>void chooseProfession(item.code)}><span>{item.category}</span><strong>{item.title}</strong><small>{item.motivation_title}</small>{chosen&&<b>{chosen.priority}. seçim</b>}</button>})}</div>{!!professions.length&&<div className="profession-active">{professions.map((item:any)=><div key={item.id}><span>{item.priority}. rota</span><strong>{item.title}</strong><small>{item.motivation_title}</small><button className="ghost" onClick={()=>void removeProfession(item.id)}><Trash2 size={14}/> Kaldır</button></div>)}</div>}</div>
 </>
}
