import { useEffect,useState } from 'react';
import { ArrowLeft, BarChart3, Building2, ChevronRight, Globe2, MapPin, Network, Printer, School, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api';

export function StudentExamResults(){
 const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [detail,setDetail]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{setError('');try{const r=await api<any>('/api/platform/exam-center/results');setRows(r.results||[])}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const open=async(row:any)=>{setSelected(row);setDetail(null);setBusy(true);setError('');try{setDetail(await api<any>(`/api/platform/exam-center/${row.id}/result`))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(selected)return <><div className="page-head"><div><span className="eyebrow">Yayınlanmış Sonuç</span><h1>{selected.title}</h1><p>{[selected.publisher_name,selected.exam_type,selected.exam_date].filter(Boolean).join(' · ')}</p></div><div style={{display:'flex',gap:8}}><button className="ghost" onClick={()=>{setSelected(null);setDetail(null)}}><ArrowLeft size={16}/> Sonuçlara Dön</button>{detail&&<button className="primary" onClick={()=>window.print()}><Printer size={16}/> Yazdır / PDF</button>}</div></div>{error&&<div className="alert error">{error}</div>}{busy&&<div className="panel empty">Karne hazırlanıyor…</div>}{detail&&<ResultCard data={detail}/>}</>;
 return <><div className="page-head"><div><span className="eyebrow">Öğrenci</span><h1>Sonuçlarım</h1><p>Merkezi sınavlarda yayınlanan Türkiye, il, ilçe, kurum, sınıf ve şube sıralamalarını görüntüleyin.</p></div><Link className="secondary" to="/student-report"><BarChart3 size={16}/> Gelişim Raporum</Link></div>{error&&<div className="alert error">{error}</div>}
 <div className="panel central-results-intro"><Globe2 size={22}/><div><strong>Türkiye Geneli Katılımcılar Arasında</strong><p>Merkezi sıralamalar yalnız platform tarafından doğrulanıp sonuçları yayınlanan sınavlarda gösterilir. Sıralama, sınava katılan öğrencileri ifade eder.</p></div></div>
 <div className="result-list">{rows.map(r=><button className="result-list-card" key={`${r.id}-${r.snapshot_version}`} onClick={()=>void open(r)}><div><span className={`scope-badge ${String(r.scope||'institution').toLowerCase()}`}>{r.scope==='CENTRAL'?'Merkezi':r.scope==='NETWORK'?'Zincir':'Kurum'}</span><h3>{r.title}</h3><p>{[r.publisher_name,r.exam_type,r.exam_date].filter(Boolean).join(' · ')}</p></div><div className="result-list-score"><span>Net</span><strong>{fmt(r.net)}</strong>{r.score!=null&&<small>Puan {fmt(r.score)}</small>}</div><div className="result-list-rank"><span>Türkiye Geneli</span><strong>{rank(r.national_rank,r.national_count)}</strong></div><ChevronRight/></button>)}{!rows.length&&<div className="panel empty">Henüz yayınlanmış merkezi sınav sonucunuz bulunmuyor. Kurum içi sonuç ve gelişim raporları için “Gelişim Raporum”u kullanabilirsiniz.</div>}</div></>;
}
function ResultCard({data}:{data:any}){const r=data.result||{};const network=(r.networkRanks||[])[0];return <><div className="student-hero result-hero"><div><span>{data.rankingLabel||r.rankingLabel||'Sınav Katılımcıları Arasında'}</span><h2>{r.exam_title}</h2><p>{r.institution_name}{r.class_snapshot?` · ${r.class_snapshot}`:''}</p></div><div className="result-big"><div><span>Net</span><strong>{fmt(r.net)}</strong></div>{r.score!=null&&<div><span>Puan</span><strong>{fmt(r.score)}</strong></div>}</div></div>
 <div className="ranking-grid"><RankCard icon={<Globe2/>} title="Türkiye Geneli" rankValue={r.national_rank} total={r.national_count}/><RankCard icon={<MapPin/>} title={r.city||'İl'} rankValue={r.city_rank} total={r.city_count}/><RankCard icon={<MapPin/>} title={r.district||'İlçe'} rankValue={r.district_rank} total={r.district_count}/><RankCard icon={<Network/>} title={network?.network_name||'Kurum Ağı'} rankValue={network?.rank||r.network_rank} total={network?.participant_count||r.network_count}/><RankCard icon={<Building2/>} title="Kurum" rankValue={r.institution_rank} total={r.institution_count}/><RankCard icon={<School/>} title={r.grade_level?`${r.grade_level}. Sınıf`:'Sınıf'} rankValue={r.grade_rank} total={r.grade_count}/><RankCard icon={<Users/>} title={r.class_snapshot||'Şube'} rankValue={r.class_rank} total={r.class_count}/></div>
 <div className="panel"><div className="panel-head"><div><h2>Ders sonuçları</h2><p>Doğru, yanlış, boş, net ve başarı yüzdesi.</p></div></div><div className="table-card"><table><thead><tr><th>Ders</th><th>Doğru</th><th>Yanlış</th><th>Boş</th><th>Net</th><th>Başarı</th></tr></thead><tbody>{(r.subjects||[]).map((s:any)=><tr key={s.subject}><td><strong>{s.subject}</strong></td><td>{s.correct_count}</td><td>{s.wrong_count}</td><td>{s.blank_count}</td><td><strong>{fmt(s.net)}</strong></td><td>{s.success_percent!=null?`%${Number(s.success_percent).toFixed(1)}`:'—'}</td></tr>)}</tbody></table></div></div><div className="alert info">Türkiye / il / ilçe sıralamaları bu sınava katılan öğrenciler arasındaki karşılaştırmadır; ilgili bölgedeki tüm öğrencileri temsil ettiği iddia edilmez.</div></>}
function RankCard({icon,title,rankValue,total}:{icon:any;title:string;rankValue:any;total:any}){return <div className={`rank-card ${rankValue&&total?'':'muted-rank'}`}><div className="rank-icon">{icon}</div><span>{title}</span>{rankValue&&total?<><strong>{Number(rankValue).toLocaleString('tr-TR')}</strong><small>/ {Number(total).toLocaleString('tr-TR')} katılımcı</small></>:<strong>—</strong>}</div>}
function rank(r:any,t:any){return r&&t?`${Number(r).toLocaleString('tr-TR')} / ${Number(t).toLocaleString('tr-TR')}`:'—'}
function fmt(v:any){return v==null?'—':Number(v).toFixed(2)}
