import { useEffect,useState } from 'react';
import { Check,RotateCcw,Sparkles,Volume2 } from 'lucide-react';
import { api } from '../api';
import './student-standard.css';

export function StudentExperienceSettings(){
 const [data,setData]=useState<any>(null);const[themes,setThemes]=useState<any[]>([]);const[form,setForm]=useState<any>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
 const load=async()=>{try{const[r,experience]=await Promise.all([api<any>('/api/student-standard/preferences'),api<any>('/api/panel-experience')]);setData(r);setThemes(experience.allowedThemes||[]);const allowed=(experience.allowedThemes||[]).map((t:any)=>t.theme_key);setForm({...r.preferences,theme_key:allowed.includes(r.preferences.theme_key)?r.preferences.theme_key:experience.defaultTheme||'ANUNEX_STANDARD'})}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const save=async(next=form)=>{if(!next)return;setBusy(true);setError('');setMessage('');try{const r=await api<any>('/api/student-standard/preferences',{method:'PATCH',body:JSON.stringify(next)});setData(r);setForm(r.preferences);window.localStorage.setItem('anunex-panel-theme',r.preferences.theme_key);window.dispatchEvent(new Event('anunex-theme-change'));setMessage('Görünümün kaydedildi.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const reset=()=>{const next={theme_key:'ANUNEX_STANDARD',appearance:'AUTO',font_key:'SYSTEM',font_scale:1,animation_level:'NORMAL',countdown_enabled:1,countdown_flip_clock:1,motivation_enabled:1,voice_motivation_enabled:0,countdown_label:null,countdown_target_date:null,motivation_identity:null};setForm(next);void save(next)};
 if(!form)return error?<div className="alert error">{error}</div>:<div className="empty">Görünüm ayarları yükleniyor…</div>;
 return <>
  <div className="page-head"><div><span className="eyebrow">Benim alanım</span><h1>✨ Görünümümü Kişiselleştir</h1><p>Telefonundaki gibi sana uygun bir görünüm seç; istersen tek tuşla sınıf düzeyinin varsayılan tasarımına dön.</p></div></div>
  {error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}
  <div className="panel"><div className="panel-head"><div><h2>Tema</h2><p>Süper Admin’in kurumun ve öğrenci rolün için açtığı güvenli temalardan seçim yapabilirsin.</p></div></div><div className="theme-choice-grid">{themes.map(t=><button key={t.theme_key} className={`theme-choice ${form.theme_key===t.theme_key?'selected':''}`} onClick={()=>setForm({...form,theme_key:t.theme_key})}><span>{Number(t.is_standard)?'Standart':'Kurum tarafından açıldı'}</span><strong>{t.name}</strong><small>{t.description}</small>{form.theme_key===t.theme_key&&<Check/>}</button>)}</div></div>
  <div className="panel"><div className="panel-head"><div><h2>Okuma ve hareket</h2><p>Rahat okuyabildiğin görünümü ayarla.</p></div></div><div className="settings-grid"><label><span>Görünüm</span><select value={form.appearance} onChange={e=>setForm({...form,appearance:e.target.value})}><option value="AUTO">Cihaza göre</option><option value="LIGHT">Açık</option><option value="DARK">Koyu</option></select></label><label><span>Yazı boyutu · %{Math.round(Number(form.font_scale)*100)}</span><input type="range" min="0.85" max="1.30" step="0.05" value={form.font_scale} onChange={e=>setForm({...form,font_scale:Number(e.target.value)})}/></label><label><span>Animasyon</span><select value={form.animation_level} onChange={e=>setForm({...form,animation_level:e.target.value})}><option value="NORMAL">Normal</option><option value="REDUCED">Azaltılmış</option><option value="OFF">Kapalı</option></select></label></div></div>
  <div className="panel"><div className="panel-head"><div><h2>Hedef ve motivasyon</h2><p>Geri sayım ve motivasyon dilini sen kontrol edersin.</p></div><Sparkles/></div><div className="settings-grid"><label className="toggle-row"><input type="checkbox" checked={Boolean(form.countdown_enabled)} onChange={e=>setForm({...form,countdown_enabled:e.target.checked?1:0})}/><span>Hedef sınav geri sayımını göster</span></label><label className="toggle-row"><input type="checkbox" checked={Boolean(form.countdown_flip_clock)} onChange={e=>setForm({...form,countdown_flip_clock:e.target.checked?1:0})}/><span>Karta dokununca hedef rotasını göster</span></label><label className="toggle-row"><input type="checkbox" checked={Boolean(form.motivation_enabled)} onChange={e=>setForm({...form,motivation_enabled:e.target.checked?1:0})}/><span>Hedefe göre motive edici hitapları kullan</span></label><label className="toggle-row"><input type="checkbox" checked={Boolean(form.voice_motivation_enabled)} onChange={e=>setForm({...form,voice_motivation_enabled:e.target.checked?1:0})}/><Volume2 size={17}/><span>Sesli motivasyonlara izin ver</span></label></div></div>
  <div className="settings-actions"><button className="ghost" disabled={busy} onClick={reset}><RotateCcw size={16}/> Varsayılan temaya dön</button><button className="primary" disabled={busy} onClick={()=>void save()}><Check size={16}/> Kaydet</button></div>
 </>;
}
