import { useEffect,useState } from 'react';
import { ArrowDown,ArrowUp,CheckCircle2,ExternalLink,GraduationCap,ListChecks,Search,Target,Trash2 } from 'lucide-react';
import { api } from '../api';
import './student-standard.css';

function num(v:any){return v==null?'—':Number(v).toLocaleString('tr-TR',{maximumFractionDigits:2})}
function pct(v:any){return v==null?'—':`%${Number(v).toLocaleString('tr-TR',{maximumFractionDigits:3})}`}
function label(t:any){return t.target_type==='LGS_SCHOOL'?t.school_name:`${t.university_name} · ${t.program_name}`}
const initialFilters={year:'',city:'',district:'',schoolType:'',placementType:'',scoreType:'',universityType:'',scholarship:'',minScore:'',maxScore:'',minRank:'',maxRank:'',maxPercentile:''};

export function StudentTargetsV2(){
 const [info,setInfo]=useState<any>(null);const[results,setResults]=useState<any[]>([]);const[q,setQ]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[selectedPriority,setSelectedPriority]=useState(1);const[options,setOptions]=useState<any>(null);const[preference,setPreference]=useState<any>({items:[]});const[filters,setFilters]=useState(initialFilters);const[dataMessage,setDataMessage]=useState('');
 const load=async()=>{try{setInfo(await api<any>('/api/student-standard/targets'))}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);
 const grade=Number(info?.gradeLevel||0);const isYks=grade===12||info?.enrollmentStatus==='GRADUATED';const type=isYks?'YKS_PROGRAM':grade===8?'LGS_SCHOOL':null;
 const loadRobot=async(targetType:string,year?:string)=>{try{const suffix=year?`&year=${year}`:'';const[o,p]=await Promise.all([api<any>(`/api/academic-targets/preference/options?type=${targetType}${suffix}`),api<any>(`/api/academic-targets/preferences?type=${targetType}${suffix}`)]);setOptions(o);setPreference(p);if(!year&&o.year)setFilters(f=>({...f,year:String(o.year)}))}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(type)void loadRobot(type)},[type]);
 const search=async()=>{if(!type)return;setBusy(true);setError('');setDataMessage('');try{const p=new URLSearchParams({type,year:filters.year||String(options?.year||'')});if(q.trim())p.set('q',q.trim());for(const[k,v]of Object.entries(filters))if(k!=='year'&&v)p.set(k,v);const r=await api<any>(`/api/academic-targets/search?${p}`);setResults(r.targets||[]);setDataMessage(r.message||`${r.targets?.length||0} doğrulanmış kayıt bulundu.`)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const choose=async(targetId:string)=>{if(!type)return;setBusy(true);setError('');try{await api('/api/student-standard/targets',{method:'POST',body:JSON.stringify({targetType:type,targetId,priority:isYks?selectedPriority:1})});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const remove=async(id:string)=>{setBusy(true);try{await api(`/api/student-standard/targets/${id}`,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const addPreference=async(targetId:string)=>{if(!type)return;try{await api('/api/academic-targets/preferences',{method:'POST',body:JSON.stringify({targetType:type,targetId})});await loadRobot(type,filters.year)}catch(e:any){setError(e.message)}};
 const removePreference=async(id:string)=>{try{await api(`/api/academic-targets/preferences/${id}`,{method:'DELETE'});await loadRobot(type!,filters.year)}catch(e:any){setError(e.message)}};
 const move=async(index:number,direction:number)=>{const items=[...(preference.items||[])],next=index+direction;if(next<0||next>=items.length)return;[items[index],items[next]]=[items[next],items[index]];try{await api('/api/academic-targets/preferences/reorder',{method:'PATCH',body:JSON.stringify({itemIds:items.map((x:any)=>x.id)})});setPreference({...preference,items})}catch(e:any){setError(e.message)}};
 const active=info?.targets||[];
 if(info&&!type)return <><div className="page-head"><div><span className="eyebrow">Hedef ve Tercih Robotu</span><h1>Akademik Hedeflerim</h1><p>LGS hedefi 8. sınıfta; YKS üniversite ve bölüm hedefleri 12. sınıf/mezun öğrencilerde açılır.</p></div></div><div className="panel"><div className="empty">Bu sınıf düzeyinde hedef seçim alanı henüz aktif değil.</div></div></>;
 return <>
  <div className="page-head"><div><span className="eyebrow">Nibiru · Resmî veri destekli</span><h1>{isYks?'YKS Hedef ve Tercih Robotu':'LGS Hedef ve Tercih Robotu'}</h1><p>{isYks?'Üniversite, bölüm, şehir, puan türü ve başarı sırasına göre doğrulanmış programları ara.':'Okul, il, ilçe, puan ve yüzdelik dilime göre doğrulanmış liseleri ara.'}</p></div><Target/></div>
  {error&&<div className="alert error">{error}</div>}
  <div className={`alert ${options?.dataReady?'info':'warning'}`}><div><strong>{options?.dataReady?`${options.year} doğrulanmış veri havuzu hazır`:'Resmî veri dosyası bekleniyor'}</strong><span>{options?.dataReady?options.policy:'Sistem veri gelmeden okul/program, taban puan veya başarı sırası üretmez. Süper Admin resmî dosyayı yüklediğinde robot açılır.'}</span></div></div>
  <div className={`target-slot-grid ${isYks?'three':''}`}>{Array.from({length:isYks?3:1},(_,i)=>i+1).map(priority=>{const t=active.find((x:any)=>Number(x.priority)===priority);return <div className={`target-slot ${priority===1?'primary':''}`} key={priority}><span>{priority}. Hedef</span>{t?<><h3>{label(t)}</h3><p>{t.target_type==='LGS_SCHOOL'?`${t.school_city||''} ${t.school_district||''}`:`${t.score_type||''} · Başarı sırası ${t.success_rank?.toLocaleString('tr-TR')||'—'}`}</p>{t.motivation_enabled&&t.motivation_label&&<div className="target-motivation">✨ {t.motivation_label}</div>}<button className="ghost" disabled={busy} onClick={()=>void remove(t.id)}><Trash2 size={15}/> Hedefi kaldır</button></>:<><GraduationCap size={30}/><h3>Hedef bekliyor</h3><button className={selectedPriority===priority?'primary':'ghost'} onClick={()=>setSelectedPriority(priority)}>Bu sıraya hedef seç</button></>}</div>})}</div>
  <div className="panel"><div className="panel-head"><div><h2>Doğrulanmış resmî kayıtlarda ara</h2><p>Filtreler yalnız kaynak dosyasında bulunan alanları kullanır.</p></div><Search/></div>
   <div className="preference-filter-grid"><label>Veri yılı<select value={filters.year} onChange={e=>{const year=e.target.value;setFilters({...filters,year});void loadRobot(type!,year)}}>{(options?.years||[]).map((x:any)=><option key={x.year} value={x.year}>{x.year} · {x.row_count} kayıt</option>)}</select></label><label>Şehir<select value={filters.city} onChange={e=>setFilters({...filters,city:e.target.value})}><option value="">Tümü</option>{(options?.filters?.cities||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label>
   {isYks?<><label>Puan türü<select value={filters.scoreType} onChange={e=>setFilters({...filters,scoreType:e.target.value})}><option value="">Tümü</option>{(options?.filters?.scoreTypes||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label><label>Üniversite türü<select value={filters.universityType} onChange={e=>setFilters({...filters,universityType:e.target.value})}><option value="">Tümü</option>{(options?.filters?.universityTypes||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label><label>Burs<select value={filters.scholarship} onChange={e=>setFilters({...filters,scholarship:e.target.value})}><option value="">Tümü</option>{(options?.filters?.scholarships||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label><label>En iyi sıra<input type="number" value={filters.minRank} onChange={e=>setFilters({...filters,minRank:e.target.value})}/></label><label>En geniş sıra<input type="number" value={filters.maxRank} onChange={e=>setFilters({...filters,maxRank:e.target.value})}/></label></>:<><label>İlçe<input value={filters.district} onChange={e=>setFilters({...filters,district:e.target.value})}/></label><label>Okul türü<select value={filters.schoolType} onChange={e=>setFilters({...filters,schoolType:e.target.value})}><option value="">Tümü</option>{(options?.filters?.schoolTypes||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label><label>Yerleştirme<select value={filters.placementType} onChange={e=>setFilters({...filters,placementType:e.target.value})}><option value="">Tümü</option><option value="CENTRAL">Merkezî</option><option value="LOCAL">Yerel</option><option value="TALENT">Yetenek</option></select></label><label>En yüksek yüzdelik<input type="number" step="0.01" value={filters.maxPercentile} onChange={e=>setFilters({...filters,maxPercentile:e.target.value})}/></label></>}
   <label>En düşük puan<input type="number" value={filters.minScore} onChange={e=>setFilters({...filters,minScore:e.target.value})}/></label><label>En yüksek puan<input type="number" value={filters.maxScore} onChange={e=>setFilters({...filters,maxScore:e.target.value})}/></label></div>
   <div className="preference-search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder={isYks?'Üniversite, fakülte veya bölüm':'Okul adı, il veya ilçe'}/><button className="primary" disabled={busy||!options?.dataReady} onClick={()=>void search()}>{busy?'Aranıyor…':'Ara'}</button></div>{dataMessage&&<p className="muted">{dataMessage}</p>}
   {!!results.length&&<div className="table-card preference-results"><table><thead><tr><th>{isYks?'Program':'Okul'}</th><th>{isYks?'Sıralama':'Yüzdelik'}</th><th>Puan</th><th>Kaynak</th><th>İşlem</th></tr></thead><tbody>{results.map((t:any)=><tr key={t.id}><td><strong>{isYks?t.program_name:t.name}</strong><div className="muted">{isYks?`${t.university_name} · ${t.city||'Şehir bilgisi yok'} · ${t.score_type}`:`${t.city} · ${t.district||''}`}</div></td><td>{isYks?(t.success_rank?.toLocaleString('tr-TR')||'—'):pct(t.percentile)}</td><td>{num(t.base_score)}</td><td>{t.source_url?<a href={t.source_url} target="_blank" rel="noreferrer">{t.source_title} <ExternalLink size={12}/></a>:'—'}</td><td><div className="row-actions"><button className="ghost" onClick={()=>void addPreference(t.id)}><ListChecks size={15}/> Listeye ekle</button><button className="ghost" onClick={()=>void choose(t.id)}><CheckCircle2 size={15}/> {isYks?`${selectedPriority}. hedef`:'Hedefim'}</button></div></td></tr>)}</tbody></table></div>}
  </div>
  <div className="panel"><div className="panel-head"><div><h2>Tercih çalışma listem</h2><p>{preference.notice||'Bu liste resmî başvuru yerine geçmez.'}</p></div><ListChecks/></div><div className="preference-list">{(preference.items||[]).map((x:any,index:number)=><div key={x.id}><strong>{index+1}. {isYks?`${x.university_name} · ${x.program_name}`:x.school_name}</strong><span>{isYks?`${x.university_city||'—'} · ${x.score_type} · ${x.success_rank?.toLocaleString('tr-TR')||'—'} sıra`:`${x.school_city||''} · ${pct(x.school_percentile)}`}</span><div className="row-actions"><button className="ghost" disabled={index===0} onClick={()=>void move(index,-1)} title="Yukarı"><ArrowUp size={14}/></button><button className="ghost" disabled={index===(preference.items||[]).length-1} onClick={()=>void move(index,1)} title="Aşağı"><ArrowDown size={14}/></button><button className="ghost" onClick={()=>void removePreference(x.id)}><Trash2 size={14}/></button>{(isYks||!active.length)&&<button className="ghost" onClick={()=>void choose(x.university_program_target_id||x.secondary_school_target_id)}>Hedef yap</button>}</div></div>)}</div>{!(preference.items||[]).length&&<div className="empty">Arama sonuçlarından doğrulanmış kayıtları çalışma listene ekleyebilirsin.</div>}
  </div>
 </>;
}
