import { useEffect,useState } from 'react';
import { BookOpenCheck,BrainCircuit,CheckCircle2,ExternalLink,RefreshCw,Route,ShieldCheck,Sparkles,Target,Video,WandSparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api';

const bandLabel:Record<string,string>={STRONG:'Güçlü',STABLE:'Dengeli',DEVELOPING:'Gelişiyor',CRITICAL:'Öncelikli',INSUFFICIENT:'Kanıt bekliyor'};
function Count({label,value,detail}:{label:string;value:any;detail?:string}){return <div className="student-intelligence-kpi"><span>{label}</span><strong>{value??0}</strong>{detail&&<small>{detail}</small>}</div>}

export function StudentGrowthCenter(){
 const[profile,setProfile]=useState<any>(null);const[graph,setGraph]=useState<any>(null);const[recoveryPlans,setRecoveryPlans]=useState<any[]>([]);const[coach,setCoach]=useState<any>(null);const[history,setHistory]=useState<any[]>([]);const[tab,setTab]=useState('overview');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const load=async(refresh=false)=>{setBusy(true);setError('');try{const[p,g,r,c,h]=await Promise.all([api<any>('/api/student-intelligence/profile',{method:refresh?'POST':'GET'}),api<any>('/api/student-intelligence/learning-graph'),api<any>('/api/platform/recovery').catch(()=>({plans:[]})),api<any>('/api/nibiru/coach/daily-plan').catch(()=>({available:false})),api<any>('/api/student-intelligence/history')]);setProfile(p.profile);setGraph(g);setRecoveryPlans(r.plans||[]);setCoach(c);setHistory(h.history||[])}catch(e:any){setError(e.message||'Öğrenci zekâ profili yüklenemedi.')}finally{setBusy(false)}};useEffect(()=>{void load()},[]);
 const createRecovery=async()=>{setBusy(true);setError('');try{const r=await api<any>('/api/platform/recovery/generate',{method:'POST',body:JSON.stringify({title:'Kişisel Eksik Tamamlama Rotam'})});setNotice(`${r.stepCount} adımlık Recovery rotası hazırlandı.`);await load(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const createCoach=async()=>{setBusy(true);setError('');try{const r=await api<any>('/api/nibiru/coach/daily-plan',{method:'POST',body:'{}'});setCoach(r);setNotice(r.reused?'Bugünkü Nibiru planın zaten hazır.':'Bugünkü Nibiru eğitim koçu planın oluşturuldu.');await load(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const p=profile?.payload||{},overall=p.overall||{},loop=p.learningLoop||{},goal=p.goalMotivation||{},guidance=p.guidance||{};
 return <>
  <div className="page-head"><div><span className="eyebrow">TEK ÖĞRENCİ ZEKÂ PROFİLİ</span><h1>Gelişim Yolculuğum</h1><p>Öğrenme Grafiği, Recovery, rehberlik, Nibiru Koç, hedefler, görevler, Sıfır Hata ve onaylı video desteği aynı kanıt profilinde birleşir.</p></div><button className="ghost" disabled={busy} onClick={()=>void load(true)}><RefreshCw size={16}/> Profili Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="alert info"><ShieldCheck size={17}/><div><strong>Kanıt ve yetki sınırı</strong><br/>Bu profil yalnız doğrulanmış ölçme verisi ve yetkiniz kapsamındaki kayıtları birleştirir. Rehberlik sonuçları ancak gerçek rehber öğretmen incelemesinden sonra görünür; sayfa bağlamı akademik kanıt değildir.</div></div>
  <div className="student-intelligence-kpis"><Count label="Ustalık" value={overall.masteryScore==null?'—':`%${overall.masteryScore}`} detail={`${overall.evidenceCount||0} kanıt`}/><Count label="Kanıt güveni" value={`%${Math.round(Number(overall.academicConfidence||0)*100)}`} detail={`Kapsama %${Math.round(Number(overall.learningCoverage||0)*100)}`}/><Count label="Recovery" value={loop.recovery?.activeCount||0} detail="aktif rota"/><Count label="Koç görevleri" value={loop.tasks?.openPersonalTaskCount||0} detail={`${loop.coach?.pendingFollowupCount||0} takip adımı`}/><Count label="Sıfır Hata" value={loop.zeroError?.unresolvedItemCount||0} detail={`${loop.zeroError?.masteredItemCount||0} tamamlandı`}/><Count label="Onaylı video" value={loop.videos?.availableApprovedCount||0} detail="önceliklerle eşleşen"/></div>
  <div className="student-intelligence-tabs"><button className={tab==='overview'?'primary':'secondary'} onClick={()=>setTab('overview')}><Sparkles size={16}/> Genel Bakış</button><button className={tab==='learning'?'primary':'secondary'} onClick={()=>setTab('learning')}><Target size={16}/> Öğrenme Grafiği</button><button className={tab==='actions'?'primary':'secondary'} onClick={()=>setTab('actions')}><Route size={16}/> Gelişim Döngüsü</button><button className={tab==='guidance'?'primary':'secondary'} onClick={()=>setTab('guidance')}><BrainCircuit size={16}/> Hedef & Rehberlik</button></div>
  {tab==='overview'&&<div className="student-intelligence-grid"><div className="panel"><h2>Öncelikli gelişim alanları</h2>{!p.priorities?.length?<div className="empty-state compact">En az üç güvenilir kanıt oluştuğunda öncelikler burada görünür.</div>:<div className="intelligence-list">{p.priorities.slice(0,6).map((x:any)=><div key={x.nodeId}><span className={`status ${x.band==='CRITICAL'?'warn':'neutral'}`}>{bandLabel[x.band]||x.band}</span><div><strong>{x.subjectName} · {x.outcomeTitle}</strong><small>%{x.masteryScore} ustalık · {x.evidenceCount} kanıt · güven %{Math.round(x.confidence*100)}</small></div></div>)}</div>}</div><div className="panel"><h2>Kanıt kaynakları</h2><div className="intelligence-list">{(p.evidenceSources||[]).map((x:any)=><div key={x.key}><CheckCircle2/><div><strong>{x.label}</strong><small>{x.count} doğrulanmış sinyal/kayıt</small></div></div>)}</div></div><div className="panel"><h2>Profil sürümleri</h2><p className="muted">Yalnız profil gerçekten değiştiğinde yeni sürüm oluşur.</p><div className="intelligence-list">{history.slice(0,6).map(x=><div key={x.id}><span className="pill">v{x.profile_version}</span><div><strong>{x.mastery_score==null?'Yetersiz kanıt':`%${x.mastery_score} ustalık`}</strong><small>{x.created_at} · {x.exam_trend}</small></div></div>)}</div></div></div>}
  {tab==='learning'&&<div className="panel"><div className="panel-head"><div><h2>Öğrenme haritası</h2><p>Ustalık, güven ve kanıt sayısı birlikte değerlendirilir; tek sınavla kesin etiket üretilmez.</p></div><Target/></div>{!graph?.nodes?.length?<div className="empty-state">Henüz yeterli öğrenme kanıtı yok.</div>:<div className="feature-grid">{graph.nodes.slice(0,80).map((n:any)=><div className="feature-card" key={n.nodeId}><div><span className={`status ${n.band==='CRITICAL'?'warn':n.band==='STRONG'?'ok':'neutral'}`}>{bandLabel[n.band]||n.band}</span><h3>{n.subjectName} · {n.outcomeTitle}</h3><small>{n.evidenceCount} kanıt · güven %{Math.round(Number(n.confidence||0)*100)}</small></div><strong>%{n.masteryScore}</strong></div>)}</div>}</div>}
  {tab==='actions'&&<div className="student-intelligence-grid"><div className="panel"><div className="panel-head"><div><h2>Recovery rotaları</h2><p>Yanlış/boş → açıklama → pratik → yeniden ölçme.</p></div><Route/></div><button className="primary" disabled={busy} onClick={()=>void createRecovery()}><WandSparkles size={16}/> Yeni Recovery Oluştur</button><div className="intelligence-list">{(loop.recovery?.plans||recoveryPlans).slice(0,8).map((x:any)=><div key={x.id}><span className="status neutral">{x.status}</span><div><strong>{x.title}</strong><small>{x.done_count||0}/{x.step_count||0} adım · {x.available_count||0} hazır</small></div></div>)}</div></div><div className="panel"><div className="panel-head"><div><h2>Nibiru Eğitim Koçu</h2><p>Kişisel görev → 5–10 soruluk mini-test → yeniden ölçme → destek/ustalık.</p></div><Sparkles/></div>{!coach?.available?<button className="primary" disabled={busy} onClick={()=>void createCoach()}>Bugünkü Planı Oluştur</button>:<><strong>{coach.plan?.title}</strong><div className="intelligence-list">{(coach.items||[]).map((x:any)=><div key={x.id}><span className={`status ${x.completed?'ok':'neutral'}`}>{x.completed?'Tamamlandı':'Açık'}</span><div><strong>{x.payload?.label||x.reference_id}</strong><small>{x.latestMiniTest?`Mini-test: ${x.latestMiniTest.status}`:`${x.payload?.minutes||0} dk · ${x.payload?.questionTarget||0} soru`}</small></div></div>)}</div></>}</div><div className="panel"><h2>Sıfır Hata ve kişisel kitap</h2><div className="intelligence-list"><div><BookOpenCheck/><div><strong>{loop.zeroError?.unresolvedItemCount||0} çözülmemiş Sıfır Hata maddesi</strong><small>{loop.zeroError?.masteredItemCount||0} madde doğrulanarak tamamlandı</small></div></div><div><BookOpenCheck/><div><strong>{loop.personalBooks?.readyCount||0} hazır kişisel kitap</strong><small>Toplam {loop.personalBooks?.totalCount||0} aktif kitap kaydı</small></div></div></div><Link className="secondary" to="/my-books">Kitaplarımı aç</Link></div><div className="panel"><div className="panel-head"><div><h2>Onaylı video köprüsü</h2><p>Yalnız profil önceliğiyle eşleşen ve sistemde onaylı videolar gösterilir.</p></div><Video/></div><div className="intelligence-list">{(loop.videos?.items||[]).slice(0,8).map((x:any)=><div key={x.id}><Video/><div><strong>{x.subject_name} · {x.title}</strong><small>{x.outcome_title} · {x.duration_seconds?`${x.duration_seconds} sn`:'süre belirtilmedi'}</small></div><a href={x.url} target="_blank" rel="noreferrer" aria-label="Videoyu aç"><ExternalLink size={16}/></a></div>)}</div>{!loop.videos?.items?.length&&<div className="empty-state compact">Önceliklerle eşleşen onaylı video henüz yok.</div>}</div></div>}
  {tab==='guidance'&&<div className="student-intelligence-grid"><div className="panel"><div className="panel-head"><div><h2>Hedef ve motivasyon</h2><p>Motivasyon kimliği ve resmî hedefler aynı profilde, puan/sıra uydurmadan saklanır.</p></div><Target/></div>{goal.identity&&<div className="goal-identity">“{goal.identity}”</div>}<div className="intelligence-list">{(goal.targets||[]).map((x:any)=><div key={x.id}><span className="pill">{x.priority}. hedef</span><div><strong>{x.school_name||`${x.university_name||''} · ${x.program_name||''}`}</strong><small>{x.future_identity_label||'Motivasyon etiketi belirlenmedi'}</small></div></div>)}</div><Link className="secondary" to="/academic-target">Hedef ve Tercih Robotunu aç</Link></div><div className="panel"><div className="panel-head"><div><h2>Rehber öğretmen onaylı gelişim</h2><p>Ham yanıtlar bu profile girmez; yalnız incelenmiş eğitimsel gelişim sinyalleri kullanılır.</p></div><BrainCircuit/></div><div className="intelligence-list">{(guidance.dimensions||[]).map((x:any)=><div key={`${x.key}-${x.observedAt}`}><span className="pill">%{Math.round(x.score)}</span><div><strong>{x.instrumentTitle} · {x.key}</strong><small>{x.summary} · güven %{Math.round(x.confidence*100)}</small></div></div>)}</div>{!guidance.dimensions?.length&&<div className="empty-state compact">Rehber öğretmen tarafından incelenmiş gelişim sinyali henüz yok.</div>}<Link className="secondary" to="/guidance-tests">Rehberlik sürecini aç</Link></div></div>}
 </>;
}
