import { useEffect,useMemo,useState } from 'react';
import { CalendarRange,Check,Palette,ShieldCheck,Sparkles } from 'lucide-react';
import { api } from '../api';

const ROLE_LABELS:Record<string,string>={INSTITUTION_MANAGER:'Kurum Yöneticisi',TEACHER:'Öğretmen',GUIDANCE_TEACHER:'Rehber Öğretmen',STUDENT:'Öğrenci',PARENT:'Veli'};
const swatches:Record<string,string>={ANUNEX_STANDARD:'linear-gradient(135deg,#ffffff 0 65%,#315efb 65%)',ANUNEX_COSMIC:'linear-gradient(135deg,#06122f,#273b92,#8b5cf6)',ANUNEX_NEON:'linear-gradient(135deg,#051029,#315efb,#d946ef)',ANUNEX_FOCUS:'linear-gradient(135deg,#f8fafc,#dbeafe,#0f3d8b)'};

export function ThemeManagement(){
 const[data,setData]=useState<any>(null),[institutions,setInstitutions]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const[access,setAccess]=useState({institutionId:'',themeKey:'ANUNEX_STANDARD',role:'STUDENT',enabled:true});
 const[campaign,setCampaign]=useState({title:'',shortMessage:'',themeKey:'ANUNEX_STANDARD',accentColor:'#C51F2E',institutionId:'',role:'',startsAt:'',endsAt:'',priority:50});
 const load=async()=>{try{const[d,i]=await Promise.all([api<any>('/api/admin/panel-experience'),api<any>('/api/institutions')]);setData(d);setInstitutions(i.institutions||[]);if(!access.institutionId&&i.institutions?.[0])setAccess(x=>({...x,institutionId:i.institutions[0].id}))}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const activeThemes=useMemo(()=>(data?.themes||[]).filter((t:any)=>Number(t.active)===1),[data]);
 const toggleTheme=async(theme:any)=>{setBusy(true);setError('');setMessage('');try{await api(`/api/admin/panel-themes/${encodeURIComponent(theme.theme_key)}`,{method:'PATCH',body:JSON.stringify({active:!Number(theme.active)})});setMessage(`${theme.name} güncellendi.`);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const saveAccess=async()=>{setBusy(true);setError('');setMessage('');try{await api('/api/admin/panel-theme-access',{method:'POST',body:JSON.stringify(access)});setMessage('Kurum ve rol tema yetkisi kaydedildi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const saveCampaign=async()=>{setBusy(true);setError('');setMessage('');try{await api('/api/admin/special-day-experiences',{method:'POST',body:JSON.stringify({...campaign,startsAt:new Date(campaign.startsAt).toISOString(),endsAt:new Date(campaign.endsAt).toISOString(),institutionId:campaign.institutionId||null,role:campaign.role||null,themeKey:campaign.themeKey||null})});setMessage('Özel gün görünümü planlandı; bitiş tarihinde otomatik kapanacak.');setCampaign(x=>({...x,title:'',shortMessage:'',startsAt:'',endsAt:''}));await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const toggleCampaign=async(item:any)=>{setBusy(true);setError('');setMessage('');try{await api(`/api/admin/special-day-experiences/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({active:!Number(item.active)})});setMessage('Özel gün yayını güncellendi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <div className="role-dashboard theme-management-page">
  <section className="role-welcome"><div><span className="eyebrow">Süper Admin · Görsel yönetim</span><h1>Tema ve Özel Gün Merkezi</h1><p>Standart temayı koruyun, alternatifleri kurum ve rol bazında açın; özel gün görünümünü başlangıç ve bitiş tarihleriyle yayınlayın.</p></div><div className="role-welcome-icon"><Palette/></div></section>
  {error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}
  <section><div className="role-section-title"><div><span className="eyebrow">Tema kataloğu</span><h2>Sistemde kullanılabilecek temalar</h2><p>ANUNEX Standard her zaman aktiftir. Diğer üç seçenek Süper Admin açmadan kullanıcılara görünmez.</p></div><ShieldCheck/></div>
   <div className="theme-admin-grid">{(data?.themes||[]).map((theme:any)=><article className={`theme-admin-card ${Number(theme.active)?'active':''}`} key={theme.theme_key}><div className="theme-preview" style={{background:swatches[theme.theme_key]||swatches.ANUNEX_STANDARD}}><span>{Number(theme.is_standard)?'STANDARD':'ALTERNATİF'}</span>{Number(theme.active)&&<Check/>}</div><div><h3>{theme.name}</h3><p>{theme.description}</p></div><button className={Number(theme.active)?'secondary':'primary'} disabled={busy||Number(theme.is_standard)===1} onClick={()=>void toggleTheme(theme)}>{Number(theme.is_standard)?'Sürekli açık':Number(theme.active)?'Devre dışı bırak':'Etkinleştir'}</button></article>)}</div>
  </section>
  <section className="panel"><div className="panel-head"><div><h2>Kurum ve rol erişimi</h2><p>Aktif bir temayı yalnız seçtiğiniz kurum ve kullanıcı rolüne açın.</p></div><Palette/></div><div className="form-grid"><label>Kurum<select value={access.institutionId} onChange={e=>setAccess({...access,institutionId:e.target.value})}>{institutions.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Tema<select value={access.themeKey} onChange={e=>setAccess({...access,themeKey:e.target.value})}>{activeThemes.map((t:any)=><option value={t.theme_key} key={t.theme_key}>{t.name}</option>)}</select></label><label>Rol<select value={access.role} onChange={e=>setAccess({...access,role:e.target.value})}>{Object.entries(ROLE_LABELS).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label></div><label className="toggle-row"><input type="checkbox" checked={access.enabled} onChange={e=>setAccess({...access,enabled:e.target.checked})}/><span>Bu tema seçilen kurum ve rol için kullanılabilsin</span></label><div className="settings-actions"><button className="primary" disabled={busy||!access.institutionId} onClick={()=>void saveAccess()}>Erişimi Kaydet</button></div>
   {!!data?.access?.length&&<div className="table-card theme-access-table"><table><thead><tr><th>Kurum</th><th>Rol</th><th>Tema</th><th>Durum</th></tr></thead><tbody>{data.access.map((row:any)=><tr key={`${row.institution_id}-${row.role}-${row.theme_key}`}><td>{row.institution_name}</td><td>{ROLE_LABELS[row.role]||row.role}</td><td>{row.theme_name}</td><td><span className={`status ${Number(row.enabled)?'ok':'neutral'}`}>{Number(row.enabled)?'Açık':'Kapalı'}</span></td></tr>)}</tbody></table></div>}
  </section>
  <section className="panel"><div className="panel-head"><div><h2>Önemli gün görünümü</h2><p>Başlangıçta otomatik yayınlanır, bitişte eski temaya otomatik döner. MEB logosu kullanılmaz.</p></div><CalendarRange/></div><div className="form-grid"><label>Başlık<input value={campaign.title} maxLength={80} onChange={e=>setCampaign({...campaign,title:e.target.value})} placeholder="Örn. 29 Ekim Cumhuriyet Bayramı"/></label><label>Başlangıç<input type="datetime-local" value={campaign.startsAt} onChange={e=>setCampaign({...campaign,startsAt:e.target.value})}/></label><label>Bitiş<input type="datetime-local" value={campaign.endsAt} onChange={e=>setCampaign({...campaign,endsAt:e.target.value})}/></label><label>Hedef kurum<select value={campaign.institutionId} onChange={e=>setCampaign({...campaign,institutionId:e.target.value})}><option value="">Tüm kurumlar</option>{institutions.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Hedef rol<select value={campaign.role} onChange={e=>setCampaign({...campaign,role:e.target.value})}><option value="">Tüm roller</option>{Object.entries(ROLE_LABELS).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Özel tema<select value={campaign.themeKey} onChange={e=>setCampaign({...campaign,themeKey:e.target.value})}>{activeThemes.map((t:any)=><option value={t.theme_key} key={t.theme_key}>{t.name}</option>)}</select></label><label>Vurgu rengi<input type="color" value={campaign.accentColor} onChange={e=>setCampaign({...campaign,accentColor:e.target.value})}/></label><label className="span-2">Kısa mesaj<input value={campaign.shortMessage} maxLength={180} onChange={e=>setCampaign({...campaign,shortMessage:e.target.value})} placeholder="Kurumlara ve öğrencilere gösterilecek kısa mesaj"/></label></div><div className="settings-actions"><button className="primary" disabled={busy||!campaign.title||!campaign.shortMessage||!campaign.startsAt||!campaign.endsAt} onClick={()=>void saveCampaign()}><Sparkles size={17}/> Özel Günü Planla</button></div>
   {!!data?.campaigns?.length&&<div className="campaign-list">{data.campaigns.map((item:any)=><div className="campaign-item" key={item.id}><i style={{background:item.accent_color}}/><div><strong>{item.title}</strong><span>{item.institution_name||'Tüm kurumlar'} · {item.role?ROLE_LABELS[item.role]:'Tüm roller'} · {new Date(item.starts_at).toLocaleString('tr-TR')} – {new Date(item.ends_at).toLocaleString('tr-TR')}</span></div><div className="campaign-actions"><span className={`status ${Number(item.active)?'ok':'neutral'}`}>{Number(item.active)?'Planlandı':'Kapalı'}</span><button className="ghost" disabled={busy} onClick={()=>void toggleCampaign(item)}>{Number(item.active)?'Kapat':'Etkinleştir'}</button></div></div>)}</div>}
  </section>
 </div>
}
