import { useState } from 'react';
import { CheckCircle2, FileUp } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';
import { InstitutionSelect } from '../components/EntitySelectors';

export function Transfers(){const{user}=useAuth();const[file,setFile]=useState<File|null>(null);const[source,setSource]=useState('EDESIS');const[institutionId,setInstitutionId]=useState('');const[job,setJob]=useState<any>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const preview=async()=>{if(!file)return;setBusy(true);setError('');const fd=new FormData();fd.append('file',file);fd.append('sourceSystem',source);if(user?.role==='SUPER_ADMIN')fd.append('institutionId',institutionId);try{const r=await api<any>('/api/imports/preview',{method:'POST',body:fd});setJob(r)}catch(e){setError(e instanceof Error?e.message:'Aktarım okunamadı.')}finally{setBusy(false)}};
 const commit=async()=>{if(!job)return;setBusy(true);try{const r=await api<any>(`/api/imports/${job.importJobId}/commit`,{method:'POST'});setJob({...job,committed:r})}catch(e){setError(e instanceof Error?e.message:'Aktarım tamamlanamadı.')}finally{setBusy(false)}};
 return <><div className="page-head"><div><span className="eyebrow">Yıl ortası geçiş</span><h1>Veri Transfer Merkezi</h1><p>Edesis, Okulizyon veya başka sistemden gelen gerçek dışa aktarım dosyalarını önizleyerek içeri alın. Kaynak şeması uydurulmaz.</p></div></div><div className="panel transfer-form"><div className="form-grid"><label>Kaynak sistem<select value={source} onChange={e=>setSource(e.target.value)}><option>EDESIS</option><option>OKULIZYON</option><option>EXCEL_CSV</option><option>OTHER</option></select></label>{user?.role==='SUPER_ADMIN'&&<InstitutionSelect value={institutionId} onChange={setInstitutionId}/>}<label>Gerçek export dosyası<input type="file" accept=".csv,.txt,.xlsx,.xls,text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>Edesis/Okulizyon için ilk gerçek örnek eşleme incelemesine alınır; doğrulanmadan veri yazılmaz.</small></label></div><button className="primary" disabled={!file||busy||(user?.role==='SUPER_ADMIN'&&!institutionId)} onClick={preview}><FileUp size={17}/> {busy?'Analiz ediliyor…':'Önizleme Oluştur'}</button></div>{error&&<div className="alert error">{error}</div>}{job&&<div className="panel"><div className="panel-head"><div><h2>Aktarım önizlemesi</h2><p>Gerçek tablolara henüz yazılmadı.</p></div></div><div className="summary-strip"><Summary label="Toplam" value={job.summary.total}/><Summary label="Eşleşti" value={job.summary.matched}/><Summary label="Yeni" value={job.summary.new}/><Summary label="Kontrol" value={job.summary.review}/></div>{job.note&&<div className="alert info">{job.note}</div>}{job.committed?<div className="success-box"><CheckCircle2/><div><strong>Aktarım tamamlandı</strong><span>{job.committed.created} yeni öğrenci · {job.committed.reused} mevcut kayıt</span></div></div>:<button className="primary huge" onClick={commit} disabled={busy||job.summary.review>0}>{job.summary.review>0?'Önce Kontrol Gerekenleri Çöz':'AKTARIMI ONAYLA'}</button>}</div>}</>}
function Summary({label,value}:{label:string;value:number}){return <div className="summary"><span>{label}</span><strong>{value}</strong></div>}
