import {useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,Download,FileSpreadsheet,FileUp,History,RotateCcw,ShieldCheck,SkipForward} from 'lucide-react';
import {api,qs} from '../api';
import {useAuth} from '../auth';
import {InstitutionSelect} from '../components/EntitySelectors';

type ImportRow={id:string;row_no:number;match_status:string;resolution:string;source:any;mapped:any;issues:string[]};

export function Transfers(){
 const{user}=useAuth();const[file,setFile]=useState<File|null>(null);const[source,setSource]=useState('EXCEL_CSV');const[institutionId,setInstitutionId]=useState('');const[job,setJob]=useState<any>(null);const[history,setHistory]=useState<any[]>([]);const[students,setStudents]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const effectiveInstitution=user?.role==='SUPER_ADMIN'?institutionId:user?.institution_id||'';
 const loadHistory=async()=>{if(!effectiveInstitution)return;const r=await api<any>(`/api/imports${qs({institutionId:user?.role==='SUPER_ADMIN'?effectiveInstitution:null})}`);setHistory(r.jobs||[])};
 const loadStudents=async()=>{if(!effectiveInstitution)return;const r=await api<any>(`/api/students${qs({institutionId:user?.role==='SUPER_ADMIN'?effectiveInstitution:null})}`);setStudents(r.students||[])};
 useEffect(()=>{void Promise.all([loadHistory(),loadStudents()]).catch((e:any)=>setError(e.message))},[effectiveInstitution]);
 const openJob=async(id:string)=>{setBusy(true);setError('');try{setJob(await api<any>(`/api/imports/${id}`))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const preview=async()=>{if(!file)return;setBusy(true);setError('');setNotice('');const fd=new FormData();fd.append('file',file);fd.append('sourceSystem',source);if(user?.role==='SUPER_ADMIN')fd.append('institutionId',institutionId);try{const r=await api<any>('/api/imports/preview',{method:'POST',body:fd});await openJob(r.importJobId);setNotice('Önizleme hazır. Henüz gerçek öğrenci tablolarına yazılmadı.');await loadHistory()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const resolve=async(row:ImportRow,action:'SKIP'|'MATCH',studentId?:string)=>{setBusy(true);setError('');try{await api(`/api/imports/${job.job.id}/rows/${row.id}`,{method:'PATCH',body:JSON.stringify({action,studentId})});await openJob(job.job.id);await loadHistory()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const commit=async()=>{if(!job||!confirm('Önizlenen ve onaylanan satırlar gerçek öğrenci kayıtlarına aktarılsın mı?'))return;setBusy(true);setError('');try{const r=await api<any>(`/api/imports/${job.job.id}/commit`,{method:'POST',body:JSON.stringify({confirmed:true})});setNotice(`Aktarım tamamlandı: ${r.created||0} yeni, ${r.reused||0} mevcut, ${r.skipped||0} atlanan kayıt.`);await openJob(job.job.id);await loadHistory();await loadStudents()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const rollback=async()=>{if(!job||!confirm('Bu aktarımın oluşturduğu kayıtlar arşivlensin mi? Sınav geçmişi ve denetim kayıtları silinmez.'))return;setBusy(true);setError('');try{const r=await api<any>(`/api/imports/${job.job.id}/rollback`,{method:'POST',body:JSON.stringify({confirmed:true,reason:'Yönetici ekranından güvenli geri alma'})});setNotice(`Aktarım geri alındı. ${r.archivedStudents||0} öğrenci kaydı arşivlendi; akademik geçmiş korundu.`);await openJob(job.job.id);await loadHistory()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const rows:ImportRow[]=job?.rows||[];const summary=job?.job?.summary||job?.summary||{};
 return <>
  <div className="page-head"><div><span className="eyebrow">Anunex · Güvenli veri geçişi</span><h1>Veri Transfer Merkezi</h1><p>Edesis, Okulizyon, Excel/CSV ve TXT/DAT dosyalarını önce önizleyin. Açık onay verilmeden gerçek tablolara hiçbir kayıt yazılmaz.</p></div><ShieldCheck/></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel transfer-form"><div className="panel-head"><div><h2>1. Kaynak dosyayı doğrula</h2><p>CSV, TXT, DAT, XLSX ve XLS desteklenir. Tek aktarım en fazla 500 satır ve 10 MB olabilir.</p></div><FileSpreadsheet/></div><div className="form-grid"><label>Kaynak sistem<select value={source} onChange={e=>setSource(e.target.value)}><option value="EXCEL_CSV">Excel / CSV</option><option value="TXT_DAT">TXT / DAT</option><option value="EDESIS">Edesis</option><option value="OKULIZYON">Okulizyon</option><option value="OTHER">Diğer</option></select></label>{user?.role==='SUPER_ADMIN'&&<InstitutionSelect value={institutionId} onChange={setInstitutionId}/>}<label>Gerçek export dosyası<input type="file" accept=".csv,.txt,.dat,.xlsx,.xls,text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>Edesis/Okulizyon özel eşlemesi, anonimleştirilmiş gerçek örnek doğrulanmadan aktive edilmez.</small></label></div><button className="primary" disabled={!file||busy||(user?.role==='SUPER_ADMIN'&&!institutionId)} onClick={preview}><FileUp size={17}/> {busy?'Analiz ediliyor…':'Önizleme Oluştur'}</button></div>
  {job&&<div className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>2. Satır önizlemesi</h2><p>{job.job?.original_file_name||'Aktarım dosyası'} · {job.job?.effectiveStatus||job.job?.status}</p></div><a className="secondary" href={`/api/imports/${job.job.id}/error-report`}><Download size={16}/> Hata raporu</a></div><div className="summary-strip"><Summary label="Toplam" value={summary.total}/><Summary label="Eşleşti" value={summary.matched}/><Summary label="Yeni" value={summary.new}/><Summary label="Kontrol" value={summary.review}/><Summary label="Atlandı" value={summary.skipped}/></div>
   <div className="table-card transfer-preview-table"><table><thead><tr><th>Satır</th><th>Öğrenci</th><th>Sınıf</th><th>Eşleşme</th><th>Sorun / karar</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className={row.resolution==='SKIP'?'row-skipped':''}><td>{row.row_no}</td><td><strong>{row.source.name||'—'}</strong><div className="muted">No: {row.source.student_number||'—'}</div></td><td>{row.source.grade_level||'—'}/{row.source.section||'—'}</td><td><span className={`status ${['ACTIVE_MATCH','GUEST_MATCH'].includes(row.match_status)?'ok':row.match_status==='NEW_GUEST'?'neutral':'warn'}`}>{row.resolution==='SKIP'?'ATLANDI':row.match_status}</span></td><td>{row.issues?.length?row.issues.map(x=><div key={x} className="transfer-issue"><AlertTriangle size={13}/>{x}</div>):'Sorun yok'}</td><td>{job.job.status!=='COMMITTED'&&row.resolution!=='SKIP'&&<div className="transfer-row-actions"><button className="ghost" disabled={busy} onClick={()=>void resolve(row,'SKIP')}><SkipForward size={14}/> Atla</button>{['AMBIGUOUS','INVALID'].includes(row.match_status)&&<select defaultValue="" onChange={e=>{if(e.target.value)void resolve(row,'MATCH',e.target.value)}}><option value="">Mevcut öğrenciyle eşleştir…</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.grade_level}/{s.section} · {s.student_number||'No yok'}</option>)}</select>}</div>}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">Önizleme satırı bulunmuyor.</div>}</div>
   {job.job.effectiveStatus==='COMMITTED'?<button className="danger" disabled={busy} onClick={rollback}><RotateCcw size={16}/> Güvenli Geri Al</button>:job.job.effectiveStatus==='ROLLED_BACK'?<div className="success-box"><History/><div><strong>Aktarım geri alındı</strong><span>Oluşturulan kayıtlar arşivlendi; sınav ve denetim geçmişi korundu.</span></div></div>:<button className="primary huge" onClick={commit} disabled={busy||Number(summary.review)>0}>{Number(summary.review)>0?'Kontrol gereken satırları eşleştirin veya atlayın':'3. AKTARIMI ONAYLA VE UYGULA'}</button>}
  </div>}
  <div className="panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Aktarım geçmişi</h2><p>Önizleme, onay, tamamlama ve geri alma hareketleri denetim kaydıyla saklanır.</p></div><History/></div><div className="cards-list">{history.map(h=><button className="list-card transfer-history" key={h.id} onClick={()=>void openJob(h.id)}><div><strong>{h.original_file_name||h.source_system}</strong><span>{h.source_system} · {h.created_at}</span></div><span className={`status ${h.effectiveStatus==='COMMITTED'?'ok':h.effectiveStatus==='NEEDS_REVIEW'?'warn':'neutral'}`}>{h.effectiveStatus}</span></button>)}{!history.length&&<div className="empty">Henüz aktarım geçmişi yok.</div>}</div></div>
  <div className="alert info" style={{marginTop:16}}><CheckCircle2/><div><strong>Veri doğruluğu ilkesi</strong><br/>Kaynakta yalnız toplam net varsa soru veya kazanım ayrıntısı üretilmez. TXT/DAT içinde ham cevaplar ve doğrulanmış cevap anahtarı varsa eski sınavlar ayrıca değerlendirme akışında yeniden işlenebilir.</div></div>
 </>;
}
function Summary({label,value}:{label:string;value:number}){return <div className="summary"><span>{label}</span><strong>{Number(value||0)}</strong></div>}
