import { useEffect,useState } from 'react';
import { CalendarDays,CheckCircle2,RefreshCw,Save } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../auth';

export function WorksheetCalendar(){
 const{user}=useAuth();const[entries,setEntries]=useState<any[]>([]);const[grade,setGrade]=useState('');const[track,setTrack]=useState('');const[series,setSeries]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[dates,setDates]=useState<Record<string,string>>({});
 const load=async()=>{setError('');try{const r=await api<any>(`/api/worksheet-calendar?grade=${grade}&track=${track}&series=${series}`);setEntries(r.entries||[]);const d:Record<string,string>={};for(const x of r.entries||[])if(x.planned_date)d[x.id]=String(x.planned_date).slice(0,10);setDates(d)}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[grade,track,series]);
 const save=async(x:any)=>{const plannedDate=dates[x.id];if(!plannedDate)return;setBusy(true);try{await api('/api/worksheet-calendar',{method:'POST',body:JSON.stringify({id:x.calendar_id||undefined,worksheetId:x.id,plannedDate,plannedWeek:x.series_sequence_no||x.sequence_no})});setNotice('Föy takvimi kaydedildi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const apply=async(x:any)=>{if(!x.calendar_id)return;setBusy(true);try{await api(`/api/worksheet-calendar/${x.calendar_id}/apply`,{method:'POST',body:'{}'});setNotice('Föy uygulandı olarak işaretlendi.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const canPlan=user?.role==='SUPER_ADMIN'||user?.role==='INSTITUTION_MANAGER';
 return <>
  <div className="page-head"><div><span className="eyebrow">Akademik Takvim</span><h1>📅 Föy Takvimi</h1><p>Planlanan uygulama tarihi, gerçek uygulama tarihi, kazanımlar, cevap/çözüm içeriği ve sınıf uygulama durumu tek ekranda izlenir.</p></div><button className="ghost" onClick={()=>void load()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel"><div className="panel-head"><div><h2>Takvim filtresi</h2><p>Öğretmen yalnız yetki alanındaki içeriği görür; kurum yöneticisi yıllık planı düzenleyebilir.</p></div><CalendarDays/></div><div className="form-grid"><label>Seri<select value={series} onChange={e=>setSeries(e.target.value)}><option value="">Tümü</option><option value="BLUE">Mavi Seri · 10 soru</option><option value="RED">Kırmızı Seri · 20 soru</option></select></label><label>Sınıf düzeyi<select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Tümü</option>{[5,6,7,8,9,10,11,12].map(g=><option key={g} value={g}>{g}. sınıf</option>)}</select></label><label>Program<select value={track} onChange={e=>setTrack(e.target.value)}><option value="">Tümü</option><option value="NUMERIC">Sayısal</option><option value="VERBAL">Sözel</option></select></label></div></div>
  <div className="table-card"><table><thead><tr><th>Hafta / Föy</th><th>Dersler</th><th>Kazanımlar</th><th>Planlanan</th><th>Gerçek</th><th>İçerik</th><th>Durum</th><th></th></tr></thead><tbody>{entries.map((x:any)=>{const sequence=x.series_sequence_no||x.sequence_no;return <tr key={`${x.id}-${x.calendar_id||'global'}`}><td><strong><span className={`worksheet-series ${x.series_code==='RED'?'red':'blue'}`}>{x.series_code==='RED'?'Kırmızı':'Mavi'}</span> Föy {sequence} · {x.title}</strong><div className="muted">{x.grade_level}. sınıf · {x.track==='NUMERIC'?'Sayısal':'Sözel'} · ders başına {x.questions_per_subject||10} soru{x.class_name?` · ${x.class_name}`:''}</div></td><td>{(x.subjects||[]).join(', ')||'—'}</td><td><div style={{maxWidth:360}}>{(x.outcomes||[]).slice(0,4).join(' · ')||'Kazanım eşleşmesi bekleniyor'}{(x.outcomes||[]).length>4&&<span className="muted"> +{x.outcomes.length-4}</span>}</div></td><td>{canPlan?<input type="date" value={dates[x.id]||''} onChange={e=>setDates(p=>({...p,[x.id]:e.target.value}))}/>:x.planned_date||`Hafta ${sequence}`}</td><td>{x.actual_date||'—'}</td><td>{x.asset_count||0} dosya · {x.solution_count||0} çözüm</td><td><span className={`status ${x.calendar_status==='APPLIED'?'ok':'neutral'}`}>{x.calendar_status||'PLANLANMADI'}</span></td><td style={{whiteSpace:'nowrap'}}>{canPlan&&<button className="ghost" disabled={busy||!dates[x.id]} onClick={()=>void save(x)}><Save size={14}/> Kaydet</button>}{x.calendar_id&&x.calendar_status!=='APPLIED'&&user?.role!=='STUDENT'&&<button className="ghost" disabled={busy} onClick={()=>void apply(x)}><CheckCircle2 size={14}/> Uygulandı</button>}</td></tr>})}</tbody></table>{!entries.length&&<div className="empty">Filtreye uygun yayımlanmış föy bulunmuyor.</div>}</div>
  <div className="alert info" style={{marginTop:16}}><strong>Nibiru bağlantısı:</strong> Nibiru “Bu hafta hangi föyü uygulamalıyım?” sorusunda yıllık takvim, son sınavlardaki kazanım eksikleri ve uygulanmış föyleri birlikte değerlendirecek.</div>
 </>;
}
