import { useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, CheckCircle2, CircleAlert, FileUp, RefreshCw, Save, Send } from 'lucide-react';
import { api, qs } from '../api';

type Track='NUMERIC'|'VERBAL';
type ProgramCode='SCHOOL'|'TYT'|'AYT';
type SubjectDraft={subjectId:string;questionCount:number;outcomeIds:string[]};
type LinkDraft={subjectId:string;questionNo:number;outcomeId:string;solutionUrl:string;topicUrl:string};

export function WorksheetAdmin(){
 const[year,setYear]=useState('2026-2027');const[program,setProgram]=useState<ProgramCode>('SCHOOL');const[grade,setGrade]=useState(7);const[numericCount,setNumericCount]=useState(16);const[verbalCount,setVerbalCount]=useState(16);
 const[rows,setRows]=useState<any[]>([]);const[options,setOptions]=useState<any>({subjects:[],outcomes:[]});const[selectedId,setSelectedId]=useState('');const[detail,setDetail]=useState<any>(null);const[subjects,setSubjects]=useState<SubjectDraft[]>([]);const[links,setLinks]=useState<LinkDraft[]>([]);const[assetType,setAssetType]=useState('PDF');const[asset,setAsset]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const loadRows=async()=>{const r=await api<any>(`/api/worksheet-admin${qs({academicYear:year,programCode:program})}`);setRows(r.worksheets||[])};
 const loadOptions=async()=>{const r=await api<any>(`/api/worksheet-admin/options${qs({gradeLevel:program==='SCHOOL'?grade:null})}`);setOptions(r)};
 const loadDetail=async(id:string)=>{if(!id){setDetail(null);return}const r=await api<any>(`/api/worksheet-admin/${id}`);setDetail(r);setSubjects((r.subjects||[]).map((s:any)=>({subjectId:s.subject_id,questionCount:Number(s.question_count),outcomeIds:(r.outcomes||[]).filter((o:any)=>o.subject_id===s.subject_id).map((o:any)=>o.outcome_id)})));setLinks((r.questionLinks||[]).map((q:any)=>({subjectId:q.subject_id,questionNo:Number(q.question_no),outcomeId:q.outcome_id||'',solutionUrl:q.solution_url||'',topicUrl:q.topic_url||''})))};
 useEffect(()=>{void Promise.all([loadRows(),loadOptions()]).catch(e=>setError(e.message))},[year,program,grade]);useEffect(()=>{if(selectedId)void loadDetail(selectedId).catch(e=>setError(e.message))},[selectedId]);
 const generate=async()=>{setBusy(true);setError('');setNotice('');try{const r=await api<any>('/api/worksheet-admin/generate-slots',{method:'POST',body:JSON.stringify({academicYear:year,programCode:program,gradeLevel:program==='SCHOOL'?grade:null,numericCount,verbalCount})});setNotice(`${r.created} föy taslağı oluşturuldu, ${r.skipped} mevcut slot atlandı.`);await loadRows()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const toggleSubject=(id:string,on:boolean)=>setSubjects(cur=>on?[...cur,{subjectId:id,questionCount:20,outcomeIds:[]}]:cur.filter(x=>x.subjectId!==id));
 const patchSubject=(id:string,patch:Partial<SubjectDraft>)=>setSubjects(cur=>cur.map(x=>x.subjectId===id?{...x,...patch}:x));
 const toggleOutcome=(subjectId:string,outcomeId:string,on:boolean)=>setSubjects(cur=>cur.map(x=>x.subjectId===subjectId?{...x,outcomeIds:on?[...new Set([...x.outcomeIds,outcomeId])]:x.outcomeIds.filter(i=>i!==outcomeId)}:x));
 const saveStructure=async()=>{if(!selectedId)return;setBusy(true);setError('');setNotice('');try{const r=await api<any>(`/api/worksheet-admin/${selectedId}/structure`,{method:'PUT',body:JSON.stringify({subjects})});setNotice('Ders, soru sayısı ve kazanımlar kaydedildi.');await loadDetail(selectedId);await loadRows();if(r.readiness?.errors?.length)setNotice('Yapı kaydedildi; yayın için eksikler devam ediyor.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const buildLinks=()=>{const out:LinkDraft[]=[];for(const s of subjects){for(let n=1;n<=Number(s.questionCount);n++){const old=links.find(x=>x.subjectId===s.subjectId&&x.questionNo===n);out.push(old||{subjectId:s.subjectId,questionNo:n,outcomeId:s.outcomeIds[0]||'',solutionUrl:'',topicUrl:''})}}setLinks(out)};
 const patchLink=(subjectId:string,q:number,patch:Partial<LinkDraft>)=>setLinks(cur=>cur.map(x=>x.subjectId===subjectId&&x.questionNo===q?{...x,...patch}:x));
 const saveLinks=async()=>{if(!selectedId)return;setBusy(true);setError('');setNotice('');try{await api(`/api/worksheet-admin/${selectedId}/question-links`,{method:'PUT',body:JSON.stringify({entries:links})});setNotice('Soru-kazanım ve video bağlantıları kaydedildi.');await loadDetail(selectedId);await loadRows()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const upload=async()=>{if(!selectedId||!asset)return;setBusy(true);setError('');setNotice('');try{const fd=new FormData();fd.append('file',asset);fd.append('assetType',assetType);await api(`/api/worksheet-admin/${selectedId}/assets`,{method:'POST',body:fd});setNotice('Dosya R2 alanına kaydedildi.');setAsset(null);await loadDetail(selectedId);await loadRows()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const setStatus=async(status:'DRAFT'|'REVIEW'|'PUBLISHED'|'ARCHIVED')=>{if(!selectedId)return;if(status==='PUBLISHED'&&!confirm('Föy yayınlansın mı? Yayından sonra içerik kilitlenecektir.'))return;setBusy(true);setError('');setNotice('');try{await api(`/api/worksheet-admin/${selectedId}/status`,{method:'PATCH',body:JSON.stringify({status})});setNotice(`Föy durumu ${status} olarak güncellendi.`);await loadDetail(selectedId);await loadRows()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const selectedSubjectIds=useMemo(()=>new Set(subjects.map(x=>x.subjectId)),[subjects]);
 return <>
  <div className="page-head"><div><span className="eyebrow">Föy Yönetim Merkezi</span><h1>Yıllık föy planı ve yayın akışı</h1><p>5–11. sınıflar ile TYT/AYT için 16 Sayısal + 16 Sözel varsayılan plan oluşturun; resmî kazanımlar, PDF, cevap anahtarı ve video bağlantıları tamamlanmadan yayınlamayın.</p></div><button className="ghost" onClick={()=>void loadRows()}><RefreshCw size={16}/> Yenile</button></div>
  {error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
  <div className="panel"><div className="panel-head"><div><h2>Yıllık plan oluştur</h2><p>İçerik oluşturmaz; yalnız yayınlanacak föy slotlarını açar.</p></div><BookOpenCheck/></div><div className="form-grid"><label>Akademik yıl<input value={year} onChange={e=>setYear(e.target.value)}/></label><label>Program<select value={program} onChange={e=>setProgram(e.target.value as ProgramCode)}><option value="SCHOOL">5–11 Okul</option><option value="TYT">TYT</option><option value="AYT">AYT</option></select></label>{program==='SCHOOL'&&<label>Sınıf<input type="number" min="5" max="11" value={grade} onChange={e=>setGrade(Number(e.target.value))}/></label>}<label>Sayısal adet<input type="number" min="0" max="32" value={numericCount} onChange={e=>setNumericCount(Number(e.target.value))}/></label><label>Sözel adet<input type="number" min="0" max="32" value={verbalCount} onChange={e=>setVerbalCount(Number(e.target.value))}/></label></div><button className="primary" disabled={busy} onClick={generate}>Yıllık Slotları Oluştur</button></div>
  <div className="table-card" style={{marginTop:20}}><table><thead><tr><th>Föy</th><th>Program</th><th>Durum</th><th>Ders</th><th>Soru</th><th>Kazanım</th><th>Dosya</th><th></th></tr></thead><tbody>{rows.map(w=><tr key={w.id}><td><strong>{w.title}</strong><br/><small>{w.track==='NUMERIC'?'Sayısal':'Sözel'} {w.sequence_no}</small></td><td>{w.program_code}{w.grade_level?` · ${w.grade_level}. sınıf`:''}</td><td><span className={`status ${w.status==='PUBLISHED'?'ok':w.status==='REVIEW'?'warn':'neutral'}`}>{w.status}</span></td><td>{w.subjects||'—'}</td><td>{w.total_questions||0}</td><td>{w.outcome_count||0}</td><td>PDF {w.pdf_count||0} · Cevap {w.answer_key_count||0}</td><td><button className="ghost" onClick={()=>setSelectedId(w.id)}>Düzenle</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">Bu filtrede föy bulunmuyor.</div>}</div>
  {detail&&<>
   <div className="section-head"><div><h2>{detail.worksheet.title}</h2><p>{detail.worksheet.status} · yayın kontrolü {detail.readiness?.ready?'hazır':'eksik'}</p></div><div style={{display:'flex',gap:8}}>{detail.worksheet.status!=='PUBLISHED'&&<button className="secondary" onClick={()=>setStatus('REVIEW')} disabled={busy}>İncelemeye Al</button>}{detail.worksheet.status!=='PUBLISHED'&&<button className="primary" onClick={()=>setStatus('PUBLISHED')} disabled={busy||!detail.readiness?.ready}><Send size={16}/> Yayınla</button>}{detail.worksheet.status==='PUBLISHED'&&<button className="secondary" onClick={()=>setStatus('DRAFT')} disabled={busy}>Taslağa Geri Al</button>}</div></div>
   <div className="summary-strip"><Ready label="Ders" ok={(detail.subjects||[]).length>0}/><Ready label="Resmî Kazanım" ok={(detail.readiness?.errors||[]).every((x:string)=>!x.toLowerCase().includes('kazanım')&&!x.toLowerCase().includes('müfredat'))}/><Ready label="PDF" ok={(detail.assets||[]).some((a:any)=>a.asset_type==='PDF')}/><Ready label="Cevap Anahtarı" ok={(detail.assets||[]).some((a:any)=>a.asset_type==='ANSWER_KEY')}/><Ready label="Video" ok={detail.readiness?.solutionCount===detail.readiness?.totalQuestions&&detail.readiness?.topicCount===detail.readiness?.totalQuestions}/></div>
   {!detail.readiness?.ready&&<div className="panel warning-panel" style={{marginTop:16}}><CircleAlert/><div><h3>Yayın için tamamlanacaklar</h3><ul>{(detail.readiness?.errors||[]).map((x:string)=><li key={x}>{x}</li>)}</ul></div></div>}
   {detail.worksheet.status!=='PUBLISHED'&&<div className="panel" style={{marginTop:20}}><div className="panel-head"><div><h2>1. Dersler ve resmî kazanımlar</h2><p>Resmî/verifiye edilmemiş kazanım seçilebilir ama PUBLISHED durumuna geçemez.</p></div></div><div className="cards-list">{options.subjects.map((s:any)=>{const cfg=subjects.find(x=>x.subjectId===s.id);const outs=options.outcomes.filter((o:any)=>o.subject_id===s.id);return <div className="list-card" key={s.id} style={{display:'block'}}><div style={{display:'flex',alignItems:'center',gap:10}}><input type="checkbox" checked={selectedSubjectIds.has(s.id)} onChange={e=>toggleSubject(s.id,e.target.checked)}/><strong>{s.name}</strong>{cfg&&<label className="compact-field" style={{marginLeft:'auto'}}>Soru<input type="number" min="1" max="100" value={cfg.questionCount} onChange={e=>patchSubject(s.id,{questionCount:Number(e.target.value)})}/></label>}</div>{cfg&&<div style={{marginTop:10,display:'grid',gap:6}}>{outs.map((o:any)=><label key={o.id} style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={cfg.outcomeIds.includes(o.id)} onChange={e=>toggleOutcome(s.id,o.id,e.target.checked)}/><span>{o.topic?`${o.topic} · `:''}{o.title}</span><small>{o.official&&o.curriculum_verified?'Resmî ✓':'Doğrulama gerekli'}</small></label>)}{!outs.length&&<small>Bu ders/sınıf için kazanım verisi yok.</small>}</div>}</div>})}</div><button className="primary" onClick={saveStructure} disabled={busy||!subjects.length}><Save size={16}/> Yapıyı Kaydet</button></div>}
   {detail.worksheet.status!=='PUBLISHED'&&<div className="panel" style={{marginTop:20}}><div className="panel-head"><div><h2>2. PDF ve cevap anahtarı</h2><p>Dosyalar R2'de tutulur; D1 yalnız metadata saklar.</p></div><FileUp/></div><div className="form-grid"><label>Tür<select value={assetType} onChange={e=>setAssetType(e.target.value)}><option value="PDF">Föy PDF</option><option value="ANSWER_KEY">Cevap Anahtarı PDF</option><option value="OTHER">Diğer</option></select></label><label>Dosya<input type="file" accept={assetType==='OTHER'?undefined:'.pdf,application/pdf'} onChange={e=>setAsset(e.target.files?.[0]||null)}/></label></div><button className="secondary" disabled={!asset||busy} onClick={upload}><FileUp size={16}/> Yükle</button><div className="cards-list" style={{marginTop:12}}>{(detail.assets||[]).map((a:any)=><div className="list-card" key={a.id}><div><strong>{a.asset_type}</strong><span>{a.file_name}</span></div></div>)}</div></div>}
   {detail.worksheet.status!=='PUBLISHED'&&<div className="panel" style={{marginTop:20}}><div className="panel-head"><div><h2>3. Soru → kazanım → video</h2><p>Her soru için çözüm videosu ve konu tekrar bağlantısı tanımlanır.</p></div><button className="secondary" onClick={buildLinks}>Soru Satırlarını Hazırla</button></div>{links.length>0&&<div style={{overflowX:'auto'}}><table><thead><tr><th>Ders</th><th>Soru</th><th>Kazanım</th><th>Çözüm URL</th><th>Konu URL</th></tr></thead><tbody>{links.map(l=>{const sub=options.subjects.find((s:any)=>s.id===l.subjectId);const outs=options.outcomes.filter((o:any)=>o.subject_id===l.subjectId);return <tr key={`${l.subjectId}-${l.questionNo}`}><td>{sub?.name||l.subjectId}</td><td>{l.questionNo}</td><td><select value={l.outcomeId} onChange={e=>patchLink(l.subjectId,l.questionNo,{outcomeId:e.target.value})}><option value="">Seçiniz</option>{outs.map((o:any)=><option key={o.id} value={o.id}>{o.title}</option>)}</select></td><td><input value={l.solutionUrl} onChange={e=>patchLink(l.subjectId,l.questionNo,{solutionUrl:e.target.value})} placeholder="https://..."/></td><td><input value={l.topicUrl} onChange={e=>patchLink(l.subjectId,l.questionNo,{topicUrl:e.target.value})} placeholder="https://..."/></td></tr>})}</tbody></table></div>}<button className="primary" disabled={busy||!links.length} onClick={saveLinks}><Save size={16}/> Soru Bağlantılarını Kaydet</button></div>}
  </>}
 </>;
}
function Ready({label,ok}:{label:string;ok:boolean}){return <div className={ok?'summary':'summary warn'}><span>{label}</span><strong>{ok?<CheckCircle2 size={18}/>:<CircleAlert size={18}/>}</strong></div>}
