import { useEffect,useState } from 'react';
import { CheckCircle2,ChevronRight,RotateCcw } from 'lucide-react';
import { api } from '../api';
import { OutcomeMiniTestCatalog } from './OutcomeMiniTestCatalog';

type Props={plan:any;showCatalog?:boolean};

function optionEntries(value:any):Array<[string,string]>{
 if(Array.isArray(value))return value.map((x,i)=>{const key=String.fromCharCode(65+i);if(x&&typeof x==='object')return[String(x.key||x.code||key),String(x.text||x.label||x.value||'')];return[key,String(x??'')]});
 if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>[k,String(v??'')]);
 return[];
}

export function CoachPlanCard({plan:initial,showCatalog=false}:Props){
 const[plan,setPlan]=useState(initial);const[test,setTest]=useState<any>(null);const[answers,setAnswers]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[repeatItem,setRepeatItem]=useState<any>(null);const[repeatConsent,setRepeatConsent]=useState(false);
 useEffect(()=>setPlan(initial),[initial]);
 const refresh=async()=>{const fresh=await api<any>('/api/nibiru/coach/daily-plan');if(fresh.available)setPlan(fresh)};
 const openTest=async(testId:string)=>{setBusy(true);setError('');try{const detail=await api<any>(`/api/nibiru/coach/mini-tests/${encodeURIComponent(testId)}`);setTest(detail);setAnswers(Object.fromEntries((detail.questions||[]).filter((q:any)=>q.student_answer).map((q:any)=>[q.question_id,q.student_answer])))}catch(e:any){setError(e.message||'Mini-test açılamadı.')}finally{setBusy(false)}};
 const startTest=async(item:any,mode:'NEW'|'REPEAT'='NEW')=>{setBusy(true);setError('');setNotice('');try{const started=await api<any>(`/api/nibiru/coach/items/${encodeURIComponent(item.id)}/mini-test`,{method:'POST',body:JSON.stringify({mode,repeatConsent:mode==='REPEAT'&&repeatConsent})});setRepeatItem(null);setRepeatConsent(false);await openTest(started.testId)}catch(e:any){setError(e.message||'Mini-test başlatılamadı.')}finally{setBusy(false)}};
 const completeSimple=async(item:any)=>{setBusy(true);setError('');try{await api(`/api/nibiru/coach/items/${encodeURIComponent(item.id)}/complete`,{method:'PATCH',body:JSON.stringify({completed:true})});await refresh()}catch(e:any){setError(e.message||'Görev güncellenemedi.')}finally{setBusy(false)}};
 const submit=async()=>{if(!test?.test?.id)return;setBusy(true);setError('');setNotice('');try{const payload=await api<any>(`/api/nibiru/coach/mini-tests/${encodeURIComponent(test.test.id)}/submit`,{method:'POST',body:JSON.stringify({answers:Object.entries(answers).map(([questionId,answer])=>({questionId,answer}))})});setTest(payload.detail);setNotice(payload.detail?.test?.selection_mode==='REPEAT'?'Tekrar çalışması kaydedildi. Bu sonuç yeni öğrenme kanıtı olarak kullanılmaz.':payload.result?.passed?'Kazanım doğrulandı ve tamamlandı.':'Yeniden ölçüm tamamlandı. Destek adımından sonra yeni mini-test açılacak.');await refresh()}catch(e:any){setError(e.message||'Mini-test gönderilemedi.')}finally{setBusy(false)}};
 const completeFollowup=async(action:any)=>{setBusy(true);setError('');try{await api(`/api/nibiru/coach/followups/${encodeURIComponent(action.id)}/complete`,{method:'PATCH',body:'{}'});await openTest(action.test_id||test.test.id)}catch(e:any){setError(e.message||'Destek adımı güncellenemedi.')}finally{setBusy(false)}};
 const items=plan?.items||[],progress=Math.round(Number(plan?.plan?.progress||0));
 return <div style={{marginTop:12,paddingTop:10,borderTop:'1px solid var(--border,#dbe2ea)',display:'grid',gap:10}}>
  {showCatalog&&<OutcomeMiniTestCatalog onOpen={openTest} busy={busy}/>}
  {plan?.available&&<strong>Bugünkü kayıtlı plan · %{progress}</strong>}
  {error&&<div className="alert error" style={{margin:0}}>{error}</div>}{notice&&<div className="alert success" style={{margin:0}}>{notice}</div>}
  <small className="muted">Yeni mini testlerde daha önce karşına çıkan sorular kullanılmaz. Tekrar çalışması, daha önce gördüğün sorularla yapılır ve yeni öğrenme kanıtından ayrı değerlendirilir.</small>
  {repeatItem&&<div className="alert info" style={{display:'grid',gap:8,margin:0}}><strong>Tekrar çalışması · {repeatItem.payload?.label||'Kazanım'}</strong><span>Bu test daha önce gördüğün soruları içerir. Sonuç tekrar çalışması olarak kaydedilir.</span><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" style={{width:'auto',minHeight:0}} checked={repeatConsent} onChange={e=>setRepeatConsent(e.target.checked)}/> Daha önce gördüğüm soruları tekrar çözmek istiyorum.</label><div><button className="secondary" disabled={busy||!repeatConsent} onClick={()=>void startTest(repeatItem,'REPEAT')}>Tekrar çalışmasını başlat</button> <button className="ghost" disabled={busy} onClick={()=>{setRepeatItem(null);setRepeatConsent(false)}}>Vazgeç</button></div></div>}
  {items.map((item:any)=>{const outcome=item.payload?.kind==='OUTCOME_PRACTICE',latest=item.latestMiniTest;return <div key={item.id} style={{display:'grid',gap:7,padding:'10px 0',borderBottom:'1px solid var(--border,#e5e7eb)'}}>
   <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}><span style={{whiteSpace:'normal',display:'inline-flex',alignItems:'center',gap:7}}>{item.completed?<CheckCircle2 size={15}/>:<span aria-hidden="true">•</span>} {item.payload?.label||'Çalışma görevi'}{item.payload?.questionTarget?` · ${item.payload.questionTarget} soru`:''}</span>
    {item.completed?<span className="status ok">Kazanım tamamlandı</span>:outcome?<button className="ghost" disabled={busy} onClick={()=>latest?.id?void openTest(latest.id):void startTest(item)}>{latest?.status==='READY'?'Mini testi aç':latest?.status==='FAILED'?'Sonucu ve desteği aç':'Mini teste başla'} <ChevronRight size={14}/></button>:<button className="ghost" disabled={busy} onClick={()=>void completeSimple(item)}>Tamamladım</button>}
   </div>
   {outcome&&latest?.status!=='READY'&&<button className="ghost" disabled={busy} onClick={()=>{setRepeatItem(item);setRepeatConsent(false)}}>Gördüğüm sorularla tekrar çalış</button>}
   {latest?.status==='FAILED'&&<small className="muted">Son ölçüm %{Math.round(Number(latest.scorePercent||0))}. Destek tamamlandıktan sonra yeniden ölçüm açılır.</small>}
  </div>})}
  {test&&<div style={{marginTop:4,padding:14,border:'1px solid var(--border,#dbe2ea)',borderRadius:14,background:'var(--panel,#fff)',display:'grid',gap:13}}>
   <div><strong>{test.test.subject_name} · {test.test.outcome_title}</strong><div className="muted" style={{fontSize:12,marginTop:3}}>{test.test.selection_mode==='REPEAT'?'Tekrar çalışması':test.test.selection_mode==='NEW'?'Yeni sorularla mini test':'Mini test · soru geçmişi doğrulanmamış'} · {test.test.cycle_no}. ölçüm {test.test.selection_mode!=='REPEAT'&&<>· geçme sınırı %{Math.round(Number(test.test.pass_threshold||.8)*100)}</>}</div></div>
   {(test.questions||[]).map((q:any)=><div key={q.question_id} style={{display:'grid',gap:7,paddingTop:10,borderTop:'1px solid var(--border,#e5e7eb)'}}><strong style={{fontSize:13}}>{q.sort_order}. {q.stem_text || 'Görsel soru'}</strong>{(q.assets||[]).filter((asset:any)=>asset.placement==='STEM'||!asset.placement).map((asset:any)=>asset.url&&<img key={asset.id} src={asset.url} alt={asset.alt_text||'Soru görseli'} style={{maxWidth:'100%',maxHeight:320,objectFit:'contain',borderRadius:8}}/>)}<div style={{display:'grid',gap:6}}>{optionEntries(q.options).map(([key,label])=><label key={key} style={{display:'flex',alignItems:'center',gap:8,fontWeight:500,cursor:test.test.status==='READY'?'pointer':'default'}}><input type="radio" name={`${test.test.id}_${q.question_id}`} value={key} checked={(answers[q.question_id]||q.student_answer)===key} disabled={test.test.status!=='READY'} onChange={()=>setAnswers(x=>({...x,[q.question_id]:key}))} style={{width:'auto',minHeight:0,margin:0}}/><span>{key}) {label}</span>{test.test.status!=='READY'&&q.correct_answer===key&&<span className="status ok">Doğru</span>}</label>)}</div>{test.test.status!=='READY'&&q.correct===0&&<small style={{color:'#b42318'}}>Senin cevabın: {q.student_answer||'Boş'}</small>}{test.test.status!=='READY'&&q.solution_text&&<small className="muted">Çözüm: {q.solution_text}</small>}</div>)}
   {test.test.status==='READY'?<button className="primary" disabled={busy||Object.keys(answers).length<(test.questions||[]).length} onClick={()=>void submit()}>Mini-testi gönder</button>:<div className={`alert ${test.test.status==='PASSED'?'success':'info'}`} style={{margin:0}}><strong>{test.test.selection_mode==='REPEAT'?'Tekrar çalışması sonucu':test.test.status==='PASSED'?'Kazanım tamamlandı':'Yeniden çalışma gerekli'} · %{Math.round(Number(test.test.score_percent||0))}</strong></div>}
   {test.test.status==='FAILED'&&<div style={{display:'grid',gap:8}}><strong>Şimdi yapılacak destek</strong>{(test.followups||[]).map((action:any)=><div key={action.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}><span>{action.action_type==='VIDEO'?'Video: ':''}{action.title}{action.payload?.questionTarget?` · ${action.payload.questionTarget} soru`:''}</span>{action.status==='DONE'?<span className="status ok"><CheckCircle2 size={13}/> Tamamlandı</span>:<button className="ghost" disabled={busy} onClick={()=>void completeFollowup({...action,test_id:test.test.id})}>Desteği tamamladım</button>}</div>)}{(test.followups||[]).some((x:any)=>x.status==='DONE')&&<button className="secondary" disabled={busy} onClick={()=>{const item=items.find((x:any)=>x.id===test.test.assignment_item_id);if(item)void startTest(item)}}><RotateCcw size={15}/> Yeni mini-test</button>}</div>}
  </div>}
 </div>;
}
