import {useRef,useState} from 'react';
import {api,qs} from '../api';

const names:Record<string,string>={EXAM:'Seçili sınavlar',QUESTION_BANK:'Soru havuzu',MINI_TEST:'Yeni mini testler',FOY:'Föy',MINI_GAME:'Mini oyun'};
export function CohortLearningSummary({institutionId,academicYear,examIds,classId}:{institutionId:string;academicYear:string;examIds:string[];classId?:string}){
 const [sources,setSources]=useState(['QUESTION_BANK','MINI_TEST','FOY','MINI_GAME']);
 const [fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState('');
 const [repeat,setRepeat]=useState('LATEST'),[data,setData]=useState<any>(null),[error,setError]=useState<any>(null),[busy,setBusy]=useState('');
 const scope=JSON.stringify([institutionId,academicYear,examIds,classId,sources,repeat,fromDate,toDate]);
 const current=useRef(scope);current.current=scope;const generation=useRef(0);
 const result=data?.scope===scope?data.result:null;
 const load=async()=>{const requested=scope,attempt=++generation.current;setBusy(requested);setError(null);setData(null);try{const result=await api<any>((classId?'/api/reporting/guidance':'/api/reporting/institution')+'/frozen-learning-summary'+qs({institutionId,classId,academicYear,sources:sources.join(','),examIds:sources.includes('EXAM')?examIds.join(','):null,repeatPolicy:repeat,fromDate:fromDate||null,toDate:toDate||null}));if(current.current===requested&&generation.current===attempt)setData({scope:requested,result})}catch(e:any){if(current.current===requested&&generation.current===attempt)setError({scope:requested,message:e.message})}finally{if(current.current===requested&&generation.current===attempt)setBusy('')}};
 return <section className="panel" style={{marginTop:20}}><h3>Tüm kaynakların sınıf ve ders özeti</h3><p>Sınav kaynağı yukarıda seçtiğiniz sınavları kullanır. Diğer kaynaklar seçilen eğitim yılındaki bütün uygun kayıtları kullanır; başlangıç ve bitiş tarihiyle kapsamı daraltabilirsiniz. Tarihler yalnız sınav dışındaki kaynaklara uygulanır. Her sınıf, ders ve müfredat sürümü ayrı hesaplanır.</p>
  <div className="form-grid"><label>Diğer kaynaklar için başlangıç<input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label>Diğer kaynaklar için bitiş<input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></label>{Object.entries(names).map(([id,name])=><label key={id}><input type="checkbox" checked={sources.includes(id)} onChange={()=>setSources(sources.includes(id)?sources.filter(x=>x!==id):[...sources,id])}/>{name}</label>)}<label>Soru havuzundaki tekrarlar<select value={repeat} onChange={e=>setRepeat(e.target.value)}><option value="LATEST">Her öğrencinin son çözümü</option><option value="FIRST">Her öğrencinin ilk çözümü</option></select></label></div>
  <button className="secondary" disabled={busy===scope||!institutionId||!/^\d{4}-\d{4}$/.test(academicYear)||!sources.length||Boolean(fromDate)!==Boolean(toDate)||sources.includes('EXAM')&&!examIds.length} onClick={()=>void load()}>{busy===scope?'Hazırlanıyor…':'Birleşik sınıf özetini hazırla'}</button>
  {error?.scope===scope&&<div className="alert error">{error.message}</div>}
  {result&&<><p>{result.message}</p><div className="summary-strip">{result.sourceCoverage.map((c:any)=><div key={c.sourceType}><strong>{names[c.sourceType]}</strong><p>{c.rowCount} kaynak kaydı</p>{Object.entries(c.excluded||{}).filter(([,v])=>Number(v)>0).map(([key,value])=><small key={key}>{({legacySnapshots:'Eski sınav kaydı',legacyRuns:'Eski çözüm kaydı',legacyTests:'Eski mini test',excludedEvidence:'Kullanılmayan kanıt',repeatedAttempts:'Tekrar çözümü',invalidEvidenceCount:'Bağlamı geçersiz kanıt',invalidSessionCount:'Bağlamı geçersiz oturum'} as Record<string,string>)[key]||'Kapsam bilgisi'}: {Number(value)} · </small>)}</div>)}</div>
  <div style={{overflowX:'auto'}}><table><thead><tr><th>Sınıf</th><th>Ders ve sürüm</th><th>Katılan dönem kaydı</th><th>Doğru / yanlış / boş</th><th>İptal</th><th>Doğruluk</th><th>Kaynak dağılımı</th></tr></thead><tbody>{result.groups.map((g:any)=><tr key={JSON.stringify([g.classId,g.enrollmentGrade,g.subjectId,g.curriculumVersionId,g.gradeLevel,g.programVersion])}><td>{g.className||'Sınıf belirtilmedi'} · {g.enrollmentGrade??'—'}</td><td>{g.subjectName||'Ders adı kaydedilmemiş'}<br/><small>{g.programVersion||'Sürüm adı kaydedilmemiş'} · {g.gradeLevel}. sınıf</small></td><td>{g.participatingEnrollmentCount}</td><td>{g.correct} / {g.wrong} / {g.blank}</td><td>{g.invalid}</td><td>{g.accuracyPercent==null?'—':`%${g.accuracyPercent.toFixed(1)}`}</td><td>{g.sourceBreakdown.map((p:any)=><div key={p.sourceType}>{names[p.sourceType]}: {p.evidenceCount} soru</div>)}</td></tr>)}</tbody></table></div>
  {!!result.outcomeFeedback?.rows?.length&&<><h4>Kazanım bazlı çalışma önerileri</h4><p>{result.outcomeFeedback.message}</p>{result.outcomeFeedback.rows.map((r:any)=><article className="panel" key={JSON.stringify([r.classId,r.enrollmentGrade,r.subjectId,r.curriculumVersionId,r.gradeLevel,r.programVersion,r.outcomeId])}><strong>{r.className||'Sınıf belirtilmedi'} · {r.titleConflict?'Kazanım tanımı kayıtlarda çelişiyor':r.outcomeTitle||r.outcomeCode||'Kazanım adı kaydedilmemiş'}</strong><p>{r.participatingEnrollmentCount} katılan dönem kaydı · {r.correct} doğru / {r.wrong} yanlış / {r.blank} boş · {r.invalid} iptal</p><ul>{r.suggestions.map((text:string)=><li key={text}>{text}</li>)}</ul></article>)}</>}
  {!result.groups.length&&<p>Seçilen kapsamda doğrulanmış akademik kanıt yok.</p>}
  {!!result.gameGroups.length&&<><h4>Mini oyun etkinliği</h4><div style={{overflowX:'auto'}}><table><thead><tr><th>Sınıf</th><th>Ders ve sürüm</th><th>Katılan dönem kaydı</th><th>Oturum</th><th>Ortalama oyun puanı</th><th>Süre / XP</th></tr></thead><tbody>{result.gameGroups.map((g:any)=><tr key={JSON.stringify([g.classId,g.enrollmentGrade,g.subjectId,g.curriculumVersionId,g.gradeLevel,g.programVersion])}><td>{g.className||'Sınıf belirtilmedi'}</td><td>{g.subjectName||'Ders adı kaydedilmemiş'} · {g.programVersion||'Sürüm adı kaydedilmemiş'}</td><td>{g.participatingEnrollmentCount}</td><td>{g.sessionCount}</td><td>{g.averageScore??'—'}</td><td>{g.totalDurationSeconds} sn / {g.totalXp} XP</td></tr>)}</tbody></table></div></>}
  </>}
 </section>;
}
