import { useEffect,useState,type ReactNode } from 'react';
import { CalendarClock,LockKeyhole } from 'lucide-react';
import { Link,useLocation } from 'react-router-dom';
import { api } from '../api';
import { useAuth } from '../auth';

export function LicenseBoundary({children}:{children:ReactNode}){
 const{user}=useAuth();const location=useLocation();const[license,setLicense]=useState<any>(null);const[loading,setLoading]=useState(Boolean(user?.institution_id));const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');
 useEffect(()=>{if(!user?.institution_id){setLoading(false);setLicense(null);return}let active=true;setLoading(true);void api<any>('/api/license/status').then(r=>{if(active)setLicense(r.license)}).catch(()=>{if(active)setLicense(null)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user?.institution_id]);
 if(loading)return <div className="panel"><span className="muted">Lisans durumu kontrol ediliyor…</span></div>;
 if(license?.locked&&['/profile','/nibiru'].includes(location.pathname))return <><div className="alert warning" style={{marginBottom:14}}><LockKeyhole size={17}/><div><strong>Kurum lisansı {license.status==='SUSPENDED'?'askıda':'aktif değil'}.</strong><span>Operasyon modülleri kapalıdır; güvenlik profiliniz ve Nibiru lisans desteği kullanılabilir.</span></div></div>{children}</>;
 const approve=async()=>{setBusy(true);try{await api('/api/license/annual-consent',{method:'POST',body:JSON.stringify({approved:true,note:'Süresi dolan demo ekranından kurum onayı'})});setNotice('Yıllık lisans talebiniz onaylandı. Süper Admin lisansı etkinleştirebilir.')}catch(e:any){setNotice(e.message||'Onay kaydedilemedi.')}finally{setBusy(false)}};
 if(license?.locked)return <div className="panel" style={{maxWidth:760,margin:'40px auto'}}><div className="panel-head"><div><span className="eyebrow">Lisans Durumu</span><h1>{license.planCode==='TRIAL_7_DAY'?'7 günlük deneme süresi sona erdi':'Kurum lisansı aktif değil'}</h1><p>Verileriniz silinmedi. Kurum hesabı güvenli biçimde korunuyor; yıllık lisans etkinleştirildiğinde kaldığınız yerden devam edebilirsiniz.</p></div><LockKeyhole size={34}/></div><div className="alert warning"><strong>{license.status}</strong> · Sistem yöneticinizle iletişime geçerek yıllık lisans seçeneğini etkinleştirebilirsiniz.</div>{notice&&<div className="alert info" style={{marginTop:12}}>{notice}</div>}<div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:14}}>{user?.role==='INSTITUTION_MANAGER'&&license.planCode==='TRIAL_7_DAY'&&<button className="primary" disabled={busy} onClick={()=>void approve()}>Yıllık Lisans Talebini Onayla</button>}<Link className="secondary" to="/nibiru">Nibiru Lisans Desteği</Link><Link className="ghost" to="/profile">Güvenlik ve Oturumlar</Link></div></div>;
 return <>{license?.planCode==='TRIAL_7_DAY'&&license.status==='ACTIVE'&&<div className="alert info" style={{marginBottom:14}}><CalendarClock size={17}/><div><strong>7 Günlük Demo</strong><span>Deneme lisansınız aktif · kalan süre: {license.daysRemaining} gün. Tüm verileriniz yıllık lisansa geçişte korunabilir.</span></div></div>}{children}</>;
}
