import app from './attendance-entry';
import type {AuthUser,Env} from './types';
import {getAuthUser} from './lib/auth';
import {all,audit,badRequest,forbidden,json,notFound,one,uuid} from './lib/db';
import {canAccessClass,loadPermissionScope} from './lib/permissions';

const SOURCES=new Set(['PHYSICAL_BOOK','DIGITAL_BOOK','WORKSHEET','TASK']);
function fail(status:number,code:string,message:string){return json({ok:false,error:{code,message}},status)}
async function requireUser(env:Env,request:Request){return getAuthUser(env,request)}
async function featureEnabled(env:Env,user:AuthUser){if(user.role==='SUPER_ADMIN')return true;if(!user.institution_id)return false;const row=await one<any>(env.DB.prepare(`SELECT COALESCE(o.enabled,f.enabled_default) enabled FROM platform_features f LEFT JOIN institution_feature_overrides o ON o.feature_key=f.feature_key AND o.institution_id=? WHERE f.feature_key='ASSIGNMENTS'`).bind(user.institution_id));return Number(row?.enabled||0)===1}

async function classAccess(env:Env,user:AuthUser,classId:string){
 const row=await one<any>(env.DB.prepare(`SELECT c.id,c.name,c.grade_level,c.institution_id,c.season_id FROM classes c WHERE c.id=? AND c.active=1`).bind(classId));if(!row)return null;
 if(user.role==='SUPER_ADMIN')return row;if(!user.institution_id||row.institution_id!==user.institution_id)return null;if(user.role==='INSTITUTION_MANAGER')return row;
 if(!['TEACHER','GUIDANCE_TEACHER'].includes(user.role))return null;const scope=await loadPermissionScope(env.DB,user,row.season_id);return canAccessClass(scope,classId)?row:null;
}
async function institutionFor(user:AuthUser,url:URL){return user.role==='SUPER_ADMIN'?url.searchParams.get('institutionId'):user.institution_id}

async function options(env:Env,user:AuthUser,url:URL){
 if(!['SUPER_ADMIN','INSTITUTION_MANAGER','TEACHER','GUIDANCE_TEACHER'].includes(user.role))return forbidden();const institutionId=await institutionFor(user,url);if(!institutionId)return badRequest('Kurum seçilmelidir.');
 let classes=await all<any>(env.DB.prepare(`SELECT c.id,c.name,c.grade_level,c.section,c.season_id FROM classes c JOIN institution_seasons s ON s.id=c.season_id WHERE c.institution_id=? AND c.active=1 AND s.status='ACTIVE' ORDER BY c.grade_level,c.section`).bind(institutionId));
 if(user.role==='TEACHER'||user.role==='GUIDANCE_TEACHER'){const scope=await loadPermissionScope(env.DB,user);const allowed=new Set([...scope.classIds,...scope.guidanceClassIds]);classes=classes.filter(x=>allowed.has(x.id))}
 const classId=url.searchParams.get('classId'),klass=classId?await classAccess(env,user,classId):null;if(classId&&!klass)return forbidden('Bu sınıf için ödev yetkiniz yok.');
 const students=klass?await all<any>(env.DB.prepare(`SELECT st.id,st.first_name,st.last_name,e.student_number FROM student_enrollments e JOIN student_entities st ON st.id=e.student_id WHERE e.class_id=? AND e.status='ACTIVE' AND st.status='ACTIVE' ORDER BY st.first_name,st.last_name`).bind(classId)):[];
 const [worksheets,physicalBooks]=await Promise.all([
  all<any>(env.DB.prepare(`SELECT id,title,grade_level,track FROM worksheets WHERE status='PUBLISHED' AND (? IS NULL OR grade_level IS NULL OR grade_level=?) ORDER BY title LIMIT 300`).bind(klass?.grade_level||null,klass?.grade_level||null)),
  all<any>(env.DB.prepare(`SELECT id,title,isbn_or_code,grade_level FROM physical_content_items WHERE active=1 AND (? IS NULL OR grade_level IS NULL OR grade_level=?) ORDER BY title LIMIT 300`).bind(klass?.grade_level||null,klass?.grade_level||null)),
 ]);
 return json({ok:true,institutionId,classes,students,worksheets,physicalBooks});
}

async function listAssignments(env:Env,user:AuthUser,url:URL){
 if(user.role==='STUDENT'){if(!user.student_id)return forbidden();const rows=await all<any>(env.DB.prepare(`SELECT a.*,c.name class_name,r.status recipient_status,r.progress,r.completed_at,(SELECT payload_json FROM assignment_items WHERE assignment_id=a.id ORDER BY sort_order LIMIT 1) item_payload FROM assignment_recipients r JOIN assignments a ON a.id=r.assignment_id LEFT JOIN classes c ON c.id=a.class_id WHERE r.student_id=? AND a.status<>'ARCHIVED' ORDER BY COALESCE(a.due_at,a.created_at) DESC LIMIT 200`).bind(user.student_id));return json({ok:true,assignments:rows.map(x=>({...x,item:parse(x.item_payload)}))});}
 if(!['SUPER_ADMIN','INSTITUTION_MANAGER','TEACHER','GUIDANCE_TEACHER'].includes(user.role))return forbidden();const institutionId=await institutionFor(user,url);if(!institutionId)return badRequest('Kurum seçilmelidir.');
 let rows=await all<any>(env.DB.prepare(`SELECT a.*,c.name class_name,u.display_name created_by_name,(SELECT COUNT(*) FROM assignment_recipients r WHERE r.assignment_id=a.id) recipient_count,(SELECT COUNT(*) FROM assignment_recipients r WHERE r.assignment_id=a.id AND r.status='COMPLETED') completed_count,(SELECT ROUND(AVG(r.progress),1) FROM assignment_recipients r WHERE r.assignment_id=a.id) average_progress,(SELECT payload_json FROM assignment_items WHERE assignment_id=a.id ORDER BY sort_order LIMIT 1) item_payload FROM assignments a LEFT JOIN classes c ON c.id=a.class_id JOIN users u ON u.id=a.created_by WHERE a.institution_id=? AND a.status<>'ARCHIVED' ORDER BY a.created_at DESC LIMIT 200`).bind(institutionId));
 if(user.role==='TEACHER'||user.role==='GUIDANCE_TEACHER'){const scope=await loadPermissionScope(env.DB,user);const allowed=new Set([...scope.classIds,...scope.guidanceClassIds]);rows=rows.filter(x=>x.class_id&&allowed.has(x.class_id))}return json({ok:true,assignments:rows.map(x=>({...x,item:parse(x.item_payload)}))});
}
function parse(value:string|null){try{return value?JSON.parse(value):{}}catch{return{}}}

async function createAssignment(request:Request,env:Env,user:AuthUser){
 if(!['SUPER_ADMIN','INSTITUTION_MANAGER','TEACHER','GUIDANCE_TEACHER'].includes(user.role))return forbidden();const b=await request.json<any>().catch(()=>null);if(!b)return badRequest('Ödev bilgileri geçersiz.');
 const classId=String(b.classId||''),klass=await classAccess(env,user,classId);if(!klass)return forbidden('Bu sınıf için ödev yetkiniz yok.');const title=String(b.title||'').trim().slice(0,180),sourceKind=String(b.sourceKind||'TASK').toUpperCase();if(title.length<3||!SOURCES.has(sourceKind))return badRequest('Ödev başlığı ve kaynak türü gereklidir.');
 const allStudents=await all<{student_id:string}>(env.DB.prepare(`SELECT student_id FROM student_enrollments WHERE class_id=? AND status='ACTIVE'`).bind(classId)),allowed=new Set(allStudents.map(x=>x.student_id));const requested=Array.isArray(b.studentIds)&&b.studentIds.length?b.studentIds.map(String):[...allowed];const recipients=[...new Set<string>(requested)].filter(id=>allowed.has(id));if(!recipients.length||recipients.length!==new Set(requested).size)return badRequest('Ödev alıcıları bu sınıfın aktif öğrencilerinden seçilmelidir.');
 const payload:any={sourceKind,label:String(b.sourceLabel||title).trim().slice(0,180),classId};let itemType='TASK',referenceId=null;
 if(sourceKind==='PHYSICAL_BOOK'){itemType='BOOK_PAGE';referenceId=String(b.physicalBookId||'')||null;payload.pageStart=Math.max(1,Number(b.pageStart||1));payload.pageEnd=Math.max(payload.pageStart,Number(b.pageEnd||payload.pageStart));if(!referenceId)return badRequest('Fiziksel kitap seçilmelidir.');const book=await one(env.DB.prepare(`SELECT id FROM physical_content_items WHERE id=? AND active=1`).bind(referenceId));if(!book)return badRequest('Fiziksel kitap bulunamadı.');}
 if(sourceKind==='DIGITAL_BOOK'){itemType='TASK';payload.url=String(b.digitalUrl||'').trim();payload.pageStart=Math.max(1,Number(b.pageStart||1));payload.pageEnd=Math.max(payload.pageStart,Number(b.pageEnd||payload.pageStart));if(!/^https:\/\//i.test(payload.url))return badRequest('Dijital kitap bağlantısı HTTPS olmalıdır.');}
 if(sourceKind==='WORKSHEET'){itemType='WORKSHEET';referenceId=String(b.worksheetId||'')||null;if(!referenceId||!await one(env.DB.prepare(`SELECT id FROM worksheets WHERE id=? AND status='PUBLISHED'`).bind(referenceId)))return badRequest('Yayınlanmış föy seçilmelidir.');}
 const id=uuid('asg'),dueAt=String(b.dueAt||'').trim()||null,statements:D1PreparedStatement[]=[env.DB.prepare(`INSERT INTO assignments(id,institution_id,season_id,class_id,source_kind,created_by,assignment_type,title,description,due_at,status) VALUES(?,?,?,?,?,?,'TEACHER',?,?,?,'ASSIGNED')`).bind(id,klass.institution_id,klass.season_id,classId,sourceKind,user.id,title,String(b.description||'').trim().slice(0,1000)||null,dueAt),env.DB.prepare(`INSERT INTO assignment_items(id,assignment_id,item_type,reference_id,payload_json,sort_order) VALUES(?,?,?,?,?,1)`).bind(uuid('asi'),id,itemType,referenceId,JSON.stringify(payload))];
 for(const studentId of recipients)statements.push(env.DB.prepare(`INSERT INTO assignment_recipients(assignment_id,student_id,status,progress) VALUES(?,?,'ASSIGNED',0)`).bind(id,studentId));await env.DB.batch(statements);await audit(env.DB,user.id,klass.institution_id,'ASSIGNMENT_CREATED','assignment',id,{classId,sourceKind,recipientCount:recipients.length,dueAt});return json({ok:true,id,recipientCount:recipients.length},201);
}

async function detail(env:Env,user:AuthUser,id:string){
 const assignment=await one<any>(env.DB.prepare(`SELECT a.*,c.name class_name,u.display_name created_by_name,(SELECT payload_json FROM assignment_items WHERE assignment_id=a.id ORDER BY sort_order LIMIT 1) item_payload FROM assignments a LEFT JOIN classes c ON c.id=a.class_id JOIN users u ON u.id=a.created_by WHERE a.id=?`).bind(id));if(!assignment)return notFound('Ödev bulunamadı.');
 if(user.role==='STUDENT'){if(!user.student_id||!await one(env.DB.prepare(`SELECT 1 FROM assignment_recipients WHERE assignment_id=? AND student_id=?`).bind(id,user.student_id)))return forbidden();}
 else if(user.role!=='SUPER_ADMIN'){if(assignment.institution_id!==user.institution_id)return forbidden();if(user.role==='TEACHER'||user.role==='GUIDANCE_TEACHER'){if(!await classAccess(env,user,assignment.class_id))return forbidden();}}
 const recipients=await all<any>(env.DB.prepare(`SELECT r.*,s.first_name,s.last_name,e.student_number FROM assignment_recipients r JOIN student_entities s ON s.id=r.student_id LEFT JOIN student_enrollments e ON e.student_id=s.id AND e.class_id=? WHERE r.assignment_id=? ORDER BY s.first_name,s.last_name`).bind(assignment.class_id,id));return json({ok:true,assignment:{...assignment,item:parse(assignment.item_payload)},recipients:user.role==='STUDENT'?recipients.filter(x=>x.student_id===user.student_id):recipients});
}

async function progress(request:Request,env:Env,user:AuthUser,id:string,studentId:string){
 const assignment=await one<any>(env.DB.prepare(`SELECT institution_id,class_id FROM assignments WHERE id=?`).bind(id));if(!assignment)return notFound('Ödev bulunamadı.');const own=user.role==='STUDENT'&&user.student_id===studentId;if(!own){if(!['SUPER_ADMIN','INSTITUTION_MANAGER','TEACHER','GUIDANCE_TEACHER'].includes(user.role))return forbidden();if(user.role!=='SUPER_ADMIN'&&(assignment.institution_id!==user.institution_id||!await classAccess(env,user,assignment.class_id)))return forbidden();}
 if(!await one(env.DB.prepare(`SELECT 1 FROM assignment_recipients WHERE assignment_id=? AND student_id=?`).bind(id,studentId)))return notFound('Ödev alıcısı bulunamadı.');const b=await request.json<any>().catch(()=>({}));const value=Math.max(0,Math.min(100,Number(b.progress||0))),status=String(b.status||'').toUpperCase();const resolved=status==='EXCUSED'?'EXCUSED':value>=100?'COMPLETED':value>0?'STARTED':'ASSIGNED';await env.DB.prepare(`UPDATE assignment_recipients SET progress=?,status=?,completed_at=CASE WHEN ?='COMPLETED' THEN CURRENT_TIMESTAMP ELSE NULL END WHERE assignment_id=? AND student_id=?`).bind(resolved==='EXCUSED'?0:value,resolved,resolved,id,studentId).run();await audit(env.DB,user.id,assignment.institution_id,'ASSIGNMENT_PROGRESS_UPDATED','assignment',id,{studentId,status:resolved,progress:value});return json({ok:true,status:resolved,progress:value});
}

export default {async fetch(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{const url=new URL(request.url),p=url.pathname;if(!p.startsWith('/api/assignment-center'))return app.fetch(request,env,ctx);const user=await requireUser(env,request);if(!user)return fail(401,'UNAUTHENTICATED','Oturum açmanız gerekiyor.');if(!await featureEnabled(env,user))return forbidden('Ödev modülü kurumunuz için etkin değil.');if(p==='/api/assignment-center/options'&&request.method==='GET')return options(env,user,url);if(p==='/api/assignment-center'&&request.method==='GET')return listAssignments(env,user,url);if(p==='/api/assignment-center'&&request.method==='POST')return createAssignment(request,env,user);let m=p.match(/^\/api\/assignment-center\/([^/]+)$/);if(m&&request.method==='GET')return detail(env,user,m[1]);m=p.match(/^\/api\/assignment-center\/([^/]+)\/recipients\/([^/]+)$/);if(m&&request.method==='PATCH')return progress(request,env,user,m[1],m[2]);return fail(405,'METHOD_NOT_ALLOWED','Bu yöntem desteklenmiyor.');}} satisfies ExportedHandler<Env>;
