import type { AuthUser, CapacityJobMessage, Env } from './types';
import { getAuthUser } from './lib/auth';
import { all, json, one } from './lib/db';
import { canReadPrintTemplate } from './lib/optical-print-access';

type WrappedApp={fetch(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>;queue?(batch:MessageBatch<CapacityJobMessage>,env:Env,ctx:ExecutionContext):Promise<void>|void;scheduled?(event:ScheduledController,env:Env,ctx:ExecutionContext):Promise<void>|void};
const fail=(status:number,code:string,message:string)=>json({ok:false,error:{code,message}},status);
function canManage(user:AuthUser){return user.role==='SUPER_ADMIN'||user.role==='INSTITUTION_MANAGER'}
async function ensureInstitution(env:Env,user:AuthUser,institutionId:string){if(user.role==='SUPER_ADMIN')return Boolean(await one(env.DB.prepare('SELECT id FROM institutions WHERE id=?').bind(institutionId)));return user.institution_id===institutionId;}

async function prepareOpticals(request:Request,env:Env,user:AuthUser):Promise<Response>{
 if(!canManage(user))return fail(403,'FORBIDDEN','Optik hazırlama yetkiniz yok.');
 const url=new URL(request.url),classId=url.searchParams.get('classId'),templateVersionId=url.searchParams.get('templateVersionId'),examId=url.searchParams.get('examId'),sort=url.searchParams.get('sort')==='name'?'name':'number';
 if(!classId||!templateVersionId)return fail(400,'VALIDATION_ERROR','Sınıf ve optik şablon seçilmelidir.');
 const cls=await one<any>(env.DB.prepare('SELECT * FROM classes WHERE id=?').bind(classId));if(!cls||!(await ensureInstitution(env,user,cls.institution_id)))return fail(403,'FORBIDDEN','Bu sınıfa erişim yetkiniz yok.');
 const template=await one<any>(env.DB.prepare(`SELECT v.*,t.name,t.owner_type,t.owner_id,t.status template_status FROM optical_template_versions v JOIN optical_templates t ON t.id=v.template_id WHERE v.id=? AND v.active=1 AND t.active=1`).bind(templateVersionId));
 if(!template)return fail(404,'NOT_FOUND','Optik şablon bulunamadı.');if(!canReadPrintTemplate(user,template))return fail(403,'FORBIDDEN','Bu optik şablona erişim yetkiniz yok.');if(!template.print_fields)return fail(400,'TEMPLATE_DEFINITION_REQUIRED','Bu optik için baskı koordinatları henüz tanımlanmamış.');
 const institution=await one<any>(env.DB.prepare('SELECT id,name,code FROM institutions WHERE id=?').bind(cls.institution_id));let exam:any=null;let bookletCodes:string[]=[];
 if(examId){exam=await one<any>(env.DB.prepare(`SELECT DISTINCT e.id,e.title,e.exam_type,e.grade_level,e.exam_date FROM exams e LEFT JOIN exam_institutions ei ON ei.exam_id=e.id AND ei.institution_id=? WHERE e.id=? AND (e.institution_id=? OR e.institution_id IS NULL OR ei.enabled=1)`).bind(cls.institution_id,examId,cls.institution_id));if(!exam)return fail(404,'EXAM_NOT_FOUND','Seçilen sınav bu kurum için kullanılamıyor.');bookletCodes=(await all<{code:string}>(env.DB.prepare(`SELECT code FROM exam_booklets WHERE exam_id=? AND active=1 ORDER BY code`).bind(examId))).map(x=>x.code);}
 const requested=(url.searchParams.get('bookletSet')||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);if(requested.some(code=>!['A','B','C','D'].includes(code)||(examId&&!bookletCodes.includes(code))))return fail(400,'BOOKLET_INVALID','Seçilen kitapçık sınavda tanımlı değil.');if(requested.length)bookletCodes=[...new Set(requested)];if(!bookletCodes.length)bookletCodes=['A'];
 const rows=await all<any>(env.DB.prepare(`SELECT s.id,s.first_name,s.last_name,e.student_number,e.grade_level,e.section FROM student_enrollments e JOIN student_entities s ON s.id=e.student_id WHERE e.class_id=? AND e.status='ACTIVE' AND s.status='ACTIVE' ORDER BY ${sort==='name'?'s.normalized_name':`cast(e.student_number as integer),e.student_number,s.normalized_name`}`).bind(classId));
 const participants=examId?await all<any>(env.DB.prepare(`SELECT student_id,booklet_code FROM exam_participants WHERE exam_id=? AND institution_id=? AND student_id IS NOT NULL`).bind(examId,cls.institution_id)):[];const participantMap=new Map(participants.map((p:any)=>[p.student_id,p.booklet_code]));const students=rows.map((student:any,index:number)=>({...student,booklet_code:participantMap.get(student.id)||bookletCodes[index%bookletCodes.length]}));
 let printFields:any;try{printFields=JSON.parse(template.print_fields)}catch{return fail(409,'TEMPLATE_PRINT_FIELDS_INVALID','Optik baskı koordinatları geçerli JSON değil.');}
 return json({ok:true,template:{id:template.id,name:template.name,pageWidthMm:template.page_width_mm,pageHeightMm:template.page_height_mm,printFields},institution,class:cls,exam,bookletCodes,students});
}

async function printBase(request:Request,env:Env,user:AuthUser):Promise<Response>{
 if(!canManage(user))return fail(403,'FORBIDDEN','Optik baskı tabanına erişim yetkiniz yok.');const url=new URL(request.url),versionId=url.searchParams.get('versionId');if(!versionId)return fail(400,'VERSION_REQUIRED','Optik sürümü gereklidir.');
 const version=await one<any>(env.DB.prepare(`SELECT v.id,t.owner_type,t.owner_id,t.status template_status FROM optical_template_versions v JOIN optical_templates t ON t.id=v.template_id WHERE v.id=? AND v.active=1 AND t.active=1`).bind(versionId));if(!version)return fail(404,'NOT_FOUND','Optik sürümü bulunamadı.');if(!canReadPrintTemplate(user,version))return fail(403,'FORBIDDEN','Bu optik baskı tabanına erişim yetkiniz yok.');
 const asset=await one<any>(env.DB.prepare(`SELECT object_key,file_name,content_type FROM optical_template_assets WHERE optical_template_version_id=? AND asset_type IN ('PRINT_BASE','BLANK_FORM') ORDER BY CASE asset_type WHEN 'PRINT_BASE' THEN 0 ELSE 1 END,created_at DESC LIMIT 1`).bind(versionId));if(!asset)return new Response('',{status:204});const object=await env.FILES.get(asset.object_key);if(!object)return fail(404,'ASSET_NOT_FOUND','Optik baskı tabanı R2 üzerinde bulunamadı.');const headers=new Headers();object.writeHttpMetadata(headers);headers.set('Content-Type',asset.content_type||headers.get('Content-Type')||'image/png');headers.set('Cache-Control','private, max-age=300');headers.set('Content-Disposition',`inline; filename="${String(asset.file_name||'optik').replace(/"/g,'')}"`);return new Response(object.body,{headers});
}

export function createOpticalPrintPolicyEntry(app:WrappedApp):ExportedHandler<Env,CapacityJobMessage>{return{async fetch(request,env,ctx){const url=new URL(request.url);if(!['/api/optical-prepare','/api/v2/optical-print-base'].includes(url.pathname))return app.fetch(request,env,ctx);if(request.method!=='GET')return fail(405,'METHOD_NOT_ALLOWED','Bu yöntem desteklenmiyor.');const user=await getAuthUser(env,request);if(!user)return fail(401,'UNAUTHENTICATED','Oturum açmanız gerekiyor.');return url.pathname==='/api/optical-prepare'?prepareOpticals(request,env,user):printBase(request,env,user);},async queue(batch,env,ctx){if(app.queue)return app.queue(batch,env,ctx);for(const message of batch.messages)message.retry({delaySeconds:30});},async scheduled(event,env,ctx){if(app.scheduled)return app.scheduled(event,env,ctx);}}}
