import app from './assignment-entry';
import type { AuthUser,CapacityJobMessage,Env } from './types';
import { getAuthUser } from './lib/auth';
import { all,audit,badRequest,forbidden,json,notFound,one,uuid } from './lib/db';
import { capacityTestStatus,processCapacityQueue,startCapacityTest } from './lib/operations-completion';
import { requireLicensedApiFeature } from './lib/feature-access';

function fail(status:number,code:string,message:string,details?:unknown){return json({ok:false,error:{code,message,details}},status)}
function parseJson<T>(value:string|null,fallback:T):T{try{return value?JSON.parse(value):fallback}catch{return fallback}}

async function scopedStudent(env:Env,user:AuthUser,requested?:string|null){
 if(user.role==='STUDENT')return user.student_id&&(!requested||requested===user.student_id)?user.student_id:null;
 if(user.role==='PARENT'&&requested){const row=await one(env.DB.prepare(`SELECT 1 ok FROM parent_student_links WHERE parent_user_id=? AND student_id=? AND active=1`).bind(user.id,requested));return row?requested:null}
 if(user.role==='SUPER_ADMIN')return requested||null;
 return null;
}

async function membershipCatalog(env:Env,user:AuthUser,url:URL){
 const plans=(await all<any>(env.DB.prepare(`SELECT id,code,name,tier,entitlement_json,monthly_live_credits,annual_price_try,billing_period FROM membership_plans WHERE active=1 ORDER BY tier`))).map(x=>({...x,entitlements:parseJson(x.entitlement_json,{})}));
 const studentId=await scopedStudent(env,user,url.searchParams.get('studentId'));let membership=null,orders:any[]=[];
 if(studentId){membership=await one<any>(env.DB.prepare(`SELECT sm.*,p.code plan_code,p.name plan_name,p.annual_price_try FROM student_memberships sm JOIN membership_plans p ON p.id=sm.plan_id WHERE sm.student_id=? AND sm.status='ACTIVE' AND (sm.ends_at IS NULL OR sm.ends_at>CURRENT_TIMESTAMP) ORDER BY p.tier DESC,sm.starts_at DESC LIMIT 1`).bind(studentId));orders=await all<any>(env.DB.prepare(`SELECT o.*,p.code plan_code,p.name plan_name FROM membership_order_requests o JOIN membership_plans p ON p.id=o.plan_id WHERE o.student_id=? ORDER BY o.requested_at DESC LIMIT 20`).bind(studentId))}
 return json({ok:true,plans,membership,orders,studentId});
}

async function createMembershipOrder(request:Request,env:Env,user:AuthUser){
 const body:any=await request.json().catch(()=>({}));const studentId=await scopedStudent(env,user,String(body.studentId||'')||null);if(!studentId)return forbidden('Yalnız kendi hesabınız veya bağlı çocuğunuz için üyelik talebi oluşturabilirsiniz.');
 const plan=await one<any>(env.DB.prepare(`SELECT * FROM membership_plans WHERE (id=? OR code=?) AND active=1`).bind(body.planId,body.planId));if(!plan)return notFound('Üyelik planı bulunamadı.');if(plan.code==='STANDARD'||Number(plan.annual_price_try||0)<=0)return badRequest('Ücretsiz Standard plan için ödeme talebi gerekmez.');
 const enrollment=await one<any>(env.DB.prepare(`SELECT institution_id FROM student_enrollments WHERE student_id=? AND status='ACTIVE' ORDER BY created_at DESC LIMIT 1`).bind(studentId));if(!enrollment)return badRequest('Aktif öğrenci/kurum kaydı bulunamadı.');
 const pending=await one<any>(env.DB.prepare(`SELECT id FROM membership_order_requests WHERE student_id=? AND status='PENDING'`).bind(studentId));if(pending)return fail(409,'MEMBERSHIP_ORDER_PENDING','Bu öğrenci için sonuçlanmamış bir üyelik talebi zaten var.',{orderId:pending.id});
 const method=String(body.paymentMethod||'BANK_TRANSFER').toUpperCase();if(!['BANK_TRANSFER','IYZICO','PAYTR','APPLE','GOOGLE','MANUAL'].includes(method))return badRequest('Geçersiz ödeme yöntemi.');
 const id=uuid('morder');await env.DB.prepare(`INSERT INTO membership_order_requests(id,student_id,institution_id,plan_id,amount_try,payment_method,status,provider_reference,receipt_note,requested_by) VALUES(?,?,?,?,?,?,'PENDING',?,?,?)`).bind(id,studentId,enrollment.institution_id,plan.id,Number(plan.annual_price_try),method,String(body.providerReference||'').trim()||null,String(body.note||'').trim()||null,user.id).run();
 await audit(env.DB,user.id,enrollment.institution_id,'MEMBERSHIP_ORDER_REQUESTED','membership_order',id,{studentId,plan:plan.code,amountTry:Number(plan.annual_price_try),paymentMethod:method});return json({ok:true,id,status:'PENDING',amountTry:Number(plan.annual_price_try),plan:plan.code},201);
}

async function adminMembershipOrders(env:Env,user:AuthUser,url:URL){
 if(user.role!=='SUPER_ADMIN')return forbidden();const status=url.searchParams.get('status');const rows=await all<any>(env.DB.prepare(`SELECT o.*,p.code plan_code,p.name plan_name,s.first_name||' '||s.last_name student_name,i.name institution_name,u.display_name requested_by_name,d.display_name decided_by_name FROM membership_order_requests o JOIN membership_plans p ON p.id=o.plan_id JOIN student_entities s ON s.id=o.student_id JOIN institutions i ON i.id=o.institution_id LEFT JOIN users u ON u.id=o.requested_by LEFT JOIN users d ON d.id=o.decided_by WHERE (? IS NULL OR o.status=?) ORDER BY CASE o.status WHEN 'PENDING' THEN 0 ELSE 1 END,o.requested_at DESC LIMIT 500`).bind(status,status));return json({ok:true,orders:rows});
}

async function decideMembershipOrder(request:Request,env:Env,user:AuthUser,id:string){
 if(user.role!=='SUPER_ADMIN')return forbidden();const body:any=await request.json().catch(()=>({}));const action=String(body.action||'').toUpperCase();if(!['APPROVE','REJECT'].includes(action))return badRequest('Karar APPROVE veya REJECT olmalıdır.');const order=await one<any>(env.DB.prepare(`SELECT o.*,p.code plan_code,p.monthly_live_credits FROM membership_order_requests o JOIN membership_plans p ON p.id=o.plan_id WHERE o.id=?`).bind(id));if(!order)return notFound('Üyelik talebi bulunamadı.');if(order.status!=='PENDING')return fail(409,'ORDER_ALREADY_DECIDED','Bu üyelik talebi daha önce sonuçlandırılmış.');
 if(action==='REJECT'){await env.DB.prepare(`UPDATE membership_order_requests SET status='REJECTED',receipt_note=COALESCE(?,receipt_note),decided_by=?,decided_at=CURRENT_TIMESTAMP WHERE id=? AND status='PENDING'`).bind(String(body.note||'').trim()||null,user.id,id).run();await audit(env.DB,user.id,order.institution_id,'MEMBERSHIP_ORDER_REJECTED','membership_order',id,{studentId:order.student_id,plan:order.plan_code});return json({ok:true,id,status:'REJECTED'});}
 const membershipId=uuid('mem'),endsAt=new Date(Date.now()+365*86400000).toISOString(),credits=Number(order.monthly_live_credits||0),periodKey=new Date().toISOString().slice(0,7);const statements:D1PreparedStatement[]=[
  env.DB.prepare(`UPDATE student_memberships SET status='EXPIRED' WHERE student_id=? AND status='ACTIVE'`).bind(order.student_id),
  env.DB.prepare(`INSERT INTO student_memberships(id,student_id,plan_id,status,starts_at,ends_at,source,external_payment_ref) VALUES(?,?,?,'ACTIVE',CURRENT_TIMESTAMP,?,'PURCHASE',?)`).bind(membershipId,order.student_id,order.plan_id,endsAt,String(body.providerReference||order.provider_reference||'').trim()||null),
  env.DB.prepare(`UPDATE membership_order_requests SET status='PAID',provider_reference=COALESCE(?,provider_reference),receipt_note=COALESCE(?,receipt_note),decided_by=?,decided_at=CURRENT_TIMESTAMP,membership_id=? WHERE id=? AND status='PENDING'`).bind(String(body.providerReference||'').trim()||null,String(body.note||'').trim()||null,user.id,membershipId,id),
 ];if(credits>0)statements.push(env.DB.prepare(`INSERT INTO live_credit_wallets(student_id,balance) VALUES(?,?) ON CONFLICT(student_id) DO UPDATE SET balance=balance+excluded.balance,updated_at=CURRENT_TIMESTAMP`).bind(order.student_id,credits),env.DB.prepare(`INSERT INTO live_credit_ledger(id,student_id,amount,reason,reference_id) VALUES(?,?,?,?,?)`).bind(uuid('lcd'),order.student_id,credits,'MEMBERSHIP_MONTHLY_GRANT',membershipId),env.DB.prepare(`INSERT INTO membership_monthly_credit_grants(membership_id,period_key,student_id,credit_amount) VALUES(?,?,?,?)`).bind(membershipId,periodKey,order.student_id,credits));await env.DB.batch(statements);
 await audit(env.DB,user.id,order.institution_id,'MEMBERSHIP_ORDER_PAID','membership_order',id,{studentId:order.student_id,plan:order.plan_code,amountTry:order.amount_try,membershipId,endsAt});return json({ok:true,id,status:'PAID',membershipId,endsAt});
}

function integrationFlags(env:Env){return{
 YOUTUBE:[Boolean(env.YOUTUBE_API_KEY)],WHATSAPP:[Boolean(env.WHATSAPP_VERIFY_TOKEN),Boolean(env.WHATSAPP_APP_SECRET),Boolean(env.WHATSAPP_ACCESS_TOKEN),Boolean(env.WHATSAPP_PHONE_NUMBER_ID)],NIBIRU_VOICE:[Boolean(env.GOOGLE_TTS_SERVICE_ACCOUNT_JSON)||Boolean(env.OPENAI_TTS_API_KEY)],TELEGRAM:[Boolean(env.TELEGRAM_BOT_TOKEN),Boolean(env.TELEGRAM_WEBHOOK_SECRET)],IYZICO:[Boolean(env.IYZICO_API_KEY),Boolean(env.IYZICO_SECRET_KEY)],PAYTR:[Boolean(env.PAYTR_MERCHANT_ID),Boolean(env.PAYTR_MERCHANT_KEY),Boolean(env.PAYTR_MERCHANT_SALT)],IOS:[Boolean(env.APPLE_TEAM_ID),Boolean(env.APPLE_BUNDLE_ID),Boolean(env.APNS_KEY)],ANDROID:[Boolean(env.ANDROID_PACKAGE_ID),Boolean(env.FCM_SERVICE_ACCOUNT_JSON)],LIVE_MEETING:[Boolean(env.LIVE_MEETING_PROVIDER_KEY)],
} as Record<string,boolean[]>}

async function completionCenter(env:Env,user:AuthUser){
 if(user.role!=='SUPER_ADMIN')return forbidden();const flags=integrationFlags(env);const implemented:Record<string,boolean>={YOUTUBE:true,WHATSAPP:true,NIBIRU_VOICE:true,TELEGRAM:false,IYZICO:false,PAYTR:false,IOS:false,ANDROID:false,LIVE_MEETING:false};const integrations=(await all<any>(env.DB.prepare(`SELECT * FROM platform_integrations ORDER BY category,label`))).map(row=>{const values=flags[row.integration_key]||[],secretsConfigured=values.length>0&&values.every(Boolean),codeReady=Boolean(implemented[row.integration_key]);return{...row,requiredSecrets:parseJson(row.required_secrets_json,[]),configured:secretsConfigured,active:codeReady&&secretsConfigured,codeReady,configuredParts:values.filter(Boolean).length,totalParts:values.length}});
 const counts=await one<any>(env.DB.prepare(`SELECT (SELECT COUNT(*) FROM curriculum_versions WHERE verified=1) verified_curricula,(SELECT COUNT(*) FROM secondary_school_targets WHERE active=1) lgs_targets,(SELECT COUNT(*) FROM university_program_targets WHERE active=1) yks_targets,(SELECT COUNT(*) FROM official_data_releases WHERE import_status='FILE_REQUIRED') official_files_required,(SELECT COUNT(*) FROM transfer_adapter_profiles WHERE status='VERIFIED') verified_transfer_adapters,(SELECT COUNT(*) FROM optical_templates WHERE active=1 AND status='READY') ready_opticals,(SELECT COUNT(*) FROM question_bank WHERE review_status='APPROVED' AND copyright_status IN ('OWNED','LICENSED','PUBLIC_DOMAIN')) approved_questions,(SELECT COUNT(*) FROM annual_content_plan_slots) annual_slots,(SELECT COUNT(*) FROM annual_content_plan_slots WHERE status='PUBLISHED') published_slots,(SELECT COUNT(*) FROM membership_order_requests WHERE status='PENDING') pending_membership_orders,(SELECT COUNT(*) FROM capacity_test_runs WHERE status='COMPLETED' AND target_count=100000) completed_100k_tests`));
 return json({ok:true,integrations,counts,delivered:{bankTransferMembership:true,pwaMobile:true,providerPayments:false,nativeIosAndroid:false,capacityQueueCode:true,capacityQueueConfigured:Boolean(env.SCALE_QUEUE)},policy:{officialData:'Kaynak URL ve doğrulama olmadan resmî veri üretilmez.',externalSecrets:'Secret değerleri API yanıtına veya D1 kayıtlarına yazılmaz.',capacityTest:'Yalnız staging ve izole sentetik tablolarda çalışır.',deferredAi:['GUIDANCE_COUNSELOR_AI','SUBJECT_TEACHER_AI']}});
}

export function numericSubject(code:string,name:string){const value=`${code} ${name}`.toLocaleUpperCase('tr-TR');return ['MAT','FEN','FİZ','FIZ','KİM','KIM','BİY','BIY','GEOMETR'].some(x=>value.includes(x))}
async function batchStatements(env:Env,statements:D1PreparedStatement[]){for(let i=0;i<statements.length;i+=80)await env.DB.batch(statements.slice(i,i+80))}

async function generateAnnualContentPlan(request:Request,env:Env,user:AuthUser){
 if(user.role!=='SUPER_ADMIN')return forbidden();const body:any=await request.json().catch(()=>({}));const academicYear=String(body.academicYear||'').trim(),weekCount=Math.max(1,Math.min(52,Number(body.weekCount||16))),questions=Math.max(5,Math.min(100,Number(body.questionsPerSubject||20)));if(!/^20\d{2}-20\d{2}$/.test(academicYear))return badRequest('Akademik yıl 2026-2027 biçiminde olmalıdır.');const grades=(Array.isArray(body.grades)?body.grades:[5,6,7,8,9,10,11,12]).map(Number).filter((x:number)=>x>=5&&x<=12);const results:any[]=[];
 for(const grade of [...new Set<number>(grades)]){const version=await one<any>(env.DB.prepare(`SELECT * FROM curriculum_versions WHERE academic_year=? AND grade_level=? AND program_code='SCHOOL' AND verified=1 ORDER BY verified_at DESC,id DESC LIMIT 1`).bind(academicYear,grade));if(!version){results.push({grade,status:'VERIFIED_CURRICULUM_REQUIRED'});continue}const outcomes=await all<any>(env.DB.prepare(`SELECT o.id,o.subject_id,o.title,s.code subject_code,s.name subject_name,COUNT(DISTINCT CASE WHEN q.review_status='APPROVED' AND q.copyright_status IN ('OWNED','LICENSED','PUBLIC_DOMAIN') THEN q.id END) approved_question_count FROM outcomes o JOIN subjects s ON s.id=o.subject_id LEFT JOIN question_learning_links l ON l.node_id='ln_'||o.id LEFT JOIN question_bank q ON q.id=l.question_id WHERE o.curriculum_version_id=? AND o.active=1 GROUP BY o.id,o.subject_id,o.title,s.code,s.name ORDER BY s.name,o.code,o.title`).bind(version.id));if(!outcomes.length){results.push({grade,status:'OUTCOMES_REQUIRED'});continue}const bySubject=new Map<string,any[]>();for(const row of outcomes){const list=bySubject.get(row.subject_id)||[];list.push(row);bySubject.set(row.subject_id,list)}const existing=await one<any>(env.DB.prepare(`SELECT id FROM annual_content_plans WHERE academic_year=? AND grade_level=? AND curriculum_version_id=?`).bind(academicYear,grade,version.id));const planId=existing?.id||uuid('acp');const statements:D1PreparedStatement[]=[];if(existing){statements.push(env.DB.prepare(`DELETE FROM annual_content_plan_slots WHERE plan_id=?`).bind(planId),env.DB.prepare(`UPDATE annual_content_plans SET week_count=?,questions_per_subject=?,status='PLANNED',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(weekCount,questions,planId))}else statements.push(env.DB.prepare(`INSERT INTO annual_content_plans(id,academic_year,grade_level,week_count,questions_per_subject,curriculum_version_id,status,created_by) VALUES(?,?,?,?,?,?,'PLANNED',?)`).bind(planId,academicYear,grade,weekCount,questions,version.id,user.id));let slotCount=0,numericSubjects=0,verbalSubjects=0;for(const [subjectId,rows] of bySubject){const track=numericSubject(rows[0].subject_code,rows[0].subject_name)?'NUMERIC':'VERBAL';if(track==='NUMERIC')numericSubjects++;else verbalSubjects++;for(let week=1;week<=weekCount;week++){const outcome=rows[(week-1)%rows.length];const count=Number(outcome.approved_question_count||0),status=count>=questions?'QUESTION_READY':'CONTENT_REQUIRED';statements.push(env.DB.prepare(`INSERT INTO annual_content_plan_slots(id,plan_id,week_no,track,subject_id,outcome_id,required_question_count,approved_question_count,status) VALUES(?,?,?,?,?,?,?,?,?)`).bind(uuid('acs'),planId,week,track,subjectId,outcome.id,questions,count,status));slotCount++}}await batchStatements(env,statements);results.push({grade,status:'PLANNED',planId,subjects:bySubject.size,issuesPerTrack:weekCount,numericIssues:numericSubjects?weekCount:0,verbalIssues:verbalSubjects?weekCount:0,slots:slotCount})}
 await audit(env.DB,user.id,null,'ANNUAL_CONTENT_PLAN_GENERATED','annual_content_plan',academicYear,{grades,weekCount,questionsPerSubject:questions,results});return json({ok:true,academicYear,results});
}

async function annualContentPlans(env:Env,user:AuthUser){if(user.role!=='SUPER_ADMIN')return forbidden();const rows=await all<any>(env.DB.prepare(`SELECT p.*,v.program_version,v.source_title,(SELECT COUNT(*) FROM annual_content_plan_slots s WHERE s.plan_id=p.id) slot_count,(SELECT COUNT(*) FROM annual_content_plan_slots s WHERE s.plan_id=p.id AND s.status='QUESTION_READY') ready_count,(SELECT COUNT(*) FROM annual_content_plan_slots s WHERE s.plan_id=p.id AND s.status='PUBLISHED') published_count FROM annual_content_plans p JOIN curriculum_versions v ON v.id=p.curriculum_version_id ORDER BY p.academic_year DESC,p.grade_level`));return json({ok:true,plans:rows})}

async function grantMonthlyMembershipCredits(env:Env){const periodKey=new Date().toISOString().slice(0,7);const rows=await all<any>(env.DB.prepare(`SELECT sm.id membership_id,sm.student_id,p.monthly_live_credits FROM student_memberships sm JOIN membership_plans p ON p.id=sm.plan_id LEFT JOIN membership_monthly_credit_grants g ON g.membership_id=sm.id AND g.period_key=? WHERE sm.status='ACTIVE' AND (sm.ends_at IS NULL OR sm.ends_at>CURRENT_TIMESTAMP) AND p.monthly_live_credits>0 AND g.membership_id IS NULL LIMIT 500`).bind(periodKey));let granted=0;for(const row of rows){const credits=Number(row.monthly_live_credits||0);const inserted=await env.DB.prepare(`INSERT OR IGNORE INTO membership_monthly_credit_grants(membership_id,period_key,student_id,credit_amount) VALUES(?,?,?,?)`).bind(row.membership_id,periodKey,row.student_id,credits).run();if(Number(inserted.meta.changes||0)!==1)continue;await env.DB.batch([env.DB.prepare(`INSERT INTO live_credit_wallets(student_id,balance) VALUES(?,?) ON CONFLICT(student_id) DO UPDATE SET balance=balance+excluded.balance,updated_at=CURRENT_TIMESTAMP`).bind(row.student_id,credits),env.DB.prepare(`INSERT INTO live_credit_ledger(id,student_id,amount,reason,reference_id) VALUES(?,?,?,?,?)`).bind(uuid('lcd'),row.student_id,credits,'MEMBERSHIP_MONTHLY_GRANT',row.membership_id)]);granted++}return granted}

export default {
 async fetch(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{
  const url=new URL(request.url),path=url.pathname;
  if(path.startsWith('/api/')){const featureUser=await getAuthUser(env,request);if(featureUser){const featureBlock=await requireLicensedApiFeature(env,featureUser,path);if(featureBlock)return featureBlock;}}
  const custom=path==='/api/membership/catalog'||path==='/api/membership/orders'||path==='/api/admin/membership/orders'||path.startsWith('/api/admin/membership/orders/')||path==='/api/admin/completion-center'||path==='/api/admin/annual-content-plans'||path==='/api/admin/annual-content-plans/generate'||path==='/api/admin/capacity-tests';if(!custom)return app.fetch(request,env,ctx);const user=await getAuthUser(env,request);if(!user)return fail(401,'UNAUTHENTICATED','Oturum açmanız gerekiyor.');
  if(path==='/api/membership/catalog'&&request.method==='GET')return membershipCatalog(env,user,url);
  if(path==='/api/membership/orders'&&request.method==='POST')return createMembershipOrder(request,env,user);
  if(path==='/api/admin/membership/orders'&&request.method==='GET')return adminMembershipOrders(env,user,url);
  const order=path.match(/^\/api\/admin\/membership\/orders\/([^/]+)$/);if(order&&request.method==='PATCH')return decideMembershipOrder(request,env,user,order[1]);
  if(path==='/api/admin/completion-center'&&request.method==='GET')return completionCenter(env,user);
  if(path==='/api/admin/annual-content-plans'&&request.method==='GET')return annualContentPlans(env,user);
  if(path==='/api/admin/annual-content-plans/generate'&&request.method==='POST')return generateAnnualContentPlan(request,env,user);
  if(path==='/api/admin/capacity-tests'&&request.method==='GET')return capacityTestStatus(env,user);
  if(path==='/api/admin/capacity-tests'&&request.method==='POST')return startCapacityTest(request,env,user);
  return fail(405,'METHOD_NOT_ALLOWED','Bu yöntem desteklenmiyor.');
 },
 async queue(batch:MessageBatch<CapacityJobMessage>,env:Env,ctx:ExecutionContext){ctx.waitUntil(processCapacityQueue(batch,env))},
 async scheduled(event:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(grantMonthlyMembershipCredits(env).then(count=>console.log(JSON.stringify({event:'membership_monthly_credits',count}))));if('scheduled' in app&&typeof app.scheduled==='function')return app.scheduled(event,env,ctx)},
} satisfies ExportedHandler<Env,CapacityJobMessage>;
