import app from './standard-review-entry';
import type { AuthUser, Env } from './types';
import { getAuthUser } from './lib/auth';
import { all,json,one,uuid } from './lib/db';

function fail(status:number,code:string,message:string){return json({ok:false,error:{code,message}},status)}
async function studentUser(env:Env,request:Request):Promise<AuthUser|Response>{const user=await getAuthUser(env,request);if(!user)return fail(401,'UNAUTHENTICATED','Oturum açmanız gerekiyor.');if(user.role!=='STUDENT'||!user.student_id)return fail(403,'STUDENT_ONLY','Bu özellik öğrenci hesabına açıktır.');return user;}
async function enrollment(env:Env,studentId:string){return one<any>(env.DB.prepare(`SELECT e.*,c.name class_name FROM student_enrollments e LEFT JOIN classes c ON c.id=e.class_id WHERE e.student_id=? ORDER BY CASE e.status WHEN 'ACTIVE' THEN 0 WHEN 'GRADUATED' THEN 1 ELSE 2 END,e.created_at DESC LIMIT 1`).bind(studentId));}
function safeCount(v:any,min=0,max=100){return Math.max(min,Math.min(max,Number(v||0)));}
async function featureAllowed(env:Env,institutionId:string|null,key:string){if(!institutionId)return false;const row=await one<any>(env.DB.prepare(`SELECT COALESCE(o.enabled,f.enabled_default) enabled FROM platform_features f LEFT JOIN institution_feature_overrides o ON o.feature_key=f.feature_key AND o.institution_id=? WHERE f.feature_key=?`).bind(institutionId,key));return Number(row?.enabled||0)===1;}

async function personalBooks(env:Env,user:AuthUser){const enr=await enrollment(env,user.student_id!);if(!await featureAllowed(env,enr?.institution_id||null,'PERSONAL_BOOKS'))return fail(403,'FEATURE_DISABLED','Kişiye Özel Kitap kurum paketinizde etkin değil.');const rows=await all<any>(env.DB.prepare(`SELECT b.*,(SELECT COUNT(DISTINCT a.book_item_id) FROM personal_book_attempts a JOIN student_personal_book_items i ON i.id=a.book_item_id WHERE i.book_id=b.id) attempted_count,(SELECT COUNT(DISTINCT a.book_item_id) FROM personal_book_attempts a JOIN student_personal_book_items i ON i.id=a.book_item_id WHERE i.book_id=b.id AND a.correct=1) mastered_count FROM student_personal_books b WHERE b.student_id=? ORDER BY b.created_at DESC LIMIT 50`).bind(user.student_id));return json({ok:true,books:rows.map(r=>({...r,config:JSON.parse(r.config_json||'{}')}))});}

async function generatePersonalBook(request:Request,env:Env,user:AuthUser){
 const body:any=await request.json().catch(()=>({}));const enr=await enrollment(env,user.student_id!);if(!enr)return fail(400,'ENROLLMENT_REQUIRED','Öğrenci sınıf kaydı bulunamadı.');
 if(!await featureAllowed(env,enr.institution_id,'PERSONAL_BOOKS'))return fail(403,'FEATURE_DISABLED','Kişiye Özel Kitap kurum paketinizde etkin değil.');
 const outcomeLimit=safeCount(body.outcomeLimit||8,1,16),perOutcome=safeCount(body.questionsPerOutcome||4,1,8);
 const weak=await all<any>(env.DB.prepare(`SELECT o.id outcome_id,o.title,o.topic,o.subtopic,o.subject_id,s.name subject_name,SUM(r.evidence_count) evidence_count,SUM(r.correct_count) correct_count,
   CASE WHEN SUM(r.evidence_count)>0 THEN CAST(SUM(r.correct_count) AS REAL)/SUM(r.evidence_count) ELSE 0 END success_rate
   FROM outcome_results r JOIN outcomes o ON o.id=r.outcome_id JOIN subjects s ON s.id=o.subject_id
   WHERE r.student_id=? GROUP BY o.id,o.title,o.topic,o.subtopic,o.subject_id,s.name
   HAVING SUM(r.evidence_count)>=3 AND (CAST(SUM(r.correct_count) AS REAL)/NULLIF(SUM(r.evidence_count),0))<0.70
   ORDER BY success_rate ASC,evidence_count DESC LIMIT ?`).bind(user.student_id,outcomeLimit));
 if(!weak.length)return fail(400,'INSUFFICIENT_EVIDENCE','Kişiye Özel Kitap oluşturmak için henüz yeterli gelişim alanı kanıtı yok.');
 const id=uuid('pbook');const title=String(body.title||'Kişiye Özel Kitabım').trim()||'Kişiye Özel Kitabım';const stmts:any[]=[];let order=1,qCount=0;
 stmts.push(env.DB.prepare(`INSERT INTO student_personal_books(id,student_id,institution_id,academic_year,grade_level,title,source_mode,status,outcome_count,question_count,config_json,generated_by) VALUES(?,?,?,?,?,?,?,'DRAFT',?,?,?,?)`).bind(id,user.student_id,enr.institution_id,enr.academic_year||null,enr.grade_level||null,title,body.sourceMode||'WEAK_OUTCOMES',weak.length,0,JSON.stringify({outcomeLimit,questionsPerOutcome:perOutcome}),user.id));
 for(const w of weak){
  stmts.push(env.DB.prepare(`INSERT INTO student_personal_book_items(id,book_id,outcome_id,subject_id,item_type,sort_order,payload_json) VALUES(?,?,?,?, 'OUTCOME_HEADER',?,?)`).bind(uuid('pbi'),id,w.outcome_id,w.subject_id,order++,JSON.stringify({title:w.title,subject:w.subject_name,topic:w.topic,subtopic:w.subtopic,successRate:w.success_rate,evidenceCount:w.evidence_count})));
  const qs=await all<any>(env.DB.prepare(`SELECT q.id,q.difficulty,q.topic,q.subtopic FROM question_bank q WHERE q.review_status='APPROVED' AND q.grade_level=? AND q.subject_id=? AND (q.owner_type='PLATFORM' OR (q.owner_type='INSTITUTION' AND q.owner_id=?)) AND (q.copyright_status='OWNED' OR (q.copyright_status IN ('LICENSED','PUBLIC_DOMAIN') AND EXISTS(SELECT 1 FROM question_provenance_records p WHERE p.question_id=q.id AND p.verification_status='VERIFIED'))) AND (q.topic=? OR q.subtopic=? OR q.topic LIKE ? OR q.subtopic LIKE ?) ORDER BY ABS(q.difficulty-3),RANDOM() LIMIT ?`).bind(enr.grade_level,w.subject_id,enr.institution_id,w.topic||'',w.subtopic||'',`%${w.topic||''}%`,`%${w.subtopic||''}%`,perOutcome));
  for(const q of qs){stmts.push(env.DB.prepare(`INSERT INTO student_personal_book_items(id,book_id,outcome_id,subject_id,bank_question_id,item_type,difficulty,sort_order,payload_json) VALUES(?,?,?,?,?,'PRACTICE_QUESTION',?,?,?)`).bind(uuid('pbi'),id,w.outcome_id,w.subject_id,q.id,q.difficulty,order++,JSON.stringify({source:'APPROVED_QUESTION_BANK'})));qCount++;}
 }
 stmts.push(env.DB.prepare(`UPDATE student_personal_books SET question_count=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(qCount,qCount>0?'READY':'DRAFT',id));await env.DB.batch(stmts);
 return json({ok:true,id,outcomeCount:weak.length,questionCount:qCount,status:qCount>0?'READY':'DRAFT',note:qCount>0?'Yalnız telif durumu uygun, onaylı soru havuzu içerikleri kitaba alındı.':'Gelişim alanları hazır; basılabilir soru havuzu henüz yeterli değil.'},201);
}

async function personalBookDetail(env:Env,user:AuthUser,id:string){const book=await one<any>(env.DB.prepare(`SELECT * FROM student_personal_books WHERE id=? AND student_id=?`).bind(id,user.student_id));if(!book)return fail(404,'BOOK_NOT_FOUND','Kişiye Özel Kitap bulunamadı.');const items=await all<any>(env.DB.prepare(`SELECT i.*,s.name subject_name,o.title outcome_title,q.stem_text,q.options_json,q.copyright_status,a.answer last_answer,a.correct last_correct,a.created_at last_attempt_at,CASE WHEN a.id IS NOT NULL THEN q.correct_answer ELSE NULL END correct_answer,CASE WHEN a.id IS NOT NULL THEN q.solution_text ELSE NULL END solution_text FROM student_personal_book_items i LEFT JOIN subjects s ON s.id=i.subject_id LEFT JOIN outcomes o ON o.id=i.outcome_id LEFT JOIN question_bank q ON q.id=i.bank_question_id LEFT JOIN personal_book_attempts a ON a.id=(SELECT pa.id FROM personal_book_attempts pa WHERE pa.book_item_id=i.id AND pa.student_id=? ORDER BY pa.created_at DESC LIMIT 1) WHERE i.book_id=? ORDER BY i.sort_order`).bind(user.student_id,id));const attempted=items.filter(x=>x.item_type==='PRACTICE_QUESTION'&&x.last_attempt_at).length,mastered=items.filter(x=>x.item_type==='PRACTICE_QUESTION'&&Number(x.last_correct)===1).length;return json({ok:true,book:{...book,config:JSON.parse(book.config_json||'{}'),attempted_count:attempted,mastered_count:mastered},items:items.map(x=>({...x,payload:JSON.parse(x.payload_json||'{}'),options:x.options_json?JSON.parse(x.options_json):null,options_json:undefined}))});}

async function personalBookAttempt(request:Request,env:Env,user:AuthUser,itemId:string){const item=await one<any>(env.DB.prepare(`SELECT i.id,i.book_id,i.item_type,q.correct_answer,q.solution_text,b.student_id FROM student_personal_book_items i JOIN student_personal_books b ON b.id=i.book_id LEFT JOIN question_bank q ON q.id=i.bank_question_id WHERE i.id=? AND b.student_id=?`).bind(itemId,user.student_id));if(!item)return fail(404,'ITEM_NOT_FOUND','Kitap sorusu bulunamadı.');if(item.item_type!=='PRACTICE_QUESTION'||!item.correct_answer)return fail(400,'QUESTION_NOT_READY','Bu kitap maddesi cevaplanabilir bir soru değil.');const body:any=await request.json().catch(()=>({}));const answer=String(body.answer||'').trim().toLocaleUpperCase('tr-TR');if(!answer)return fail(400,'ANSWER_REQUIRED','Bir cevap seçin veya yazın.');const correct=answer===String(item.correct_answer).trim().toLocaleUpperCase('tr-TR');await env.DB.prepare(`INSERT INTO personal_book_attempts(id,book_item_id,student_id,answer,correct,score) VALUES(?,?,?,?,?,?)`).bind(uuid('pba'),itemId,user.student_id,answer,correct?1:0,correct?1:0).run();const progress=await one<any>(env.DB.prepare(`SELECT COUNT(DISTINCT CASE WHEN a.id IS NOT NULL THEN i.id END) attempted,COUNT(DISTINCT CASE WHEN a.correct=1 THEN i.id END) mastered,COUNT(DISTINCT i.id) total FROM student_personal_book_items i LEFT JOIN personal_book_attempts a ON a.book_item_id=i.id AND a.student_id=? WHERE i.book_id=? AND i.item_type='PRACTICE_QUESTION'`).bind(user.student_id,item.book_id));return json({ok:true,correct,correctAnswer:item.correct_answer,solutionText:item.solution_text||null,progress:{attempted:Number(progress?.attempted||0),mastered:Number(progress?.mastered||0),total:Number(progress?.total||0)}});}

async function zeroErrorBooks(env:Env,user:AuthUser){const enr=await enrollment(env,user.student_id!);if(!await featureAllowed(env,enr?.institution_id||null,'ZERO_ERROR_BOOKLET'))return fail(403,'FEATURE_DISABLED','Sıfır Hata Kitapçığı kurum paketinizde etkin değil.');const rows=await all<any>(env.DB.prepare(`SELECT z.*,e.title source_exam_title,e.exam_date,(SELECT COUNT(*) FROM zero_error_booklet_items i WHERE i.booklet_id=z.id AND i.bank_question_id IS NOT NULL) total_practice_count,(SELECT COUNT(*) FROM zero_error_booklet_items i WHERE i.booklet_id=z.id AND i.item_status='MASTERED') mastered_count FROM zero_error_booklets z LEFT JOIN exams e ON e.id=z.source_exam_id WHERE z.student_id=? ORDER BY z.created_at DESC LIMIT 50`).bind(user.student_id));return json({ok:true,booklets:rows.map(r=>({...r,config:JSON.parse(r.config_json||'{}')}))});}

async function generateZeroError(request:Request,env:Env,user:AuthUser){
 const body:any=await request.json().catch(()=>({}));const examId=String(body.examId||'').trim();if(!examId)return fail(400,'EXAM_REQUIRED','Sıfır Hata Kitapçığı için bir sınav seçilmelidir.');const enr=await enrollment(env,user.student_id!);if(!enr)return fail(400,'ENROLLMENT_REQUIRED','Öğrenci sınıf kaydı bulunamadı.');
 if(!await featureAllowed(env,enr.institution_id,'ZERO_ERROR_BOOKLET'))return fail(403,'FEATURE_DISABLED','Sıfır Hata Kitapçığı kurum paketinizde etkin değil.');
 const existing=await one<any>(env.DB.prepare(`SELECT id FROM zero_error_booklets WHERE student_id=? AND source_exam_id=? AND status IN ('ACTIVE','READY','GENERATING_PDF') ORDER BY created_at DESC LIMIT 1`).bind(user.student_id,examId));if(existing)return fail(409,'BOOKLET_ALREADY_ACTIVE','Bu sınav için açık bir Sıfır Hata Kitapçığın zaten var.');
 const answers=await all<any>(env.DB.prepare(`SELECT q.id question_id,q.subject_id,sa.status,o.id outcome_id,o.title outcome_title,o.topic,o.subtopic FROM exam_participants ep JOIN student_answers sa ON sa.participant_id=ep.id JOIN exam_questions q ON q.id=sa.exam_question_id LEFT JOIN question_outcomes qo ON qo.exam_question_id=q.id LEFT JOIN outcomes o ON o.id=qo.outcome_id WHERE ep.student_id=? AND ep.exam_id=? AND sa.status IN ('WRONG','BLANK') ORDER BY coalesce(q.global_no,9999),q.question_no`).bind(user.student_id,examId));
 if(!answers.length)return fail(400,'ZERO_ERROR_ALREADY','Bu sınavda Sıfır Hata Kitapçığına girecek yanlış veya boş soru bulunmuyor.');
 const wrong=answers.filter(x=>x.status==='WRONG').length,blank=answers.filter(x=>x.status==='BLANK').length,id=uuid('zeb');const perSource=safeCount(body.practicePerSource||2,1,4);let practice=0,unavailable=0,order=1;const stmts:any[]=[env.DB.prepare(`INSERT INTO zero_error_booklets(id,student_id,institution_id,source_exam_id,title,status,wrong_count,blank_count,practice_count,unresolved_count,config_json,generated_by) VALUES(?,?,?,?,?,'ACTIVE',?,?,?,?,?,?)`).bind(id,user.student_id,enr.institution_id,examId,String(body.title||'Sıfır Hata Kitapçığım').trim()||'Sıfır Hata Kitapçığım',wrong,blank,0,answers.length,JSON.stringify({practicePerSource:perSource}),user.id)];
 for(const a of answers){
  const similar=await all<any>(env.DB.prepare(`SELECT q.id,q.difficulty FROM question_bank q WHERE q.review_status='APPROVED' AND q.grade_level=? AND q.subject_id=? AND (q.owner_type='PLATFORM' OR (q.owner_type='INSTITUTION' AND q.owner_id=?)) AND (q.copyright_status='OWNED' OR (q.copyright_status IN ('LICENSED','PUBLIC_DOMAIN') AND EXISTS(SELECT 1 FROM question_provenance_records p WHERE p.question_id=q.id AND p.verification_status='VERIFIED'))) AND (q.topic=? OR q.subtopic=? OR q.topic LIKE ? OR q.subtopic LIKE ?) ORDER BY ABS(q.difficulty-3),RANDOM() LIMIT ?`).bind(enr.grade_level,a.subject_id,enr.institution_id,a.topic||'',a.subtopic||'',`%${a.topic||''}%`,`%${a.subtopic||''}%`,perSource));
  if(similar.length){for(const q of similar){stmts.push(env.DB.prepare(`INSERT INTO zero_error_booklet_items(id,booklet_id,source_exam_question_id,outcome_id,subject_id,original_status,bank_question_id,cycle_no,item_status,sort_order,payload_json) VALUES(?,?,?,?,?,?,?,1,'PRACTICE_READY',?,?)`).bind(uuid('zei'),id,a.question_id,a.outcome_id||null,a.subject_id,a.status,q.id,order++,JSON.stringify({outcomeTitle:a.outcome_title,source:'APPROVED_QUESTION_BANK'})));practice++;}}
  else{unavailable++;stmts.push(env.DB.prepare(`INSERT INTO zero_error_booklet_items(id,booklet_id,source_exam_question_id,outcome_id,subject_id,original_status,cycle_no,item_status,sort_order,payload_json) VALUES(?,?,?,?,?,?,1,'TO_REVIEW',?,?)`).bind(uuid('zei'),id,a.question_id,a.outcome_id||null,a.subject_id,a.status,order++,JSON.stringify({outcomeTitle:a.outcome_title,note:'Benzer basılabilir soru henüz havuzda yok.'})));}
 }
 stmts.push(env.DB.prepare(`UPDATE zero_error_booklets SET practice_count=?,unresolved_count=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(practice,practice,practice>0?'READY':'ACTIVE',id));await env.DB.batch(stmts);
 return json({ok:true,id,wrongCount:wrong,blankCount:blank,practiceCount:practice,unresolvedCount:practice,unavailableCount:unavailable,status:practice>0?'READY':'ACTIVE'},201);
}

async function zeroErrorDetail(env:Env,user:AuthUser,id:string){const booklet=await one<any>(env.DB.prepare(`SELECT z.*,e.title source_exam_title,e.exam_date FROM zero_error_booklets z LEFT JOIN exams e ON e.id=z.source_exam_id WHERE z.id=? AND z.student_id=?`).bind(id,user.student_id));if(!booklet)return fail(404,'BOOKLET_NOT_FOUND','Sıfır Hata Kitapçığı bulunamadı.');const items=await all<any>(env.DB.prepare(`SELECT i.*,s.name subject_name,o.title outcome_title,q.stem_text,q.options_json,q.copyright_status,a.answer last_answer,a.correct last_correct,a.created_at last_attempt_at,CASE WHEN a.id IS NOT NULL THEN q.correct_answer ELSE NULL END correct_answer,CASE WHEN a.id IS NOT NULL THEN q.solution_text ELSE NULL END solution_text FROM zero_error_booklet_items i LEFT JOIN subjects s ON s.id=i.subject_id LEFT JOIN outcomes o ON o.id=i.outcome_id LEFT JOIN question_bank q ON q.id=i.bank_question_id LEFT JOIN zero_error_attempts a ON a.id=(SELECT za.id FROM zero_error_attempts za WHERE za.booklet_item_id=i.id AND za.student_id=? ORDER BY za.created_at DESC LIMIT 1) WHERE i.booklet_id=? ORDER BY i.sort_order`).bind(user.student_id,id));const practice=items.filter(x=>x.bank_question_id),mastered=practice.filter(x=>x.item_status==='MASTERED').length;return json({ok:true,booklet:{...booklet,config:JSON.parse(booklet.config_json||'{}'),total_practice_count:practice.length,mastered_count:mastered},items:items.map(x=>({...x,payload:JSON.parse(x.payload_json||'{}'),options:x.options_json?JSON.parse(x.options_json):null,options_json:undefined}))});}

async function zeroErrorAttempt(request:Request,env:Env,user:AuthUser,itemId:string){const item=await one<any>(env.DB.prepare(`SELECT i.*,q.correct_answer,q.solution_text,z.student_id FROM zero_error_booklet_items i JOIN zero_error_booklets z ON z.id=i.booklet_id LEFT JOIN question_bank q ON q.id=i.bank_question_id WHERE i.id=? AND z.student_id=?`).bind(itemId,user.student_id));if(!item)return fail(404,'ITEM_NOT_FOUND','Sıfır Hata çalışma sorusu bulunamadı.');if(!item.bank_question_id||!item.correct_answer)return fail(400,'PRACTICE_NOT_READY','Bu madde henüz cevaplanabilir benzer soruya bağlı değil.');const body:any=await request.json().catch(()=>({}));const answer=String(body.answer||'').trim().toLocaleUpperCase('tr-TR');if(!answer)return fail(400,'ANSWER_REQUIRED','Bir cevap seçin veya yazın.');const correct=answer===String(item.correct_answer).trim().toLocaleUpperCase('tr-TR');await env.DB.batch([env.DB.prepare(`INSERT INTO zero_error_attempts(id,booklet_item_id,student_id,answer,correct,score) VALUES(?,?,?,?,?,?)`).bind(uuid('zea'),itemId,user.student_id,answer,correct?1:0,correct?1:0),env.DB.prepare(`UPDATE zero_error_booklet_items SET item_status=?,last_score=?,last_attempt_at=CURRENT_TIMESTAMP WHERE id=?`).bind(correct?'MASTERED':'NEEDS_REPEAT',correct?1:0,itemId)]);const remain=await one<any>(env.DB.prepare(`SELECT COUNT(*) c FROM zero_error_booklet_items WHERE booklet_id=? AND bank_question_id IS NOT NULL AND item_status<>'MASTERED'`).bind(item.booklet_id));await env.DB.prepare(`UPDATE zero_error_booklets SET unresolved_count=?,status=?,completed_at=CASE WHEN ?=0 THEN CURRENT_TIMESTAMP ELSE completed_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(Number(remain?.c||0),Number(remain?.c||0)===0?'COMPLETED':'READY',Number(remain?.c||0),item.booklet_id).run();return json({ok:true,correct,correctAnswer:item.correct_answer,solutionText:item.solution_text||null,unresolvedCount:Number(remain?.c||0)});}

export default {async fetch(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{const url=new URL(request.url),p=url.pathname;const ours=p.startsWith('/api/student-books/');if(!ours)return app.fetch(request,env,ctx);const auth=await studentUser(env,request);if(auth instanceof Response)return auth;if(p==='/api/student-books/personal'&&request.method==='GET')return personalBooks(env,auth);if(p==='/api/student-books/personal'&&request.method==='POST')return generatePersonalBook(request,env,auth);const pa=p.match(/^\/api\/student-books\/personal\/items\/([^/]+)\/attempt$/);if(pa&&request.method==='POST')return personalBookAttempt(request,env,auth,pa[1]);const pd=p.match(/^\/api\/student-books\/personal\/([^/]+)$/);if(pd&&request.method==='GET')return personalBookDetail(env,auth,pd[1]);if(p==='/api/student-books/zero-error'&&request.method==='GET')return zeroErrorBooks(env,auth);if(p==='/api/student-books/zero-error'&&request.method==='POST')return generateZeroError(request,env,auth);const zd=p.match(/^\/api\/student-books\/zero-error\/([^/]+)$/);if(zd&&request.method==='GET')return zeroErrorDetail(env,auth,zd[1]);const za=p.match(/^\/api\/student-books\/zero-error\/items\/([^/]+)\/attempt$/);if(za&&request.method==='POST')return zeroErrorAttempt(request,env,auth,za[1]);return fail(404,'NOT_FOUND','Öğrenci kitap API yolu bulunamadı.');},async scheduled(event:ScheduledController,env:Env,ctx:ExecutionContext){if('scheduled' in app&&typeof app.scheduled==='function')return app.scheduled(event,env,ctx);}} satisfies ExportedHandler<Env>;
